### ISSUE TITLE
Feild to run on Ubuntu 16.04 (Golem 0.5.2)

### ISSUE THREAD

**Issue by kcisek** [golemfactory/clay#1003]
:~/golem$ ./golemapp

Failed to import scrypt. This is not a fatal error but does
mean that you cannot create or decrypt privkey jsons that use
scrypt

WARNING  [golem.appconfig                    ] Can't open file /home/zlom/.local/share/golem/SimpleEnv/minilight.ini: [Errno 2] No such file or directory: '/home/zlom/.local/share/golem/SimpleEnv/minilight.ini'
INFO     [golem.client                       ] Client "", datadir: /home/zlom/.local/share/golem/default 
WARN [04-18|18:44:04] No etherbase set and no accounts found as default 
INFO [04-18|18:44:04] Starting peer-to-peer node               instance=Geth/v1.6.0-stable-facc47cb/linux-amd64/go1.8.1
INFO [04-18|18:44:04] Allocated cache and file handles         database=/home/zlom/.ethereum/testnet/geth/lightchaindata cache=128 handles=1024
INFO [04-18|18:44:04] Initialised chain configuration          config="{ChainID: 3 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 10 EIP158: 10 Engine: ethash}"
INFO [04-18|18:44:04] Disk storage enabled for ethash caches   dir=/home/zlom/.ethereum/testnet/geth/ethash count=3
INFO [04-18|18:44:04] Disk storage enabled for ethash DAGs     dir=/home/zlom/.ethash                       count=2
INFO [04-18|18:44:04] Loaded most recent local header          number=0 hash=419410…ca4a2d td=1048576
INFO [04-18|18:44:04] Starting P2P networking 
WARN [04-18|18:44:04] Light client mode is an experimental feature 
INFO [04-18|18:44:04] RLPx listener up                         self="enode://158581da626649d5c5e00a1dedad8bcb074692d1c7e45d07cde5330dfcef3c5640618dab6aedf33a57f907798a8ceb8733c0f492109daa2caeee620e18c656b2@[::]:30303?discport=0"
INFO [04-18|18:44:04] IPC endpoint opened: /home/zlom/.ethereum/testnet/geth.ipc 
ERROR    [golem.docker.manager               ] 
                ***************************************************************
                Docker is not available, not building images.
                Golem will not be able to compute anything.
                Command 'docker info' returned [Errno 2] No such file or directory
                ***************************************************************
                
Traceback (most recent call last):
  File "/home/mfrancis/Projects/golem/golemapp.py", line 105, in <module>
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
  File "/home/mfrancis/Projects/golem/golemapp.py", line 70, in start
  File "/home/mfrancis/Projects/golem/gui/startapp.py", line 134, in start_app
  File "/home/mfrancis/Projects/golem/gui/startapp.py", line 73, in start_client
  File "/home/mfrancis/Projects/golem/golem/docker/manager.py", line 102, in check_environment
EnvironmentError
Failed to execute script golemapp

**Comment by mfranciszkiewicz** [comment]
You may need to restart your computer (or log out and log in again) to apply group membership changes - your user has been added to the `docker` group during installation.

**Comment by kcisek** [comment]
Thank you for answer.
I did sudo shutdown -r now after installation
and the output from group zlom, is:
groups zlom
zlom : zlom adm cdrom sudo dip plugdev lpadmin sambashare
so no docker group, also when I type
groups
zlom adm cdrom sudo dip plugdev lpadmin sambashare

**Comment by kcisek** [comment]
Also output from getent group | grep docker
is empty.

**Comment by mfranciszkiewicz** [comment]
Please try adding the `docker` group manually and run `sudo usermod -aG docker zlom`. Then, log out and back in.

**Comment by kcisek** [comment]
Hello.
I created manually group docker and add my user to that group as you said. So now I have:
groups zlom
zlom : zlom adm cdrom sudo dip plugdev lpadmin sambashare docker
but still when I try to run ./golemapp i get:
./golemapp

Failed to import scrypt. This is not a fatal error but does
mean that you cannot create or decrypt privkey jsons that use
scrypt

WARNING  [golem.appconfig                    ] Can't open file /home/zlom/.local/share/golem/SimpleEnv/minilight.ini: [Errno 2] No such file or directory: '/home/zlom/.local/share/golem/SimpleEnv/minilight.ini'
INFO     [golem.client                       ] Client "", datadir: /home/zlom/.local/share/golem/default 
WARN [04-19|11:05:21] No etherbase set and no accounts found as default 
INFO [04-19|11:05:22] Starting peer-to-peer node               instance=Geth/v1.6.0-stable-facc47cb/linux-amd64/go1.8.1
INFO [04-19|11:05:22] Allocated cache and file handles         database=/home/zlom/.ethereum/testnet/geth/lightchaindata cache=128 handles=1024
INFO [04-19|11:05:22] Initialised chain configuration          config="{ChainID: 3 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 10 EIP158: 10 Engine: ethash}"
INFO [04-19|11:05:22] Disk storage enabled for ethash caches   dir=/home/zlom/.ethereum/testnet/geth/ethash count=3
INFO [04-19|11:05:22] Disk storage enabled for ethash DAGs     dir=/home/zlom/.ethash                       count=2
INFO [04-19|11:05:22] Loaded most recent local header          number=0 hash=419410…ca4a2d td=1048576
INFO [04-19|11:05:22] Starting P2P networking 
WARN [04-19|11:05:22] Light client mode is an experimental feature 
INFO [04-19|11:05:22] RLPx listener up                         self="enode://158581da626649d5c5e00a1dedad8bcb074692d1c7e45d07cde5330dfcef3c5640618dab6aedf33a57f907798a8ceb8733c0f492109daa2caeee620e18c656b2@[::]:30303?discport=0"
INFO [04-19|11:05:22] IPC endpoint opened: /home/zlom/.ethereum/testnet/geth.ipc 
INFO [04-19|11:05:23] Block synchronisation started 
ERROR    [golem.docker.manager               ] 
                ***************************************************************
                Docker is not available, not building images.
                Golem will not be able to compute anything.
                Command 'docker info' returned [Errno 2] No such file or directory
                ***************************************************************
                
Traceback (most recent call last):
  File "/home/mfrancis/Projects/golem/golemapp.py", line 105, in <module>
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
  File "/home/mfrancis/Projects/golem/golemapp.py", line 70, in start
  File "/home/mfrancis/Projects/golem/gui/startapp.py", line 134, in start_app
  File "/home/mfrancis/Projects/golem/gui/startapp.py", line 73, in start_client
  File "/home/mfrancis/Projects/golem/golem/docker/manager.py", line 102, in check_environment
EnvironmentError
Failed to execute script golemapp

**Comment by mfranciszkiewicz** [comment]
Could you paste the output of `sudo docker version`?

**Comment by kcisek** [comment]
mhm, Docker is not installed - strange, I thought it was installed together with Golem...

**Comment by mfranciszkiewicz** [comment]
This issue is most likely connected to #1005, which will soon be resolved. For now, please install docker manually.
