### ISSUE TITLE
Add support to render OpenGL with Blender

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#1012]
Currently Golem is not able to render cartoons like: https://download.blender.org/demo/test/ForYou.blend
There is no command line to support OpenGL rendering, but we can additional options to the script. Check this [discussion](https://blender.stackexchange.com/questions/2573/render-with-opengl-from-the-command-line) for references.

**Comment by ggruszczynski** [comment]
I have done an attempt to integrate OpenGL but it must run with UI, 
thus it is not possible to embed it into docker.

Branch:
https://github.com/golemfactory/golem/tree/Attempt_to_run_Blender_OpenGL

**Comment by mfranciszkiewicz** [comment]
It seems that someone has done it: https://github.com/thewtex/docker-opengl
