### ISSUE TITLE
issues 

### ISSUE THREAD

**Issue by gipskruid** [golemfactory/clay#1016]
Hi all treeing to run on OS 10.11.3 El Capitain

getting stuck with: any help?

WARNING  [golem.appconfig                    ] Can't open file /Users/Joekiepau/Library/Application Support/golem/SimpleEnv/minilight.ini: [Errno 2] No such file or directory: '/Users/Joekiepau/Library/Application Support/golem/SimpleEnv/minilight.ini'
INFO     [golem.client                       ] Client "", datadir: /Users/Joekiepau/Library/Application Support/golem/default 
WARN [04-21|21:31:40] No etherbase set and no accounts found as default 
INFO [04-21|21:31:40] Starting peer-to-peer node               instance=Geth/v1.6.0-stable-facc47cb/darwin-amd64/go1.8.1
INFO [04-21|21:31:40] Allocated cache and file handles         database=/Users/Joekiepau/Library/Ethereum/testnet/geth/lightchaindata cache=128 handles=1024
INFO [04-21|21:31:40] Initialised chain configuration          config="{ChainID: 3 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 10 EIP158: 10 Engine: ethash}"
INFO [04-21|21:31:40] Disk storage enabled for ethash caches   dir=/Users/Joekiepau/Library/Ethereum/testnet/geth/ethash count=3
INFO [04-21|21:31:40] Disk storage enabled for ethash DAGs     dir=/Users/Joekiepau/.ethash                              count=2
INFO [04-21|21:31:41] Loaded most recent local header          number=761044 hash=7d5360…807683 td=570973180285531
INFO [04-21|21:31:41] Starting P2P networking 
Fatal: Error starting protocol stack: listen tcp :30303: bind: address already in use

**Comment by egalano** [comment]
It looks like you are already running geth on that machine and Golem is trying to start a new geth process.

**Comment by gipskruid** [comment]
thanks @egalano , i closed Ethereum wallet next problem:

Failed to import scrypt. This is not a fatal error but does
mean that you cannot create or decrypt privkey jsons that use
scrypt

WARNING  [golem.appconfig                    ] Can't open file /Users/Joekiepau/Library/Application Support/golem/SimpleEnv/minilight.ini: [Errno 2] No such file or directory: '/Users/Joekiepau/Library/Application Support/golem/SimpleEnv/minilight.ini'
INFO     [golem.client                       ] Client "", datadir: /Users/Joekiepau/Library/Application Support/golem/default 
WARN [04-21|21:46:07] No etherbase set and no accounts found as default 
INFO [04-21|21:46:07] Starting peer-to-peer node               instance=Geth/v1.6.0-stable-facc47cb/darwin-amd64/go1.8.1
INFO [04-21|21:46:07] Allocated cache and file handles         database=/Users/Joekiepau/Library/Ethereum/testnet/geth/lightchaindata cache=128 handles=1024
INFO [04-21|21:46:07] Initialised chain configuration          config="{ChainID: 3 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 10 EIP158: 10 Engine: ethash}"
INFO [04-21|21:46:07] Disk storage enabled for ethash caches   dir=/Users/Joekiepau/Library/Ethereum/testnet/geth/ethash count=3
INFO [04-21|21:46:07] Disk storage enabled for ethash DAGs     dir=/Users/Joekiepau/.ethash                              count=2
INFO [04-21|21:46:07] Loaded most recent local header          number=761044 hash=7d5360…807683 td=570973180285531
INFO [04-21|21:46:07] Starting P2P networking 
WARN [04-21|21:46:07] Light client mode is an experimental feature 
INFO [04-21|21:46:07] RLPx listener up                         self="enode://7c9336aba172b8cf5cc41563d8ae18dc5a5a9cebff6745589f967aa8c2a839324e7a41012878fb3edf56015a92849d4b6b0aa8acc0b07aada493dfae230f43fc@[::]:30303?discport=0"
INFO [04-21|21:46:07] IPC endpoint opened: /Users/Joekiepau/Library/Ethereum/testnet/geth.ipc 
ERROR[04-21|21:46:07] Failed to retrieve current release       err="Missing trie node 40bcaeed491b9c002f2f7af3141041bd0f4e02ad5320d6ec12c338c85bb73529"
Starting "golem"...
(golem) Waiting for VM to come online...
(golem) Waiting on a pseudo-terminal to be ready... vmx_init: processor not supported by Hypervisor.framework
Machine didn't return an IP after 120 seconds, aborting
ERROR    [golem.docker.manager               ] DockerMachine: failed to start the VM: Command '['docker-machine', 'start', 'golem']' returned non-zero exit status 1
Error checking TLS connection: Host is not running

**Comment by mfranciszkiewicz** [comment]
The OS X Hypervisor framework is reporting that your processor is not supported. This means that Docker's xhyve driver is not compatible with your hardware.

You can verify the compatibility by:
- typing `sysctl kern.hv_support` in terminal. It should print `kern.hv_support: 1`
- typing `sysctl -n machdep.cpu.brand_string`. Your processor should support _Unrestricted Mode_, which is available in _Wolfdale_ and later architectures. For reference, see https://en.wikipedia.org/wiki/List_of_Intel_CPU_microarchitectures

**Comment by gipskruid** [comment]
@mfranciszkiewicz thanks.. hardware problem indeed :(

**Comment by doncat99** [comment]
@gipskruid, What does hardware problem means? I met the same problem as well, any hint? Thanks.

**Comment by gipskruid** [comment]
Means your computer processor isnt strong enough. Nothing you can do..

Op 22 jun. 2017 11:44 schreef "doncat99" <notifications@github.com>:

@gipskruid <https://github.com/gipskruid>, What does hardware problem
means? I met the same problem as well, any hint? Thanks.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/golemfactory/golem/issues/1016#issuecomment-310331200>,
or mute the thread
