### ISSUE TITLE
Subtask renders correctly but shows status "Failure" [Golem 0.5.3] [macOS 10.12.4]

### ISSUE THREAD

**Issue by jet86** [golemfactory/clay#1022]
I have discovered that all subtasks are coming back with a status "Failure" however when I look in the task's tmp folder, the subtasks have actually correctly rendered. The "stderr.log" file in each subtask folder gives the same error message:

> AL Lib: (EE) ALCplaybackOSS_open: Could not open /dev/dsp: No such file or directory

**System details**
Golem 0.5.3
macOS 10.12.4

**Comment by badb** [comment]
This error message should not cause task failure. It's not important for task that can be rendered in Golem. 

1. Are there any additional error messages in logs? 
2. Did you use advance verification options? If yes what was the parameters? 
3. Did this error happen once or is it reoccuring? For one specific scene or for all scenes?

**Comment by jet86** [comment]
1. There are no other error messages in stderr.log - stdout.log appears to show that the rendering is completed successfully for the subtask. I will post a copy of stderr.log and stdout.log a bit later. Are there any other log files that would be useful for me to post?
2. I did not enable advanced verification
3. This happened with 2 different scenes I have tested. I will try with some other scenes later to confirm.

**Comment by slowkow** [comment]
@jet86 Can I please ask you explain how to verify that the task completed? Where is the output located?

I'm also getting this message:

```
INFO [05-02|11:03:38] Imported new block headers               count=1   elapsed=16.625ms number=856132 hash=d181f6…85ac01 ignored=0
WARNING  [golem.task.taskkeeper              ] Wrong task header received Deadline already passed
WARNING  [golem.task.taskkeeper              ] Wrong task header received Deadline already passed
WARNING  [golem.task.taskkeeper              ] Wrong task header received Deadline already passed
INFO [05-02|11:03:55] Imported new block headers               count=1   elapsed=13.468ms number=856133 hash=f9184b…a2afaa ignored=0
HyperG: done   ef5e0977732dbf683007d3434869f4180627a4eb273f412037b0025deac34540
WARNING  [golem.docker.task_thread           ] Task stderr:
['blender', '-b', '/golem/resources/piscina3.blend', '-y', '-P', '/golem/work/blenderscript.py', '-o', '/golem/output/test_render3_3', '-F', 'EXR', '-f', '1']
AL lib: (EE) ALCplaybackOSS_open: Could not open /dev/dsp: No such file or directory

ERROR    [golem.task.taskthread              ] Task computing error: Subtask computation failed with exit code 247
```

System:
Golem 0.5.3
Ubuntu 17.04

**Comment by badb** [comment]
@slowkow This error message means that your docker run out of memory. How much memory do you have available on your system and how much have you set for Golem?

**Comment by slowkow** [comment]
I'm testing golem on a Linode server with 1GB memory. I guess it'd be nice to add "recommended system resources" to the documentation, with a listing of RAM, CPU, and GPU recommendations.

**Comment by jet86** [comment]
This issue is still occurring for me on 0.6.0 - please let me know what details are needed to determine the cause of this problem.

**Comment by jet86** [comment]
Attached is a zip of the tmp folder including multiple "failed" subtasks, as well as the correctly rendered slices of each subtask.
[tmp.zip](https://github.com/golemfactory/golem/files/1035539/tmp.zip)
