### ISSUE TITLE
UnicodeDecodeError - Windows 10

### ISSUE THREAD

**Issue by CTKaaa** [golemfactory/clay#1062]
What should I do with this error at start application?

Im not programmer. Please, help me!

![default](https://cloud.githubusercontent.com/assets/28686011/26033379/b6f94fb2-38b3-11e7-93d7-6d71a4ca5aa4.png)

```!python

File "c:\python27\lib\ntpath.py", line 108, in join
path += "\\" + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb3 in position 14: ordinal not in range(128)
```

**Comment by jiivan** [comment]
It's realted to this bug in `Python2`: https://bugs.python.org/issue20140

The easiest workaround for now is to run golem by user without non-ascii characters in username.

**Comment by badb** [comment]
This was fixed by switching to Python3
