### ISSUE TITLE
What is the relation between output image resolution and rendering time (for Blender)?

### ISSUE THREAD

**Issue by azawlocki** [golemfactory/clay#108]
One method of estimating how much time will be required to render an image with Blender renderer could be to reduce the resolution to, say, 0.01 of the final number of pixels. Is it reasonable to expect that the final image will require 100x more time than the reduced version?

**Comment by magdasta** [comment]
![timevspixels](https://cloud.githubusercontent.com/assets/13525071/12352403/fb945ba0-bb85-11e5-9c03-d2fa67abec8e.png)

**Comment by chfast** [comment]
It's hard to see, are they linear?
