### ISSUE TITLE
Uninstaller Leaves Junk Behind (Windows 10)

### ISSUE THREAD

**Issue by Deozaan** [golemfactory/clay#1082]
As mentioned in my comment in Issue #1075:

I ran the uninstaller which told me after a second or so that everything had been uninstalled. But I still have Kitematic (Alpha), Docker Quickstart Terminal, and Oracle VM VirtualBox shortcuts on my desktop. In my opinion this is bad behavior. An uninstaller should uninstall all the stuff that the installer installed.

I see no listing for Kitematic in Windows' Uninstall Programs section of the Control Panel. Clicking the shortcut makes it open a Docker Toolbox, which does show up in the control panel. Uninstalling it gets rid of the Kitematic and Docker Quickstart shortcuts. Uninstalling VirtualBox gets rid of the VirtualBox shortcut. But now I'm left wondering what other junk got left behind on my system by this.

**Comment by maaktweluit** [comment]
Docker Toolbox is no longer bundled with golem since version 0.19.0
Thanks again for the report!
