### ISSUE TITLE
fix public / private port ambiguity

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#109]
In network node class we have private port, public port, private and public address and a list of addresses. The system seems to work fine, but mainly because we have a nice type of nat in the office, where public port usually = private port. Is public port properly set in different situation? Is it properly used by other nodes?

**Comment by mfranciszkiewicz** [comment]
`P2PService.find_node` (called by `PeerSession._send_peers`) explicitly returns private addresses and ports. Because nodes currently filter reachable private addresses with addition to public ones, both should be sent in the `Peers` message.

**Comment by etam** [comment]
@badb @mfranciszkiewicz 
Question:
In `P2PService.find_node` if `node_key_id` is None we might send peers we haven't received hello from. So we're not sending key_id for example (the `node_info` field might be None and `node_name` might be an empty string).

But in `P2PService.try_to_add_peer` the logic assumes that key_id is there.

So: Do we want to support sending reduced info like only (IP address, port) pair?

If yes, then `P2PService` needs refactoring around `try_to_add_peer` method and `incoming_peers` dictionary. If not we just need to cleanup `find_node` method.

**Comment by mfranciszkiewicz** [comment]
@etam On the other hand, we're always sending a `node` object ( `golem.network.p2p.Node` ) in the response, so all known node info is already included in a `Peers` message. A recent change, which made it to 0.13.0, takes advantage of that fact. Golem now tries to connect to (in order):
1. a known ip:port
2. public address : public port
3. private addresses : private port

#2385 tries to get rid of `task_owner_addr` and `task_owner_port` sent in `TaskHeader` along with a `node` object, which makes them redundant (and, in some cases, making connections not possible).

**Comment by etam** [comment]
@mfranciszkiewicz 

> On the other hand, we're always sending a `node` object ( `golem.network.p2p.Node` ) in the response, so all known node info is already included in a `Peers` message.

Are we? As I wrote, `PeerSession.node_info` is `None` after creating the `PeerSession` object and is set a value in `_react_to_hello`. If we send `Peers` message while we haven't received `Hello` from other node, we're sending `None` in "node".

**Comment by mfranciszkiewicz** [comment]
@etam `self.p2p_service.add_peer` and `self.p2p_service.add_to_peer_keeper` are called when the connection is verified.

You've been running this code since 0.13.0.

**Comment by etam** [comment]
Oh, ok. So in `Task` message we can just send a list of serialized `Node` objects? Dicts created in `find_node` seems redundant.

**Comment by mfranciszkiewicz** [comment]
Yes. I even wanted to incorporate this change into that PR, but it grew a bit too much.

**Comment by etam** [comment]
We have a lot of ways to detect our network:
- stun to detect public ip
- connecting to `DEFAULT_CONNECT_TO`, `DEFAULT_CONNECT_TO_PORT` to detect which local address is used.
- calling monitor `ping-me` to have ports checked from outside.

**Comment by etam** [comment]
There's one thing we're not detecting, but can be implemented: public port.

When connecting to other node, the remote node can send in a response hello the port which he sees the connection is coming from. This could be also used to detect public IP (this could replace STUN).

This could  work for P2P and Task ports. Hyperdrive should handle this by itself and report it's public port to golem.

**Comment by mfranciszkiewicz** [comment]
@etam This would only work if the remote node initiated a connection to us, not the other way around. In the latter case, it will be a random port assigned by the operating system.

Currently, public ports are read via UPnP (if available).

**Comment by etam** [comment]
>  In the latter case, it will be a random port assigned by the operating system.

Right. My knowledge about networking needs some refreshing.

So, in case someone manually creates a port mapping on router, where external listening port is different, then it seems there's no way to detect it.

**Comment by mfranciszkiewicz** [comment]
Summing up:
- node's public IP address is discovered with STUN and also UPnP (if available and enabled)
- public ports are known only thanks to UPnP, otherwise are assumed to be same as private ones
- currently, we try to make use of all addresses sent by the other node and filter out unreachable ones (using naive address - network matching)
- there are few PRs addressing this issue:
    - #2540 - Allow users to specify the public IP address and ports via command line / config file
    - #2385 - Cleanup socket addresses in `TaskHeader`, `WaitingTaskResult` / `WaitingTaskFailure`
    - #2454 - Drop owner_address, owner_port and owner_key_id from Task classes and builders
