### ISSUE TITLE
Payment GUI

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#110]
Implement a method in graphical user interface that allows to see received and send payments. 
There should be two methods, that allow us to check the payments group by nodes and group by tasks.

**Comment by badb** [comment]
The basic version of draft is ready. Things that should be changed:
- Some payment data should be part of Golem state. They should be saved in database and recover after application restart.
- Only newest payments should be loaded with possibility to load more. 
- There should more information about computing / requesting node, maybe after double clicking the row.

**Comment by globatum** [comment]
@chfast and @badb How's this coming along? Are we ready to close this? I think the latest GUI should have addressed many concerns.
