### ISSUE TITLE
No log files if Golem is not run as administrator on windows 10

### ISSUE THREAD

**Issue by luithefirst** [golemfactory/clay#1111]
Only if golemapp.exe is run as administrator logs are being created in "C:\Program Files (x86)\Golem\logs".

There is no warning in the console that this failed.

**Comment by lagorsse** [comment]
I am not part of the golem dev team, however, I intend to understand more the code to implement an application.

From [wikipedia](https://www.wikiwand.com/en/User_Account_Control)

> Applications written with the assumption that the user will be running with administrator privileges experienced problems in earlier versions of Windows when run from limited user accounts, often because they attempted to write to machine-wide or system directories (such as Program Files) or registry keys (notably HKLM). UAC attempts to alleviate this using File and Registry Virtualization, which redirects writes (and subsequent reads) to a per-user location within the user’s profile. For example, if an application attempts to write to “C:\program files\appname\settings.ini” and the user doesn’t have permissions to write to that directory, the write will get redirected to “C:\Users\username\AppData\Local\VirtualStore\Program Files\appname\settings.ini”.

So it's normal, the log file is just written somewhere else, there is no error to catch. However, a warning could be displayed.

I will try to do a code proposition.

**Comment by badb** [comment]
The logs should be saved in C:\Users\<your user name>\.local\golem if your run golem in non-administrative mode (which is recommended).
