### ISSUE TITLE
Cant install on windows

### ISSUE THREAD

**Issue by influence160** [golemfactory/clay#1127]
Exception in attachement

![golem](https://user-images.githubusercontent.com/3180939/27265047-4f886132-548e-11e7-96f0-10ad6aa5b600.png)

**Comment by Josh1billion** [comment]
You need to add your Geth directory to your Windows system path.  I ran into this as well, and that fixed it.

**Comment by influence160** [comment]
i thing golem dont install geth, because when i search for "geth" in my C:\ i dont find any thing

**Comment by Josh1billion** [comment]
Hmm, in that case you should be able to just download + install Geth manually and add it to your path.  Assuming the Geth installation is the only part of the Golem installation that failed, it may work.

**Comment by badb** [comment]
Golem tries to install geth, but geth Windows installer used restrictive limits on PATH length. It should be fixed now, so we're hoping that new realses will be free from this issue (https://github.com/ethereum/go-ethereum/pull/3419). 
Right now, you can check if there's no geth install in C:\Program Files\Geth and if not dowload id and add to PATH manually. Sorry for inconvenience.

**Comment by influence160** [comment]
i have installed Geth manually and reexecute Golem, now i have more log but an other Exception
![image](https://user-images.githubusercontent.com/3180939/27502171-91e0a00c-5872-11e7-8fb8-8a58ad263518.png)


maybe he does not install all required things not only Geth ?
