### ISSUE TITLE
[FUNC] Add identifier in version for custom builds

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/clay#1137]
Hey Golem team,

A few days ago i came across your project and I think its an amazing concept. Since then i have checked out the repository, got it running and read though most of the docs.

The first thing i saw when running from source was that the version was exactly the same as the release, 85 commits ago.

I propose to add an identifier to the version so the developer can easily see what build is running. This can be done using git:
```
git describe --tags --always --dirty
```

When on a tag this picks the tag as version, when behind it appends the number of commit and a partial sha, like this:

|state|output|
|------|--------|
|tag|0.6.0|
|develop|0.6.0-85-g0eba37f|
|dirty|0.6.0-85-g0eba37f-dirty|

When [attempting to implement](https://github.com/golemfactory/golem/compare/develop...maaktweluit:build-sha-in-version?expand=1) this i found the returned value is a valid semver in all 3 cases.
Though besides this i can not for see any other impact of this change, please advise.

Please let me know what you think, if its a bad idea please toss it. But when you like it, i can finish the sample in code and make it into a merge able PR.

Thanks for reading! 
Hope it helps!

Maaktweluit

**Comment by jiivan** [comment]
Fixed by #1856
