### ISSUE TITLE
converting relative to absolute path in sripts/maketestgt.py does not work

### ISSUE THREAD

**Issue by azawlocki** [golemfactory/clay#114]
This line: https://github.com/imapp-pl/golem/blob/develop/scripts/maketestgt.py#L8
should include a call to `os.path.abspath()`:

```
dir_ = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
```

We better check if `__file__` is used correctly in other places where it was introduced as a replacement for `GOLEM` env var, for example here: https://github.com/imapp-pl/golem/blob/develop/golem/appconfig.py#L52

**Comment by badb** [comment]
https://github.com/imapp-pl/golem/pull/115
