### ISSUE TITLE
Allow to change min reputation value for requestor/provider nodes

### ISSUE THREAD

**Issue by kascheri12** [golemfactory/clay#1190]
My requestor reputation has become -768%. When I try to start a task as a requestor, I am disconnected from the network. Nodes can't compute my subtasks because my reputation is so poor. There is no way to change the minimum requestor score to something less than -100% from the GUI. I would like to, as a provider, set my minimum required requestor value to be -1000% so that I can compute subtasks for nodes like mine.

**Comment by badb** [comment]
There are some problems with computing properly estimated reputation value. However the fact that your node has low reputation, you are constantly disconnected and can't compute task, implicates that your node is not working properly. Probably you don't have public ip or forwarded ports: https://github.com/golemfactory/golem/wiki/Testing#how-to-start-testing
Maybe there is also some problems with geth no your machine, that pushes your reputation further down. Can you please check if there are some ERRORS when you start golem node?
