### ISSUE TITLE
Replace pyelliptic

### ISSUE THREAD

**Issue by mfranciszkiewicz** [golemfactory/clay#1217]
We should look for a replacement for`pyelliptic` since it is no longer maintained.

Proposed replacement: https://github.com/pyca/cryptography

**Comment by Wolf480pl** [comment]
AFAIK this issue reduces to ethereum/pydevp2p#58 cause I don't see pyelliptic used anywhere in golem code.

**Comment by Wolf480pl** [comment]
`cryptography` doesn't call (or provide a way to call) OpenSSL's `check_key` :(

**Comment by mfranciszkiewicz** [comment]
Initial 1.1-compatible version of `pyelliptic`: https://github.com/mfranciszkiewicz/pyelliptic

**Comment by maaktweluit** [comment]
Yay! maybe we can also resolve some of the loading / path hacks at the top of https://github.com/golemfactory/golem-messages/blob/master/golem_messages/cryptography.py

**Comment by badb** [comment]
@mfranciszkiewicz Can we close this issue?

**Comment by mfranciszkiewicz** [comment]
@badb I believe so. Closing.
