### ISSUE TITLE
Description of minimum requirements for Golem node

### ISSUE THREAD

**Issue by slowkow** [golemfactory/clay#1221]
Could you please add some text describing minimum hardware requirements for a Golem node?

I'm thinking of something like this:

> To run a Golem node that renders Blender scenes efficiently, we recommend a machine with at least XXX GB of RAM, a XXX Ghz CPU with XXX cores, and a graphics card with XXX RAM and XXX cores. Our tests show that machines with these resources are able to finish rendering most Blender scenes in XXX minutes. Machines with fewer resources will not be efficient and will not complete jobs in a timely manner.

The best place for this text would be:

- the README
- the Wiki
- other text that is visible to newcomers

I apologize if you already have this documented somewhere. I was not able to find it the last time I searched around.

**Comment by ArcAster** [comment]
I think a more concise definition of "efficient" is necessary.  Once Golem is running with real ETH, it's likely people will look for "minimum hardware requirements" in terms of the monetary returns they'll make or the bare minimum to run a working node.

It might be a good idea to list benchmarks for common consumer CPU's (intel Core-i7 7700k, Ryzen 1700), a few "budget" Xeon CPU's  (i.e. Xeon e5-2660 or e5-2670) and on the low end something embedded or an arm platform (xeon D, intel, atom cxxx or desktop ARM v8 platform?) capable of running Docker (being able to run Docker seems to be the current lower-bound in terms of hardware compatibility).

**Comment by slowkow** [comment]
Of course, exhaustive benchmarks with many variables would be even more useful than a concise paragraph with some technical details. This is also more work.

Let's start simple: what are some examples of machines that are known to work as Golem nodes?

If you have a working Golem node that is successfully rendering scenes, please feel free to create a post in this issue.

Template:

```
CPU: Intel/AMD/ARM XXX Ghz XXX model
RAM: XXX GB
GPU: Nvidia/AMD XXX GB XXX model

Scene XXX renders in XXX minutes.
Scene XXX renders in XXX minutes.
etc.
```

**Comment by jet86** [comment]
The problem is that scenes vary dramatically in complexity and render time, and you also don't know what your node is rendering.

**Comment by slowkow** [comment]
To address this problem, choose some examples scenes, like the ones that are distributed with golem.

**Comment by jet86** [comment]
That doesn't address the problem. You are either a requestor or a provider for any particular task. If you are a requestor, you know what scene is being rendered and how long it took, but not the specs of the nodes doing the subtask computations. If you are a provider, you know what your specs are, but not what scene is being rendered or even what part or how much of the scene you are rendering (in general you won't even know when you are rendering, though you could monitor processes to work out that you are rendering something).

**Comment by badb** [comment]
@dixon-hill Would it be possible to add minimal requirements to some FAQ & wiki pages?

**Comment by dixon-hill** [comment]
@badb I have an explanation here. If there is anything you think I should expand upon, let me know. https://github.com/golemfactory/golem/wiki/FAQ#what-are-the-optimal-settings-for-my-machine-to-run-golem
