### ISSUE TITLE
Errors when running Golem on win8/x64 : ƒÆ╗ Cannot start Golem: Error: spawn golemapp ENOENT and Golem exited with code 4294967295

### ISSUE THREAD

**Issue by Bogrolls** [golemfactory/clay#1228]
Gday,

I had the previous version of golem running and working. I have installed the latest version this morning and when I execute the binary the GUI appears but does not appear to do anything. 0 Nodes etc.

The command prompt says this 
C:\Program Files (x86)\Golem>
IPC Handlers created.
­ƒÆ╗ Starting Golem...
­ƒÆ╗ Cannot start Golem: Error: spawn golemapp ENOENT

I see another user has a similar problem on the slack channel, however I couldn't see what the solution was.

https://golemproject.slack.com/archives/G1RBKD5B2/p1499789247245776

I've tried basic stuff, running as admin etc. All port forwards are in place and worked with previous versoin, not sure what else to try.

Any help would be appreciated.

Thanks.

**Comment by Bogrolls** [comment]
Can Confirm that adding C:\Program Files (x86)\Golem to the %PATH% variable did fix this issue.
Like others i've got another issue now.

Dialogue box comes up (shortly after the GUI) and says "Failed to execture script golemapp", the cmd prompt shows the below exit code.

C:\Program Files (x86)\Golem>
IPC Handlers created.
­ƒÆ╗ Starting Golem...
­ƒÆ╗ Golem exited with code 4294967295

C:\Program Files (x86)\Golem>golem

C:\Program Files (x86)\Golem>
IPC Handlers created.
­ƒÆ╗ Starting Golem...
­ƒÆ╗ Golem exited with code 4294967295

**Comment by barryleybovich** [comment]
As additional info here, I noticed that there was no geth process running so I ran it manually but ended up with no change. Here's my full exchange afterwards for reference. 
```
C:\Program Files (x86)\Golem>docker-machine create golem --driver virtualbox
Creating CA: C:\Users\Barry\.docker\machine\certs\ca.pem
Creating client certificate: C:\Users\Barry\.docker\machine\certs\cert.pem
Running pre-create checks...
(golem) Image cache directory does not exist, creating it at C:\Users\Barry\.docker\machine\cache...
(golem) No default Boot2Docker ISO found locally, downloading the latest release...
(golem) Latest release for github.com/boot2docker/boot2docker is v17.06.0-ce
(golem) Downloading C:\Users\Barry\.docker\machine\cache\boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v17.06.0-ce/boot2docker.iso...
(golem) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
Creating machine...
(golem) Copying C:\Users\Barry\.docker\machine\cache\boot2docker.iso to C:\Users\Barry\.docker\machine\machines\golem\boot2docker.iso...
(golem) Creating VirtualBox VM...
(golem) Creating SSH key...
(golem) Starting the VM...
(golem) Check network to re-create if needed...
(golem) Windows might ask for the permission to create a network adapter. Sometimes, such confirmation window is minimized in the taskbar.
(golem) Found a new host-only adapter: "VirtualBox Host-Only Ethernet Adapter #2"
(golem) Windows might ask for the permission to configure a network adapter. Sometimes, such confirmation window is minimized in the taskbar.
(golem) Windows might ask for the permission to configure a dhcp server. Sometimes, such confirmation window is minimized in the taskbar.
(golem) Waiting for an IP...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with boot2docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: docker-machine env golem

C:\Program Files (x86)\Golem>docker-machine env golem
SET DOCKER_TLS_VERIFY=1
SET DOCKER_HOST=tcp://192.168.99.100:2376
SET DOCKER_CERT_PATH=C:\Users\Barry\.docker\machine\machines\golem
SET DOCKER_MACHINE_NAME=golem
SET COMPOSE_CONVERT_WINDOWS_PATHS=true
REM Run this command to configure your shell:
REM     @FOR /f "tokens=*" %i IN ('docker-machine env golem') DO @%i

C:\Program Files (x86)\Golem>@FOR /f "tokens=*" %i IN ('docker-machine env golem') DO @%i

C:\Program Files (x86)\Golem>golem

C:\Program Files (x86)\Golem>
IPC Handlers created.
ƒÆ╗ Starting Golem...
ƒÆ╗ Golem exited with code 4294967295
```

**Comment by mfranciszkiewicz** [comment]
`Failed to exectue script golemapp` usually indicates that a dependency has failed to start. To make sure that all dependencies are available for Golem, try executing the following commands in a command line window:
- `docker-machine` (Windows and macOS)
- `geth version`
- `hyperg --version`

If any of these fail, please try adding the relevant installation directories to your `PATH` environment variable.

Also, please note that running `geth` manually will cause the client to synchronize with the main (not _test_) network. Golem currently uses the test network to execute transactions.

**Comment by barryleybovich** [comment]
@mfranciszkiewicz marek, all of those commands individually work for me. is there a way to manually run `geth` and point it to the testnet? I believe `geth` is my problem

**Comment by mfranciszkiewicz** [comment]
@barryleybovich The problem is that geth's port and ipc socket path are both set by Golem. A new geth instance will be started anyway. 

Here's an example invocation: 
`C:\Program Files\Geth\geth.EXE --datadir=C:\Users\%USER%\AppData\Local\golem\golem\default\ethereum\rinkeby --cache=32 --syncmode=light --rinkeby --port=53257 --ipcpath=C:\Users\%USER%\AppData\Local\Temp\rinkeby-53257 --nousb --verbosity 3`

You can view Golem's process tree to see if geth child process is missing. `Process Explorer` is a great tool for that.
