### ISSUE TITLE
Use Docker for windows instead of Docker toolbox

### ISSUE THREAD

**Issue by alexeyyakimovich** [golemfactory/clay#1229]
Hi!

I'm using windows 10 and i already have "Docker for windows" installed.

Can i reuse installed Docker?

And i also have the same troubles as #1228. Can multiple Docker be the cause?

**Comment by mfranciszkiewicz** [comment]
On Windows, Docker for Windows cannot be used alongside Docker Toolbox. Golem does not currently support Docker for Windows.

If you encounter the `ENOENT` error, try adding Golem's installation path to your system `PATH` variable.  Here's a guide on how to do that: https://www.java.com/en/download/help/path.xml .

**Comment by BlackRule** [comment]
Will it be supported?
