### ISSUE TITLE
Changing config using old GUI switches end port to 0

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#1230]
1. Describe steps that can reproduce this issue. 
2. Fix issue

**Comment by banasiakadam60** [comment]
To reproduce:
1) `cat ~/.local/share/golem/default/app_cfg.ini | grep 'end port'`
2) `end port` should be set to `60102`
3) Launch `golemapp` (old GUI)
4) Go to `Preferences`->`Provider`
5) Change anything (eg. RAM or CPU) and save with `Change` on the bottom of the window
6) `cat ~/.local/share/golem/default/app_cfg.ini | grep 'end port'`
7) `end port` would be set to `0`

**Comment by banasiakadam60** [comment]
Right now, with #1323 `end port` in point 7 should still be set to `60102`

**Comment by badb** [comment]
Not important anymore, because old GUI was removed.
