### ISSUE TITLE
Running tasks inside docker

### ISSUE THREAD

**Issue by azawlocki** [golemfactory/clay#124]
A task should specify a docker image in addition to the script file and resource files. Task script and resources should be copied to the docker container running the specified image, and run there.

**Comment by badb** [comment]
Blender and Lux are already running in Docker. We need also a simple docker container with python and the move Dummy Task to Docker. 

We still don't now what to do with VRay, PBRT and 3dsmax.

**Comment by chfast** [comment]
I would drop the other environments for now.
