### ISSUE TITLE
Are you guys dead ?

### ISSUE THREAD

**Issue by h4rpreet** [golemfactory/clay#1241]
wtf are you doing guys ? 75% from last month. No progress, nothing. Wtf is this man ? Check the price it has dropped so much. Do you even care to fix the blockchain due to which withdrawals deposits can work again on polo ???

Comon release brass so price can go up and i can dump this shit coin. 

Regards

**Comment by WaterTrooper** [comment]
WOW. You are such a nice and helpful human.
