### ISSUE TITLE
How do I login into Golem?

### ISSUE THREAD

**Issue by mohtamohit** [golemfactory/clay#1250]
Hello, I recently downloaded Golem to my PC so that I rent out some computing power of my PC. But, here, I don't see a login option into the Desktop app, how would, my wallet in that case be maintained?
See, the screen in the attached screenshot and I don't see any login option there, maybe because of which I am unable to "Start Golem" i.e clicking on "Start Golem" gives no response.

![golem](https://user-images.githubusercontent.com/16120547/29005908-6fc46d9c-7b03-11e7-9802-43d8d0326a47.JPG)

**Comment by vectraboyv6** [comment]
same here matey :(

**Comment by mohtamohit** [comment]
@badb @mfranciszkiewicz Can you please help us with this ?

**Comment by badb** [comment]
Hi! 
You are not able to log into golem, it just should generate you a new id and use it to connect with the network. This message means that your Golem app does not start properly. Firstly, check if there is no geth process active before you start Golem - it may cause problems. If that doesn't help check this webpage: 
https://docs.golem.network/10-troubleshooting.html
If you still cannot find a solution, then please send us email to tech@golem.network with more details, ie. your OS, and golem log files.

**Comment by mohtamohit** [comment]
Thank you @badb. Will try again and get back if there are problems again.
