### ISSUE TITLE
ETH Wallet configuration

### ISSUE THREAD

**Issue by Fabryprog** [golemfactory/clay#1251]
Hello.

Can i use my ether wallet id into golemapp?

I am using linux with nogui params

**Comment by badb** [comment]
No, it's not possible yet. Golem is still on testnet and it uses automatically generated Ethereum addresses.

**Comment by Fabryprog** [comment]
Hello. Golem is still on testnet?

king regards

**Comment by maaktweluit** [comment]
Yes, golem is still running on the testnet
