### ISSUE TITLE
Two tests fail on Arch Linux w/ Python 3.6

### ISSUE THREAD

**Issue by marmistrz** [golemfactory/clay#1255]
Log: https://gist.github.com/marmistrz/d4c76b9cc5ba495512afb2bf772bc6f7

**Comment by badb** [comment]
Can you make sure that this issue is still relevant? First error was probably caused by indeterminism in dummy_task test.

**Comment by marmistrz** [comment]
The problem still persists and is similar to the latest failed AppVeyor build: https://ci.appveyor.com/project/golemfactory/golem/build/develop-1328 (but not exactly the same)

This seems to be related to the hyperdrive, since it's the only place which requests the port 3292.

**Comment by marmistrz** [comment]
It looks like the problem is gone. Maybe I still had the errors due to not having rerun `setup.py develop`.
Actually, now only the GUI fails, but the GUI is to be removed soon (tm), so closing.
