### ISSUE TITLE
The LuxRender docker test leaves artifacts

### ISSUE THREAD

**Issue by marmistrz** [golemfactory/clay#1256]
... in the project root dir. The test is located in `/home/marcin/proj/golem/tests/golem/docker/test_docker_luxrender_task.py`

	luxrender-output.exr
	luxrender-output.png

They should be removed on cleanup, actually: there's even a field `files_to_remove`

**Comment by ggruszczynski** [comment]
fixed in https://github.com/golemfactory/golem/pull/1286
