### ISSUE TITLE
MacOS installation issue

### ISSUE THREAD

**Issue by leonchu886** [golemfactory/clay#1265]
Could be a newbie question, but simply couldn't find any answers online...

Tried to install the MacOS Golem yesterday but encounter issues below. 

I can run the command “sudo chown root:wheel /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve” separately and it asked my root password. But during the “brew” process, it didn’t ask the pasword and just failed…

**brew cask install golem — verbose**
==> Satisfying dependencies
==> Installing Formula dependencies: golem
==> Installing golemfactory/golem/golem
==> Downloading https://github.com/golemfactory/golem/releases/download/0.7.1/golem-macos-0.7.1.tar.gz
Already downloaded: /Users/leon/Library/Caches/Homebrew/golem-0.7.1.tar.gz
==> Verifying golem-0.7.1.tar.gz checksum
tar xzf /Users/leon/Library/Caches/Homebrew/golem-0.7.1.tar.gz
==> echo docker-machine-driver-xhyve need root owner and uid
docker-machine-driver-xhyve need root owner and uid
==> sudo chown root:wheel /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
Failed to execute: sudo chown root:wheel /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
Error: Failed executing: sudo chown root:wheel /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
Follow the instructions here:
 https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/formula.rb:1804:in `block in system’
/usr/local/Homebrew/Library/Homebrew/formula.rb:1742:in `open’
/usr/local/Homebrew/Library/Homebrew/formula.rb:1742:in `system’
/usr/local/Homebrew/Library/Taps/golemfactory/homebrew-golem/golem.rb:26:in `install’
/usr/local/Homebrew/Library/Homebrew/build.rb:139:in `block (2 levels) in install’
/usr/local/Homebrew/Library/Homebrew/formula.rb:1093:in `block in brew’
/usr/local/Homebrew/Library/Homebrew/formula.rb:1905:in `block in stage’
/usr/local/Homebrew/Library/Homebrew/resource.rb:97:in `block in unpack’
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp’
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run’
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir’
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run’
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp’
/usr/local/Homebrew/Library/Homebrew/resource.rb:93:in `unpack’
/usr/local/Homebrew/Library/Homebrew/resource.rb:85:in `stage’
/usr/local/Homebrew/Library/Homebrew/formula.rb:1884:in `stage’
/usr/local/Homebrew/Library/Homebrew/formula.rb:1088:in `brew’
/usr/local/Homebrew/Library/Homebrew/build.rb:114:in `block in install’
/usr/local/Homebrew/Library/Homebrew/utils.rb:554:in `with_env’
/usr/local/Homebrew/Library/Homebrew/build.rb:111:in `install’
/usr/local/Homebrew/Library/Homebrew/build.rb:188:in `<main>’
Error: Kernel.exit

**brew doctor**
Your system is ready to brew.

**brew --config**
HOMEBREW_VERSION: >1.2.0 (no git repository)
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8518ffdee19c0c985e8631e836b78624e4926c7f
Last commit: 27 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2e06c93bb235678476490e6c04e6ccde5ae53432
Core tap last commit: 27 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.11.0 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.6.0_65-b14-468
macOS: 10.12.6-x86_64
Xcode: N/A
CLT: 8.3.2.0.1.1492020469
X11: N/A

Thanks!

**Comment by O1O1O1O** [comment]
Same problem here - was hoping it was fixed by now.  I found some suggestions that `brew` doesn't allow sudo commands to run any more.  

However I found another issue about this that tells you how to eliminate the offending `chown` and `chmod` from the installation scripts and do them by hand. 
 See https://github.com/caskroom/homebrew-cask/issues/37308

Worked for me!
