### ISSUE TITLE
golem.network.p2p.node.Node should probably be a model

### ISSUE THREAD

**Issue by marmistrz** [golemfactory/clay#1274]
It's serialized as a JsonField here: https://github.com/golemfactory/golem/blob/9d087d90e358daf4cdb1c8b72eab45a817287075/golem/model.py#L176

This could be avoided if the class were simply a peewee Model (which can be used as a normal Python class, as far as I can see), constituted a separate table and the `sender_node_details` field were just a ForeignKey

**Comment by Krigpl** [comment]
Not relevant anymore.
