### ISSUE TITLE
Supported Ubuntu version?

### ISSUE THREAD

**Issue by mwinfie** [golemfactory/clay#1279]
The install script notes that it is for Ubuntu and Mint, but doesn't mention any version numbers. I'm getting a bunch of error messages running the install script on Ubuntu Server 17.04 and didn't know if I should be using a different version.

This is the output so far. It has been sitting at this point for a while and looks like it may have locked up. The last line that fails on the symbolic link is because I tried running this script once already with the same results.

------@------:~$ ./install.sh
./install.sh: line 15: python: command not found
./install.sh: line 15: python: command not found
./install.sh: line 15: python: command not found
Docker not found. Do you want to install it? (y/n) y
Geth not found. Do you want to install it? (y/n) y

INSTALLING GOLEM DEPENDENCIES

[sudo] password for -----:

INSTALLING GETH

gpg: keybox '/tmp/tmp420gyk7t/pubring.gpg' created
gpg: /tmp/tmp420gyk7t/trustdb.gpg: trustdb created
gpg: key 1C52189C923F6CA9: public key "Launchpad PPA for Ethereum" imported
gpg: Total number processed: 1
gpg:               imported: 1
Warning: apt-key output should not be parsed (stdout is not a terminal)

INSTALLING DOCKER

Cannot install docker. Install it manually: https://docs.docker.com/engine/installation/

Installing HyperG

wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
tar: This does not look like a tar archive

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
mv: cannot stat 'hyperg': No such file or directory
ln: failed to create symbolic link '/usr/local/bin/hyperg': File exists

**Comment by maaktweluit** [comment]
it looks like `python` is missing, can you check using `python --version`?
maybe ubuntu 17 only has `python2` or `python3`?

This causes HyperG to have the wrong install file.

P.S. you can use ``` on a line before and after the logs to format them all `monospace`

**Comment by mwinfie** [comment]
That was the issue. Thanks!

**Comment by etam** [comment]
I've stumbled upon the same problem. Fresh vagrant image of ubuntu xenial (16.04) does not have 'python' command, only 'python3'. We've migrated golem code to python3, so I think the install.sh should also use it.

**Comment by maaktweluit** [comment]
No need for python here, bash can handle it all:
```
wget -qO- --header='Accept: application/json' \
 https://api.github.com/repos/mfranciszkiewicz/golem-hyperdrive/releases \
 | grep browser_download_url | grep linux | head -n 1 | grep -o 'https[^"]*'
```

**Comment by etam** [comment]
Well, yes. But you're assuming you get a pretty printed json.

**Comment by maaktweluit** [comment]
indeed, combining the first 2 grep's into the `grep -o` could also work with non pretty json.

since github is currently giving pretty json it seems better then assuming `python` is installed on 16.04
