### ISSUE TITLE
Windows Install Error - PATH not updated, orginial length 1777 > 1024

### ISSUE THREAD

**Issue by addons-xx** [golemfactory/clay#1280]
I have an error during install on windows.

I get AddToPath: original length 117 > 1024

from geth 1.6.5-cf87713d Setup: Installing

Bob
![geth1](https://user-images.githubusercontent.com/1128665/29494875-5af5264e-8568-11e7-84cb-65b3dfd0ba0c.jpg)

**Comment by banasiakadam60** [comment]
We only launch `geth` installer during installation. This problem is not in our installer, but in geth's. I've reported an [issue](https://github.com/ethereum/go-ethereum/issues/15118) in their repository.
Thank's for reporting ;)

**Comment by ederenn** [comment]
Any warning of this kind is bad UX. Even though it's error in theirs installer, golem user shouldn't see such a warning. If they cannot fix it, it should be hidden during golem installation - for example by changing PATH 

push PATH
PATH = nil
install geth
GETHS = PATH
pop PATH
PATH += GETHS

**Comment by badb** [comment]
Issue was solved with newer geth version. And we're not install geth client anymore.

**Comment by Mauricionik** [comment]
I just get the same error on version 1.7.3 (last version). :/
There is some action that I should perform to get that fixed?

Regards.

**Comment by apopovic** [comment]
Geth is trying to apply an environment variable but there are already to many signs. Delete not used path variables and it will work.
