### ISSUE TITLE
Line endings are inconsistent within the project.

### ISSUE THREAD

**Issue by marmistrz** [golemfactory/clay#1281]
`golemapp.py` has LF endings (Linux endings)
`apps/rendering/resources/imgrepr.py` has CRLF endings (Windows endings)

**Comment by maaktweluit** [comment]
is this also a rule in one of the linters? can help keep it clean :)

**Comment by marmistrz** [comment]
Hmmm... you could use dos2unix and check if anything has changed. Other than that, I don't know from the top of my head.

**Comment by maaktweluit** [comment]
https://docs.pylint.org/en/1.6.0/features.html

`expected-line-ending-format: LF`

can enforce this, eslint ( javascript ) has the same rule, thats how i know about it

**Comment by maaktweluit** [comment]
Commented this on the PR :)

**Comment by ggruszczynski** [comment]
It was decided to close this issue since we haven't noticed any bugs related to line ending issues (yet).
However, we may need reopen it in the future...
