### ISSUE TITLE
Investigate & fix payment matching problems

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#1291]
Sometimes batched transactions are not properly noticed by providers. Investigate what is the reason and fix it. It the simplest version it should expect that requestor will send tx.id. In the more advance version it should be just done by monitoring the blockchain.

**Comment by badb** [comment]
Check this PR for what was alread y done: https://github.com/golemfactory/golem/pull/1316

**Comment by ggruszczynski** [comment]
Allow batched payments #1441

**Comment by badb** [comment]
There are still some active issues: 

- https://github.com/golemfactory/golem/issues/1593
- https://github.com/golemfactory/golem/issues/1507
- https://github.com/golemfactory/golem-electron/issues/155
