### ISSUE TITLE
Allow to start task without GUI

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#1292]
Some time ago we have working --task option that allow user to run task saved in .gt file from command line. We removed this option becaues user can't save tasks in .gt format anymore and additionally we've change task creating API. 
The purpose of this task is to add this option again and define new file format that this option is able to read as task definition.

**Comment by marmistrz** [comment]
We settled the high-level vision of the task, no technical progress made yet due to #1254 and #1258.
