### ISSUE TITLE
Type checking in runtime

### ISSUE THREAD

**Issue by inexxt** [golemfactory/clay#1298]
In many places, types are now checked using `isinstance()`.
It would be probably a good idea to change that to some decorator or use `enforce` instead.

**Comment by marmistrz** [comment]
It would be best to annotate the whole code and run `mypy` statically, but that's not a job for one day. There are lots of places where it can't be done trivally.

**Comment by inexxt** [comment]
But still, it may sometimes be useful to do it in the runtime (eg if things are constructed dynamically, or in the annotated-not annotated code transitions) - mypy (and generally - static type checking) alone doesn't have such capabilities.
I suppose that some of these `insinstance()` checks were put there for these reasons.
