### ISSUE TITLE
Impossible to start session with Node

### ISSUE THREAD

**Issue by FabianGabor** [golemfactory/clay#1303]
I'm having connection issues. Port forwarding done, Golem GUI starts and shows 1-4 Nodes. Not getting any tasks so I created one. Logs show connection issues.

[golem.log.txt](https://github.com/golemfactory/golem/files/1250148/golem.log.txt)

Port forwarding on LEDE (previously OpenWRT):

![port_forwards](https://user-images.githubusercontent.com/1741703/29686925-f781988e-891a-11e7-9b4a-c4ae8198f53a.jpg)

**Comment by badb** [comment]
Hi!
Are you sure, that you don't have restrictive firewall or security software blocking external connections? 
Do you see the warning about ports being not available when you start Golem?

**Comment by kamathba** [comment]
I've done the same steps. Setup port forwarding, can see my node in https://stats.golem.network/show, but the task I created stays at 0% waiting. Main messages that repeat continuously:

WARNING  [golem.network.transport.tcpnetwork ] Decryption of message failed
WARNING  [golem.task.tasksession             ] Fail to decrypt message wrong ecies header

and,

WARNING  [golem.task.taskserver              ] Impossible to start session with Node , (key: 1e79d79c8ce10fe890392a2339b655fdbd3b823e2d278c76785418d60521538a70b3f3720c8c94fe66204cbabdb046e559bcdb5e3524874329be00cfcd151674)

Can provide more information if it would help

**Comment by badb** [comment]
@kamathba Can you send us your logs to tech@golem.network? Which OS are your using?
