### ISSUE TITLE
Add API key to github scripts

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/clay#1314]
In PR #1300 there is a script: `scripts/get-slow-argument.py` that calls the github API.
This fails some times on the public CI cloud due to rate limits.

If we add an authentication key to the call the limits are higher and it will fail a lot less.
Make sure the new value is stored as password in the CI tools, most offer masking sensitive data.

**Comment by badb** [comment]
@maaktweluit Is this issue still valid?

**Comment by maaktweluit** [comment]
Still valid but now we own the agents it is even less priority.
