### ISSUE TITLE
Completed tasks stuck in Awaiting status

### ISSUE THREAD

**Issue by cbetz** [golemfactory/clay#1318]
After completing tasks, in the History view I see the tasks in Awaiting status. I've waited several days:

![image](https://user-images.githubusercontent.com/458549/29814954-141dd07e-8c7d-11e7-84ed-0a35ad49cbfd.png)

I checked the net stats and it appears the tasks have completed:

![image](https://user-images.githubusercontent.com/458549/29814978-23c328da-8c7d-11e7-8796-4e37c150dd4a.png)

Is the expectation that these will advance to another status and the (test) GNT balance increased? Later version?

**Comment by badb** [comment]
This problem should be fixed by https://github.com/golemfactory/golem/pull/1316.
