### ISSUE TITLE
Tests for CLI with patching get segfault 

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#1338]
It was observed on Linux with Python 3.5.3. Tests from `tests/golem/interface/test_cli.py` gets segfault if they are called together with the rest of the suite. If only tests from this one file are called then everything works fine. 
Ask @banasiakadam60 for further details.

**Comment by Wolf480pl** [comment]
Each of these is enough to trigger the segfault:
`python -m pytest tests/apps/core/gui/controller/test_newtaskdialogcustomizer.py tests/golem/interface/test_cli.py`
`python -m pytest -v tests/apps/core/gui/controller/test_newtaskdialogcustomizer.py tests/golem/interface/test_cli.py -k 'test_execute_interactive or test_customizer'`

**Comment by Wolf480pl** [comment]
Adding `import readline` to `test_newtaskdialogcustomizer.py` right after `customizer._show_add_resource_dialog()` causes it to segfault without `test_cli.py`, with just one test: `test_customizer`.

**Comment by Wolf480pl** [comment]
Happens when you `QDialog.open()` and then `import readline` without importing readline before. Quick workaround: add `import readline` at the beginning of `test_newtaskdialogcustomizer.py`.

**Comment by Wolf480pl** [comment]
Minimal script reproducing the segfault:
```
from PyQt5.QtWidgets import QDialog, QMainWindow, QApplication

app = QApplication([])
window = QMainWindow()
QDialog(window).open()
import readline
```
