### ISSUE TITLE
Check code for saving task manager state

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#1339]
Check the code for dumping task manager state & task keeper state, do any necessary refactoring & changes.

**Comment by marmistrz** [comment]
As for the Task Manager, you mean dumping the tasks from the CLI or the `dump_task` function of taskmanager.py?

**Comment by badb** [comment]
Ask @badb or @jiivan for further details.

**Comment by marmistrz** [comment]
@badb this is a no-op, since I've already asked you :)

**Comment by badb** [comment]
There is this PR: https://github.com/golemfactory/golem/pull/1382
Please make sure that it's rebased/merged with develop and generally refreshed. Than it should be properly tested and merged. 
Additionally we may want to have a good quality test suite that covers task persistance issue.
