### ISSUE TITLE
Check Blender caching system

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#134]
Piotr Arłukowicz wrote: However, caching system (however imperfect) is the only place to keep things stable and deterministic. 
Check and describe how caching system in Blender works and does it change anything for Golem project.

**Comment by globatum** [comment]
@badb any movement on this?

**Comment by badb** [comment]
Blender cache generated on requestor machine can be added as normal Blender resources. This mechanism should be used to render simulation (fire, particles, smoke, etc.)
