### ISSUE TITLE
Error libcrypto.so.1.1: undefined symbol: ECDH_OpenSSL when launch ./golemcli -i 

### ISSUE THREAD

**Issue by lotrdocker** [golemfactory/clay#1344]
On Debian 9, the error **libcrypto.so.1.1: undefined symbol: ECDH_OpenSSL** occurs when **./golemcli -i** is executed.

There is a workaround. The version 1.0.2 of the library is also installed on the system, I renamed libcrypto.so.1.1 to, for example, libcrypto.so.1.1.bak and create a link named libcrypto.so.1.1 to libcrypto.so.1.0.2.

**Comment by marmistrz** [comment]
I'm not really sure which distros are officially supported by the Golem team, but see the workaround I did on Arch Linux, which ships with OpenSSL 1.1 too: https://github.com/golemfactory/golem/wiki/Installing-Golem-on-Arch-Linux-(unofficial)#final-patches

**Comment by ghost** [comment]
I too am having this problem with golemcli. 
Linux 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64 GNU/Linux

@lotrdocker I'm not that experienced working with Linux systems, so would it be possible for you to explain what you did in more detail? Thanks
