### ISSUE TITLE
Stuck on 'Starting Golem' 

### ISSUE THREAD

**Issue by Sneatbusiness** [golemfactory/clay#1349]
I can load the UI version on Windows however it's stuck saying 'Starting Golem' and I see a few CMD screens pop up for a moment and go.

Firewall on router/PC is disabled and I forwarded correct ports. Tried uninstalling and running as admin.

**Comment by badb** [comment]
Hi @Sneatbusiness 
Have you checked this list: https://docs.golem.network/10-troubleshooting.html ?
Usually problem like that is caused by wrongly configured PATH or problems with docker. Let us know if something from this instruction helps.
