### ISSUE TITLE
Mathematical absolute difference between two pictures

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#135]
Check how this method is working and decide if it can be used in Golem for image comparison / verification.

**Comment by azawlocki** [comment]
Any details?

**Comment by badb** [comment]
Piotr Arłukowicz wrote:  Blender can compare files using nodes also, which is just a _mathematical absolute difference_ between two pictures. I can be easily normalized, and the image which is the difference can be produced. This is not a numerical value however, and we can think about introduction some measures here. 
We should check whether this method may give as better results than PSNR.

**Comment by magdasta** [comment]
The '_mathematical absolute difference_' is just a difference calculated pixel per pixel on all channels (RGBA) (the result is a black picture when both are identical). This is a good technique to compare pictures which should be identical,  but this is not the case I suppose.
