### ISSUE TITLE
Change Python version in Dockers to Python3

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#1357]
Right now Golem is using Python3, while in Docker files we still have Python2. It's not a major issue, but may cause confussion and problems with further development.

**Comment by lukasz-glen** [comment]
Python 3.6, to be clear.
Updating the Docker image is simple. It is important to test it. We need to check if old and new Dockers  generate the same images/subtasks. The threat is that resulting images are different in size (rounding problem) or in quality or execution of Dockers are incompatible.
Please do not include new Docker in Golem production branch - it is more business decision.

**Comment by lukasz-glen** [comment]
Tests:
1. Mimic execution of Docker: render the same subtasks as regular Golem do. Check rendered images.
2. Create Golem with new Docker image and check if it works properly - computes subtasks.
