### ISSUE TITLE
Microsoft Visual studio throws an error during Golem installation if previous version was installed

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#1375]
During installation process, Golem tries to install Microsoft Visual C++ 2015 in a slightly older version that is currently supported. Therefore an error is triggered, if someone has newer version installed. Installation process is continued later properly and Golem works properly, but that's a bad UX.

**Comment by joshkirby** [comment]
I also had this problem during installation. Is there a workaround? Because of this I'm getting "Fatal Error! Failed to execute script golemapp" upon startup of the app.

**Comment by maaktweluit** [comment]
@joshkirby this warning during the installation should not cause the app to give this error when starting.

Good things to check when this error happens are:
- Is Golems program files folder in the PATH?
- Is C:\OpenSSL created and in your PATH?

When these checks are completed golem should create logs about any other error, if you are running the latest version they are in `C:\Users\<NAME>\.golem\default\logs` 

Feel free to tag me in the #testers channel on rocket chat if you have any more questions.
