### ISSUE TITLE
Support for geth 1.7.x

### ISSUE THREAD

**Issue by mfranciszkiewicz** [golemfactory/clay#1384]
Currently, only 1.6.x versions are supported and the application refuses to start. This affects both Ubuntu and macOS installations.

**Comment by kascheri12** [comment]
Why was this closed? What's the workaround? Did it get solved? I'm stuck not being able to run golemapp on a fresh Ubuntu installation with the latest version of geth.

**Comment by mfranciszkiewicz** [comment]
These start up issues have been resolved in #1384. The easiest workaround is to downgrade `geth` to 1.6.7.
