### ISSUE TITLE
Windows 8 is not supported

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#1393]
there should be some warning of this kind - not supported, out of date, not compatible, won't work properly - during an installation on win 8

**Comment by badb** [comment]
@maaktweluit Is this functionality included out-of-the box in Advance installer?

**Comment by maaktweluit** [comment]
@badb yes, we can select a list of available windows versions, should we only allow windows 10 pro next release?

**Comment by badb** [comment]
@maaktweluit Yes, please!
