### ISSUE TITLE
Create separated databases for golem instances

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#141]
Right now there is only one database that keeps data for all golem nodes on current machine. So users may have access to other users data. We should probably separate databases and put them in user's folders.

**Comment by chfast** [comment]
Refer to https://github.com/imapp-pl/golem/issues/83.

Ideally would be to finalize the design and refactor the code accordingly as it is needed. We should have a wiki page describing it, also describing individual files and directories in the "data dir".
