### ISSUE TITLE
Remove key_changed methods

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#1413]
Find all occurrences and remove them. One for sure is in `client.py`. We don't want to support this method longer.

**Comment by ai-nick** [comment]
hey I could work on this

**Comment by Wolf480pl** [comment]
@nickwilliamsnewby sure, go ahead, but if it's not done until monday, we'll have to do it ourselves.

**Comment by veruz** [comment]
Seeing as this hasn't been closed yet, still need someone to do it? If it's simple removal I could get on it.
