### ISSUE TITLE
A mechanism checking whether a new version of Golem is currently available on GitHub

### ISSUE THREAD

**Issue by gborowik** [golemfactory/clay#1430]
Due to the incompatibility of Golem versions, it would be nice to check and inform the user whether the new version of Golem is available on GitHub and should be downloaded.

**Comment by badb** [comment]
It will be inconvenient to use github API for that (limits!). We should check this somewhere else where it's not causing this problems. Monitor might not be the best idea, so let's add this check in seed nodes, ie. Golem node should compare it's version with seeds version.
