### ISSUE TITLE
Make sure that p2p2 behaves as expected 

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#1436]
* [ ] number of peers send as a reponse to send_peers should be constant (and probably less than dozen) 
* [ ] peer send as a reponse to send_peers shold be known closest neighbours of node that was asking
* [ ] make sure that old nodes are disconnected after some time
* [ ] make sure that nodes with "better" addresses, ie. closest in xor distance are prefered

There should be automate tests created for those points and they should be fixed in case of problems.

**Comment by mfranciszkiewicz** [comment]
Kademlia fixes: #1474 
Limiting the number of peers + peer neighborhood: #1491

**Comment by Krigpl** [comment]
Checking for closest neighbours and replacing old peers: #1537
