### ISSUE TITLE
Can not run golem. Start button not active.

### ISSUE THREAD

**Issue by Slavenin** [golemfactory/clay#1464]
Hi! I install latest version golem with installer. But after run start button is disabled. Firewall and antivirus i disable. Ports is open. W10 pro x64
![image](https://user-images.githubusercontent.com/4180077/31374515-f64a5914-ada6-11e7-9c46-883e2bd69496.png)

**Comment by badb** [comment]
Golem is still in starting phase. As you can see at the bottom, the dot is still red and some configuration is going on. This can take quite a long time. When everything is finished the button should become enabled. 
@Slavenin Can you affirm that after a couple of minutes message in the right corner is different? 

@ederenn This is a big UX problem and this behaviour app behaviour may not be clear to many users. Can you create an issue about this in golem-electron github?

**Comment by Slavenin** [comment]
>This can take quite a long time. When everything is finished the button should become enabled.

Where i will can see progress?

@badb, after ten minutes nothing change.
![2017-10-11_12-56-55](https://user-images.githubusercontent.com/4180077/31434034-e876321c-ae83-11e7-8eef-e13d9f9f9f17.png)

**Comment by 9head9tail** [comment]
![image](https://user-images.githubusercontent.com/16586875/33616061-1be63770-da1f-11e7-931f-c681ac999499.png)


what do i have to do to active the start golem button

**Comment by golemUser1** [comment]
Hi can you check the log file at:
C:\Users\$USERNAME$\AppData\Local\golem\golem\default\logs
