### ISSUE TITLE
differences in "Installation-on-Windows" instructions

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#1468]
supposed to be:

![55194cdec761dab107ceb5a6](https://user-images.githubusercontent.com/32061891/31401178-69b92ae2-adf2-11e7-9fda-03f2ae65d96e.jpg)

receieved:
 
![2](https://user-images.githubusercontent.com/32061891/31401261-ace653b2-adf2-11e7-8ea0-c93539c31e66.png)
(modify installer)

after clicking "fix it" (napraw), setup successful 

![3c](https://user-images.githubusercontent.com/32061891/31401499-541889fc-adf3-11e7-9291-09ac0ed67820.jpg)

**Comment by maaktweluit** [comment]
This happens when a newer version is already installed, as far as i have tested the newer version works fine for us too.

As a first step i will check for the current version, and then try to add incremental versions as well.
