### ISSUE TITLE
troubles with port forwarding, windows

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#1469]
after successful setting external ip, and forwarding 40102, 40103, 3282 ports, some check ups were run  - all ports remained "filterd" or  "timed out", golem nodes remained inactive

after:

typing "docker-machine regenerate-certs golem" in console

reoppening golem app

and reforwarding 3282 port (typo in port number)

golem started working

tested on:

![typ kompa](https://user-images.githubusercontent.com/32061891/31403194-ba523218-adf8-11e7-9710-d00dd1ecf2ca.png)

**Comment by badb** [comment]
What exactly is the problem here?

**Comment by ederenn** [comment]
Unclear message to user. When the ports are still closed - what actions should be taken, or is it just waiting because golem is trying to establish connections in the background ?
 Unclear solution - what had helped.

**Comment by msayle81** [comment]
I think I am having a similar issue to what ederenn has described. I have forwarded the ports as detailed in the in the wiki, however whenever I start golem.exe, the 'Golem is having trouble connecting. You may need to check your router ports.' error message pops up. Left clicking on the popup makes it go away, and the status at the bottom of the app changes from Connecting to network, to 1 Node (or 2 Nodes etc). Changing to the Tasks tab also shows that Golem is ready (screenshots attached)

<img width="344" alt="connecting_to_network" src="https://user-images.githubusercontent.com/24998750/31818396-ade89628-b5e3-11e7-8ea8-9e9eb520d2cc.png">
<img width="345" alt="1_node" src="https://user-images.githubusercontent.com/24998750/31818398-ae2c7b0e-b5e3-11e7-8d9b-7c2c7d1717e8.png">
<img width="345" alt="tasks" src="https://user-images.githubusercontent.com/24998750/31818400-ae5e567e-b5e3-11e7-8fdc-ec0e22b5d531.png">

Does that mean I am successfully connecting? If so then it seems the error message is popping a little bit too early, before the app has finished connecting to the network, and may be confusing users that they have a networking issue even though they don't. Or do? I am not sure ;-)

Hope this helps

**Comment by ederenn** [comment]
Good remark, thank you for reporting it.  Currently this error message is popping up too early and in fact it's unnecessary. We're working on it, it will be solved in the next release.

**Comment by Sylhetrin** [comment]
Hi ALl,

Please help same problem i have with my Golem app. i have already open the virtual ports under my pc ip address? anything else i can do? 

![image](https://user-images.githubusercontent.com/36536215/36431131-1657e4ec-1657-11e8-90c1-11cc0b27c7e0.png)

192.168.1.4 is my pc ip address
