### ISSUE TITLE
Distillate common parts from scripts

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#147]
Computing task codes (scripts) don't use any external golem libraries and their code is often very similiar. 
One idea is to create libraries with common functionalities and add them to docker images. Maybe there is a better solution?

**Comment by chfast** [comment]
This is good idea. But let's keep it as a independent package.

**Comment by magdasta** [comment]
Scripts use gnr.renderingenvironment (blendertask, 3dsmaxtask, luxtask, vraytask) and golem.core.common (updategolem) - I'm not sure if keeping the scripts independent would be easy
