### ISSUE TITLE
Automatic tests for scripts

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#148]
We should find a method to test scripts, ie. task code that is computed inside docker. Blender and Luxtask are partially covered by docker tests, but this test isn't seen in codecov. 
Probably new "docker"-style of scripts that gets parameters from `params.py` instead from `extra_data` context can be simply covered by normal unit tests.

**Comment by shadeofblue** [comment]
@badb do you think that the `node_integration_tests` satisfy this requirement?

**Comment by badb** [comment]
To a great extend, but not fully - I guess we cannot track codecoverage easily.
Anyway apps script should have their own separate test suits in the future, so we can close this issue.

**Comment by shadeofblue** [comment]
okay, closing then
