### ISSUE TITLE
closing "fatal error" pop-up

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#1485]
Closing "fatal error" pop-up should close whole app. Currently clicking "ok" is closing only pop-up. The rest of application remains opened but unresponsive.  Only action possible is turning of the app.

**Comment by badb** [comment]
@ederenn Is this issue still valid? Can you close it if it's not or move to golem-electron if it is?

**Comment by ederenn** [comment]
it's valid in 0.11.0 Golem version, it is possible to get this message, by clicking Golem shortcut several times. Closing pop-up does not close application window.
in 0.12.0 it's not - clicking several times opens multiplied interface

<img width="1641" alt="screen shot 2018-03-01 at 18 02 53" src="https://user-images.githubusercontent.com/32061891/36858369-44a299de-1d7b-11e8-9e3f-f8d72451e0e1.png">

**Comment by badb** [comment]
@
