### ISSUE TITLE
if receieved "Fatal error" message, it should stay in front of application view

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#1486]
currently "fatal error" pop-out can be hidden under main application window
![fatal error](https://user-images.githubusercontent.com/32061891/31553836-0a54288a-b03c-11e7-8946-dd28d0ebf0a3.png)

![error pod spodem](https://user-images.githubusercontent.com/32061891/31553842-0ed63a74-b03c-11e7-81f4-ad49b66858b6.png)

**Comment by badb** [comment]
@ederenn Can you move this issue to golem-electron?

**Comment by ederenn** [comment]
https://github.com/golemfactory/golem-electron/issues/120

**Comment by maaktweluit** [comment]
Should this issue be closed now its moved?
