### ISSUE TITLE
Benchmark results API doesn't send default benchmark result

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#1493]
Default benchmark is treated differently than the other benchmarks. It is not computed in TaskComputer and is not registered with other apps. However, we should still attach it to other benchmarks results when we are sending full list of benchmarks.

**Comment by badb** [comment]
@mdtanrikulu Can you please tell me exactly with which API call do you have this problem? comp.environment.performance returns four benchamark results with DEFAULT included.

**Comment by mdtanrikulu** [comment]
@badb Here is the issue. #1475
