### ISSUE TITLE
install.sh in case of errors recomends getting help at http://golemproject.org:3000/

### ISSUE THREAD

**Issue by etam** [golemfactory/clay#1495]
...but there's nothing a browser could connect to.

**Comment by etam** [comment]
@badb While grepping for golemproject.org I've also found this: https://github.com/golemfactory/golem/blob/develop/golem/ethereum/scripts/eth.py#L36
Is it correct?

**Comment by badb** [comment]
The second one looks correct (old faucet on Pebble).
