### ISSUE TITLE
Remove old blockchain after the fork

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#1499]
After Byzantium fork and without geth version update many golem nodes may have wrong branch of the rinkeby blockchain kept. In new release we are updating geth version, but we should also remove chaindata for those users. We cannot do it during installation, because we don't know what directiories are used by a user to keep golem data. 
Golem after the start should check the hash of the forking blog and remove the chain data if it's not proper.

**Comment by mfranciszkiewicz** [comment]
Geth 1.7.2 automatically rewinds the existing chain to the Byzantium block and synchronizes with the correct chain.

Solution: upgrade to 1.7.2, remove manual chain initialization with rinkeby.json.

**Comment by mfranciszkiewicz** [comment]
Resolved in #1514
