### ISSUE TITLE
Failure in `TestDirSize.test_dir_size` (`du` strikes again)

### ISSUE THREAD

**Issue by azawlocki** [golemfactory/clay#150]
This assertion does not hold in my system: 
https://github.com/imapp-pl/golem/commit/2c37bad9beb7a32329de4d4fab0e8729fb4995a2?diff=unified#diff-b83968492e5a79c521762afe7383f724R27
`os.path.getsize()` returns `4096` for an empty dir, not `0`.

**Comment by badb** [comment]
Sorry, I've changed that to a same value that I used in asserLess below. It's probably much too huge, but it doesn't really matter here. Check if it works.  https://github.com/imapp-pl/golem/commit/3e1421f51d9cdf51fefabaf02e87721779ea2ca0

**Comment by azawlocki** [comment]
It works on my system, but in the first place, why do we want to assert that an empty dir occupies less than 10000 bytes in the fs? What if there is an fs with block size >= 10000?

**Comment by badb** [comment]
I thought that 10000 is a very safe estimation. Hm, ok, so we may just save `get_dir_size` for an empty folder and than check whether new sieze is at leasto for 50000 greater than empty dir size. 
But do you know whether test in lines 38-43 is safe in that case? I add there a new file to which we don't have access and try to check whether `get_dir_size` doesn't change much (because it can't check new file size).

**Comment by badb** [comment]
And again.... (on Magda's Linux so, it's not a windows issue this time). 

```
__________________________ TestDirSize.test_dir_size
___________________________

self = <test_fileshelper.TestDirSize testMethod=test_dir_size>

    def test_dir_size(self):
        with self.assertRaises(OSError):
            get_dir_size("notexisting")

        self.assertFalse(os.listdir(self.testdir))
        empty_dir_size = get_dir_size(self.testdir)
        self.assertIsInstance(empty_dir_size, int)

        with open(self.testfile1, 'w') as f:
            f.write("a" * 20000)
        os.makedirs(self.testdir2)
        with open(self.testfile2, 'w') as f:
            f.write("b" * 30000)
        size = get_dir_size(self.testdir)

        self.assertGreater(size, empty_dir_size)
        self.assertGreaterEqual(size, 50000)

        self.assertGreater(get_dir_size(get_golem_path()), 3 * 1024 * 1024)

        if not is_windows():
            os.makedirs(self.testdir3)
            with open(self.testfile3, 'w') as f:
                f.write("c" * 30000)
            os.chmod(self.testdir3, 0o200)
            new_size = get_dir_size(self.testdir)
            self.assertGreaterEqual(new_size, size)

            errors = []
            get_dir_size(self.testdir, report_error = errors.append)
>           self.assertEqual(len(errors), 1)
E           AssertionError: 0 != 1

tests/golem/core/test_fileshelper.py:53: AssertionError
========== 1 failed, 143 passed, 18 skipped, 3 error in 65.83 seconds
==========
```

**Comment by badb** [comment]
@magdasta Did it ever happen again?
