### ISSUE TITLE
Transaction are marked as confirmed even though they have failed. 

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#1507]
![problem1](https://user-images.githubusercontent.com/483392/31657197-14f871f2-b32e-11e7-8cb7-7d1b671dbc30.png)
![problem2](https://user-images.githubusercontent.com/483392/31657344-696f81b2-b32e-11e7-9a57-a5f90a98a5d8.png)

**Comment by chfast** [comment]
Tx: [0x61ce8fe969ee265072bdbfd90ce4a1a2b2134d89b0a8ca9efb4b54ecffe28d0e](https://rinkeby.etherscan.io/tx/0x61ce8fe969ee265072bdbfd90ce4a1a2b2134d89b0a8ca9efb4b54ecffe28d0e).
