### ISSUE TITLE
[code smells] sharing global variables across modules

### ISSUE THREAD

**Issue by ggruszczynski** [golemfactory/clay#1510]
The Golem's global variables/constants are stored in 'golem/core/variables' (and perhaps in other places...) like `X = 123`

then, they are imported in the headers:
``` python

from golem.core.variables import X
```

ISSUE:
*** If you change `X` in module A.py then it won't be automatically changed in module B.py.

TODO:
- [ ] scan the code and check which `globals` are `variables` and which are `const`
- [ ] if they are variables then a bug may easily raise because of ***
- [ ] fix imports i.e., make the 'globals' really shared across modules (e.g., pack them into a class which is accessed by reference in python)

REFERENCES:
https://bytes.com/topic/python/answers/19859-accessing-updating-global-variables-among-several-modules
https://docs.python.org/2/faq/programming.html#how-do-i-share-global-variables-across-modules 

https://codehabitude.com/2013/12/24/python-objects-mutable-vs-immutable/

**Comment by mfranciszkiewicz** [comment]
They are all constants (note the caps). None of them is changed in the application. They either serve a purpose of:
- the one true value
- default value of a variable

The name `variables` and comments inside the file are, in this context, misleading.
