### ISSUE TITLE
error in dimensions box, mac

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#1516]
binnary version, macos, after brew update
bmw blender scene, low res, 500x400

first dimensions are marked red - as if there was an error 
it was possible to render 500x400 before update. 
golem is not allowing to start a task, still marking box in red

<img width="479" alt="screen shot 2017-10-18 at 17 21 36" src="https://user-images.githubusercontent.com/32061891/31727824-e8fdb7da-b42a-11e7-8a77-381b0d5ca4ff.png">

**Comment by ederenn** [comment]
not reproducible, after cancelling task and uploading it again, golem froze at naming tab, not allowing to click next. 
after reopening the app it was possible to start a task

**Comment by ederenn** [comment]
I've received something similar. After clicking "next" on task name tab, on next tab every box was marked red. Before typing or clicking anything. 
<img width="489" alt="screen shot 2017-10-20 at 13 43 16" src="https://user-images.githubusercontent.com/32061891/31820339-26b900a8-b5a1-11e7-9b4e-e04f812da930.png">

**Comment by badb** [comment]
@ederenn @mdtanrikulu Is it still valid or can we close this one?

**Comment by ederenn** [comment]
Haven't seen it in a while, I'll reopen issue if it appears again.

**Comment by mdtanrikulu** [comment]
@badb Nope, fixed in a time ago.
