### ISSUE TITLE
incoming payments still in awaiting state

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#1523]
incoming payments are staying in awaiting state, outgoing are confirmed or sent
the same for windows and mac, source versions

<img width="475" alt="screen shot 2017-10-19 at 15 21 37" src="https://user-images.githubusercontent.com/32061891/31774990-964d3c50-b4e7-11e7-91fa-6a4354bdebe7.png">

![plusminus](https://user-images.githubusercontent.com/32061891/31775001-a07590ec-b4e7-11e7-9936-7992e5a2d7a1.png)

**Comment by Krigpl** [comment]
I believe this is working correctly now.
