### ISSUE TITLE
Quality settings needed in settings tab

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#1530]
Right now user can set resolution of an image (in dimension boxes), there should be added settings for DPI - for image quality.

instead of "dimensions" there should be "resolution"

![frame](https://user-images.githubusercontent.com/32061891/31824397-2a73c24c-b5af-11e7-9286-3e9d776db791.jpg)

**Comment by ederenn** [comment]
quality can be improved by setting time of rendering, how long renderer should be computing ray tracing etc, how many cycles, sample rate, something like that

**Comment by badb** [comment]
More precisely it would be nice to have option that allows user to set Cycle sampling rate.
