### ISSUE TITLE
Automatically clear old computation related directories

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#1560]
Currently all the data that are used in Golem to generate and verify images are stored on a user hdd in specific directories. It's important for us to debug computation, however they dir size can grow up relatively quickly when Golem is intensly used. 
In the old interface there was a button that allows user to clean the directories. There is still a CLI command that allows to do it. There is no such options in the new GUI and it shouldn't be reintroduce. Instead golem data directories should be cleaned up automatically - data that are older than X should be removed. It's not defined how big should be X, however 3 days seems to be a safe option. 

Remember that this must work on all three OS.

**Comment by etam** [comment]
@badb When deleting thing is any internal synchronization required? Without it, it might be possible that data is removed while being used. Or do we just assume, that X is big enough that it's not needed?
As I see, the golemcli command has no such synchronization.

**Comment by badb** [comment]
We can assume that X is big enough that it's not needed.
