### ISSUE TITLE
RPM Based Linux Install Script

### ISSUE THREAD

**Issue by seangtkelley** [golemfactory/clay#1578]
Are there any plans for creating an install script for rpm based linux distributions (RHEL, CentOS, Fedora, etc...)?

**Comment by piotrantosik** [comment]
:+1:

**Comment by frafra** [comment]
It is a bad idea to have a script in the first place: manual procedure + package would be better.

Setup (tested on Fedora 27):
```
# dnf install docker gcc python3-devel libscrypt
# pip3 install scrypt
# ./install.sh
```

Run:

```
# setfacl -m user:username:rw /var/run/docker.sock
$ ./golem/golemapp
```

**Comment by xrow** [comment]
Want that too

**Comment by coreyryanhanson** [comment]
Would love to see a CentOs version as well.

**Comment by boralprophecy** [comment]
+1

**Comment by qinghuangchan** [comment]
+1

**Comment by HenryWait** [comment]
RPM package would be lovely!
