### ISSUE TITLE
Malicious Requestor can claim that he has already made a payment.

### ISSUE THREAD

**Issue by ggruszczynski** [golemfactory/clay#1583]
Provider should verify that the Requstor has priv keys to the `sender eth account`. 
Otherwise, a malicious Reqestor can scan blockchain to find transactions incoming to the Provider's account and claim that they were performed by him.

Solution:
The Requestor has to sign payment confirmation msg (e.g. the `subtask_id` field) with his eth keys.

**Comment by Krigpl** [comment]
This is no longer relevant.
