### ISSUE TITLE
No logs file created

### ISSUE THREAD

**Issue by etam** [golemfactory/clay#1587]
I've installed golem 0.9.0-RC using `./install.sh -dev`. Launched golem/electron/golem.

There are no log files from golem, either under `.local/share/golem/default/logs/` nor in the electron directory.

**Comment by etam** [comment]
I've installed 0.9.0 using `./install.sh`. Like above, still no logs from golem. There is new `geth.log` file though.

**Comment by etam** [comment]
I've installed latest 0.9.0. Still no golem logs.

**Comment by badb** [comment]
@etam Do you still have this problem with 0.11.0?

**Comment by etam** [comment]
@badb can't test it now, because 0.11.0 fails to run with openssl 1.1. Once 0.12 gets released I'll test it.

**Comment by etam** [comment]
With test binaries of 0.12 it seems fixed
