### ISSUE TITLE
Add flag to run golem with different log severity 

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#1597]
We can change log severity by editing logging.ini, but it will be more convenient if we are able to just change this with just adding specific flag that will change the severity. It's suggested that it will have three levels: 

* normal (no flag): log warnings and higher
* verbose (--verbose, -v): all logs (debug and higher)
* quiet (--quiet, -q): only critical and exceptions

**Comment by maaktweluit** [comment]
Made a step in this direction with: #1660 

Only the flags differ from the proposed solution:
- Normal: logs info and higher
- Verbose ( `--loglevel DEBUG` ): all logs
- Quiet ( `--loglevel WARNING` ): only warnings and up

Looks like the only thing currently missing is real quiet mode, maybe this can be solved adding `--loglevel ERROR` as an allowed option too.
