### ISSUE TITLE
Test test_processmonitor.py hangs on Windows

### ISSUE THREAD

**Issue by lukasz-glen** [golemfactory/clay#1599]
Test test_processmonitor.py hangs when executed on Windows with command python3 -m pytest. Reported by RDProjekt, verification is needed, maybe the reason is lack of public IP. Citation:

Nie przechodzi też test: tests\golem\core\test_processmonitor.py (wiesza się).

Przy czym u mnie się wiesza gdy się uruchomi wszystkie testy, np.:

python3 -m pytest

ale gdy się wykonuje tylko ten test, albo nawet wszystkie z golem:

python3 -m pytest tests/golem

to przechodzi.

**Comment by badb** [comment]
@RDProjekt We were not able to reproduce this, are you still able to observe this issue?

**Comment by RDProjekt** [comment]
Tests on Windows no longer hang when I run them using pytest ("pytest" or "python -m pytest"). i.e. in the same way as it is done in CI. I double checked this using various Windows machines.

They still hang when run by executing "python setup.py test" but I guess we just should not execute them that way.

So perhaps this issue can be considered as closed.
