### ISSUE TITLE
Clean install, new user, start-up not available in GUI... networking error?

### ISSUE THREAD

**Issue by Weldopedia** [golemfactory/clay#1603]
Hi, after uninstalling hyper-V, and restarting, I installed the golem.network 0.9 GUI with no problems (except installer has older version of 2015 C++).  Without running anything else, I start up the Golem GUI and wait for setup.  Then the GUI never advances from "Docker VM created."  I was searching around and poking and prodding and my conclusion is that I think the GUI is unable to communicate with the virtualbox VLAN.  When I run the Kitematic program, an error saying Kitematic is waiting too long for a response from the 2nd virtualbox adapter appears.  So I think the Golem GUI is timing out as well... any suggestions?

**Comment by badb** [comment]
@Weldopedia Have you tried running 0.11.0 version of Golem app? If you observe similiar problems with the new version, please let us know.
