### ISSUE TITLE
Remove geth from installation package, allow user to add their own geth instaces

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#1613]
We've added tools that allows user to interact with external geth services and does not require user to have local copy of geth. 
The code for starting local geth is still there.
What we should however do, is to remove geth from the installer and add option to the configuration that allows user to start their own geth instace if it's already installed on their machines. 
Configuration may expect that geth location is added to the path, may depened on some other environment variable (whatever is created by geth) or may allow user to define their own full path to geth.

**Comment by maaktweluit** [comment]
From reading the code it seems there is a command-line argument `--start-geth` that defaults to `False` and controls if local `geth` is started and used.

The next steps in this issue are:
- Remove geth from installers
  - mac
  - windows
  - linux
- Add electron option to toggle `--start-geth` on from the GUI
- test, test, test

**Comment by maaktweluit** [comment]
Tested it locally by removing geth from brew.
Golemapp 0.9.0 still working.

Then [removed it](https://github.com/golemfactory/homebrew-golem-dev/commit/c7fcb181a84ed3d2eb3e29f357269c00a1ff3394) with @gborowik from the homebrew dev repo. Will prepare a PR for the live repo so it can be merged on `0.9.1` release day

**Comment by maaktweluit** [comment]
Tested installer generation on windows, works!
