### ISSUE TITLE
Cleanup DirManager usage

### ISSUE THREAD

**Issue by etam** [golemfactory/clay#1622]
Right now DirManager seems to be used in two ways:

1. With golem's config directory as root_path it manages subdirs like "resources", "reference_data", "test", etc.
2. With any other subdirectory as root_path it's used to manage some deeper subdirs, like here: https://github.com/golemfactory/golem/blob/develop/golem/task/taskmanager.py#L87

I think it could be cleaned up to get rid of the second case. Possibly with one instance of DirManager created in Client and shared with TaskServer and ResourceServer.

This would also allow to simplify functions like Client.get_computed_files_dir, by using DirManager directly.

**Comment by etam** [comment]
@ggruszczynski you said you've done something in this direction. Do you have any comments?

**Comment by ggruszczynski** [comment]
Yes, we should have one instance of DirManager. 
Our code needs refactoring of I/O path.  Feel free to do so.

The rule is simple: keep it consistent across the project, i.e., 
clean copy-pasted 'path-helpers' functions and use one DirManager everywhere.

There is also a `fileshelper.py` which can be merged into DirManager.

btw, taskmanager isn't a clever one ;-)

``` python 
        self.root_path = root_path
        self.dir_manager = DirManager(self.get_task_manager_root())

...
     
    def get_task_manager_root(self):
        return self.root_path
```
