### ISSUE TITLE
Send Provider errors to stats monitor

### ISSUE THREAD

**Issue by lukasz-glen** [golemfactory/clay#1625]
There is a few % of subtasks that fail (see stats monitor). We have little knowledge what went wrong. Short error description should be send to stats monitor. It can be packed together with other stats and send to monitor or it can be send separately. It is up to an implementor to choose a proper way. On the monitor side error descriptions should be only stored for further analysis.

**Comment by maaktweluit** [comment]
From rocket chat someone had some idea's for the stats send to the monitor.
If not picked up in this issue please make a follow up issue to extend the send data.

- Benchmark scores
- Hardware specs
  - CPU speed
  - CPU model
  - ....

**Comment by ktomala** [comment]
This is resolved by https://github.com/golemfactory/golem-internal/issues/68 and https://github.com/golemfactory/golem/issues/2298 and https://github.com/golemfactory/golem-electron/issues/244

I'm marking this as duplicate.
