### ISSUE TITLE
Can not delete task/task persistance

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#1630]
Running from source, develop on Mac OS 10.12.

When trying to delete my task it does not go away. In the logs there is a WARNING:
```
WARNING  [golem.task.taskmanager             ] This is not my task '5d08e20f-b68e-4b46-9e9a-d92f3c0fdc2e'
```
Steps taken before this happened:
- Start task
- Shutdown golem ( app and electron ), the task was in waiting state
- Re-start both
- Task was still there and could not be deleted, task still in waiting state
- Task ended with timeout
- Task is still not able to be deleted.

Will try to reproduce and get a stable scenario where this goes wrong.

**Comment by ederenn** [comment]
Repeated on Windows, source version
task has timed out, 
application and electron was closed, 
restarted both
task is not able to be deleted

**Comment by ederenn** [comment]
Mac and Windows, source version, develop
checked during every state of a task - preparing, waiting, duration, finished task
 
steps to reproduce:
~ upload and start a task
~ wait for one of the states:
                           - preparing
                           - waiting
                           - duration
                           - finished
~ during chosen state, put computer in sleeping mode
~ wake up computer
~ wait for task to finish 
~ close app and reopen it
~ task is not able to be deleted

however, task is finished after sleep mode, it does not end in timeout

**Comment by ederenn** [comment]
encountered last week on Windows binaries:
after sleep mode in preparing state - task disappears after waking up 
after sleep mode in waiting state - task hangs permanently in waiting state, does not end in timeout nor computes. 
Timeout is set for specific amount of time, e.g. 15 min, after more than two hours task still was in waiting
after sleep mode, task in duration ended in timeout

needs double check if these problems still exist

**Comment by badb** [comment]
@ederenn Can you confirm that those behaviours with sleep mode for preparing and waiting state don't repeat themselves with current code version?

**Comment by badb** [comment]
@ederenn Please close this issue if you don't observe this behaviour anymore or comment if you do.
