### ISSUE TITLE
Error with command `settings show`

### ISSUE THREAD

**Issue by kascheri12** [golemfactory/clay#1632]
Error in golemapp logs
```
ERROR    [twisted                            ] WAMP message serialization error: huge unsigned int
```

Error in golemcli logs
```
>> settings show
ERROR    [golem.rpc                          ] RPC: call error: [Failure instance: Traceback (failure with no frames): <class 'autobahn.wamp.exception.SerializationError'>: success return value from invoked procedure "env.opts" could not be serialized: WAMP message serialization error: huge unsigned int
]
[21:49:47.009446] ERROR: Exception: success return value from invoked procedure "env.opts" could not be serialized: WAMP message serialization error: huge unsigned int
```

**Comment by maaktweluit** [comment]
hey @kascheri12 ,

Thanks for the report!
Some questions to help reproduce the errors:

- What OS are you using?
- How are you running golem? ( source or binary )
- When does the error occur? ( seen it before golemapp fully started, does it happen after too )

**Comment by kascheri12** [comment]
I believe this happened on MacOS 10.13.1 and I think the issue is due to Terminal. I'm not sure if I was running from source or binary but it seemed like a buggy terminal window. When I exit the golemcli, my terminal session was still not acting correctly. I solved this by closing the session and opening a fresh one, navigating back into golemcli and then everything was working right.
