### ISSUE TITLE
no milestones anymore?

### ISSUE THREAD

**Issue by Alino** [golemfactory/clay#1639]
Hi, I remember that this project had issues tagged with milestones for brass golem, iron golem etc.
Why are all milestones closed, where are the next milestones? I used to watch your progress with these milestones. Now I have no idea how close you are to the brass golem release.

**Comment by maaktweluit** [comment]
Hey @Alino 

The milestones are moved to trello:
https://trello.com/b/YL1qZ2pZ/brass-kanban

The blog post where this was announced has some more information on how / why:
https://blog.golemproject.net/11-after-11-11-5c7b8dd6df85
