### ISSUE TITLE
Files lost in transmission

### ISSUE THREAD

**Issue by magdasta** [golemfactory/clay#164]
Sometimes (quite often) master node doesn't receive files sent by slave (occurs in blender rendering, other engines need further investigation). The problem seems to be only with image files - logs are sent properly.
[slave_log.txt](https://github.com/imapp-pl/golem/files/128342/slave_log.txt)
[master_log.txt](https://github.com/imapp-pl/golem/files/128341/master_log.txt)
![gui](https://cloud.githubusercontent.com/assets/13525071/13014260/36b50778-d1b3-11e5-89c3-f6d96ba4b8bf.png)

**Comment by badb** [comment]
From logs it doesn't seem like it doesn't receive files. We have: 

> File data receiving 100 %                       2016-02-12 17:50:47,399 - golem.network.transport.tcpnetwork - INFO - Receiving file asdsad50001.exr, size 1730
> File data receiving 100 %  

And then it tries to pay for properly verified task. Are those .exr files saved in master's res directory? Maybe there is a problem with extension (lack of extension) or problem with putting images together?

**Comment by magdasta** [comment]
.exr was received only for subtasks 1 and 5 (visible in log). Also, .exr are saved only for these subtasks in the res dir:

drwxrwxr-x 2 magda magda    4096 lut 12 17:50 .
drwxrwxr-x 3 magda magda    4096 lut 12 17:50 ..
-rw-rw-r-- 1 magda magda    1736 lut 12 17:50 asdsad10001.exr
-rw-rw-r-- 1 magda magda      85 lut 12 17:50 asdsad1_1.err.log
-rw-rw-r-- 1 magda magda  382424 lut 12 17:50 asdsad1_1.log
-rw-rw-r-- 1 magda magda      85 lut 12 17:50 asdsad2_1.err.log
-rw-rw-r-- 1 magda magda  382552 lut 12 17:50 asdsad2_1.log
-rw-rw-r-- 1 magda magda      85 lut 12 17:50 asdsad3_1.err.log
-rw-rw-r-- 1 magda magda  382576 lut 12 17:50 asdsad3_1.log
-rw-rw-r-- 1 magda magda      85 lut 12 17:50 asdsad4_1.err.log
-rw-rw-r-- 1 magda magda  358769 lut 12 17:50 asdsad4_1.log
-rw-rw-r-- 1 magda magda    1730 lut 12 17:50 asdsad50001.exr
-rw-rw-r-- 1 magda magda      85 lut 12 17:50 asdsad5_1.err.log
-rw-rw-r-- 1 magda magda  358910 lut 12 17:50 asdsad5_1.log
-rw-rw-r-- 1 magda magda 1447254 lut 12 17:50 current_preview
-rw-rw-r-- 1 magda magda 1447254 lut 12 18:10 current_task_preview

In the slave's log all subtasks' .exr are sent, the extension seems to be OK for all of the files.
