### ISSUE TITLE
Can't connect on OS X

### ISSUE THREAD

**Issue by lagorsse** [golemfactory/clay#1661]
[golem.log](https://github.com/golemfactory/golem/files/1472745/golem.log)

I can't connect from my OS X, my ports are forwarded.

**Comment by badb** [comment]
Hi @lagorsse!
Your golem instance is not started properly, because it cannot run docker. 
Did you have previous version of golem installed?

**Comment by maaktweluit** [comment]
this docker error was solved by running `docker-machine rm golem && docker-machine create --driver xhyve golem`.
