### ISSUE TITLE
Is this ONLY limited to blender and rendering?

### ISSUE THREAD

**Issue by ghost** [golemfactory/clay#1671]
I need to run nodejs projects.

**Comment by badb** [comment]
Hi @TheRoboKitten!
Right now we are developing Brass - MVP concentrated on rendering with Blender and Luxrender. Further use cases will be supported in next release. We are however collecting requirements for additional use cases. Can you please write to contact@golem.network? I'll contact you with the right person to talk to about your nodejs projects.
