### ISSUE TITLE
Awaiting orders

### ISSUE THREAD

**Issue by Saintnicolai** [golemfactory/clay#1679]
Hi there, quite new to golem and dont know if im making a mistake or have done anything wrong but all tasks come up as "awaiting" and there are quite a few at this moment. how do I start making the tasks so they won't be awaiting orders. 
![skaermbillede 2017-11-19 kl 18 25 49](https://user-images.githubusercontent.com/33811370/32993908-1bc1f09c-cd57-11e7-8305-bbd555599493.png)

**Comment by kascheri12** [comment]
That's your history actually. Those are payments that have been made to another node in return for the computations to complete your tasks.
The tasks you're requesting can be found in the "Tasks" tab up at the top next to "Network".

**Comment by Saintnicolai** [comment]
So how do I make it so that I get the eter in my account?

________________________________________________________

Kindest regards

Nicolai Mandix Hansen
Coffee Ambassador | Campus Instructor US/UK
Nmh@joejuice.com<mailto:Nmh@joejuice.com>
+45 28710886 DK
+1 6467892157 US
+44 7932534600 UK

JOE & THE JUICE A/S
Østergade 26a
1100 København K
www.joejuice.com<http://www.joejuice.com>

IDGT 18:36:27

On 20 Nov 2017, at 02.22, Kenneth Ascheri <notifications@github.com<mailto:notifications@github.com>> wrote:


That's your history actually. Those are payments that have been made to another node in return for the computations to complete your tasks.

**Comment by maaktweluit** [comment]
This alpha version of golem uses the rinkeby test network of ethereum. There is no way inside the app to move your test GNT to another account.
