### ISSUE TITLE
MacOS wont run benchmark

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/clay#1698]
reported by @lagorsse on rocket

[golem_gal.log.txt](https://github.com/golemfactory/golem/files/1500281/golem_gal.log.txt)

```
2017-11-23 11:48:58 WARNING  golem.docker.task_thread            Task stderr:
/usr/bin/python: can't open file '/golem/work/job.py': [Errno 2] No such file or directory
```
Shows up for each benchmark on boot

- Tried installing golem with homebrew on sierra 10.12.6 (16G29)
- Did not work, then tried homebrew-dev and it worked.
- Had problems with docker-machine #1661 was solved by re-creating the `golem` docker-machine.
- Now this error shows up.

**Comment by maaktweluit** [comment]
Same bug has just been spotted on windows #1736 logs are in the comments there.

**Comment by kenadian** [comment]
Is there a solution for this? I've been trying to get around this for a bit. Don't know enough about how Docker to configure my way around.

2018-05-28 19:18:17 WARNING  golem.docker.task_thread            Task stderr:
/usr/bin/python: can't open file '/golem/work/job.py': [Errno 2] No such file or directory

I notice that I don't have a /Users/UserDirectory/.golem/ which I believe is where /golem/work/job.py should be hanging out if I'm supposed to be having a good time.

Thanks!

**Comment by ghost** [comment]
Yes python download it from GitHub and reinstall Golem.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by mdtanrikulu** [comment]
To fix this issue on Mac; 
1. Remove `golem` docker machine via `docker-machine rm golem`
2. Run `golemapp.py` to create docker machine automatically via `python golemapp.py` for source, `golemapp` for binary.
or to create docker machine manually; first run 
```
docker-machine create --driver xhyve --xhyve-virtio-9p
```
then run golem.
