### ISSUE TITLE
installation from source, no information how to install Graphical User Interface

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#1711]
Currently there's an information how to install source version of Golem, it is not mentioned that Graphical User Interface is not included, where from it can be installed (links, commands)  and whole instruction for installing GUI is missing.

It would be useful to have such an information under source installing instructions - for installing GUI go to page (with further instructions).

**Comment by jamuszyn** [comment]
Added message with a link while updating OS-x install instructions.
