### ISSUE TITLE
requests.exceptions.ProxyError

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/clay#1724]
Issue made from PR #1721 by @Hardstyles:

Hello i used a vpn and must go through a proxy.
Unfortunately, I can not find a config file where you can set this.

```
requests.exceptions.ProxyError: HTTPSConnectionPool(host='192.168.99.101', port=2376): Max retries exceeded with url: /v1.21/images/golemfactory%2Fblender%3A1.3/json (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden',)))
```

**Comment by badb** [comment]
@maaktweluit Do you know if this error is fixed?

**Comment by maaktweluit** [comment]
@badb  Not that i know of, we do not test much with vpn enabled, if you like i can enable it and run some tests
