### ISSUE TITLE
Seed only nodes with current protocol_id

### ISSUE THREAD

**Issue by jiivan** [golemfactory/clay#1728]
Current scenario:
 1. Seed (or any other) node runs for some time and collects some amount nodes in it's peer keeper and sqlite db.
 2. Node upgrades and hist protocol version changes.
 3. Node reached maximum connections capacity (`opt_peer_num`) and automatically disconnects any new incoming connection after sending a list of nodes.
 4. The incoming node gets a list of nodes that in worst case scenario are all using invalid protocol id.
 5. Cannot connect to p2p network.

Possible solution:
 Periodically clean all peer lists from nodes with mismatched protocol version.

**Comment by etam** [comment]
When sending a list of nodes, they are taken from `P2PService.peers`. Nodes are added there after their version is verified in `PeerSession._react_to_hello` (to be more precise, after responding to `ChallengeSolution` or `RandVal` message).

So even if in database there are nodes still running old version, seed won't send them to other nodes until it connects with them and verifies their version.

I don't know how bootstrap_go works yet.

**Comment by etam** [comment]
It seems that bootstrap_go works similarly.

The completely different thing is that it needs to be updated to the latest protocol.
