### ISSUE TITLE
Connection type (client/server) unknown, critical twisted

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#1730]
encountered on windows, source version, develop branch, after git pull (protocol id changed to 18;18 )

`` 2017-12-06 15:58:06 CRITICAL twisted                             b'Unhandled Error\nTraceback (most recent call last):\n  File "C:\\Users\\ederenn\\Projects\\golem-env\\lib\\site-packages\\twisted\\python\\log.py", line 103, in callWithLogger\n    return callWithContext({"system": lp}, func, *args, **kw)\n  File "C:\\Users\\ederenn\\Projects\\golem-env\\lib\\site-packages\\twisted\\python\\log.py", line 86, in callWithContext\n    return context.call({ILogContext: newCtx}, func, *args, **kw)\n  File "C:\\Users\\ederenn\\Projects\\golem-env\\lib\\site-packages\\twisted\\python\\context.py", line 122, in callWithContext\n    return self.currentContext().callWithContext(ctx, func, *args, **kw)\n  File "C:\\Users\\ederenn\\Projects\\golem-env\\lib\\site-packages\\twisted\\python\\context.py", line 85, in callWithContext\n    return func(*args,**kw)\n--- <exception caught here> ---\n  File "C:\\Users\\ederenn\\Projects\\golem-env\\lib\\site-packages\\twisted\\internet\\iocpreactor\\reactor.py", line 119, in _callEventCallback\n    evt.callback(rc, numBytes, evt)\n  File "C:\\Users\\ederenn\\Projects\\golem-env\\lib\\site-packages\\twisted\\internet\\iocpreactor\\tcp.py", line 552, in cbAccept\n    self.handleAccept(rc, evt)\n  File "C:\\Users\\ederenn\\Projects\\golem-env\\lib\\site-packages\\twisted\\internet\\iocpreactor\\tcp.py", line 594, in handleAccept\n    protocol.makeConnection(transport)\n  File "C:\\Users\\ederenn\\Projects\\golem-env\\lib\\site-packages\\twisted\\internet\\protocol.py", line 494, in makeConnection\n    self.connectionMade()\n  File "C:\\Users\\ederenn\\Projects\\golem\\golem\\network\\transport\\tcpnetwork.py", line 555, in connectionMade\n    self.server.new_connection(self.session)\n  File "C:\\Users\\ederenn\\Projects\\golem\\golem\\network\\p2p\\p2pservice.py", line 177, in new_connection\n    session.start()\n  File "C:\\Users\\ederenn\\Projects\\golem\\golem\\network\\p2p\\peersession.py", line 194, in start\n    raise Exception(\'Connection type (client/server) unknown\')\nbuiltins.Exception: Connection type (client/server) unknown\n ' ``

**Comment by Krigpl** [comment]
Fixed by #1731
