### ISSUE TITLE
No Work

### ISSUE THREAD

**Issue by AniimaL** [golemfactory/clay#1736]
Hello, 

I Open the port, i think Golem is ok on my computer but I never get a task. Why should I do ? 
If someone can help me plz.

![golem 4](https://user-images.githubusercontent.com/34220386/33742213-8c7f6a9a-dba7-11e7-9a7f-942542c647e0.PNG)
![golem 3](https://user-images.githubusercontent.com/34220386/33742214-8ca06498-dba7-11e7-9f3e-925c0d080e05.PNG)
![golem 1](https://user-images.githubusercontent.com/34220386/33742215-8cbd3cbc-dba7-11e7-9442-259550093d4d.PNG)
![golem 2](https://user-images.githubusercontent.com/34220386/33742216-8cd7f85e-dba7-11e7-9435-5206c3cbf409.PNG)

**Comment by maaktweluit** [comment]
Hey @AniimaL 

Thank you for your report!

From what you describe here everything should be fine, lets run some checks to see:
- Can you see yourself on https://stats.golem.network/show
- Did you test your open ports with an external tool? f.i. canyouseeme.org ( app must be running )
- Can you check for errors in your logs? `~/.golem/logs` on mac/linux and `C:\Users\<USER>\.golem\logs` on win.

You can paste the error lines here surrounded in ``` or send the while file

**Comment by AniimaL** [comment]
Hello @maaktweluit 

I Test ports with canyouseeme  and yes they are all open ! 

But I can't find logs :s

**Comment by AniimaL** [comment]
It's ok I find the logs 
[golem.log](https://github.com/golemfactory/golem/files/1543743/golem.log)

**Comment by slonus** [comment]
I have the same issue https://github.com/golemfactory/golem/issues/1700  and still no solution

**Comment by AniimaL** [comment]
UP PLZ !

**Comment by maaktweluit** [comment]
Hey @AniimaL 

This seems related to #1698 as well, @slonus can you check your log if you have the same error?

```
2017-12-06 23:28:27 WARNING  golem.docker.task_thread            b'Task stderr:\nshell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
/usr/bin/python: can't open file '/golem/work/job.py': [Errno 2] No such file or directory
```

Will comment on that issue that its on windows as well, this one can be closed as duplicate after we collected some more information:

- What version of golem are you running? ( v0.9.1? )
- How did you install Golem ( from installer? )
- Did you install golem before
  - If so, did you uninstall before installing
- Did you configure anything manually during or after installation? ( other folders then default, other settings then default )

**Comment by AniimaL** [comment]
@maaktweluit 

Yes, Golem 0.9.1, I install It from installer ans this was the 1st version of Golem I install. 

Humm yes, I install Golem in Desktop just that.

**Comment by slonus** [comment]
Hi @maaktweluit,

Yesterday I completely  uninstalled golem and today I've made a new installation of Golem 0.9.1 from installer. (the previous was 0.9.0 -> uninstall -> install 0.9.1).

There are no errors in the log file:
[golem.log](https://github.com/golemfactory/golem/files/1548802/golem.log)

**edit:**
Today I did clear install. I removed everything somehow connected to golem.  My node has now a different name.  Currently connected to 9 Nodes, 1000GNT, 0.02ETH. I haven't touch any settings, no task. Stopped golem increased the slider for machine resources to 61 - no tasks.

**new log after clean install**
[golem.log](https://github.com/golemfactory/golem/files/1548995/golem.log)

**Comment by AniimaL** [comment]
Me too after uninstal / reinstall  same issue :s 

To complicated, I will stop here.

**Comment by maaktweluit** [comment]
@slonus indeed the logs look OK, how long have you been running it? since it is a test net there are not always tasks requested.
For the second logs, did you quit the app at the end? if not it did crash there.

@AniimaL same error in the logs? the team will start investigating this error.
If you see any other error that might help please post it.

Thanks again both for running the alpha! its of great help to make the app better :)

**Comment by slonus** [comment]
Hi @maaktweluit ,

I closed the app. So there was no crash. I usually try about 30 to 60 minutes. 
I tried to create a task to see if it gets to other systems. I am connected to 9 nodes. 
Finally the log is full of some errors and warnings, hopefully interesting reading for you ;)

[golem.log](https://github.com/golemfactory/golem/files/1552550/golem.log)

**Comment by AniimaL** [comment]
I uninstall / reinstall. You can see the log
[golem.log](https://github.com/golemfactory/golem/files/1556679/golem.log)

**Comment by slonus** [comment]
Something has happened after upgrade to 0.10.0. I am getting no tasks but at least looks like I can request some work.
![obrazek](https://user-images.githubusercontent.com/19738712/34294987-45b397e8-e70b-11e7-8b29-5901e8ddb362.png)

It also seems that I already spent some GNTs on the requested work
![obrazek](https://user-images.githubusercontent.com/19738712/34295050-8e80b2bc-e70b-11e7-979f-45777ec05014.png)

**Comment by ilbarillo2014** [comment]
Hello, same situation with Golem v 0.10.0 is ok on my computer but I never get a task: 10 nodes running, but no history.
I got a possibile network connection problem, starting Golem, but I see the forwarded ports 40102, 40103 and 3282 opened...
Could you help me please ?

**Comment by lonelymyp** [comment]
Same problem. 0.10.0 default install from windows installer.
Folder `C:\Users\....\.golem` is empty.
In addition, I can not change the amount of resources allocated, always zero percent, cursor in the form of a crossed out circle

**Comment by golemUser1** [comment]
I seem to have the same issue #1700 .
i am running golem on  windows. my minimum price is very low, as same as reputation, so i expected having some jobs.
but nothing....

I checked https://stats.golem.network/show and found my golem client there:
![grafik](https://user-images.githubusercontent.com/35274214/34743979-fb195fc6-f58b-11e7-8df8-6db7f57e1b1b.png)

I also checked the Ports on CanYouSeeMe.org: 
all three (40102,40103,3282) port are open. 
I openend them for TCP and UPD connections.

I even tried rendering the "Render Local Test" with a demo. 
SO it seems that the golem is up and running correctly.

do you have an overview of offered Taks? 
that could be helpful. (I mean the umber of open tasks, and the nmebr of runnign tasks to be added to the stats page!)
maybe i simply came online at the wrong time, when there are no jobs published.

or maybe it is an Performance issue, maybe the performance of my golem is too low, so i am not selected?
![grafik](https://user-images.githubusercontent.com/35274214/34744384-50a212e8-f58d-11e7-98b5-e3ebc3d45b05.png)
somehow my Blender Benchmark seems way too low, for my NVidia graphics card.


however, i am not alone with this topic, just by looking at the List form https://stats.golem.network/show, I can see that 50% of all online golems, have not performed a single task.

**Comment by badb** [comment]
Hi @AniimaL @slonus @lonelymyp @golemUser1!
There were many changes in Golem app since you tried to use it, please try the newest version and if you still have problems with receiving job from the network please contact our user support on [Rocket](http://chat.golem.network/)!
