### ISSUE TITLE
Resource handshake error ... 'timeout' and 'Peer blocked'

### ISSUE THREAD

**Issue by kascheri12** [golemfactory/clay#1737]
I have multiple nodes running - I know which cliid's are mine. 
1. Why is my node being blocked? 
2. Can I forcefully unblock a node? 
3. Also, can I un-ban a node from a task?
4. What's the timeout for the Resource handshake? 
5. Why does my other node keep timing out now? 

This was not the behavior yesterday. These two nodes are located inside the same subnet - it should not timeout. They were computing together successfully 1 day ago.

```
INFO     [golem.resources                    ] Starting resource handshake with 'c18a7b661591f85654a744cee38b4bc1689194b4a8fb9cb5a34e42605efbe170f7c125ab1113d764f5e5181df3ab85a21710d13c329da5763b5e0b2a48891f98'
INFO     [golem.pay                          ] Peer count: 25
INFO     [golem.pay                          ] ETH: 0.01587866
INFO     [golem.pay                          ] GNT: 779.1666666666665
INFO     [golem.pay                          ] Next sendout in 456 s
INFO     [golem.pay                          ] Peer count: 25
INFO     [golem.pay                          ] ETH: 0.01587866
INFO     [golem.pay                          ] GNT: 779.1666666666665
INFO     [golem.pay                          ] Next sendout in 443 s
ERROR    [golem.resources                    ] Resource handshake error ('c18a7b661591f85654a744cee38b4bc1689194b4a8fb9cb5a34e42605efbe170f7c125ab1113d764f5e5181df3ab85a21710d13c329da5763b5e0b2a48891f98'): 'timeout'
ERROR    [golem.resources                    ] Resource handshake error ('c18a7b661591f85654a744cee38b4bc1689194b4a8fb9cb5a34e42605efbe170f7c125ab1113d764f5e5181df3ab85a21710d13c329da5763b5e0b2a48891f98'): 'Peer blocked'
```

Requestor = golem-0.9.1 on MacOS 10.13.2
cliid c18a7..... = golem-0.9.1 on MacOS 10.13.1

**Comment by badb** [comment]
1. Nodes are blocked when they are not able to exchange resources between each other. 
2. You cannot, because it doesn't make sense - if nodes are not able to exchange simple resouce between themselves, they won't be able to exchange resources and results. 
3. Nope. 
4. 20 seconds 
5. Older HyperG version were not working with each other in internal network. This should be fixed now. Feel free to reopen this issue if you observe this again in 0.11.0.
