### ISSUE TITLE
Windows unit test failing 'test_paymentskeeper.py'

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/clay#1738]
Running from source on windows server 2016 on AWS.

When running tests on windows the payment keeper fails on different points, sometimes it succeeds.

Logs from below are from different runs:
```
>       self.assertEqual(all_payments[0]["subtask"], "xxxxxx")
E       AssertionError: 'zzzzzz' != 'xxxxxx'
E       - zzzzzz
E       + xxxxxx
```

```
>       self.assertEqual(all_payments[2]["subtask"], "xxxyyy")
E       AssertionError: 'aabbcc' != 'xxxyyy'
E       - aabbcc
E       + xxxyyy
```

```
>       self.assertEqual(res[1].subtask, "xyz2")
E       AssertionError: 'xyz3' != 'xyz2'
E       - xyz3
E       ?    ^
E       + xyz2
E       ?    ^
```

```
>       self.assertEqual(res[0].subtask, "xyz1")
E       AssertionError: 'xyz2' != 'xyz1'
E       - xyz2
E       ?    ^
E       + xyz1
E       ?    ^
```

Am i missing a dependency? Can i provide any more data to investigate?
I can run the test manually with the same flaky results.

**Comment by badb** [comment]
@maaktweluit Do you still have this problems or is it solved?

**Comment by maaktweluit** [comment]
Tested this by removing the 2 skip lines, the same 2 errors show up. #2122

**Comment by maaktweluit** [comment]
`test_paymentskeeper.py` no longer exists.
