### ISSUE TITLE
Personal configurations disappear occasionally after restart

### ISSUE THREAD

**Issue by mdtanrikulu** [golemfactory/clay#1760]
I don't know if it's related with sqlite or something else, saved presets and node name disappeared after some restarts. I couldn't check hw preset yet but I'm trying to create same case to check.

**Comment by etam** [comment]
Presets are stored in internal database. We also keep the SCHEMA_VERSION in the database. If it changes (no matter up or down) we make no migration. We just drop all tables and create new ones. So presets that are stored in it are lost.

Currently there is a difference in SCHEMA_VERSION between develop and b0.11.0

So the easy solution is to say "it's not a bug, it's a feature". The harder solution is to start supporting database migrations.

**Comment by etam** [comment]
#191
