### ISSUE TITLE
Computing abilities 

### ISSUE THREAD

**Issue by mirsakhawathossain** [golemfactory/clay#1763]
Can golem work on python or other programming files? Is it possible to use golem for volunteer computing? If so I will use it.

**Comment by badb** [comment]
Hi @sakhawat18!

Not yet, it will be possible after more generalise task API is created. Are you able to describe us your use case with more details, so we can figure out how quickly it can be integrated with Golem? If yes, then please send us email to tech@golem.network and refer this issue.
