### ISSUE TITLE
Cant compute tasks on computer in golem office network.

### ISSUE THREAD

**Issue by Elfoniok** [golemfactory/clay#1765]
On the other node i can see that it accepted task but is not able to download resources.

Maybe its because its trying to use different address that was used using resource handshake?
In yesterday test we saw that resource handshake was done on local ip address, and then hyperg was trying to use public address.

Right now it should be quite easy to reproduce, some of our nodes in office are unable to compute task.

**Comment by mfranciszkiewicz** [comment]
Resolved with the 0.10.1 patchset
