### ISSUE TITLE
Docker machine problem, after installing Golem on Windows with previously installed Golem

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#1786]
Instalation itself goes successfully - installer is asking about removing previous version of golem, shortcut is created, no errors visible during installation.
After first launch of Golem, application remains in "starting Golem" state

message in logs:

```
2017-12-15 19:36:45 ERROR    golem.docker.manager                b'DockerMachine: failed to start the VM: Command '['docker-machine', 'restart', 'golem']' returned non-zero exit status 1.'
2017-12-15 19:36:46 WARNING  golem.docker.manager                b'DockerMachine: failed to env the VM: Command '['docker-machine', 'env', '--shell', 'cmd', 'golem']' returned non-zero exit status 1.'
2017-12-15 19:36:46 INFO     golem.pay                           b'Peer count: 25 '```

**Comment by ederenn** [comment]
manual solution
- close Golem
- close VirtualBox in Task Menager
- hit windows key and type "Add or remove programs"
- then search for "virtual" and select "modify"
- click repair

**Comment by maaktweluit** [comment]
This will be partially solved by #1988 

To make it even better, shall i add a warning or look for a fix from the application side @badb ?

**Comment by badb** [comment]
@maaktweluit Can you make some tests with different version of VMs and try to figure out when does the problem occur exactly so we can understand it better?

**Comment by maaktweluit** [comment]
Installed golem-0.9.1 on windows 10, versions:
- Docker : 17.06.2-ce
- Virtual Box : 5.1.26

Installed golem-0.10.0 on windows 10, versions:
- Docker : 17.10.0-ce
- Vitrual Box : 5.2.0

Installed golem-0.11.0 on windows 10, versions:
- Docker : 17.10.0-ce
- Vitrual Box : 5.2.0

Installed latest Docker stable, versions:
- Docker : 18.01.0-ce
- Vitrual Box : 5.2.4

During this whole test only between 0.9.1 and 0.10.0 the VirtualBox required repair. Making me think the bug only shows up when upgrading VirtualBox from 5.1.x to 5.2.x

**Comment by maaktweluit** [comment]
Made an item of this based on the new template of common problems and solutions:

# "Error Starting Docker" after upgrade of golem
## Symptoms:
- When `golem` starts it shows the error "Error Starting Docker"
![screen shot 2018-02-09 at 18 14 34](https://user-images.githubusercontent.com/10008353/36040756-b3bc64ae-0dc6-11e8-84e4-08fa270300d9.png)

- When starting `Docker Quickstart Terminal` it shows error "Error creating machine"
![screen shot 2018-02-09 at 18 15 57](https://user-images.githubusercontent.com/10008353/36040768-bcba4b02-0dc6-11e8-829f-ff2bb13af2e9.png)

- In `golem.log` it shows `ERROR    golem.docker.manager    DockerMachine: failed to start the VM: Command '['docker-machine', 'restart', 'golem']' returned non-zero exit status 1.`

## Description:
During the upgrade of golem, VirtualBox also got updated, this caused the existing docker-machines to stop working. 

## Resolution:
- close Golem
- close VirtualBox in Task Manager
- hit windows key and type "Add or remove programs"
- then search for "virtual box" and select "modify"
- click modify -> repair
- restart
## Found
20 Dec 2017 by @ederenn
## Relates to:
https://github.com/golemfactory/golem/issues/1786
## Affected version:
golem 0.9.1 and before

**Comment by no-tably** [comment]
Can confirm this is happening on golem-0.11.0 as well.

**Comment by maaktweluit** [comment]
@Misterdudeman did the resolution mentioned by @ederenn as first comment resolve the issue for you?

**Comment by moredillon** [comment]
Can confirm this is still happening on Windows 10, release version 0.15.0. I thought the original fix (repair/updating Virtual Box) worked for me. Nevermind, I'm still getting errors starting docker.

tried to start it via command prompt and get the same error

> docker-machine start golem
> Starting "golem"...
> (golem) Check network to re-create if needed...
> Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm golem --type headless failed:
> VBoxManage.exe: error: The virtual machine 'golem' has terminated unexpectedly during startup with exit code 1 (0x1).  More details may be available in 'C:\Users\user\.docker\machine\machines\golem\golem\Logs\VBoxHardening.log'
> VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine
