### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Chamith888** [golemfactory/clay#1797]
I m not a IT programmer but with my limited knowledge i installed the Golem Brass release, and set up the port forwarding also. But the "Start Golem" is not activated yet. There is a msg which reads "Docker VM Created". Any idea what should i do next ?
![image](https://user-images.githubusercontent.com/34727803/34235969-100520b8-e5ed-11e7-8dae-ef4a3f60eace.png)

**Comment by bullcrypto** [comment]
Had the same issue - rebooted machine - reran 0.10.0 and waited roughly 4 minutes. Windows asked permission to for programs (2) to use network, and it started.

**Comment by Chamith888** [comment]
thanks bullcrypto, 
The issue was the VT. I had to enable Intel VT from Bios and it worked.

**Comment by maaktweluit** [comment]
Great to hear it was solved! 
Going to close it now, feel free to re-open or open a new issue when you have any issues.

A good place to check when making an issue are the logs: `%LOCALAPPDATA%\golem\golem\default\logs` on windows
