### ISSUE TITLE
Info on installing and running GNR

### ISSUE THREAD

**Issue by azawlocki** [golemfactory/clay#18]
- Complete list of dependencies (python packages and other)
- Ideally on both linux (Ubuntu?) and windows 
- Maybe move from Readme.md to wiki

**Comment by chfast** [comment]
README.md should stay. But it should not be very long. If "building" instruction are going to be long, lets put them as wiki page.

**Comment by badb** [comment]
https://github.com/imapp-pl/golem/wiki/Installation
