### ISSUE TITLE
Golem installation

### ISSUE THREAD

**Issue by Date1** [golemfactory/clay#1805]
Well, I tried to install Golem, I have followed each step of installation but I can't execute golemapp. Please help me out

**Comment by badb** [comment]
Hi @Date1! 

Can you give us more detail? What OS are you using? What is exactly the problem? Have you checked this website https://docs.golem.network/10-troubleshooting.html? Can you share your logs with us?

**Comment by Date1** [comment]
I keep having the error of "can't execute golemapp" but I don't know how to kill geth 
Thank you for your help

**Comment by shijuleon** [comment]
See if you get hints from my installation process
shijuleon.com/blog/2017/12/22/install-golem-on-debian-10-buster.html

**Comment by badb** [comment]
@Date1 What OS are you using?

**Comment by Date1** [comment]
I am using Windows 7 premium

**Comment by badb** [comment]
@Date1 Windows 7 is not officially supported, Golem only supports Windows 10. 

Anyway, please send us your logs to tech@golem.network. They should be located in C:\Users\<your username>\.golem\logs. Please refer to issue 1805 in your email.

**Comment by maaktweluit** [comment]
when using the 0.10.0 release the logs have moved to: `%LOCALAPPDATA%\golem\golem\default\logs`
