### ISSUE TITLE
Golem stuck on 'Starting' [Alpha2 0.10.0] [OSX 10.12.6]

### ISSUE THREAD

**Issue by apolikamixitos** [golemfactory/clay#1812]
When I try to open the client, the screen is stuck with `Starting Golem` with no progress indication, I checked the debug tools it showed the WebSocket `ws://127.0.0.1:6xxx` connection wasn't established (Refused connection).

I checked all the processes related to Golem, I found the one related to running the worker, I tried to run it manually and I received this message:

```/usr/local/Cellar/golem/0.10.0/bin/golemapp -u -m crossbar.worker.process --cbdir "/Users/apolikamixitos/Library/Application Support/golem/default/crossbar" --worker worker-001 --realm crossbar --type router --loglevel info --title Golem

Failed to import scrypt. This is not a fatal error but does
mean that you cannot create or decrypt privkey jsons that use
scrypt

CROSSBAR_RICH_LOGGING_ENABLE=True
{"worker_title": "Router", "worker_id": "worker-001", "pid": 22813, "python": "CPython", "reactor": "KQueueReactor", "log_time": 1514411235.077891, "level": "info", "namespace": "crossbar.worker.process.run", "text": "Router worker \"worker-001\" process 22813 starting on CPython-KQueueReactor .."}

{"peer": "<pipe>", "abort": true, "reason": "WebSocket opening handshake timeout (peer did not finish the opening handshake in time)", "log_time": 1514411240.00547, "level": "warn", "namespace": "autobahn.twisted.websocket.WebSocketServerProtocol", "text": "dropping connection to peer <pipe> with abort=True: WebSocket opening handshake timeout (peer did not finish the opening handshake in time)"}
```

I hope this is helpful for you.

**Comment by maaktweluit** [comment]
Hey @apolikamixitos 

Thank you for the report!

Could you please share the logs of the golem application?
windows logs are in `%LOCALAPPDATA%\golem\golem\default\logs`, mac logs are in `~/Library/Application\ Support/golem/default/logs` and linux in `~/.local/share/golem/default/logs`

This way we can pinpoint the error and debug it faster.

**Comment by badb** [comment]
@apolikamixitos Please try out version 0.11.0. If the problem occurs again, feel free to comment and reopen the issue!
