### ISSUE TITLE
Golem GUI app - Docker fails to pull images

### ISSUE THREAD

**Issue by Technoprenerd** [golemfactory/clay#1817]
Version: 
Latest (28 December 2017)  GUI Golem app version.
Installed instructions from golem's wiki for gui on Mac.

Gui is stuck on 'Error pulling docker images'.

Log file:

> '
> WARNING  [golem.docker.manager               ] Docker: pulling image golemfactory/base:1.2
> INFO     [golem.pay                          ] Peer count: 25
> ERROR    [golem.docker.manager               ] Docker: error pulling images: Command '['docker', 'pull', 'golemfactory/base:1.2']' returned non-zero exit status 1.
> WARNING  [golem.docker.manager               ] Docker: building image golemfactory/base:1.2
> ERROR    [golem.core.async                   ] Caught async exception:
> Traceback (most recent call last):
>   File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
> 
>   File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
> 
>   File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
> 
>   File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
> 
> --- <exception caught here> ---
>   File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
> 
>   File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
> 
>   File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
> 
>   File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
> 
>   File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/node.py", line 60, in _run
> 
>   File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/node.py", line 91, in _setup_docker
> 
>   File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/docker/manager.py", line 146, in check_environment
> 
>   File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/docker/manager.py", line 317, in build_images
> 
>   File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/report.py", line 117, in wrapper
> 
>   File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/docker/manager.py", line 334, in _build_images
> 
>   File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/docker/manager.py", line 299, in command
> 
>   File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
> 
>   File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
> 
> subprocess.CalledProcessError: Command '['docker', 'build', '-t', 'golemfactory/base', '-f', 'core/resources/images/Dockerfile', '.']' returned non-zero exit status 1.
> 
> INFO     [golem.pay                          ] Peer count: 25
> INFO     [golem.pay                          ] Synchronized!
> INFO     [golem.pay                          ] ETH: 0.01541288
> INFO     [golem.pay                          ] GNT: 1000.0
> '

**Comment by maaktweluit** [comment]
Hey @Technoprenerd 

Thank you for the report!

Could you share the results of `docker-machine ls`?

Sometimes when docker updates the machine needs to be re-created. This can be done with:
- Close golem
- run in terminal `docker-machine rm golem` and confirm with `y`
- Open golem

The first start can take longer since it has to create the machine.

When this does not work for some people it helped to remove the whole docker cache folder, `sudo rm -rd ~/.docker`. Please note this removes all docker images you ever used, only a problem in case you use docker for other things too.

Hope it helps, if it does not feel free to comment again or tag me on rocket https://chat.golem.network

**Comment by Technoprenerd** [comment]
Hey @maaktweluit 

Results: 
 ~ docker-machine ls
NAME    ACTIVE   DRIVER   STATE     URL                       SWARM   DOCKER        ERRORS
golem   -        xhyve    Running   tcp://192.168.64.9:2376           v17.12.0-ce

The IP is not existing on my LAN, so maybe that's it?

Will try those commands...

[EDIT]

Commands, removing golem docker and deleting docker directory do not work.

Still stuck with this error:

<img width="457" alt="screen shot 2017-12-29 at 15 37 54" src="https://user-images.githubusercontent.com/3128223/34439529-ee08deaa-ecae-11e7-88de-6ae89f41149f.png">

**Comment by maaktweluit** [comment]
Thanks!

That IP is assigned by docker, it looks good.

Too bad the 2 commands did not work.
Can you try the `pull` command manually to see if it gives a more clear error?
```
# ensure the machine is running
docker-machine restart golem 

# make docker command use this machine
eval $(docker-machine env golem)

# pull the images
docker pull golemfactory/base:1.2
```

**Comment by Technoprenerd** [comment]
@maaktweluit 

Alright, here is the output

```
➜  ~ docker-machine restart golem
Restarting "golem"...
Starting "golem"...
(golem) Waiting for VM to come online...
(golem) Waiting on a pseudo-terminal to be ready... done
(golem) Hook up your terminal emulator to /dev/ttys010 in order to connect to your VM
Machine "golem" was started.
Waiting for SSH to be available...

Detecting the provisioner...

Unable to verify the Docker daemon is listening: Maximum number of retries (10) exceeded
➜  ~
➜  ~
➜  ~ eval $(docker-machine env golem)

➜  ~ docker pull golemfactory/base:1.2

Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.64.1:53: read udp 192.168.64.11:56823->192.168.64.1:53: i/o timeout
```

Daemon is not running.

However, I've got the Docker.app running in my menu...

**Comment by maaktweluit** [comment]
Will dig into those errors and let you know.

On windows the docker daemon does not work when the docker app is running, maybe it is the same on mac.. Could you close docker.app and try again?

**Comment by Technoprenerd** [comment]
Closed Docker.app and still the same error.

**Comment by badb** [comment]
@Technoprenerd Are you able to run `docker run hello-world` or generally download any official docker images? 
Can you check if this topic can be related in any way? 
https://stackoverflow.com//questions/23111631/cannot-download-docker-images-behind-a-proxy

**Comment by Technoprenerd** [comment]
@badb : 

Works when Docker.app is running in Mac, with Hello-World: 

`
➜  ~ docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
`

Pull for golem not working:

`
➜  ~ sudo docker pull golemfactory
Using default tag: latest
Error response from daemon: pull access denied for golemfactory, repository does not exist or may require 'docker login'
➜  ~ docker pull golem
Using default tag: latest
Error response from daemon: pull access denied for golem, repository does not exist or may require 'docker login'
`

Even when docker login, it is still not working:
`
Login Succeeded
➜  ~ sudo docker pull golemfactory/base:1.2
1.2: Pulling from golemfactory/base
Digest: sha256:b8f4e2e74c7c242873ee86989105cfb6f2e05d89eea5b9d6a9eb2ce46439e3c6
Status: Image is up to date for golemfactory/base:1.2
➜  ~ docker run golem
Unable to find image 'golem:latest' locally
docker: Error response from daemon: pull access denied for golem, repository does not exist or may require 'docker login'.
`

Weird.

**Comment by maaktweluit** [comment]
Indeed strange errors generated there by docker.

Some users in chat had problems with docker after an upgrade and in they're case `sudo rm -rd ~/.docker` helped. Please note this deletes all downloaded docker images and machines. Be careful if you use docker outside of golem.

**Comment by badb** [comment]
@Technoprenerd 
This first pull that you have tried does not work because you have called `docker pull golemfactory` instead of specifing exact name and tag, ie `docker pull golemfactory/base:1.2`. 
The second pull seems to work properly! Can you try to run `docker run golemfactory/base:1.2`?

Have you tried to install 0.11.0 version of Golem?

**Comment by ChrisHelmsC** [comment]
I am having the same issue on my Mac. I am able to `docker pull golemfactory/base:1.2` and it states that the current image is up to date. Have tried all of the above steps but its still stuck on "Error pulling docker images".

Error Log:
 ```
19:45:21 WARNING  golem.docker.manager                Docker: pulling image golemfactory/base:1.2
2018-01-28 19:45:21 ERROR    golem.docker.manager                Docker: error pulling images: Command '['docker', 'pull', 'golemfactory/base:1.2']' returned non-zero exit status 1.
2018-01-28 19:45:21 WARNING  golem.docker.manager                Docker: building image golemfactory/base:1.2
2018-01-28 19:45:21 ERROR    golem.core.async                    Caught async exception:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
    
--- <exception caught here> ---
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/node.py", line 62, in _run
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/node.py", line 93, in _setup_docker
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/report.py", line 118, in wrapper
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/docker/manager.py", line 147, in check_environment
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/docker/manager.py", line 322, in build_images
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/report.py", line 118, in wrapper
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/docker/manager.py", line 339, in _build_images
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/docker/manager.py", line 304, in command
    
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['docker', 'build', '-t', 'golemfactory/base', '-f', 'core/resources/images/Dockerfile', '.']' returned non-zero exit status 1.

2018-01-28 19:45:31 INFO     golem.pay                           Peer count: 25 
2018-01-28 19:45:31 INFO     golem.pay                           ETH: 0.01886778 
2018-01-28 19:45:31 INFO     golem.token                         TestGNT: 1000.0 GNTW: 0.0 
2018-01-28 19:45:44 INFO     golem.pay                           Peer count: 25 
2018-01-28 19:45:44 INFO     golem.pay                           ETH: 0.01886778 




```

**Comment by badb** [comment]
@ChrisHelmsC Can you check what is the exact error that command `docker pull golemfactory/base:1.2` returns on your machine?

**Comment by Technoprenerd** [comment]
@badb 
This first pull that you have tried does not work because you have called docker pull golemfactory instead of specifing exact name and tag, ie docker pull golemfactory/base:1.2.
The second pull seems to work properly! Can you try to run docker run golemfactory/base:1.2?

Log info from running docker run golemfactory/base:1.2 : 
(Docker.app running in MacOS)

➜  ~ sudo docker pull golemfactory/base:1.2
Password:
1.2: Pulling from golemfactory/base
Digest: sha256:b8f4e2e74c7c242873ee86989105cfb6f2e05d89eea5b9d6a9eb2ce46439e3c6
Status: Image is up to date for golemfactory/base:1.2
➜  ~ docker run golemfactory/base:1.2
➜  ~ docker-machine ls
NAME    ACTIVE   DRIVER   STATE     URL                        SWARM   DOCKER        ERRORS
golem   -        xhyve    Running   tcp://192.168.64.11:2376           v17.12.0-ce

Then do Golem.app in Mac/SpotLight, it runs the app.
Still stuck/frozen with 'Pulling Docker Images' on the bottom of the app screen.
(this was on Golem 0.10.0 GUI for MacOS).

Have you tried to install 0.11.0 version of Golem?

Downloaded the 0.11.0 version, 
➜  golem-0.11.0 ./golemapp
INFO     [golem.version ] GOLEM Version: 0.11.0

then started the golem.app GUI.
In the GUI screen it now states : 'Golem - docker', with a red dot.

<img width="449" alt="screen shot 2018-02-12 at 09 18 22" src="https://user-images.githubusercontent.com/3128223/36088028-b289ff68-0fd5-11e8-8031-00fe018d952e.png">


EDIT:

Updated/Reinstalled with latest version, for Mac using Brew. https://github.com/golemfactory/homebrew-golem 

Getting 'Starting Golem' now.

<img width="446" alt="screen shot 2018-02-12 at 09 29 27" src="https://user-images.githubusercontent.com/3128223/36088375-40d30d68-0fd7-11e8-86ac-5fe19986081f.png">

**Comment by badb** [comment]
@Technoprenerd  Did Golem starts correctly with newer veresion?

**Comment by Technoprenerd** [comment]
@badb : I am getting this message now.
(Firewall open, ports open etc...)

Docker is available.

<img width="455" alt="screen shot 2018-02-17 at 08 54 08" src="https://user-images.githubusercontent.com/3128223/36339196-3683a524-13c0-11e8-97c2-553985cc9ec7.png">
