### ISSUE TITLE
Have one version of imapp/blender Docker image

### ISSUE THREAD

**Issue by azawlocki** [golemfactory/clay#182]
Now there are two:
1) one is built by `scripts/Dockerfile.blender` and is used to compute Blender tasks in regular GNR nodes
2) the other one is built by `tests/imunes/Dockerfile.blender` and is used as a base for the image `imapp/gnr` used by testing Golmem in IMUNES.

**Comment by chfast** [comment]
Is this still relevant?

**Comment by badb** [comment]
Imunes tests have to be rewritten / changed, so this issue is probably not important any more.
