### ISSUE TITLE
[UX] Windows UAC feature must be ON

### ISSUE THREAD

**Issue by Gffy** [golemfactory/clay#1831]
There is an error when starting Golem when UAC is OFF
Please add to the troubleshooting section!

**Comment by maaktweluit** [comment]
Hey @Gffy 

Thank you for the report!
Tried to reproduce it today on my windows and it seems to work for me.
Could you please describe your scenario in more details so i can reproduce and document it?
For example:
- Did installation work with UAC OFF?
- Is there any error in the logs when you start golem with UAC OFF?
- Did you upgrade golem or install clean?
- What version are you installing? ( i guess latest `0.10.0` )

Thanks again for helping out!

Have a great day!

Maaktweluit

**Comment by Gffy** [comment]
Installation works with UAC OFF. I installed clean latest version. Tried on windows 2012R2 and windows 10, both x64.
But when i try to start it with UAC OFF, I get an error (screen and logs attached).

[golem.log](https://github.com/golemfactory/golem/files/1644035/golem.log)
![Error message](https://user-images.githubusercontent.com/34920371/35115291-bc4149a8-fc98-11e7-8d02-0d2f3a6167f7.PNG)

**Comment by maaktweluit** [comment]
Thank you for the information!

Will run some tests and see if i can find the root cause.
