### ISSUE TITLE
Cant get GNT to Requester

### ISSUE THREAD

**Issue by alptiginsaki** [golemfactory/clay#1832]
Hi I am working at the project as a Provider. In the History tab I have lots of awaiting message. That mean I can not get GNT to the requester. I am adding the pictures for better explanation . Can someone help me for that?
![screen shoot1](https://user-images.githubusercontent.com/17874876/34469878-f73f64c2-ef37-11e7-826a-db157751a322.PNG)
![screen shoot2](https://user-images.githubusercontent.com/17874876/34469879-f76180ac-ef37-11e7-839c-acbd8523c32c.PNG)

**Comment by badb** [comment]
@kascheri12 It seems that it's your node that was not able to pay for comptuations here. Can you please check your logs and figure out if there were additional problems with geth during this time?

**Comment by alptiginsaki** [comment]
[golem.log.2017-12-30.zip](https://github.com/golemfactory/golem/files/1598569/golem.log.2017-12-30.zip)
Hi @badb and @kascheri12 I checked log file and found it at "C:\Users<USER>\AppData\Local\golem\golem\default\logs" directory. But I could not understand anything sorry. Name is golem.log.2017-12-30

**Comment by golemUser1** [comment]
golen is an ERC20 Coin. 
That means that it is processed by the Etherium Blockchain. Every Transaction will also cost minor fee in Ether. (called GAS in this Gui).

can you just look up if you have enough ETH in you account?
![grafik](https://user-images.githubusercontent.com/35274214/34745617-67ac93e2-f591-11e7-8e77-2ea05580a1ae.png)

Otherwise you have to buy some ETH, for your transactions.

**Comment by badb** [comment]
GNT is not an ERC20 coin and remember that we're still on testnet! It means that we're using test GNT and test ether from rinkeby chain. You get them from our faucets, please don't buy anything yet to test golem!

Thanks for the @alptiginsaki, there's one error in your log that show some unstable work of Geth service which might cause this issue back then. Are you still have only "awaiting" transaction or were you able to observe some completed ones?

**Comment by alptiginsaki** [comment]
Hi @badb thank you for the reply but nothing changed I have still "awaiting" transaction. I restart the program and realized that I have a error for communication then I press OK and Golem start to mining and join the network.

**Comment by golemUser1** [comment]
same as: #1318?

**Comment by alptiginsaki** [comment]
No it is not same as 1318 and I am still waiting transaction. Why did you closed the issue?
