### ISSUE TITLE
Add support for Allowlist to Golem

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#1836]
There is Denylist implemented in Golem: https://github.com/golemfactory/golem/pull/1046 that allows you to block nodes with specific ids. 

For testing multi-OS integrations we would like to also have Allowlist. When on Denylist we put specific text  eg. "ALL" instead of node ID as the only content than all nodes will be blocked and only nodes with id-s that are directly place in allow.txt will be able to contect with each other. This functionality will allow to prepare us better test scenarios.

**Comment by etam** [comment]
Based on input from @Krigpl I've changed the design a bit. Instead of having a separate file with allowed nodes, everything is in `deny.txt`. Adding a line with `ALL_EXCEPT_ALLOWED` makes it an allowed list.
