### ISSUE TITLE
change bid while waiting

### ISSUE THREAD

**Issue by chriscrutt** [golemfactory/clay#1844]
if no-one is taking your bid, (currently it doesn't let you change anything while Golem is running) could you change your bid to be higher without stopping? also maybe increasing/decreasing golem without having to stop it...

Maybe you could allow us to change variables such as those above, and then have a "save changes" button which restarts golem... hopefully not losing any rendering projects or etc? or would it not have to restart

**Comment by badb** [comment]
It's not really possible in the nearest future, because it will overcomplicate protocol, but it's a good suggestion for the future and potentially change the protocol in the next releases.
