### ISSUE TITLE
Withdraw GNT

### ISSUE THREAD

**Issue by chriscrutt** [golemfactory/clay#1845]
I cannot find a current way to withdraw my GNT to the Ethereum TestNet wallet from the funds I would be acquiring from Golem Brass. Will there be a way implemented/is there before it goes off the TestNet?

**Comment by maaktweluit** [comment]
Hey @chriscrutt 

This is currently now implemented yet, there is an issue to start on this: #750
This issue would be a next step after the account features have been added.

**Comment by chriscrutt** [comment]
sweet
