### ISSUE TITLE
Task stuck preparing/waiting

### ISSUE THREAD

**Issue by chriscrutt** [golemfactory/clay#1846]
MacBook Pro 

After my tasks have been "prepared for computation" (I know this because it doesn't say 'Preparing...' underneath my task anymore) they go to "Waiting...". I assume, they are waiting for people to complete them/render my .blend file. however, at the bottom it still says "Task is preparing for computation".

It's also been awhile since I've "put them on the market", a stopwatch/timecounter would be nice to know how long I've waited for a task to be completed

<img width="453" alt="screen shot 2018-01-03 at 3 53 44 pm" src="https://user-images.githubusercontent.com/6835463/34544949-63d4d3b2-f09e-11e7-947c-1e7f67c0f5de.png">

**Comment by wp31** [comment]
I have the same issue.

**Comment by badb** [comment]
1. To how many nodes were you connected? Did you have warning about closed ports?
2. Did you change the default reputation option? 
3. What price did you set? 

This three are usually the main blockers that make other people not compute your tasks. 
You can also check in your logs if there are any nodes getting "banned" from tasks, ie. they tried to compute it but failed.

**Comment by wp31** [comment]
Thanks Aleksandra.  
1)  I was connected to 10 nodes.  I didn't receive any warning about closed ports.
2)  I did not change the default reputation option
3)  I tried different prices ranging from 1 GNT to 3 GNT/hr

I'll try to check the logs next time.

**Comment by wp31** [comment]
I'm trying again with the same result and here are a couple of screen shots of the logs.
<img width="1419" alt="screen shot 2018-01-10 at 11 50 46 am" src="https://user-images.githubusercontent.com/22955449/34784710-0c17efba-f5fd-11e7-8825-7caa1f3f34ef.png">
<img width="1411" alt="screen shot 2018-01-10 at 11 51 34 am" src="https://user-images.githubusercontent.com/22955449/34784711-0c285b2a-f5fd-11e7-8dcc-d40e1442c5da.png">

**Comment by badb** [comment]
Hi @wp31 & @chriscrutt 
There is a new version of Golem available. Can you try it out and see if it's working properly? If the problem still occurs, then please send us the logs to contact@golem.network or via https://chat.golem.network and reference the number of the issue!

**Comment by wp31** [comment]
Thanks, just did that on rocketchat
