### ISSUE TITLE
Golem restarts or UI bug

### ISSUE THREAD

**Issue by hochmanjoel** [golemfactory/clay#1854]
After clicking 'Stop Golem' I clicked over to 'Tasks' while the screen was faded. Upon clicking back into 'Network' it looked as though Golem was running again. I clicked 'Stop Golem' and without clicking over the screen is faded and has yet to come back to full color with a 'Start Golem' option.

**Comment by badb** [comment]
@ederenn Can you try to reproduce this behaviour?

**Comment by hochmanjoel** [comment]
All I have to do is click “Stop Golem”. It automatically starts when I open
the application because I have not been able to stop it since it was first
started.

**Comment by ederenn** [comment]
yes, mac binaries 0.10.0, it seems it's not stopping golem at all 
<img width="480" alt="screen shot 2018-01-10 at 17 21 29" src="https://user-images.githubusercontent.com/32061891/34784066-85943dd2-f62d-11e7-81b9-109d0fa2948a.png">
, 

on windows works fine for me

**Comment by badb** [comment]
@ederenn Can you confirm that this is issue is not valid anymore in 0.11.0?

**Comment by ederenn** [comment]
With binaries 0.11.0 for mac it seems ok now. Several stopping/starting and no permanent faded screen.
