### ISSUE TITLE
Golem not sending task

### ISSUE THREAD

**Issue by magdasta** [golemfactory/clay#186]
One of two instances of Golem running on the same machine is unable to send task to the second one - last master's log info is `golem.task.taskmanager - INFO - Task [task_num] added`, the slave doesn't log anything. It is still possible to send tasks from slave to master (instances' roles swap). Don't know yet if the same occurs on separate machines.
[MasterLog.txt](https://github.com/imapp-pl/golem/files/167419/log.txt)

**Comment by badb** [comment]
@magdasta Is it still an issue or is it fully solved with new resource management?
