### ISSUE TITLE
Golem start button not active / machine does not exist

### ISSUE THREAD

**Issue by ceto14** [golemfactory/clay#1863]
I am trying to start golem but the start button seems to forever stay inactive.
I tried troubleshooting but upon entering the standard solutions from the https://docs.golem.network/10-troubleshooting.html site, nothing seems to work.

![golem_issue](https://user-images.githubusercontent.com/35155340/34633840-2819e2f8-f27f-11e7-9494-a950d406b810.jpg)

This is somewhat weird also.

Also the directory where the log files should be is empty.

please help.

**Comment by golemUser1** [comment]
I run into the same problem as you.

I used the "Docker Quickstart Terminal"
You can remove the faulty vm with the command :
docker-machine rm golem

and then recreate it with the command from the help page:
docker-machine create golem --driver virtualbox

That worked for me.
  
Log Errors look similar to Issue #1786, so there might be a relation

**Comment by badb** [comment]
@golemUser1 advice should solve the issue!
@ceto14 Please feel free to reopen if it doesn't help you.
