### ISSUE TITLE
Add user possibility to choose geth instance. 

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#1882]
Right no we're connecting to external geth instances.

 Advance user may still want to use their own local geth instances. The proper code for starting geth was implemented and should still work, we just need to add a command line flag `--start-geth` (or something similar) that will set `start_geth` option in EthereumTransactionSystem to `True`. 
This should of course be deeply tested if nothing was broken in the meantime. 

We need also a second option when we will not start geth on our own, but instead allow user to  configure geth instance http address. It may be set by adding `--geth-address <address>` option to command line. Please, make sure that the app behaves in an rational way if the given geth instance is not available or configured incorrectly.

**Comment by tworec** [comment]
`--start-geth` is already there. I'll just add the `--get-address` option

**Comment by maaktweluit** [comment]
I see this issue did not auto-close.

Next time you can use one of these keywords to link the issue and the PR: https://help.github.com/articles/closing-issues-using-keywords/

**Comment by tworec** [comment]
closed via #1910
