### ISSUE TITLE
libsecp256k1 not found

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/clay#1890]
Found by @mfranciszkiewicz on [buildbot](https://buildbot.golem.network/buildbot/#/builders/6/builds/75)

```
____________________ ERROR collecting tests/test_logging.py ____________________
ImportError while importing test module '/Users/buildbot-worker/worker/unittest_macOS/build/tests/test_logging.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_logging.py:4: in <module>
    from golem.testutils import PEP8MixIn
golem/testutils.py:14: in <module>
    from golem.ethereum import Client
golem/ethereum/__init__.py:1: in <module>
    from golem.ethereum.client import Client
golem/ethereum/client.py:7: in <module>
    from .node import NodeProcess
golem/ethereum/node.py:16: in <module>
    from ethereum.transactions import Transaction
.venv/lib/python3.6/site-packages/ethereum/transactions.py:7: in <module>
    from secp256k1 import PublicKey, ALL_FLAGS, PrivateKey
.venv/lib/python3.6/site-packages/secp256k1.py:5: in <module>
    from _libsecp256k1 import ffi, lib
E   ImportError: dlopen(/Users/buildbot-worker/worker/unittest_macOS/build/.venv/lib/python3.6/site-packages/_libsecp256k1.abi3.so, 2): Library not loaded: /usr/local/lib/libsecp256k1.0.dylib
E     Referenced from: /Users/buildbot-worker/worker/unittest_macOS/build/.venv/lib/python3.6/site-packages/_libsecp256k1.abi3.so
E     Reason: image not found
```

**Comment by maaktweluit** [comment]
While investigating this issue i found a few things:
- Buildbot mac_01 and mac_02 have different mac versions. One is not as requested
- `secp256k1-0.13.2-cp36-cp36m-macosx_10_10_x86_64.whl` from `https://builds.golem.network/simple/secp256k1` does not work
- `secp256k1-0.13.2.tar.gz` from https://pypi.python.org/simple/secp256k1 does work

I propose to remove the 10_10 version from our pypi server so it can use the global, generic one.

**Comment by mfranciszkiewicz** [comment]
I've temporarily removed `secp256k1-0.13.2-cp36-cp36m-macosx_10_10_x86_64.whl` from our pypi repository; secp256k1 will be build from `secp256k1-0.13.2.tar.gz` on macOS 10.10

**Comment by maaktweluit** [comment]
re-ran the build and it passed the point where it failed.

Seems to be fixed with this

https://buildbot.golem.network/buildbot/#/builders/6/builds/78

Will close when it is green.

**Comment by maaktweluit** [comment]
Test success!
