### ISSUE TITLE
ERROR    golem.core.keysauth                 b'Cannot verify signature: Invalid recovery id.'

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#1898]
2018-01-15 11:53:59 ERROR    golem.core.keysauth                 b'Cannot verify signature: Invalid recovery id.'

encountered on Windows, binaries, 
appeared after 10 min of app running, one small task was added (400x400, 2 frames, 6 subtasks), 
not sure if this appeared before or after task was added

**Comment by jiivan** [comment]
Possibly related to: https://github.com/golemfactory/golem-messages/issues/70#issuecomment-357284438
