### ISSUE TITLE
Buildbot: Do not re-use old hyperg

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/clay#1900]
Found during review of #1754

Currently when HyperG is already running the buildbot-worker will re-use this process.

A better test state would be to kill any old processes and start a new one.

Please also align this between windows mac and linux.
Tests can fail immediately when HyperG is not able to be (re)started.

**Comment by ktomala** [comment]
MR is ready to merge: https://github.com/golemfactory/golem/pull/1923

**Comment by maaktweluit** [comment]
PR is merged, so closing this one

@ktomala you can link the issue and pr by using https://help.github.com/articles/closing-issues-using-keywords/
