### ISSUE TITLE
Find a tool to automate data migration after database schema changes

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#191]

**Comment by mfranciszkiewicz** [comment]
There are migration tools available in `peewee`'s `playhouse`:
http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#migrate

In general, the migration process cannot be fully automated. I.e. table / column renaming cannot be inferred from schema changes and would be seen as a drop + create. This part has to be explicitly specified by the developer.

**Comment by mfranciszkiewicz** [comment]
Resolved in #2023
