### ISSUE TITLE
Add support for animations in blender

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#192]

**Comment by magdasta** [comment]
Seems like this feature wouldn't be very useful - based on Todd's answers, the most common way of rendering animations is saving frames in separated image files. Besides, some of the video formats supported by blender use system-dependent codecs, which would probably be hard to manage in Golem. We can consider supporting some simpler formats (like AVI Raw or AVI JPEG), but it can still result in problems (for instance blender animations can contain sound, which may result in further problems with audio encoding, etc). So all of it looks like requiring quite a lot of work.
