### ISSUE TITLE
Run Docker with OpenCV in verification function

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#1937]
Docker with OpenCV (https://github.com/golemfactory/golem/pull/1932) should be run in Blender verification function on crops that were generated (https://github.com/golemfactory/golem/pull/1933 & https://github.com/golemfactory/golem/tree/blender_verifier_2). 
A dirty draft on how to run can be found here: https://github.com/golemfactory/golem/tree/blender_verifier_draft
The crops should be matched with proper cuts of the result (pixel computation should already be done, but cutting out results isn't). 
In this issue we only want to generate proper metrics and do not interpret them. If we're able to generate them we assume that task was verified properly, if we assume that the answer is "not sure".

**Comment by Elfoniok** [comment]
Commit is here:
https://github.com/golemfactory/golem/pull/1985
