### ISSUE TITLE
[FUNC] make an Error Message if the Ports are not forwarded. (windows 0.10.0)

### ISSUE THREAD

**Issue by golemUser1** [golemfactory/clay#1947]
when starting golem with Ports 40102, 40103 and 3282 the programm shown nearly sign of error.
only this message appears:
![grafik](https://user-images.githubusercontent.com/35274214/35247837-1f830c96-ffcc-11e7-9e40-bffdb205550f.png)
But shortly after clicking on it :
![grafik](https://user-images.githubusercontent.com/35274214/35247860-336acc08-ffcc-11e7-9a27-58b4ce260620.png)
It seems to be connected to 6 nodes. It even appears on the statistik page.

Without the ports it is not operational. any attempt to submit a task resulted in a timeout. (recieving tasks is currently not testable for me)

going through the logs of that session does only show:

> 2018-01-22 23:34:03 WARNING  golem.task.taskserver               b'Impossible to start session with Node , (key: a62fbeed2600c52a1837e0fbf84106947c859c43bb4ce992ea526fa40f0040428fe0ee2c7483a1b2a9726b14c9169a3d20435405ea793fb3a74859f3697ea814)'
> and similar entries as errors.

nothing that tells me that my ports are closed!
Please make a check for this and a better erro message. otherwise there will be zombie golems, that are nonfunctional!

**Comment by badb** [comment]
Nodes that don't have forwarded ports may still be useful for the network in the way that they can route information about peers and tasks for other nodes. They may, however, not be able to compute anything that comes from outside their local network. You are right that this should be more visible.

**Comment by jamuszyn** [comment]
Additional information about ports issue was implemented with improved footer
