### ISSUE TITLE
payments in history tab are saved with wrong time

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#1962]
Incoming transactions for subtasks are appearing in GUI in real time, but are saved with wrong time - with one hour added in advance, as if the were in different timezone. 
For example, payment for subtask from 10.35.31 will be shown as 11.35.31

![2](https://user-images.githubusercontent.com/32061891/35336646-5aea4512-0119-11e8-9711-82b6284ad6cd.PNG)

noticed in b.011.0

**Comment by Krigpl** [comment]
@mdtanrikulu Could you check whether UI is handling timezones properly? The timestamps are always in Unix epoch.

**Comment by badb** [comment]
@mdtanrikulu Is this issue fixed?

**Comment by mfranciszkiewicz** [comment]
Fixed in https://github.com/golemfactory/golem/pull/2553
