### ISSUE TITLE
Task does not get computed

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/clay#1968]
Relates to #1846 reported by @wp31 on golem chat

Running 0.11.0 on mac, when adding a task it remains in the status "waiting".
When checking the logs we see:
```
2018-01-24 13:45:29 WARNING  twisted                             dropping connection to peer tcp4:127.0.0.1:61000 with abort=True: WebSocket ping timeout (peer did not respond with pong in time) 
2018-01-24 13:45:29 WARNING  twisted                             session closed with reason wamp.close.transport_lost [()]
```

Tried to remove `~/Library/Application Support/golem/default/hyperg`, this did not resolve the issue in this case.

Golem worked at version 0.9.0, from then ports are still forwarded.

**Comment by golemUser1** [comment]
I recognise this log line:

> 2018-01-24 13:45:29 WARNING  twisted                             session closed with reason wamp.close.transport_lost [()]

afterward, the whole communication was screwed up.
i have seen it myself at: #1877

**Comment by badb** [comment]
@maaktweluit Can you get full logs of this issue in 0.11.0 version?

**Comment by golemUser1** [comment]
I am not sure if it is the same. but somehow i also had a tsk transmit problem. I tried to transmit one of the demo task again. and it didn't worked.
here are the logs:
[golem.error.log](https://github.com/golemfactory/golem/files/1665691/golem.error.log)
[golem.log](https://github.com/golemfactory/golem/files/1665692/golem.log)

PS: i checked port forwarding. the entry:

> 
2018-01-25 21:33:11 WARNING  golem.network.upnp                  b'IGD: cannot map port 40103 (TCP): ConflictInMappingEntry'

apperead after a golem restart. somehow the upnp does not detected that a port forwarding was already installed.

**Comment by badb** [comment]
@golemUser1 Thanks! That's really helpful. Did you golem app was able to work again after the crash visible in logs at 22:15 or was it totaly unresponsive?

**Comment by maaktweluit** [comment]
@badb Shared the logs with you, hope it helps!

**Comment by mfranciszkiewicz** [comment]
```
2018-01-24 08:39:30 WARNING  golem.monitor  Port status: 40102: timeout, 40103: timeout, 3282: timeout
```

Shows that there was an issue with wp31's port forwarding setup.

**Comment by wp31** [comment]
How come it's a problem given that 11.0 was supposed to not require port forwarding anymore?  Router?

In any case, I just configured port forwarding and Golem seems to be rendering a task.  Note that I had my ports forwarded in the past and had been rendering successfully.  I don't know how that was somehow disabled.

**Comment by mfranciszkiewicz** [comment]
@wp31 Port forwarding is not required if your router supports UPnP (IGD). This doesn't seem to be the case, unfortunately:
`2018-01-24 08:39:29 WARNING  golem.network.upnp                  IGD: discovery error: no devices discovered`

**Comment by wp31** [comment]
Ok thanks Marek.  I confirm Golem is rendering perfectly now.

**Comment by maaktweluit** [comment]
Thank you all for the reports, logs and resolution!

Closing this issue, feel free to re-open or create a new one when the issue persists.
