### ISSUE TITLE
[UX]  Can't change resources

### ISSUE THREAD

**Issue by asato-ma** [golemfactory/clay#1979]
On Win10 I can't change resources and Im running on full power of CPU?! 

![capture_002_26012018_180921](https://user-images.githubusercontent.com/10796124/35451626-23afd9c0-02c4-11e8-8b4f-99d0015337a9.jpg)

![capture_003_26012018_181037](https://user-images.githubusercontent.com/10796124/35451659-46edda7c-02c4-11e8-89fb-2ab74d70afed.jpg)

**Comment by badb** [comment]
Hi @asato-ma!
You must stop golem to be able to change the resources. 

This behaviour may not be very intuitive, so @jamuszyn here's another UX problem for you.
