### ISSUE TITLE
Make DockerToolbox installation optional if previous version was already installed

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#1988]
When we update Golem version on Windows and override DockerToolbox version there is a risk of changeing VirtualBox  version that user had already installed and breaking existing VirtualMachines. Reinstallation of DockerToolbox should be option, so user should be able not to update DockerToolbox version.

**Comment by maaktweluit** [comment]
![screen shot 2018-02-01 at 15 13 57](https://user-images.githubusercontent.com/10008353/35682921-a5702f44-0762-11e8-90aa-e237a65133b8.png)

Will make a commit to the advanced installer buildbot branch to add this to next release.

**Comment by maaktweluit** [comment]
Resolved here: https://github.com/golemfactory/golem/commit/ed1772b812c618acd594bc154d2c2f26a3d6ecf8

The branch can be tweaked and released when the signing flow is complete.
