### ISSUE TITLE
Improve provider selection function

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#1989]
Propose a better function for choosing the best providers for the task. Right now it's FIFO with checking that provider fulfil basic requirements. We can optimize provider selection function based on chosen criterion (eg. price, reputation) 

Check this very old Contest PR to see how it can be implemented: https://github.com/golemfactory/golem/compare/task-assign

**Comment by tworec** [comment]
some reference? :)

**Comment by Krigpl** [comment]
https://github.com/golemfactory/golem/pull/3482
