### ISSUE TITLE
Improve task selection function 

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#1990]
Right now provider chooses the task that he/she wants to compute randomly. Propose a better method to of choosing proper task based on chosen criterium (eg. deadline, price, reputation). 

https://github.com/golemfactory/golem/blob/task-assign/golem/task/taskserver.py#L79

**Comment by tworec** [comment]
some reference to code changes?

**Comment by Krigpl** [comment]
https://github.com/golemfactory/golem/pull/3482
