### ISSUE TITLE
requirements inconsistency

### ISSUE THREAD

**Issue by etam** [golemfactory/clay#1997]
requirements.txt

> pyasn1==0.4.1

requirements-test.txt

> pyasn1==0.2.3

**Comment by etam** [comment]
@maaktweluit

**Comment by maaktweluit** [comment]
At first buildbot required to downgrade, this was already in there before i worked on it.

Will test this on buildbots tonight when its calm and make a PR to remove it when no longer required.

**Comment by maaktweluit** [comment]
You are right, the second requirement was no longer needed.
Made a PR and tested both buildbot jobs with success!
Invited you to review.
