### ISSUE TITLE
"Error" when doing Local Render Test

### ISSUE THREAD

**Issue by wp31** [golemfactory/clay#2003]
Tried to render a Blender demo file  "Production Benchmark" (https://download.blender.org/demo/test/benchmark.zip) and the gui says "Error" instead of the normal "Success" when doing the local test at the beginning.  Screen shot
<img width="482" alt="screen shot 2018-01-31 at 1 16 10 pm" src="https://user-images.githubusercontent.com/22955449/35640050-147e221c-068a-11e8-8093-a30202ab3a89.png">

**Comment by maaktweluit** [comment]
Hey @wp31 

Thank you for the report!
Production benchmark is quite a big render, this will stress your local machine during the test.

Are there any extra assets required for this render? if so, are they included in the job?

Could you please attach the logs from your application?

**Comment by wp31** [comment]
There weren't any extra assets for this render.  Just one .blend file.

I sent you the logs.

**Comment by maaktweluit** [comment]
Thank you for the logs, it seems the subtask failed with this error:
`Task computing error: Subtask computation failed with exit code 247`

Doing quick search on this error code gives no result, will consult with the team and get back to you.

**Comment by maaktweluit** [comment]
After consulting the team this is an out of memory error.
How many resources are assigned to your golem machine? this benchmark requires  > 12 GB RAM, > 6 cores (approximately)

**Comment by badb** [comment]
We should display more information about Errors. Issue for that is here: https://github.com/golemfactory/golem-electron/issues/217
