### ISSUE TITLE
Add logic for updates in golem-messages re: `SubtaskResultsRejected`

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/clay#2010]
the signature of the `SubtaskResultsRejected` has changed and those changes in `golem-messages` need to be reflected in golem core

**Comment by lukasz-glen** [comment]
Do you consider those two reasons: Requestor could not download results using Concent and Requestor could not download results not using Concent?

**Comment by badb** [comment]
@shadeofblue @jiivan Is this one fixed?

**Comment by shadeofblue** [comment]
@badb ah, sorry, the automatic closing didn't work for some reason ...
