### ISSUE TITLE
[ERR] Benchmark did not complete (windown10, 0.11.0, VM 5.2.6)

### ISSUE THREAD

**Issue by golemUser1** [golemfactory/clay#2031]
![grafik](https://user-images.githubusercontent.com/35274214/35768639-5ccd9e9a-08ff-11e8-8286-5fc4b6f30666.png)

i realised today that my benchmark was incomplete. i tried to rereun it, but then it is stuck on calculating.
I found the following log entries:

> 2018-02-03 14:40:01 WARNING  golem.task                          b'Failed to compute benchmark'
> 2018-02-03 14:40:01 ERROR    golem.task.benchmarkmanager         b'Unable to run DUMMYPOW benchmark: '
> 2018-02-03 14:40:01 ERROR    golem.task.taskthread               b'Task computing error: Strings are not supported by Failure'
> 2018-02-03 14:40:01 ERROR    golem.task.taskthread               b'['  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\golem\\docker\\task_thread.py", line 101, in run\n', '  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\golem\\task\\localcomputer.py", line 95, in task_computed\n', '  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\golem\\task\\localcomputer.py", line 108, in computation_failure\n', '  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\golem\\task\\benchmarkmanager.py", line 42, in error_callback\n', '  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\twisted\\internet\\defer.py", line 498, in errback\n', '  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\twisted\\python\\failure.py", line 218, in __init__\n']'
> 2018-02-03 14:40:01 WARNING  golem.task                          b'Failed to compute benchmark Strings are not supported by Failure'
> 2018-02-03 14:40:01 ERROR    golem.task.benchmarkmanager         b'Unable to run DUMMYPOW benchmark: Strings are not supported by Failure'

One thing might have an influence. recently my antivir programm said that the Oracle VM was out of date. i updated then to the newest version.

**Comment by badb** [comment]
This should be fixed in 0.13.0
