### ISSUE TITLE
[FUNC] use a single type of ID in network logging. (0.11.0)

### ISSUE THREAD

**Issue by golemUser1** [golemfactory/clay#2033]
I tried to analyse some of the network logs deeper but failed, because of inconsistent logging.
That because some messages use diffent kinds of ID's to identify the other nodes, and i don't know how to map them. this would be a great help to indeitfy network problems and faulty nodes.

> Connecting to peer '94.23.57.58':40102'
> Starting peer session '94.23.57.58':40102'
> Closing 98.165.230.104 : 40102'

uses IPv4 only.

> Connection to peer failure 129f5c45-24d3-4dac-b2f2-87a4d787f121.

uses anozher kind of ID. so i can't see which peer connection did't worked....

> TOO MANY PEERS, DROPPING CONNECTION: SLTResearch 24.225.110.214: 40102'

this uses the name and the Ipv4. thats better.

> add peer to incoming 'Drohlum bootstrap go' '94.23.196.166' 0 ('22d8874dd237c188effb123bf88edcf979e38e6984a4e9becef85bed71b39fa58d529b2567cb56ca7ba4b605f743edf1a607805a75f438c8b571f2d8bfc57485')'

uses IPv4, a name and some long ID.

> Starting resource handshake with 'ebd4ff6c36eca6bd5eba05109f6f5ed71a4c3af58fc5f210a778052e22cc8e94927456ab26853507e20d22e881fecfc5a089f87310c5aef9ee9a37b3ae4b4c08''
> Resource handshake error ('5b913897a0d7d993b37777786e23f990cf9804c6ad17311b92815531d5ef9883dbfa56e7fd3ba1d6dee5340ca538d61344ded302d7dc9f04b10751533db418e9'): 'timeout''
> Finished resource handshake with '36f62f20fa9ab2be0dc0a243189839636883fd07e0b1a171178357cffdedddc5cdcb265b70f2e839d9e626720e6f8ac5c22d14ebd37fd658e083e246152324e6''
> Adding peer '843d86d9f8e7e870909ad213dbe8072614d453d5e9adb7179dce3700b0e6bad092fd835ecb768425998d44cccaf5113deafd9a929540221b18fa9b5abf09961e', key id difficulty: 2'
> Cannot yet assign task for 'e587f4093e0a1e0ddffbcfb476d350d9f4fbeef80cc3d34ebf37c4ebe079012349e1081a80dc81c0240beaf0c953a8879c5f31dbbf9eb2bfc5f51967b36d230a': resource handshake is required'
> Can't remove peer ef53bea302ea9268638e2886055825e2b4fcc9e142eba8a80302de9d90597311bad07f9f9ae23103bbd2ff32773f043aeb0d2b7593c4a9cd1fa68b25dbe55e9d, unknown peer"
> Task owned by c988bfa7a5e4b52909ca9843741dbf8cc15af64ef4eb50e74b07b1b3ba6413191efb8782db86d6137ce127ec573c85d97f98a99412250bf0d89621eb72d086ce dies, task_id: bb4bc1ea-f314-4ea6-9c2a-6dd578d405eb'

uses only the long id, so if the add node entry is not there, indon't know which node i am talking, or haveing problems....

If you make log files. then make them usabale.

**Comment by maaktweluit** [comment]
in the releases 0.18, 0.19 and the upcoming 0.20 there are a lot of improvements to the consistency of the logs.

closing this issue, please re-open or make a new one if you find another inconsistent log :)
