### ISSUE TITLE
reverse proxy for geth

### ISSUE THREAD

**Issue by etam** [golemfactory/clay#2041]
Let's continue here the discussion from #1887.

A summary:
- We have a reverse proxy at `rinkeby.golem.network`, which forwards connections to geth clients and provides https.
- Currently there are some stateful operations, so we can't do every request to a different instance. @Krigpl knows details.

Possible solutions:
- Make requests stateless and keep a round robin reverse proxy. Maybe create more proxies to avoid single point of failure.
- Stay with the current design. Just add proxies for every geth instance (without round-robin), to provide https.

**Comment by etam** [comment]
@mfranciszkiewicz @maaktweluit

**Comment by maaktweluit** [comment]
I vote the setup we currently have but then stateless. 1 proxy per 1 geth server seems overkill to me, also the ssl certificate must be on many more places.

**Comment by Krigpl** [comment]
Fixed in a way where mapping connections is consistent, i.e. requests from same IP address will go to the same geth instance which solves this issue.
Adding the proxy in https://github.com/golemfactory/golem/pull/2332
