### ISSUE TITLE
on private connection Golem has problems reconnecting with peer after stopping/starting

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#2046]
two multi os Golems are connected on private - with specific id_protocol number and --peer argument.

They establish connection with each other, but after hitting "stop golem"  and ''start golem" button, Golem not retrying to connect with saved peer id. 
It is trying to connect every other peer - and failing because of id_protocol as expected.
From logs: with saved peer id it has connected once, before stopping, after starting no tries with this specific one.
In GUI: No nodes connected

this pattern is reproducible, but not for every time

**Comment by ederenn** [comment]
-restarting the other one (not the one that was stopped) helped reestablishing the connection
-restart with --peer argument

**Comment by ederenn** [comment]
investigated closely:

mac - windows
stopped - running
started again - no nodes

mac - windows
running - stopped
connecting - started again

mac - windows
stopped - running
started again, (nn) - no nodes
no nodes - restarted (with stop button)
connects - connects

mac - windows
stopped - running
started again (nn) - no nodes
restarted (with stop button) - no nodes
no nodes - no nodes


mac - windows
stopped - running
started again, (nn) no nodes
no nodes - restarted (whole app)
connects - connects

mac - windows
stopped - running
started again (nn) - no nodes
restarted (whole app) - connects

**Comment by maaktweluit** [comment]
@ederenn are you still able to reproduce this issue? else i think we can close it
