### ISSUE TITLE
Resubmit for subtasks is not working after timeout of a task

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#2053]
In second preview window for subtasks, there's a possibility to resubmit a subtask. It is not working after timeout of a whole task - clicking it does nothing, no subtask restart, no task restart.
Before task timeout it is not necessary to have such a possibility, other nodes should undertake failed subtask.

<img width="756" alt="screen shot 2018-02-06 at 15 18 38 copy" src="https://user-images.githubusercontent.com/32061891/35867180-74980eaa-0b59-11e8-91ae-12e7d0580cfa.png">

**Comment by badb** [comment]
It's not a bug, it's a feature...
However, this button should not be visible or should be disabled if task has hit the timeout. 
For subtasks that were positiviely finished there should be an option to restart them (if the whole task was not finished yet), but it shouldn't be visible / active for failed subtask and there should be a warning that restarting subtask that was already computed will result with higher price of whole task. 

This is however GUI issue. 
@ederenn Can you move this issue to golem-electron (and close this one here)?

**Comment by ederenn** [comment]
moved to:
 https://github.com/golemfactory/golem-electron/issues/218
