### ISSUE TITLE
Don't duplicate in ComputeTaskDef parameters that were already declared TaskHeader

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#2073]
Duplicated data:
* task owner
* environement
* key_id / task_owner_key_id
* return_address / task_owner_address
* return_port / task_owner_port
* environment 
* docker-images

We may consider adding task header inside ComputeTaskDef, if that's necessary, but duplicating those fields will require additional checks and is just bringing chaos. 

Return port and address were introduced when we consider that it may be possible to send results back to different place than requestor, but it's not implemented now and we should not keep it "just-in-case".

**Comment by Wiezzel** [comment]
@badb I realized it would be easier to remove the duplicate fields from TaskHeader than to remove them from ComputeTaskDef. You also suggested it here: https://github.com/golemfactory/golem/blob/develop/golem/task/taskbase.py#L67
Is this an acceptable solution?

**Comment by badb** [comment]
Environment must be kept in TaskHeader. Basic information about task owner, ie. key_id, address and port as well. There's additional problem that those information are duplicated in TaskHeader itself, ie. for example key_id is both in task_owner data structure and in task_owner_key_id field. 
The tricky part is to check which one of them is really used.

**Comment by Wiezzel** [comment]
@badb Fine, so I will keep environment and task_owner in TaskHeader while docker_images will be in ComputeTaskDef.
