### ISSUE TITLE
Progressive rendering support for Blender files

### ISSUE THREAD

**Issue by jamuszyn** [golemfactory/clay#2076]
This is something that users ask about quite often. Support for Cycles engine would be good. And Blender will release new version in near future with Eevee engine.

**Comment by badb** [comment]
Can you plase specify what do you mean by progressive rendering for Cycle?

**Comment by jamuszyn** [comment]
If i understood this correctly it is giving user full size output at the beginning and is improving in quality of a render so user can decide at some point that the result that he has is enough and can stop rendering. Cycle is mainly for GPU rendering, but one of the testers said that he uses Cycles with CPU, and from what i seen most of Blender users use this engine, and are waiting for Eevee that is going to come with new big Blender release.
