### ISSUE TITLE
ERROR    [golem_sci.implementation           ] {'code': -32000, 'message': 'filter not found'} 

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#2087]
Mac, source version, 

```ERROR    [golem_sci.implementation           ] {'code': -32000, 'message': 'filter not found'} ```

**Comment by Krigpl** [comment]
Root cause described here: https://github.com/golemfactory/golem-smart-contracts-interface/issues/5
Closing this one in favor of the above.
