### ISSUE TITLE
Blender plugins may cause problems

### ISSUE THREAD

**Issue by jamuszyn** [golemfactory/clay#2104]
This issue came up with latest user test. Plugins that may cause some issues: AnimAll, dinamic sky, Prolighting skies.
 Further research should be conducted and most popular Blender plugins should be checked.

**Comment by maaktweluit** [comment]
The main problem we saw when using the plugins is assets are missing when loading the .blend file in golem.

These assets are auto-generated by the plugin, maybe we can export them in a plain .blend file all together.
