### ISSUE TITLE
Valgrind returns errors for c++ taskcollector

### ISSUE THREAD

**Issue by magdasta** [golemfactory/clay#212]
All of the errors say "Conditional jump or move depends on uninitialised value(s)". Seems like a problem with FreeImage library or a valgrind bug (? https://bugs.launchpad.net/ubuntu/+source/valgrind/+bug/1094586). We should investigate if this is dangerous.

[log.txt](https://github.com/imapp-pl/golem/files/177944/log.txt)

**Comment by badb** [comment]
@banasiakadam60 Is this one finished?

**Comment by banasiakadam60** [comment]
Yes, it can be closed
