### ISSUE TITLE
problems with rerunning benchmark test after stopping Golem with Stop button

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#2154]
### Symptoms:

after changing resources settings, calculate in Performance tab is not showing results

no benchmark errors in logs

### Steps to reproduce
- Golem running normally, 
- hit Stop Golem button
- change basic resources with slider
- hit Start Golem button
- go to Settings tab, performance chart, hit calculate button

calculating is not ending (in gui)

#### Encountered on:
Windows 10
GOLEM Version: 0.11.0+dev399.g0bfff9e72 
Protocol Version: 99 
golem_messages Version: 1.9.0

**Comment by maaktweluit** [comment]
are there any related errors in the logs during this process?

**Comment by ederenn** [comment]
I think it was not shown in logs, but here is error log from 19.02.2018
[golem.error1902.log](https://github.com/golemfactory/golem/files/1740213/golem.error1902.log)

**Comment by maaktweluit** [comment]
Tested this locally on `0.12.0` and it seems to work properly.

I noted there are no info logs at all surrounding these steps, will try to add info for starting / stoping and running benchmarks
