### ISSUE TITLE
Unable to add machine learning / big data analytics tasks to Golem Network

### ISSUE THREAD

**Issue by gokulsan** [golemfactory/clay#2164]
I have setup Golem Factory platform on my Mac Machine (MacOS 10.13.2). I could successfully setup the Golem Node. It is up and running. My Golem Wallet is showing a balance of 1000 GNT. Now I am trying to add the tasks in the Golem. It is only accepting Blender and LuxRender as Task Resource files. I don't have any Blender or LuxRender files.

Can I know why Blender / LuxRender files are required. Can I add task resource files related to machine learning pipelines or Big Data Analytics workloads to Golem. This will help me to utilize the computing power of Golem for diverse workloads and intense tasks?

**Comment by wp31** [comment]
Currently, Golem is only meant to do rendering with Blender or LuxRender.  In the future, Golem will have increasing more functionality including the ability to do Machine Learning tasks and those involving Big Data Analytics.  

If you want to try out Golem, you can find Blender files here:  https://www.blender.org/download/demo-files/

**Comment by badb** [comment]
@gokulsan Please write to use to contact@golem.network and describe with more details what would you like to do with Golem. We'll see what can be done in short term.
