### ISSUE TITLE
Configure round-robin DNS entry for seed nodes 

### ISSUE THREAD

**Issue by ktomala** [golemfactory/clay#2170]
Currently seed nodes IP addresses are hard-coded in Golem. This is quite limiting in terms of scalability, node discovery and servers management including future scaling. 

I'd like to propose to create seeds.golem.network DNS entry with round-robin A records that will return all current seed node addresses. What this will achieve is:

- decoupling of hard-coded IP addresses,
- improve reliability of discovery,
- distribute connection load over all seed nodes (not only hard-coded ones),
- allow us to transparently change seed nodes when needed,
- allow us to transparently add more seed nodes if required,
- not rely on specific server provider,
- in future possibly automatically add A record entries in DNS for seeds.golem.network.

This can be implemented with two phases:

1. Create a RR DNS entry and add another SEEDS entry for `seeds.golem.network` in `golem/network/p2p/p2pservice.py`
2. If everything works correctly, we could possibly get rid of IP addresses from SEEDS entry altogether and leave only `seeds.golem.network` entry.

Further improvements in the future:

- when we achieve significant network scale we could implement DNS anycast with geolocation for seeds.golem.network to provide seeds that are nearest to client network location, achieving much better connection times on startup.

**Comment by m-cameron** [comment]
I support the further improvement. Golem can use the free [IP2Location LITE](https://lite.ip2location.com)  to geolocate the client location and server location to decide the nearest connections.

**Comment by ktomala** [comment]
seeds.golem.network was implemented in RR fashion for mainnet seed nodes some time ago. This task can be considered completed.
