### ISSUE TITLE
[Concent] UC2 / Forced Download - Payload failure

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/clay#2180]
Support for the Payload failure (payload hash mismatch / corrupted results) reason to request Concent assistance in the "Forced Download" use case (use case 2)

In a situation where the Requestor finds that the downloaded payload's computed hash doesn't match the one declared in the `ReportComputedTask` message, the Requestor requests assistance from the Concent by sending them the `ForceGetTaskResult` message.

**Comment by cameel** [comment]
Just to make things clear when you'll be testing this: in the current implementation Concent never actually sends this message. Instead, if the hash does not match, it responds with HTTP 400 (containing a JSON message with an error) to the request that uploads the data.

So effectively it's not possible to successfully upload invalid files and this case never occurs.

**Comment by shadeofblue** [comment]
@cameel this is not a case when the the Concent is required to send a message - it's a situation where the Requestor finds that the payload's computed hash doesn't match the one declared in the RCT and only then requests assistance from the Concent by sending them the `ForceGetTaskResult` message.

**Comment by lukasz-glen** [comment]
@shadeofblue is right.
But it is ok for Concent to respond http 400 in the situation you've mentioned.

**Comment by cameel** [comment]
Oh, OK. It was just just a clarification anyway.

**Comment by shadeofblue** [comment]
actually, it seems this one is automatically satisfied after https://github.com/golemfactory/golem/issues/2177 as HyperG verifies the content while downloading and by supporting that, we're taking care of both scenarios
