### ISSUE TITLE
Set a value in the field subtask_price in the message TaskToCompute

### ISSUE THREAD

**Issue by lukasz-glen** [golemfactory/clay#2200]
When the field field subtask_price is added in the message TaskToCompute [(see this issue)](https://github.com/golemfactory/golem-messages/issues/157), provide logic corresponding logic.

1. The field subtask_price is should be set as the value (price of subtask)*(subtask timeout).
2. Correct logic of payments. The value of payment should be equal to the value set in the field subtask_price.
3. The value computation_time in the message ReportComputedTask should be ignored.

**Comment by jiivan** [comment]
closed by #2631
