### ISSUE TITLE
Deleting Finished tasks is delayed

### ISSUE THREAD

**Issue by dixon-hill** [golemfactory/clay#2209]
In GUI, I click the trash can icon to the right of a finished task, confirm delete in the pop up, and the task remains.

Tested while with started and stopped Golem app, same behavior. Deleted tasks only disappear when shutting down and reopening the app.

See screencast:

https://www.screencast.com/t/hLudVJDJ

**Comment by dixon-hill** [comment]
Tested behavior today and the tasks were deleted without issue. The issue may only be cause when trying to delete finished tasks while, computing another task at the same time.

**Comment by badb** [comment]
@dixon-hill Do you have logs? It's probably caused by RPC router crashing and loosing connection between GUI and Golem (but that's just a guess).
