### ISSUE TITLE
Multiple confirmations of Ethereum payments

### ISSUE THREAD

**Issue by chfast** [golemfactory/clay#221]
Add support for waiting for multiple confirmations of Ethereum payment. The number of confirmations should be configurable. Ethereum Wallet uses 12.

**Comment by globatum** [comment]
@chfast this one is labeled for brass 0.4 but we are at 0.6. can we close this?

**Comment by paulperegud** [comment]
#planned

**Comment by paulperegud** [comment]
related task: #1291
