### ISSUE TITLE
Possible issue with `subtask_id` reuse

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/clay#2211]
We need to make sure that either is NOT true:
* `subtask_id` is generated once and such subtask is then sent to multiple Providers for execution (after the previous one(s) fail(s))
* we identify history messages with just the `task_id` + `subtask_id`

If both of those conditions is true (and possibly, that is the case in the current implementation), then a history of communication for a single provider can influence the subtask life for another Provider.

Thus, again - if both of those conditions are true now - we need to update Golem Core to change either the way we handle subtasks (and specifically their ids) or the way we identify historical messages.

**Comment by shadeofblue** [comment]
@jiivan @mfranciszkiewicz I think we could add a `node` to the query parameters when retrieving the `NetworkMessage`s - that way, if the node always refers to the "other Golem core" pertaining the a particular subtask (even in case the messages we exchange with the Concent), we wouldn't have those collissions... 

thoughts?

**Comment by jiivan** [comment]
Necessity of manual addition of `node` in each subtask query would introduce a huge possibility for bugs. Also some dicts would be less readable i.e. `subtask2taskmapping` etc.

In my opinion just making `subtask_id` globally unique is the solution. If we use something like `<node_id>:<uuid1>` than we would only need to verify `<node_id>` when `TaskToCompute` is received.

**Comment by jiivan** [comment]
1. Both `subtask_id` and `task_id` should be unique. Also check resource id?
1. Check code for `uuid4`. Replace it with `<node_id><uuid1>`
1. Separator is not necessary. W can assume prefix has fixed lengh (`len(node_id)`)
1. Verifying logic should be placed in golem-messages to avoid code duplication in concent
1. Places to look:
   1. `golem_messages.message.tasks.TaskToCompute (ComputeTaskDef)` (subtask)
   1. `golem.task.taskkeeper.TaskKeeper.add_task_header` ?
   1. `golem_messages.message.p2p.Tasks` (tasks list)

**Comment by Krigpl** [comment]
How is uuid1 better here instead of uuid4? Since we need to use sender_node's ID anyway when working with subtask IDs.

**Comment by jiivan** [comment]
@Krigpl `uuid4` is simple random and thus is not unique (even on one node). Even though the probability is *very* small why not cut it down to zero with a prefix (node_id) and timestamp (uuid1) to avoid problems?

`uuid1` should be unique as long as we won't generate more than 1 id per 100 nanoseconds.

The downside of `uuid1` is that it exposes `MAC address` and generators clock. It can be circumvented partially by using `<node_id><timestamp><uuid4>`. Then only clock will be exposed.

**Comment by shadeofblue** [comment]
the issue has been resolved in https://github.com/golemfactory/golem/issues/2670 and in earlier issues mentioned above
