### ISSUE TITLE
Node not in peer list, still computing tasks

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/clay#2216]
When testing release `0.12.0` i found my ubuntu server ( in the cloud ) does not get any peers from the office in `golemcli network show`, when checking the logs it shows the p2psession is trying to connect on the private IP instead of the public one.

Strange is in `golemcli network dht` the nodes are all shown properly with public IP.

Tasks get computed between the nodes but both do not see each other in the active peer list.

**Comment by jiivan** [comment]
Could it be related to #109 ?

**Comment by mfranciszkiewicz** [comment]
@jiivan Most probably. I've added a comment there.

**Comment by maaktweluit** [comment]
Grabbed a log from re-starting my node after upgrading this morning, only mwu-mac shows up as its public IP, none of the nodes are in `golemcli network show`

[golem.log](https://github.com/golemfactory/golem/files/1759132/golem.log)
