### ISSUE TITLE
Enable Docker in CircleCI tests

### ISSUE THREAD

**Issue by azawlocki** [golemfactory/clay#222]
Let's try to enable docker in circleci and see what happens. 
See: https://circleci.com/docs/docker

**Comment by azawlocki** [comment]
As of 24556fd323bdcfa290f89f655b4ef306aabd6fe3, all Docker tests pass in CircleCI.
Changes required for Docker to work:
- For some unknown reasons, calls to `client.remove_container()` raised exception `docker.errors.NotFound` (see output from tests at https://circleci.com/gh/imapp-pl/golem/640). The workaround was to wrap these calls in `try: ... except`, see c77c44ae246ca4e6ce9c993138d941941ca4732b)
- In `create_container()` specifying keyword arg `disable_network=True` caused any subsequent `start()` on the created container to fail with: 
  
  ```
  APIError: 500 Server Error: Internal Server Error ("Cannot start container 099e66dbdf74da3f6b25d75720301b31e9c8f86330c77459fda46f7823211002: empty namespace path for non-container network")
  ```
  
  (See https://circleci.com/gh/imapp-pl/golem/647). It started working when I removed the keyword arg. The effect of this change is that the containers are connected to the default `docker0` network interface created by docker.

**Comment by chfast** [comment]
Can you add the workarounds as issues?
