### ISSUE TITLE
Connection to peer failure None.

### ISSUE THREAD

**Issue by etam** [golemfactory/clay#2226]
This happens:
```
INFO     [golem.network.p2p.p2pservice       ] Connection to peer failure None.
```

Only with setting `golem.network.transport.tcpnetwork` logging to `DEBUG` you can see with which peer was a problem and the reason, like key difficulty not met, or mismatch in protocol version.

**Comment by etam** [comment]
Also, in logs peers are referred by name or id. This log line shows some UUID, so it's still hard to get what's wrong.

**Comment by mfranciszkiewicz** [comment]
The `None` value here is a `conn_id`. `conn_id` in logs is in no way correlated with node's id, so it provides little information to us. IMO this should be refactored or removed.
