### ISSUE TITLE
golemcli incomes error

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/clay#2234]
Running on ubuntu 16.04 server, latest golem b0.12.0 binaries.

```
$ golemcli incomes
[16:26:25.213399] ERROR: Exception: 'block_number'
```

**Comment by Wiezzel** [comment]
Found the guilty: https://github.com/golemfactory/golem/commit/6134a3eff772bb892cb224e0056fbc956f8eb3fb#diff-dc593ab27634482a97a6c0e15c9d001eL77
