### ISSUE TITLE
Geth connectivity issue - for payments

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#2237]
Guarantee we don't send multiple transactions for the same thing.

Scenario: send a transaction to geth, receive timeout in response. We need to check whether the transaction went through or not.

**Comment by Krigpl** [comment]
This should be implemented in smart-contracts-interface. @mfranciszkiewicz I'm fine with taking this task over if you like.

**Comment by mfranciszkiewicz** [comment]
@Krigpl Please do; you are more familiar with the sci code.
