### ISSUE TITLE
Reconnect with geth after network loss 

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#2238]
Problem: What happens during temporary internet connectivity issues. Steps to safely recover from this.

Reconnect to remote geth servers. Recover the geth state (as the connection are stateful now). Pull missing changes about payments from blockchain. Send stale payments/task results. Ask for task results if Requestor.

**Comment by mfranciszkiewicz** [comment]
There are 3 separate issues here:
- [x] reconnecting to remote geth servers and recovering the state (sync, stale payments, event filters)
- [ ] sending pending task results (https://github.com/golemfactory/golem/issues/2223)
- [x] querying providers for task results.

**Comment by Krigpl** [comment]
This is done
