### ISSUE TITLE
Tests with GPU rending

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#225]
Can we render Blender scenes using GPU? 
Can we render Luxrender scenes? 
It's propably not possible on windows instances (VM/Docker problems), but is it possible on Linux.

**Comment by maaktweluit** [comment]
nvidia has a docker image that we can use to test this: https://github.com/NVIDIA/nvidia-docker/tree/2.0

**Comment by maaktweluit** [comment]
As far as i know this is implemented now, please re-open if not correct..
