### ISSUE TITLE
[Concent] Requestor needs to ensure they have a deposit

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/clay#2250]
When both parties agree to use the Concent service, before sending `TaskToCompute`, the Requestor needs to ensure they have sufficient deposit to satisfy Provider's requirements or otherwise, the Provider can reject the `TaskToCompute`.

**Comment by lukasz-glen** [comment]
duplicates [#2761 ](https://github.com/golemfactory/golem/issues/2761)
