### ISSUE TITLE
Feature Request: golemcli settings set clean_resources_older_than <seconds>

### ISSUE THREAD

**Issue by kascheri12** [golemfactory/clay#2269]
Also: golemcli settings set clean_tasks_older_than_seconds <seconds>

This functionality would be useful for me.

**Comment by badb** [comment]
I agree, that it would be quite useful, but it should be used with extereme caution after we're on mainnet.

**Comment by maaktweluit** [comment]
If anyone wants to pick up a first issue, the allowed settings are found at:
https://github.com/golemfactory/golem/blob/develop/golem/interface/client/settings.py#L57

**Comment by wfjvdham** [comment]
The link is not working anymore
