### ISSUE TITLE
`golemcli tasks show` no remaining?

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/clay#2272]
It looks like there are always 0 tasks remaining, looking at the total % this should not be the case:

```
golemcli tasks show
id                                      remaining    subtasks  status     completion
------------------------------------  -----------  ----------  ---------  ------------
a1e5b01d-f5b2-43b0-9910-3ed311efb155            0          33  Computing  87.88 %

```

**Comment by Wiezzel** [comment]
This is remaining time, not remaining tasks. :stuck_out_tongue: But nevertheless it shouldn't always show 0.

**Comment by maaktweluit** [comment]
ahhh, TIL, thanks :)

**Comment by Wiezzel** [comment]
I will rename this column to "ETA" and make it display some reasonable values.
