### ISSUE TITLE
Keep track of the reason the task isn't supported.

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#231]
Golem Taskeeper keeps information about all of tasks in the network. Some of them are supported and some not. In the future, user may look at the list of all tasks available and see what should she do to support that type of a task, ie. install new software, lower the price or update application.

**Comment by Wolf480pl** [comment]
Should I expose this information by RPC, or is a public method on taskkeeper enough?

**Comment by badb** [comment]
We should also write this information in log (INFO severity), RPC call may also be a nice addition for debugging process.

**Comment by maaktweluit** [comment]
@Wolf480pl the related PR is merged, can this issue be closed?

**Comment by Wolf480pl** [comment]
@maaktweluit dunno. AFAIK this information is passed around but still not exposed anywhere. Ask @badb whether actually using the information somewhere is part of the issue.

**Comment by maaktweluit** [comment]
checked and can indeed be closed
