### ISSUE TITLE
Flaky test_blender_verification?

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/clay#2320]
The last week we notice this test is randomly failing, for example
```
E                   AssertionError: assert 1786 < ((2042 - 223) - 33)
tests/apps/blender/task/test_blender_verification.py:187: AssertionError
```
in https://buildbot.golem.network/buildbot/#/builders/6/builds/1926
detailed logs: https://buildbot.golem.network/buildbot/#/builders/6/builds/1926/steps/6/logs/stdio

the numbers are different but the end result is always `0 < 0` -> ERROR

**Comment by maaktweluit** [comment]
https://circleci.com/gh/golemfactory/golem/8759?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by Elfoniok** [comment]
Fix:
https://github.com/golemfactory/golem/pull/2421
