### ISSUE TITLE
Concent allowance in stats

### ISSUE THREAD

**Issue by lukasz-glen** [golemfactory/clay#2323]
There is a system parameter that enable or disable Concent usage. Extend monitor stats with information if Concent is enabled or disabled. Add logic on the monitor side, persist this information in the database, but do not show it on monitor UI (detailed list with all nodes).

**Comment by jiivan** [comment]
There are two places to look at:
1. `golem.network.concent.client.ConcentClientService(enabled)`. Comment in code suggests that it should be removed but actually it shouldn't. It should be controlled by a commandline switch (something like `--disable-concent` and `--enable-concent`)
   1. It's invoked here: https://github.com/golemfactory/golem/blob/6a943f4a08c33890513cf1cbb7e0241892db09e9/golem/client.py#L133-L136
1. https://github.com/golemfactory/golem/blob/6a943f4a08c33890513cf1cbb7e0241892db09e9/golem/task/tasksession.py#L462-L464

The conclusion is that for now there is no system parameter that can be used in stats. All nodes have `ConcentClientService` disabled, but they announce (in `TaskToCompute.concent_enabled`) that concent is active.

**Comment by jiivan** [comment]
Status of concent can be fetched from `enabled` property of `ConcentClientService` which is instantiated in `golem/client.py` :
https://github.com/golemfactory/golem/blob/9768f23bdbf3e7d27946fa43eef3fbc284cef3a6/golem/network/concent/client.py#L190-L192

**Comment by lukasz-glen** [comment]
Update: there is no need for logic on the monitor side, please do just Golem part.
