### ISSUE TITLE
Resources in stats

### ISSUE THREAD

**Issue by lukasz-glen** [golemfactory/clay#2329]
In the monitor we can see number of CPU cores and RAM. But it is not clear what is it. Is it node's system infrastructure or Golem configuration (user can set resources in Golem GUI).

1. Stats should have total available resources and declared in Golem configuration.
2. There is a benchmark in Golem. Benchmark is expressed by a number of unknown units. Figure out how many Gflops is it. Send this value to stats.

Persist all new data in the monitor's database.

**Comment by tworec** [comment]
>  But it is not clear what is it. Is it node's system infrastructure or Golem configuration 
The latter. See 
https://github.com/golemfactory/golem/blob/85f470dbd631ce5ebb7bc008b058b1772cb3f8ed/golem/monitor/model/nodemetadatamodel.py#L15-L16
