### ISSUE TITLE
All packages in requirements*.txt should have specified versions

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#2347]
We want to make sure that all packages defined in requirements files have exact specified versions and it's possible to install them on clean OSs.

**Comment by etam** [comment]
While on it, I think we could follow this guide: https://www.kennethreitz.org/essays/a-better-pip-workflow

**Comment by maaktweluit** [comment]
Made a guide on the wiki: https://github.com/golemfactory/golem/wiki/How-to-freeze-pip-modules

**Comment by Krigpl** [comment]
Done
