### ISSUE TITLE
 stats for tasks of a requester

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#2360]
it would be nice feature to have statistics of tasks that were requested on Golem - how many subtasks of specific task were computed, how many are left, and how many ended in failure (and why). Now it can be seen somehow in dev mode - dots with computing nodes. User can check it manually - inconvenient with many subtasks, no statistics there.

**Comment by maaktweluit** [comment]
~some of this info is available at `golemcli tasks stats` but i agree with you there could be more detailed info for better debugging~

I was wrong, the issue is as "requester", in that case `golemcli tasks show` can show only the % of completed tasks, and remaining tasks seems broken #2272
