### ISSUE TITLE
  Task computing error: Subtask computation failed with exit code 250

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#2361]
#### Encountered on:
Mac, binaries
Golem version 0.13.0

tried to add fishy_cat.blend
in interface I've received  error during local render test
in `golem.log`

```2018-03-14 15:45:42 WARNING  golem.docker.task_thread            Task stderr:
['blender', '-b', '/golem/resources/fishy_cat.blend', '-y', '-P', '/golem/work/blenderscript.py', '-o', '/golem/output/testresult_1', '-noaudio', '-F', 'PNG', '-t', '2', '-f', '1']
terminate called after throwing an instance of 'St9bad_alloc'
  what():  std::bad_alloc

2018-03-14 15:45:42 ERROR    golem.task.taskthread               Task computing error: Subtask computation failed with exit code 250
2018-03-14 15:45:42 ERROR    golem.task.taskthread               []
2018-03-14 15:45:42 WARNING  golem.task                          Task not tested properly Subtask computation failed with exit code 250
```
<img width="480" alt="screen shot 2018-03-14 at 15 48 51" src="https://user-images.githubusercontent.com/32061891/37426740-afb1b060-27c7-11e8-87fc-d70bb28cdd77.png">

[stderr.log](https://github.com/golemfactory/golem/files/1812772/stderr.log)

**Comment by maaktweluit** [comment]
Can you upload the .blend file or .zip used?

Is this the latest version from the docker demo site?

**Comment by mfranciszkiewicz** [comment]
bad_alloc is a sign of running out of memory. This could happen if verification was running in background.
