### ISSUE TITLE
Clarify golem.pay logs

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/clay#2368]
```2018-03-15 14:22:41 INFO     golem_sci.client                    Peer count: 25
2018-03-15 14:22:41 INFO     golem.pay                           ETH: 0.0231956
2018-03-15 14:22:41 INFO     golem.pay                           GNT: 0.0 GNTB: 1141.7166666666667
```

This is printed every 10 seconds.

- What does peer count mean? p2p peers? is this needed in INFO?
- Can we reduce the interval? we can set it to 60s or only print on changes
- Can we combine the ETH GNT and GNTB balances in 1 line with less digits?

**Comment by Krigpl** [comment]
- peer count is the geth's peer count and comes from golem_sci. I guess it makes sense to decrease the severity of this log message
- the interval is set to 13 seconds and should be of this magnitude for now - changing when the logs are displayed is better
- yes
