### ISSUE TITLE
Binary from the "develop" branch fails to start

### ISSUE THREAD

**Issue by mfranciszkiewicz** [golemfactory/clay#2389]
`Stopping because of 'setup client' error: <twisted.python.failure.Failure builtins.ModuleNotFoundError: No module named 'golem_sci.contracts.data'>`

**Comment by Krigpl** [comment]
Which OS ?

**Comment by mfranciszkiewicz** [comment]
macOS. But it seems that ‘data’ is not bundled by PyInstaller.
