### ISSUE TITLE
Make sure that tests remove their temporary files

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#239]
For example:
- tmpdirectories
- databases
- chunk image files

Additional task:
- check that tests doesn't change real nodes configuration and database data

**Comment by chfast** [comment]
I will check the status of that in #246.

**Comment by chfast** [comment]
The are 3 tests that left some files:

```
drwx------ 1 chfast chfast 1936 kwi 13 13:45 test_keysauth.TestEllipticalKeysAuth.test_sign_verifypExTJq
drwx------ 1 chfast chfast   16 kwi 13 13:43 test_localcomputer.TestLocalComputer.test_computerZbZhLc
drwx------ 1 chfast chfast  840 kwi 13 13:46 test_peersession.TestPeerSession.test_encrypt_descryptuMwgm1
```

**Comment by chfast** [comment]
In case of `test_localcomputer.TestLocalComputer.test_computer` there is a race condition. The dir is being removed while its content is modified by LocalComputer.

**Comment by badb** [comment]
https://github.com/imapp-pl/golem/pull/285
