### ISSUE TITLE
Detect amount of Ram needed for verification.

### ISSUE THREAD

**Issue by Elfoniok** [golemfactory/clay#2394]
Because rendering even small part of scene need same amount of RAM, (it is just way faster). It is possible that user will be unable to properly verify task. With default ram usage of docker container for tasks it may be to low and it will simply crash with error that it was unable to verify task.

Possibly solution to this would be detect how much memory particular scene needs. Providing this information to the user it is up to him to provide enough amount of ram. Or maybe (if he is unable to provided it) he may skip verification on his own risk?

Despite that ram of docker container should be defined per task and dynamically. So after detection (possibly on local render test?) so mapping task to container should be made and proper configuration should be set.

**Comment by badb** [comment]
We already tried to done this during LocalRenderTest. We try to measure there RAM usage and than it's set as required RAM for providers. There are still some problems with it however:
* memory measurement is not done very precise and can be improved
* verification should not be run in parallel
* user should be warned that with lowering golem caps he's risking verification failures
* user should get more information about out-of-ram LockalRenderTests problems (ie. error 247). This information is showed in logs but not in GUI.
