### ISSUE TITLE
Facade Python interface for GNR

### ISSUE THREAD

**Issue by azawlocki** [golemfactory/clay#24]
Extend and improve GNR interfaces:
- [ ] Python interface - a facade class.
- [x] CLI interface - simple like `python gnr-node.py`. It should not import any Qt packages.
- [ ] Merge and clean up startup scripts: `admmain.py`, `grandmmain.py`, `main.py`.

**Comment by azawlocki** [comment]
On a second thought, it may be just an interface (set of Python functions) for running rendering tasks from test scripts.

**Comment by chfast** [comment]
Having a facade Python interface is enough for me.

**Comment by paulperegud** [comment]
@mfranciszkiewicz I think this was resolved by #621
