### ISSUE TITLE
Test blenderrendertask doesn't work for "TGA" on windows

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#240]

**Comment by magdasta** [comment]
What are the symptoms?

**Comment by badb** [comment]
It looks like tga files aren't close properly and the test cannot remove in tearDown. Adding "img.close()" doesn't help.

**Comment by magdasta** [comment]
Something similiar happens on linux, but it seemed to work after all (files were created in the test dir and results of the calculations in the test were fine, but some (harmless?) errors were present in log). I'm not sure why this happens.

**Comment by badb** [comment]
I don't think you should spend time on this right now. Let's just remove TGA from this test. We may add it back in the future, when we find out that someone is really using this format.

**Comment by magdasta** [comment]
Ok, sure. I saw the issue, wanted to take a quick look in case I could fix it quickly ;)
