### ISSUE TITLE
Check docker capabilities

### ISSUE THREAD

**Issue by chfast** [golemfactory/clay#241]
Each running docker container has list of capabilities - what it is allowed to do.
The default list is probably too wide for Golem needs. E.g. `NET_BIND_SERVICE` allows biding to net port.

https://opensource.com/business/15/3/docker-security-tuning
https://docs.docker.com/engine/security/security/

**Comment by badb** [comment]
We should also remember about restrictions from user config, ie max memory usage, max disk usage, max num cores.

**Comment by badb** [comment]
See the resource management section: https://github.com/imapp-pl/golem/wiki/Docker
