### ISSUE TITLE
OSX 10.13.3 Golem GUI hangs on setting VM environment

### ISSUE THREAD

**Issue by S1W** [golemfactory/clay#2437]
Ports are open, status bar is stuck with message "Setting VM environment".  
Golem version 0.1.8

**Comment by maaktweluit** [comment]
Hey @S1W 

Could you run these commands to check if the VM is created properly?
Its best to turn off golem before the commands.

```
docker-machine ls
```

This will show the status of the VM. When it has errors or warnings you can try a restart with:
```
docker-machine restart golem
```

After this command succeeded it should show no more errors in `docker-machine ls` then you can try to start golem again.
