### ISSUE TITLE
Authenticate stats that are sent to the monitor

### ISSUE THREAD

**Issue by lukasz-glen** [golemfactory/clay#2439]
For the moment anyone can send any stats to the monitor, it can also impersonate someone.
Provide basic security for stats. Stats that are sent to the monitor should be signed by a node, the monitor should verify the signature before processing stats.

**Comment by RDProjekt** [comment]
To do this we need to use nodejs packages secp256k1 and js-sha3 in monitor, is that ok ?

**Comment by RDProjekt** [comment]
Also, while working on this issue we noticed that public key used as node ids is in uncompressed form(64 bytes), but compressed form is 33 bytes, so maybe node ids might be shorter ?

**Comment by RDProjekt** [comment]
We heard that release without signing stats is planned, so how should monitor react on stats sended by older clients without a signature ?
