### ISSUE TITLE
Get the root path form dir manager in CoreTaskBuilder

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#2449]
We pass both root_path and dir_manager as arguments in constructor. Dir manager should now what a root_path is. This may be part of https://github.com/golemfactory/golem/issues/1622.

**Comment by PeruvianCoder** [comment]
Hi I wanted to contribute to the project and get my feet wet with the source code, I thought this would be a good place to start. Is this issue still needed to be worked on?

**Comment by maaktweluit** [comment]
Hi @GMDays 

Thank you for the interest to contribute :)

@Wiezzel was working on this, looks like it is already part of the branch `1622_...`
Lets check with him before picking up this issue!

**Comment by PeruvianCoder** [comment]
@maaktweluit thank you for the response! @Wiezzel have you already cleaned this issue up, or is there something still left pending for me to contribute? I'm just trying to get myself introduced to the source code, and thought this was a straightforward place to start.

**Comment by Wiezzel** [comment]
@GMDays I started working on #1622 which is a larger issue possibly including this one but I never finished it. So if you want to take this one please help yourself.

**Comment by merabet00** [comment]
bon jour 
a dit tout calculer mes rester vigilant a tout geste
