### ISSUE TITLE
Address validation function should receive address None instead of 'None' 

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#2461]
We should be able to just make quick check if address is None in _is_address_valid function and return False if it is. However somewhere in the code we change the address to string and receive information about empty address in string format as 'None'.

**Comment by maaktweluit** [comment]
From #2352  I noticed it is as `'None'` during tcpnetwork transport:
```
2018-03-13 14:04:25 DEBUG    golem.network.transport.tcpnetwork  SafeProtocol._load_message(): received <Hello...
...
'prv_addr': 'None',
...
```
