### ISSUE TITLE
Make sure that enqueue_new_task accept only one type of arguments

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#2467]
Right now in old dummy_task that is used for integration tests we are passing task to client.enqueue_new_task. In other places we're adding dictionary that represents task definition and we're buliding the task using task_manager.create_task. 
test_dummy_task runner should be fixed to pass the dictionary.

**Comment by jiivan** [comment]
If this issue is resolved, #3331 won't happen again.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/161383729

**Comment by jiivan** [comment]
Currently this issue is relevant for `golem.task.rpc.ClientProvider.create_task`. `enqueue_new_task` always takes `task` as parameter.

**Comment by dybi** [comment]
@jiivan, I have scanned the code and haven't found any call to `golem.task.rpc.ClientProvider.create_task` with `Task` as argument (except for a unit test that checks if compatibility fix works). 

I would propose to remove the compatibility fix and the unit test, else you are sure there are some unobvious calls (i.e. via some callbacks, `setattr`s, etc.).
