### ISSUE TITLE
Improve test coverage of ToS

### ISSUE THREAD

**Issue by Krigpl** [golemfactory/clay#2475]
Change like this https://github.com/golemfactory/golem/pull/2462 should break at least one test.
And while at this it wouldn't hurt to refactor ToS as suggested here https://github.com/golemfactory/golem/pull/2373#discussion_r176162100

**Comment by Wiezzel** [comment]
I will do this when #2462 is reverted.

**Comment by Wiezzel** [comment]
Closed by #2489
