### ISSUE TITLE
IPFS as an (optional?) resource transfer protocol

### ISSUE THREAD

**Issue by azawlocki** [golemfactory/clay#25]
Implement resource transfer over IPFS, as a replacement for the current methods or as an additional method.

**Comment by chfast** [comment]
I think it is done. Should we discuss IPFS pros and cons? @mfranciszkiewicz?

**Comment by badb** [comment]
Pros:
- It's really working! Yay!
- Probably much safer and less buggy than our code. 
- We don't have to worry about nats and private network for sending resources.
- Trendy technology that probably will get much better in the next two years. 

Cons:
- Much slower for local computations, which make "quick" and simple local tests a nightmare. 
- Much slower for very small data. 

Conclusion:
Local tests are not typical use cases and our old methods of resource sending won't be much quicker for nodes in different private networks. So let's keep it,
