### ISSUE TITLE
Error when submitting tasks too quickly

### ISSUE THREAD

**Issue by kascheri12** [golemfactory/clay#2505]
Error while running `tags/0.14.0` on Mac 10.13.2

Receive an error regarding available ETH when creating tasks within approx 60 seconds of each other. 

```
ERROR    [golem.client                       ] Cannot create task {'name': 'Golem Task Simple', 'type': 'Blender', 'subtasks': 20, 'options': {'frame_count': 1, 'output_path': '', 'format': 'PNG', 'resolution': [3000, 2000], 'frames': '1', 'compositing': False}, 'timeout': '20:00:00', 'subtask_timeout': '0:5:00', 'bid': 3, 'resources': ['/Users/kennethascheri/Downloads/golem-header/golem-header.blend']} 
Traceback (most recent call last):
  File "/Users/kennethascheri/GitHub/kascheri12/golem/golem/client.py", line 639, in create_task
    self.enqueue_new_task(t_dict)
  File "/Users/kennethascheri/GitHub/kascheri12/golem/golem/client.py", line 518, in enqueue_new_task
    self.funds_locker.lock_funds(task)
  File "/Users/kennethascheri/GitHub/kascheri12/golem/golem/transactions/ethereum/fundslocker.py", line 67, in lock_funds
    extension="ETH")
golem.transactions.ethereum.exceptions.NotEnoughFunds: Not enough ETH available. Required: 12536000000000000, available: 2709198000000000
```

After a few seconds I try again to create task, receive same error except with available balance `5709198000000000`. Again after a few seconds with balance `8173198000000000`, until a few more seconds and then finally a task is created successfully. 

All the while, my account balance hasn't changed.
```
>> account info
finances:
  available_balance: 981.500000 GNT
  eth_address: '0xcacacd0d43a8cb1159f4da3f5529948a11bcb655'
  eth_balance: 0.019917 ETH
  reserved_balance: 18.500000 GNT
  total_balance: 1000.000000 GNT
node_name: ''
provider_reputation: 0
requestor_reputation: 0
```

**Comment by badb** [comment]
Hi! Your funds should be unlock after 24 hours. Function that unlock resources after deleting tasks or getting timeout was merged today.

**Comment by kascheri12** [comment]
I didn't need to delete tasks or anything for it to work, only waiting a minute or two.

1. Why can't I create a second task immediately after creating first one? I can create a second task 2 minutes after creating the first one, but not 10 seconds.
1. Why is my "available balance" increasing over time (that's what the error messages are telling me) while my wallet (via account info) hasn't change at all?

**Comment by badb** [comment]
2. When you add a new task to the network some funds need to pay for computation, ie. GNT and ETH are locked by Golem. ETH lockup is quite strict, it's locked enough ETH to pay for gas in the worst possible scenario, ie. highest possible gas price and every subtask being computed by different providers. Locks are removed after real payments are scheduled (with better price estimation), after task is deleted or 24 hours after task got timeout. Therefore your available balance increase with time. Wallet (account info) doesn't display locked funds. 
1. Is it possible that the first task was partially finished in 2 minutes?

**Comment by kascheri12** [comment]
Thank you, that makes complete sense and answers that question about functionality. 
Yes, the task was partially finished in 2 minutes and subtasks were scheduled for payment.
