### ISSUE TITLE
A lot of __init__.py files, are they necessary??

### ISSUE THREAD

**Issue by douglaslimaxx** [golemfactory/clay#2527]
I saw that there is a lot of __init__.py files in diferent places. I'm learning about that, sorry if i'm wrong. But those files are empty, are they necessary?

**Comment by maaktweluit** [comment]
Hey @douglaslimaxx 

They are there so our `pyinstaller` will see all folders. This is the process of making the source code into runnable binaries.

A more detailed answer and links to the docs can be found here: https://stackoverflow.com/a/44287914

**Comment by douglaslimaxx** [comment]
oh thank you.
