### ISSUE TITLE
Handling insufficient funds in GUI

### ISSUE THREAD

**Issue by kascheri12** [golemfactory/clay#2528]
GUI doesn't explain exactly why I don't have sufficient funds.
Related to #2505 
![screen shot 2018-03-28 at 8 40 01 am](https://user-images.githubusercontent.com/4165385/38040417-55909194-3264-11e8-8390-7baf25a8c3c3.png)
![screen shot 2018-03-28 at 8 45 38 am](https://user-images.githubusercontent.com/4165385/38040474-719b737c-3264-11e8-8b46-85d8bd037629.png)
![screen shot 2018-03-28 at 8 46 24 am](https://user-images.githubusercontent.com/4165385/38040507-84d64106-3264-11e8-82f8-052d14c4c947.png)

**Comment by kascheri12** [comment]
I see this and wonder - the estimate is only 0.17 tGNT - I have that amount of tGNT in my wallet.. What do I need to do to have enough funds?

**Comment by kascheri12** [comment]
1. Add estimate of ETH for the task also?
2. Tell me in pop-up that ETH is the issue so I know to add more ETH to wallet.

**Comment by badb** [comment]
@mdtanrikulu Do you receive more detailed error messages with this RPC call? Is it possible to display it?
