### ISSUE TITLE
Vulnerability in GNTPaymentChannel

### ISSUE THREAD

**Issue by LimaYes** [golemfactory/clay#2573]
Hi Guys,

in your GNTPaymentChannel contract there is this:

`
// Fund existing channel; can be done multiple times.
    function onTokenReceived(address _from, uint _value, bytes _data) {
        bytes32 channel;
        assembly {
          channel := mload(add(_data, 32))
        }
        PaymentChannel ch = channels[channel];
        require(_from == ch.owner);
        ch.deposited += _value;
        Fund(ch.receiver, channel, _value);
    }
`

This function is not private and can be called from anywhere. By not using msg.sender and msg.value but allowing the caller to set _from and _value, you can just increase your deposited value "for free" without actually spending any tokens. Then you can approve those funds to, for example, the receiver of your payment channel and have him withdraw that. The shared balance gets drained and others are left with nothing.

Just add a private modifier, that should do it!

Best wished from the XEL project.

**Comment by Krigpl** [comment]
Hey, thanks for the report. 
GNTPaymentChannels represents work in progress and is far from being ready for deployment and use. Please see https://github.com/golemfactory/golem-contracts/issues/31
Closing this issue in favor of the abovementioned.
