### ISSUE TITLE
Add support for changing sampling in Blender

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#2604]
We want to add ability for user to change rendered scene sampling for Blender scenes (Cycles scenes only, not Blender render). It will require changes in core and gui. Default sampling should be also read from blender log analyser.
For Blender Render scenes this option should be just ignored.

**Comment by Elfoniok** [comment]
This done here:
https://github.com/golemfactory/golem/commit/e0dd6eed559464c24b3aff11751ad5a357d92437
