### ISSUE TITLE
MacBook Pro Sierra 10.12.6 - Accept TOS button is broken

### ISSUE THREAD

**Issue by maxenceC** [golemfactory/clay#2610]
Hello, 

<img width="494" alt="capture d ecran 2018-04-10 a 16 36 30" src="https://user-images.githubusercontent.com/9789436/38563604-8ee8ce4c-3cdd-11e8-98bc-4fe4e23dd138.png">

I've just downloaded golem mainnet app and followed the instruction for MacOS, but I can't get pass the TOS, the accept button appears to be broken (nothing is happening)

**Comment by maxenceC** [comment]
The errors I get in the dev. console : 

<img width="449" alt="capture d ecran 2018-04-10 a 16 40 48" src="https://user-images.githubusercontent.com/9789436/38563792-fcc49cde-3cdd-11e8-83b4-53964933e191.png">

**Comment by maxenceC** [comment]
Okay, I think It's just related to port forwarding

**Comment by maaktweluit** [comment]
@maxenceC Hey, Thank you for the report!

It seems the golemapp in the background has stopped for some reason, could you please check its logs?

They can be found here: https://github.com/golemfactory/golem/wiki/Testing#where-are-the-logs

**Comment by maxenceC** [comment]
Which log file should I copy-paste ? 

golem.error.log 
golem.log
gui.log

**Comment by niposs1** [comment]
I have the same issue on Win10... just found out that doing a 'repair' on Oracle Virtual Box software and then a reboot solves the issue... it's a know issue from 2017 on previous versions

**Comment by maxenceC** [comment]
A few more people are having the same issue on reddit : 
https://www.reddit.com/r/CryptoCurrency/comments/8b6wjk/golem_release_brass_mainnet_on_github/

>I have port forwarded but when I click accept on terms nothing happens.

I think that it's not related to the ports

EDIT: The same person added : "All I had to do was enable virtualization in my BIOS. Try if it works for you too :)"

**Comment by maaktweluit** [comment]
@maxenceC we found this happens when a critical error occurs while starting golemapp.

Most of the times the docker did not install correctly and golem was not able to connect to it.

you can upload `golem.log` here on this issue or send it to contact@golem.network

**Comment by maxenceC** [comment]
@maaktweluit, actually you already fixed the bug on the chat.

For others, here is a copy-paste from the chat:

> when running: docker-machine create --driver xhyve --xhyve-virtio-9p golem

>I get : Error with pre-create check: "Error detecting VBox version: exit status 126"

>ahh, i remember that error: could you tests `which VBoxManage `

> /usr/local/bin/VBoxManage

>"that is the problem, it tries to make a virtualbox instead of a xhyve box"

I removed Virtualbox: rm -rf /usr/local/bin/{VBox,vbox}* and started golem app again, everything is working fine now

**Comment by maaktweluit** [comment]
Great! thank you for sharing the info here again!

Will close the issue for now, please dont hesitate to re-open or make another one if you have any more issues :)
