### ISSUE TITLE
error messages with linux mint

### ISSUE THREAD

**Issue by JonasBrendt** [golemfactory/clay#2611]
a@a ~/Desktop $ sh ./install.sh
./install.sh: 13: ./install.sh: declare: not found
./install.sh: 14: ./install.sh: declare: not found
./install.sh: 15: ./install.sh: declare: not found
./install.sh: 16: ./install.sh: declare: not found
./install.sh: 17: ./install.sh: declare: not found
./install.sh: 18: ./install.sh: declare: not found
./install.sh: 19: ./install.sh: declare: not found
./install.sh: 20: ./install.sh: declare: not found
./install.sh: 23: ./install.sh: declare: not found
./install.sh: 24: ./install.sh: declare: not found
./install.sh: 33: ./install.sh: declare: not found
./install.sh: 34: ./install.sh: declare: not found
./install.sh: 38: ./install.sh: Syntax error: "(" unexpected
a@a ~/Desktop $ wget https://raw.githubusercontent.com/golemfactory/golem/develop/Installer/Installer_Linux/install.sh
--2018-04-10 22:06:59--  https://raw.githubusercontent.com/golemfactory/golem/develop/Installer/Installer_Linux/install.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.112.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.112.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12310 (12K) [text/plain]
Saving to: ‘install.sh.1’

install.sh.1                                    100%[=======================================================================================================>]  12,02K  --.-KB/s    in 0,003s  

2018-04-10 22:07:00 (4,09 MB/s) - ‘install.sh.1’ saved [12310/12310]

a@a ~/Desktop $ chmod +x install.sh
a@a ~/Desktop $ ./install.sh
Docker not found. Do you want to install it? (y/n) y

INSTALLING GOLEM DEPENDENCIES

[sudo] password for a: 

INSTALLING DOCKER

OK

Installing HyperG

W: The repository 'https://download.docker.com/linux/ubuntu sylvia Release' does not have a Release file.
E: Failed to fetch https://download.docker.com/linux/ubuntu/dists/sylvia/stable/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

E: Package 'docker-ce' has no installation candidate

usermod: group 'docker' does not exist

Error occurred during installation

Done installing Golem dependencies

Installing Golem

Downloading Golem package

**Comment by maaktweluit** [comment]
Hey @JonasBrendt,

This means the docker installation does not work on your OS from the golem script.
I recommend to install `docker-ce` manually and then run the `./install.sh` again.

**Comment by mchelen** [comment]
The `install.sh` is actually a Bash script, not SH. So it must be executed like:
```
chmod +x install.sh
./install.sh
```
or
```
bash install.sh
```

**Comment by dragononcrypto** [comment]
maaktweluit is right, Docker won't install on versions of Linux Mint that has the Linux Standard Base (LSB) description set correctly to LM. The install script is currently based on the LSB whereas Linux Mint requires Ubuntu repositories. LSB previously used to reference Ubuntu version, but more recently now correctly provides Linux Mint release information. 
Hence the pull request to change LSB to Ubuntu-codename sourced from /etc/os-release, as the script will otherwise only work for older versions of LM.
