### ISSUE TITLE
Can someone explain how to get past the accept button on mac please

### ISSUE THREAD

**Issue by bizkd** [golemfactory/clay#2612]
It doesn't let me start using it because i cant accept the terms of service

**Comment by BlinkyStitt** [comment]
Same. I can't get past the accept button on OSX or on Linux. I scroll down and the "Accept" button turns from grey to blue, but clicking it does nothing.

Clicking the "Decline" button works, but that obviously blocks the app from working

**Comment by dragononcrypto** [comment]
Stupid question probably but works in Linux terminals, have you tried spacebar?

**Comment by erzwo** [comment]
Same Problem here on Windows 10 - Testnet

**Comment by spelgubbe** [comment]
same problem, win10, mainnet

edit: it seems I have to turn on virtualization (VT-x) in BIOS

**Comment by badb** [comment]
1. Remember that you have to scroll down to be able to accept the terms. 
2. It seems that it's sometimes hang on this step if there's a problem with docker. 
Can you please check docker related steps from here: https://golem.network/documentation/09-common-issues-troubleshooting/
It it won't help please join https//chat.golem.network to get some help in real time.

**Comment by alviecoin** [comment]
same problem on mac
