### ISSUE TITLE
[win10] need to couble click "X" to quit

### ISSUE THREAD

**Issue by erzwo** [golemfactory/clay#2614]
As the title says. On Win 10 I nearly always need to click the windowclosing "X" two times for the golem window to disappear.
//Edit: Often while(because?) it is having trouble to connect to the network - god know why. Maybe problems using IPv6 connections?

**Comment by maaktweluit** [comment]
There are some checks before golem closes, please wait a bit and golem should close automatically after the first X.

Could you check or share your logs? after the first X it should show "Shutting down..."

**Comment by Silko5** [comment]
If that's the case I think you should implement some message for the user, like "Golem closing...", so the user knows that the first click already did the work.

**Comment by erzwo** [comment]
Ok the network problems got solved after enabling cpu virtualization (now I know VT-d is not the only switch to touch :D )
I'll report back in case the problem exists - if it is not closing after first click.
