### ISSUE TITLE
connecting to remote RPC interface at https://geth.golem.network:55555

### ISSUE THREAD

**Issue by miloshev** [golemfactory/clay#2618]
On two Windows 10 installations, after logging in the client hangs. 
In golem.log i see continuous "connecting to remote RPC interface at https://geth.golem.network:55555"
with 0, 1 and 2 addresses also.
I have forwarded the ports on my firewall, but cant see a single packet passing.
The docker machine seems fine without errors.
In gui.log there is:
warn: Fetch golem.status failed! wamp.error.no_such_procedure {} no callee registered for procedure <golem.status> location=SAGA > HANDLER
2018-04-11T12:15:07.617Z - warn: TypeError {} location=SAGA > GOLEM
2018-04-11T12:15:12.622Z - warn: TypeError {} location=SAGA > GOLEM
.........

**Comment by badb** [comment]
@miloshev Hi, thanks for reporting! 

Can you please send full logs to contact@golem.network with reference to this issue? 

Is the problem reproducible after app restart?

**Comment by miloshev** [comment]
Ok, I will send the logs.

By the way I can’t even ping these servers

**Comment by miloshev** [comment]
It seems that there is some filtering of the IPs that connect to GETH servers (geth.golem.network)
I have connected through VPN popping out of Netherlands and now it works.
I have tried telnetting to the servers on port 55555 and it does not work from my home network (Bulgaria).
It works however from my VPS in Digital ocean and through the VPN link.

**Comment by miloshev** [comment]
Ok, so the reason is port 55555 is getting filtered from my ISP i suppose. All other ports work fine instead of this. Maybe some management port don't know.
