### ISSUE TITLE
Same output for different tasks

### ISSUE THREAD

**Issue by chfast** [golemfactory/clay#262]
Do not allow setting the same output file for different tasks. That is default when task is cloned.

**Comment by badb** [comment]
Why? Shouldn't it be a user's concern?

**Comment by chfast** [comment]
Yes. This is UX issue.

**Comment by badb** [comment]
Maybe we should just create an empty file after the task was started and then we may just warn that the file will be overwritten and ask user if he really want to do this.

**Comment by chfast** [comment]
It happened to me I had 2 tasks, and the second one overwrote the result of the first one.

Multiple non-exclusive solutions are possible:
- Offer the output file to be the named after source file: {name}.blend -> {name}.png.
- Lock the output file for running tasks.
- Ask the user if wants to save result into an existing file (confirm override).

**Comment by globatum** [comment]
@chfast has this been resolved? We are now at Brass 0.6 and this was for 0.4. ready for closure?
