### ISSUE TITLE
Error starting docker??

### ISSUE THREAD

**Issue by bizkd** [golemfactory/clay#2624]
Ive been trying to get this program to work for two days first i cant even accept the terms now another problem. Why would this program be released with so many simple problems?? Does anyone know how to fix this issue

<img width="462" alt="screen shot 2018-04-11 at 12 46 00 pm" src="https://user-images.githubusercontent.com/38267971/38639571-8032bb20-3d86-11e8-8ef2-8a72d0ce84b6.png">

**Comment by jfru** [comment]
+1

**Comment by jfru** [comment]
Following these instructions that I noticed in the terminal after installing xhyve fixed it for me:
"To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: docker-machine env golem"
