### ISSUE TITLE
Cannot un-install windows 64 bit brass golem client

### ISSUE THREAD

**Issue by noconstruct** [golemfactory/clay#2625]
I Cannot un-install windows 64 bit brass golem client, installation on my machine has caused an issue with virtualbox, the path cannot be found for the uninstaller. 

" C:\Windows\system32\msiexec.exe 

Windows cannot access the specified device, path, or file. You may not have the appropriate permissions to access the item. "

I am logged in as Administrator for this entire domain.

Another note. The Docker tool also has a similar error with the un installer.

**Comment by maaktweluit** [comment]
hey @noconstruct 

Could you try uninstalling Golem, docker and virtualbox from the control pannel > add or remove programs?

When this does not work could you make a screenshot of the error?

When all 3 are uninstalled you should be able to install virtualbox and make it work again
