### ISSUE TITLE
golem.task.taskserver.WaitingTaskResult should be a dict

### ISSUE THREAD

**Issue by jiivan** [golemfactory/clay#2633]
This class is just an implicit dict.

**Comment by tworec** [comment]
why this is closed while TODO is still in the code?

**Comment by jiivan** [comment]
It's been dataclassed in develop

https://github.com/golemfactory/golem/blob/490f754b13b3c498c09a07fcdc724ddcb1d73465/golem/task/taskserver.py#L1092-L1109
