### ISSUE TITLE
Not working on MAC OS X El Capitan (10.11.6)

### ISSUE THREAD

**Issue by cyberminotaure** [golemfactory/clay#2639]
Hello! 

I have followed in detail the instructions... and it's not working... when I start Golem...

golemapp --monitor
[57765] Error loading Python lib '/var/folders/4c/6_5s86cj7s7fhwk76vs49f540000gn/T/_MEIxRNEnj/Python': dlopen: dlopen(/var/folders/4c/6_5s86cj7s7fhwk76vs49f540000gn/T/_MEIxRNEnj/Python, 10): Symbol not found: _clock_getres
  Referenced from: /var/folders/4c/6_5s86cj7s7fhwk76vs49f540000gn/T/_MEIxRNEnj/Python (which **was built for Mac OS X 10.12**)
  Expected in: /usr/lib/libSystem.B.dylib
 in /var/folders/4c/6_5s86cj7s7fhwk76vs49f540000gn/T/_MEIxRNEnj/Python

When using the GUI... it's says "Connecting..." forever...

Any idea?

Thanks in advance for your help!

Regards,

:-)

**Comment by ivy-oak** [comment]
https://github.com/golemfactory/golem/wiki/FAQ#installing-golem
perhaps visit canyouseeme.org and verify the forwarded ports specified in golem are active

**Comment by cyberminotaure** [comment]
Port forwarding has been enabled in my router is working.  To test it I simulated a service running on 40102 by doing:  nc -l 40102... (listening on this port)

Then I do a nc -v -w 1 my_local_IP 40102 ...  (to check if port is open)

I get:  Connection to my_local_IP port 40102 [tcp/*] succeeded!

So I know the port forwarding on 40102, 40103 & 3282 are working.

But when I start Golem mainnet.app application (on my MAC)...  I got the robot picture saying Beta... and Connecting is there forever... nothing... else...

**Comment by badb** [comment]
Hi @cyberminotaure!
Can you please send us logs to contact@golem.network and refernce this issue in the email?

**Comment by maaktweluit** [comment]
hi @cyberminotaure,

Since the last release (0.15.0) we no longer supply binaries compatible with OSX 10.11, since they are build on 10.12

You can try running it from source or building binaries on 10.11, it should work, but it is no longer officially supported.
