### ISSUE TITLE
Dockey NOT installed...

### ISSUE THREAD

**Issue by taiwil** [golemfactory/clay#2654]
I have Homebrew installed on my Mac.  I have done the install numerous times.  
i Still keep getting this error. 
Error: /usr/local/opt/docker not present or broken
Please reinstall docker. Sorry :(
Please give me some advice. 
thank you

**Comment by badb** [comment]
Hi @taiwil!
Firstly, please try to follow steps from this page: https://golem.network/documentation/09-common-issues-troubleshooting/
If this doesn't help, then please join https://chat.golem.network? You can get there some user support in real time. Alternatively, you can describe your problem and send email to contact@golem.network. Please attach your logs (https://golem.network/documentation/15-understanding-logs/) if you choose this form of communication.

**Comment by ghost** [comment]
Run The Docker
Go to GOOGLE type in how to restart golem docker in APPLE MAC not sure if its an apple pr mac or both

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
