### ISSUE TITLE
Subtasks not computed after changing of IP

### ISSUE THREAD

**Issue by ktomala** [golemfactory/clay#2662]
Task with multiple subtasks will not finish if the IP address is changed during requested task computation (from requestor side). No providers are connecting for the subtask that is labeled as "Failed" after IP address change (moving between WiFi AP's locations, etc.)

**Comment by badb** [comment]
It's not a bug per se, rather not very fortunate design decision. We should however consider improving protocol to support address changes.

**Comment by ghost** [comment]
Open Dyn DNS
