### ISSUE TITLE
FS: Golem VPN-like connection for users with blocked ports by ISP

### ISSUE THREAD

**Issue by naviretlav** [golemfactory/clay#2668]
Hi. I think that it would be great if Golem could have an internal VPN-like connection protocol. 

Most of the users that have limited internet connection and use LTE/4G ( mobile routers ) or 3G ( phone hot spots ) have blocked ports by ISP. The only way to fix that is to use VPN. In China it's even worse since using VPN for internet access is illegal. 

The simple solution would be to have the encrypted extra VPN-like protocol inside golem client app that connects to main golem network or even to other users.  At beginning this feature could be limited only to the ports that golem needs to work. In future this could be expanded to make the true VPN/THOR like network using Golem network.

**Comment by ghost** [comment]
Use either Quad 9.9.9.9 or 1.1.1.1 as DNS on Router

**Comment by naviretlav** [comment]
@qanon1111 , this doesn't solve the issue at all. The ISP filters and blocks all the connections.

**Comment by Incrediblez7** [comment]
1.1.1.1 doesn't work in China.
