### ISSUE TITLE
[UX] After Brass is installed default slider to some amount of computing power.

### ISSUE THREAD

**Issue by 4943591** [golemfactory/clay#2675]
After installing Golem Brass the computer restarts and then you can begin using Golem. However, if you open Golem, the process begins by default and left me thinking that my computer was ready to process tasks. 

However, because the slider of Machine resources is defaulted at zero, my computer spent a couple of days on without computing a single task. Of course after some research I realized that you can edit the slider after clicking on "Stop Golem" 

This could be avoided by either defaulting the slider to at least some computing power, or defaulting Golem to be stopped and let the user start it by clicking on the button. 

Hope this feedback helps!

**Comment by badb** [comment]
Hi @maflores16 
There is a bug in GUI that doesn't display properly allocated resources after Golem is started, but in fact those resources are allocated.
There can be another reason why your computer was not able to compute task, having too low allocated reasource is just one option. Is everything working correctly now?

**Comment by 4943591** [comment]
Well, ports are open, nodes display on Golem, but I've never seen a task be completed. I just thought maybe there weren't tasks to compute at the moment. 

Yesterday I left my computer on and this morning when I wiggled the mouse to turn on the monitors it quickly showed that the nodes were back to zero and changed immediately to a couple until reaching 10 nodes. Does Golem turn off if computer is idle for too long or when the computer is set to monitors turning off (not suspending the pc)?
