### ISSUE TITLE
Sending balance to monitor sholud be configurable.

### ISSUE THREAD

**Issue by Elfoniok** [golemfactory/clay#2681]
Function which was sending account balances to monitor was simply removed (as we didn't use those data). As @Wiezzel points this should be configurable. 

Task is to restore this function, probably it would be great to design such solution where one can easy enable/disable data sent to monitor, with simple configuration settings. It would be best if in case when message is disabled signal was not propagated at all.

For example:
send_payment_info is used in handler function, this cause handler to early return, when this could be used to not connect handler at all, or even not send signal from payment processor.

**Comment by Wiezzel** [comment]
Ref: https://github.com/golemfactory/golem/pull/2651#pullrequestreview-112034901

**Comment by Krigpl** [comment]
Not relevant anymore
