### ISSUE TITLE
Add RPC call to see provider state 

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#2704]
Providers may be interested if their nodes is currently computing task or not. It will be display in GUI in footer but we need a proper RPC call that displays current state of provider, ie. 
* computing subtask (deadline: xxx)
* trying to get subtask from task
* waiting for tasks
We may want to add additional states if that's possible. 

We want to also add proper CLI method that displays result of this method.

**Comment by etam** [comment]
Instead of creating new command, a new line is added to `golemcli tasks stats`.
