### ISSUE TITLE
How to find GNT wallet address used by node?

### ISSUE THREAD

**Issue by kascheri12** [golemfactory/clay#2713]
I can't seem to find the address of my node's GNT wallet. How do I add GNT so I can request more tasks?

**Comment by kascheri12** [comment]
I was confused when reading the output of `golemcli account info` since `eth_address` doesn't specifically tell me that it's a gnt address also. 
I have since sent GNT to this address and successfully seen the amount in my node's account info.

**Comment by maaktweluit** [comment]
The GNT address is the same as the ETH address, from CLI this is less clear then from the GUI
