### ISSUE TITLE
Connected to Nodes 10 to be exact

### ISSUE THREAD

**Issue by ghost** [golemfactory/clay#2728]
Iam connected to 10 nodes with 1 GNT. Iam providing, I have yet to see anyone request after changing settings from trusted network 0 to 100, still no requestors, I have my resources set to 100 and I want to know why I have 10 nodes riding my coat tail and not providing me with any payment regardless if rendering I dont want 10 nodes riding my coat tail from 100 to 0 network. at .1 payout to 1.0.

**Comment by ghost** [comment]
Can anyone say they have been paid anything on  this platform as promised ?

**Comment by maaktweluit** [comment]
Hey @qanon1111 

be careful changing trust settings, with wrong configuration you might never pick up any tasks.
Currently the network has a lot of providers and not so much requestors, it can take a while before you pick up any task.

Did you confirm your ports are forwarded correctly? when nodes are connected and ports forwarded you are ready to compute :D

I'm not sure what promise you refer to, please read the risks involved with participating in this BETA: https://golem.network/documentation/02-risks/

When you have any more questions feel free to re-open this ticket or create a new one.
