### ISSUE TITLE
GOLEM throw NordVPN

### ISSUE THREAD

**Issue by joaopaulopinho** [golemfactory/clay#2746]
Hello. Using golem app for some days now. Today I bought a VPN (nordVPN) and I started it on the PC where it was running. But now, with the VPN active, I have "problem with ports". How can I solve it and put it back to work?

**Comment by marce1994** [comment]
i think, you can't do that. seems that golem creates a vpn too.
a vpn is just for web browsing, not to give your server some more "privacy". @joaopaulopinho Normally, vpn services, has firewalls or something like that.

**Comment by badb** [comment]
VPN will allow you to make outgoing connections but will block you incoming traffic and golem will still use your normal ip address ports to describe task requestor location. So right now it's not possible.
If we add some relaying services or data routing through other nodes, it may help (as for other network scenarios when ports are not forwarded).
