### ISSUE TITLE
Golem on Raspberry Pi3B+ Ubuntu 16.04

### ISSUE THREAD

**Issue by heiko1234** [golemfactory/clay#2747]
Hey there,

I'm new to this project but I found it very interesting. 

Since I have 2 Raspberrys left from an old project, I was thinking I can use either Pi3B or PiB+ for this project.
I installed Ubuntu 16.04 Mate on pi3B+ (yes, it works fine), installed Docker-CE (separated before golem) and then Golem. The installation run without any errors. 
I then tryed to run golemapp but I got an error. Maybe it can be fixed?! Maybe it is something simple?!

The error for $ sudo golemapp
/user/local/bin/golemapp: 1: /user/local/bin/golemapp: Syntax error: Unterminated quoted string 

I'm not sure where I need to check to make it running.
I updated the OS with $sudo apt-get update and $sudo apt-get upgrade but it is still not running.

It would be greate if a Pi3 could be introduced to the network...I guess there some more interested in this topic.
Thanks for your help and adivices. Any hints are welcome.

**Comment by badb** [comment]
Hi @heiko1234!
Raspberry Pi3B+ is still below minimal requirements for golemapp so there are many things that can go bad. 
Debugging binary vesion can be difficult, so if you are able to spend more time on this, I would strongly suggest you to try to install the source code version so you can get much better error messages.

**Comment by mfranciszkiewicz** [comment]
Golem binaries are built for the x86-64 architecture, whereas the Pi board is based on an ARM processor; it's not possible to run the released binaries. Also, Docker images are pre-built for the x86 architecture.

The only option to run Golem on a raspberry is to install it from source, build the Docker images by hand and manually build / link or start [HyperG](https://github.com/mfranciszkiewicz/golem-hyperdrive) before running Golem.
