### ISSUE TITLE
Open VirtualBox preventing Windows from shutting down

### ISSUE THREAD

**Issue by mikalehmann** [golemfactory/clay#2748]
I always get the message that VirtualBox is preventing Windows (10) from shutting down after I used Golem. I assumed that VirtualBox would quit after ending Golem, but that's not the case.

**Comment by badb** [comment]
Hi @Lehmax 
Are you using version 0.15.1 or 0.15.0?

**Comment by mikalehmann** [comment]
0.15.1. Sorry for forgetting to mention that.

**Comment by badb** [comment]
Stopping VirtualBox after all tasks & verification is finished may be added to the todo list for this task: https://github.com/golemfactory/golem/issues/2606
