### ISSUE TITLE
New logo proposal to Golem

### ISSUE THREAD

**Issue by foways** [golemfactory/clay#2749]
<h4>Hi everyone, this is my first contribution to GOLEM, I have designed a logo that is a minimalist and clean logo.</h4>

<h3>Basic concept of logo design:</h3>

![concept](https://user-images.githubusercontent.com/38687140/39528266-d2f363be-4e4d-11e8-9e58-f0b62923de72.png)

<h3>And here's the final result of the logo I've created:<h3>

![1](https://user-images.githubusercontent.com/38687140/39527727-62227e78-4e4c-11e8-9a29-2ec8bbd0577b.png)
![2](https://user-images.githubusercontent.com/38687140/39527740-6abf5e2a-4e4c-11e8-9da7-fff179c60531.png)
![3](https://user-images.githubusercontent.com/38687140/39527771-7ef8ae8c-4e4c-11e8-8709-27316db5c703.png)
![bw](https://user-images.githubusercontent.com/38687140/39527893-d6b4b8a0-4e4c-11e8-8787-49668da9f616.png)

<h2>Give me feedback if you like this, and I am also welcome if any suggestions for improvement.</h2>

**Comment by badb** [comment]
Hi @k-syusteem, 
Thank you for your proposal! Can you send it to contact@golem.network so people responsible for branding can take a look?

**Comment by foways** [comment]
Hi @badb!
Already, I have submitted it before creating the issue here!
