### ISSUE TITLE
[Concent] Automatic Concent desposits

### ISSUE THREAD

**Issue by jiivan** [golemfactory/clay#2761]
| Role | When |-|
|-|-|-|
| Requestor | immediately after creating `TaskHeader` and putting it in `P2P service`| Done |
| Provider | When requesting additional verification | In progress |

| Role | Min amount | Optimal amount |-|
|-|-|-|-|
| Requestor | `2tp deposit + 1tp gntw` | `4tp deposit + 1tp gntw` | Done |
| Provider | `subtask_price` | `4*subtask_price`| In progress |

**Comment by lukasz-glen** [comment]
Please refer to [G 5.4](https://docs.google.com/document/d/1fY2E8uRXVJjdmWjl1l5qz02TterB_wIlspHGbBw_LkM/edit#heading=h.ifd047f71yjw) and [G 6.1 and G 6.2](https://docs.google.com/document/d/1fY2E8uRXVJjdmWjl1l5qz02TterB_wIlspHGbBw_LkM/edit#heading=h.h2xnlx3ide7r)

**Comment by jiivan** [comment]
Already done in:
https://github.com/golemfactory/golem/blob/2aa5d432594227aeba1c6302eba9a76f0096e431/golem/task/tasksession.py#L702-L719
