### ISSUE TITLE
it is not possible to restart whole frame of a finished task

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#2762]
### Steps to reproduce:

- Upload multiframe task (in this example two frames and 10 subtasks)
- Wait for task to finish
- Go to second preview window with finished frames (this one with rectangles), hover over the frame, click "Resubmit"

result:

task was not restarted

in task tab:
<img width="513" alt="screen shot 2018-05-10 at 15 48 58" src="https://user-images.githubusercontent.com/32061891/39883323-cddcb8d2-5486-11e8-8c5d-3d0618cb055d.png">
progress bar jumped backwards, to 50% but status of a task remained finished

in settings of a task five subtasks (one frame) were restarted

<img width="520" alt="screen shot 2018-05-10 at 15 49 13" src="https://user-images.githubusercontent.com/32061891/39885372-b5bf4886-548c-11e8-85ed-0daa47ccb409.png">

in golemcli
task is shown as finished, 50%

<img width="757" alt="screen shot 2018-05-10 at 15 49 48" src="https://user-images.githubusercontent.com/32061891/39885403-cb636aa0-548c-11e8-9183-00e8190654bd.png">

#### Encountered on:
binaries from build 0.15.1+dev4.ge1b40e48e, Mac Os

**Comment by badb** [comment]
Was the new task created? Are pictures and description about finished tasks that was restarted? Do you have logs?

**Comment by ederenn** [comment]
Yes, pictures are about finished task that was restarted. No, new task wasn't created.
Logs from that day:

[golem.2018-05-10.log](https://github.com/golemfactory/golem/files/2026523/golem.2018-05-10.log)

**Comment by badb** [comment]
It seems that two tasks were created, but the second one has some problems with properly defined number of total tasks. This should be investigated further. Do you remember exact parameters of your scene, ie. number of frames & total tasks?

**Comment by ederenn** [comment]
2 frames, 10 subtasks. (five subtasks per frame). resolution from file.
