### ISSUE TITLE
[Concent] Provider checks Requestor's GNTB balance and deposits

### ISSUE THREAD

**Issue by lukasz-glen** [golemfactory/clay#2766]
When Provider gets new subtask to compute and Concent is enabled for this subtask, he checks if Requestor has required GNTB balance and deposit. Please refer to [documentation (G 6.3, G 6.3.1 and G 6.3.2)](https://docs.google.com/document/d/1fY2E8uRXVJjdmWjl1l5qz02TterB_wIlspHGbBw_LkM/edit#heading=h.h2xnlx3ide7r)

**Comment by lukasz-glen** [comment]
@jiivan you have done some work with Concent negotiation, please check it up if it is partially done

**Comment by jiivan** [comment]
> G 6.3
> Provider gets new subtask to compute
> This existing use case. This description regards only its interaction with contracts.
> After Provider receives TaskToCompute but before he starts to compute, Provider checks if Concent flag in TaskToCompute is set properly and then he checks Requestor’s wallet and deposit. If Concent flag in TaskToCompute is not set properly, then Provider cancels computation by sending CannotComputeTask. Provider checks if Requestor’s GNTW balance is at least (total task price). If Concent is enabled, then Provider checks if Requestor’s deposit is at least 2*(total task price). If it is not then Provider cancels computation by sending CannotComputeTask.
> Relations: G 6.3.1, G 6.3.2
> 
> G 6.3.1
> Provider checks Requestor’s deposit
> Input: required value, Requestor’s Etherum address
> This simple function checks if deposit of the given Ethereum address is not less than the required value. It also checks locked_until field, if it is set and will elapse within 48 hours, then deposit should be considered as invalid.
> TODO confirm 48 hours time interval
> 
> G 6.3.2
> Provider checks Requestor’s GNT balance
> Input: required GNTW value, Requestor’s Etherum address
> This simple function checks if GNTW balance of the given Ethereum address is not less than the required value.
>
