### ISSUE TITLE
Interface communication problem with Golem. Please restart.

### ISSUE THREAD

**Issue by jish** [golemfactory/clay#2767]
I have opened up ports `40102`, `40103`, and `3282`.

<img width="892" alt="screen shot 2018-05-14 at 6 51 23 pm" src="https://user-images.githubusercontent.com/1817/40032276-4a814578-57a8-11e8-8bee-d8e5e143e182.png">

I see an error `Stopping because of 'keys or docker' error` in `~/Library/Application Support/golem/default/mainnet/logs/golem.error.log`

    2018-05-14 18:32:09 WARNING  golem.docker.manager                Docker: building image golemfactory/base:1.2
    2018-05-14 18:32:09 ERROR    app                                 Stopping because of 'keys or docker' error: <twisted.python.failure.Failure twisted.internet.defer.FirstError: FirstError[#2, [Failure instance: Traceback: <class 'subprocess.CalledProcessError'>: Command '['docker', 'build', '-t', 'golemfactory/base', '-f', 'core/resources/images/Dockerfile', '.']' returned non-zero exit status 1.
    /usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py:916:_bootstrap_inner
    /usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py:864:run
    /Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/_threads/_threadworker.py:46:work
    /Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/_threads/_team.py:190:doWork
    --- <exception caught here> ---
    /Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/threadpool.py:250:inContext
    /Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/threadpool.py:266:<lambda>
    /Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/context.py:122:callWithContext
    /Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/context.py:85:callWithContext
    /Users/buildbot-worker/worker/buildpackage_macOS/build/golem/node.py:237:start_docker
    /Users/buildbot-worker/worker/buildpackage_macOS/build/golem/report.py:121:wrapper
    /Users/buildbot-worker/worker/buildpackage_macOS/build/golem/docker/manager.py:147:check_environment
    /Users/buildbot-worker/worker/buildpackage_macOS/build/golem/docker/manager.py:324:build_images
    /Users/buildbot-worker/worker/buildpackage_macOS/build/golem/report.py:121:wrapper
    /Users/buildbot-worker/worker/buildpackage_macOS/build/golem/docker/manager.py:341:_build_images
    /Users/buildbot-worker/worker/buildpackage_macOS/build/golem/docker/manager.py:306:command
    /usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py:336:check_output
    /usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py:418:run
    ]]>

**Comment by badb** [comment]
Hi @jish 
Does restarting the app help? If not, try steps described here: https://golem.network/documentation/09-common-issues-troubleshooting/docker-errors-on-windows-10/
If you have further problems please contact us on rocket: https://chat.golem.network

**Comment by boralprophecy** [comment]
In Windows 10, this solves the issue : 

STEP 1:
Open the command prompt as an Administrator.

STEP 2:
Run the command with no argument: bcdedit

STEP 3:
Disable Hyper-V by running the command: bcdedit /set hypervisorlaunchtype off

STEP 4:
Restart your PC system to use VirtualBox.    ( NOTE : Don't ShutDown, use the restart feature ).

Source : https://discuss.erpnext.com/t/virtualbox-wont-run-raw-mode-unavailable-courtesy-of-hyper-v/34541/10
