### ISSUE TITLE
Add minimal performance option in GUI

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#2771]
The aim of Golem is to speed up computation therefore requestors may only want to choose providers with performance equal or above their machine’s performance. 
We are able to set performance by hand from CLI but it would be good to add it nicely presented in GUI. 

What is required:
* Defining if we want to set this option per task or as a general config - all
* Design of convenient way for users to set this option. Users probably should be able to check their own performance and edit required performance accordingly to their own benchmark result. @jamuszyn
* Implementation of the designed GUI @mdtanrikulu
* Implementation of proper RPC calls (if one that are right now are not adequate to chosen method). @tworec

**Comment by tworec** [comment]
It is partially addressed in #2734

**Comment by tworec** [comment]
interaction from @jamuszyn https://invis.io/6JJ0IF9ZU54#/297977145_dont_Want_To_Be_A_Provider_Copy_2

**Comment by tworec** [comment]
implementing this is useless w/o fixing golemfactory/golem-electron#346 first

**Comment by tworec** [comment]
@badb @mdtanrikulu @jamuszyn lets summarise our decisions:

We will introduce `performance multiplier` expressed as percentage of current requestor performance value. It will affect all golem use cases -- work offer will be accepted only when:

`[provider performance] >= [requestor performance] * [performance multiplier] / 100`

Performance multiplier can vary from `0%` to `1000%` (10x). By default we will set it to `100%`.

# Examples
Assume that we (as a requestor) have `blender performance = 700`. Given that, when `performance multiplier` is set to:
- `0` we will accept all work offers
- `50` we will accept work offers from providers with at least half of our (requestor) blender performance ie. `>= 350` 
- `100` accept only providers as strong as we are or strongest `>= 700`
- `200` accept only at least twice as strong as we are `>= 1400`

**Comment by tworec** [comment]
RPC part is done https://github.com/golemfactory/golem/pull/2734
waiting for review

@mdtanrikulu check out new RPC mappings.

**Comment by jamuszyn** [comment]
Updated UI https://invis.io/WRJHIZFYVD8#/299290253_Calculate_Benchmark

**Comment by mdtanrikulu** [comment]
The final decision for the upcoming release is; 

We will keep minimal performance slider as easy as possible and in safe range. Thumb of the slider will run onto 10 simple steps. 

- Level (step) `0` will accept all work offers
- Every step will increase desired score by `300`. (Max will be `3000` for blender usecase)
- Users will be able to see which level their performance on.

**Comment by tworec** [comment]
RPC names will stay unchanged:
- `performance.multiplier` for get value
- `performance.multiplier.update` for set
and will accept float value between 0 and 10

CLI would allow to set this value event beyond 10x.

**Comment by tworec** [comment]
This is not resolved yet, as I do not see GUI changes...

**Comment by tworec** [comment]
ok, there is golemfactory/golem-electron#348 with GUI changes, but not merged yet
