### ISSUE TITLE
Tile banding visible in an output of a scene rendered using Blender Render

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/clay#2772]
The task resources (scene):

[wlochaty2.zip](https://github.com/golemfactory/golem/files/2007970/wlochaty2.zip)

parameters:

```
{
    "duration": 18705.01483798027,
    "preview": "/home/blue/golem-provider/rinkeby/res/8817d446-5840-11e8-af88-2409ba74ad65/tmp/current_task_preview.PNG",
    "id": "8817d446-5840-11e8-af88-2409ba74ad65",
    "name": "wlochaty2",
    "type": "Blender",
    "subtasks": 10,
    "progress": 1.0,
    "options": {
        "frame_count": 1,
        "output_path": "/home/blue/Documents",
        "format": "PNG",
        "resolution": [
            3840,
            2400
        ],
        "frames": "1",
        "compositing": false
    },
    "time_started": 1526389482.1630464,
    "time_remaining": 0.0,
    "status": "Finished",
    "timeout": "10:00:00",
    "subtask_timeout": "1:00:00",
    "bid": 1.0,
    "resources": [
        "/home/blue/Documents/wlochaty2/wlochaty2.blend",
        "/home/blue/Documents/wlochaty2/puchacz_canopy.jpg"
    ]
}
```

**Comment by shadeofblue** [comment]
This is the output rendered using Golem with 10 subtasks:

![wlochaty2](https://user-images.githubusercontent.com/7963044/40103533-0be641fa-58ee-11e8-9c83-7adc1dbdda10.PNG)

**Comment by shadeofblue** [comment]
This is the output rendered using Blender directly:

![untitled](https://user-images.githubusercontent.com/7963044/40105631-d0f07ace-58f3-11e8-9d2f-847f1f42b523.png)

**Comment by Elfoniok** [comment]
Actually one can see that the division line exists on material itself, hair doesn't have much with this. For this effect material option "Subsurface scattering" is responsible. We don't know why yet, but if scene is rendered part by part (like in golem when scene is divided on strips) in some areas of such material it yields clear divisions between subsequent strips.

**Comment by Elfoniok** [comment]
Here is output without hairs (slightly lower resolution)
![wlochaty2 4](https://user-images.githubusercontent.com/662433/40167193-acb08bb8-59c0-11e8-8fd2-0450a5028375.PNG)

**Comment by magdasta** [comment]
Are we going to support the "subsurface scattering" effect? Or are we going to give up on it?

**Comment by badb** [comment]
Give up on it. Blender Render is going to be removed in next Blender version anyway. And this issue can be fixed by properly preparing scene, ie. prebaking textures. 

We are going to add proper info to docs / tutorials, though.
