### ISSUE TITLE
Golem is not connecting automatically with external nodes 

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#2801]
when running Golem, in interface it is shown "no nodes connected", while external nodes are working.
Golem starts connecting to external nodes after typing in console window `golemcli network connect seeds`

```
 b'GOLEM Version: 0.15.1+dev184.g711bb19 '
b'Protocol Version: 27 '
b'golem_messages Version: 2.9.0 '
```

**Comment by badb** [comment]
Not a bug, it's a feature ;) 
Golem uses default hardcoded list of seeds / bootstrap nodes. All the hardcoded ones right now point to 0.15.1. New one that work with 0.16.0 were not added to hardcoded seed list yet.
