### ISSUE TITLE
Print task ID after using tasks create in the CLI

### ISSUE THREAD

**Issue by cryptobench** [golemfactory/clay#2809]
Right now the steps to getting the task ID is by first calling `golemcli tasks create filename` and then calling `golemcli tasks show`.

It would make things a lot easier if the terminal just printed 2 lines after calling `golemcli tasks create filename` 

One being the currently implemented one **Completed in x**
Second being the **task ID**

**Comment by maaktweluit** [comment]
This issue has been resolved by #3031
