### ISSUE TITLE
[Concent] deposit pool for integration tests

### ISSUE THREAD

**Issue by lukasz-glen** [golemfactory/clay#2819]
Because of transactions duration it would be more efficient to maintain a pool of Ethereum accounts with deposits already paid and reuse them for tests.

**Comment by shadeofblue** [comment]
ah, @maaktweluit I think you bravely took this one ;)

**Comment by maaktweluit** [comment]
indeed: https://github.com/golemfactory/golem-granary

There is also a server setup that will start serving the `node_integration_tests` soon
