### ISSUE TITLE
Improve docker images management

### ISSUE THREAD

**Issue by chfast** [golemfactory/clay#282]
- [ ] Version Golem docker images, e.g. golem/blender:0.1.
- [ ] Do not build the image again if already available.
- [ ] Cache built images on CircleCI: https://github.com/imapp-pl/golem/pull/254/commits/1830f046c3d3d8baa4843e1b420cc0939197e528.

**Comment by badb** [comment]
This task is connected with that one #182

**Comment by badb** [comment]
- [x] Version Golem docker images, e.g. golem/blender:0.1.
- [x] Do not build the image again if already available.
- [ ] ~~Cache built images on CircleCI: https://github.com/imapp-pl/golem/pull/254/commits/1830f046c3d3d8baa4843e1b420cc0939197e528.~~
  Cache doesn't seem to speed up builds very much (they still have to be loaded from ziped files).
