### ISSUE TITLE
Add statistics display to CLI

### ISSUE THREAD

**Issue by cryptobench** [golemfactory/clay#2861]
Would be cool to have some kind of metrics or stats query from the CLI

`golemcli tasks stats`

> Total tasks requested: **xx**
+ for each status:
> Total [status]: **xx**

`golemcli node uptime` [ research needed ]

> Total uptime: **xx**
> Total computation time: **xx**

> [to be checked/decided] can we accumulate those values between Golem runs?
> Cumulative total uptime:
> Cumulative total computation time: 

`golemcli tasks`

> Total GNT spent: **xx**
> Total ETH spent: **xx**

`golemcli incomes total`

> Total amount of GNT received: **xx GNT**

**Comment by badb** [comment]
@jamuszyn Can you take a look at this?

**Comment by jamuszyn** [comment]
@badb Looks good, adding to the CLI changes list
