### ISSUE TITLE
Payment disappears after being added to the history

### ISSUE THREAD

**Issue by tenninebt** [golemfactory/clay#2876]
Hello,

I have noticed a strange behaviour where completed jobs are first shown on the history, then mysteriously disappear. When I compare the successful tasks vs history count, I see 6 missing payments. I actually screen captured some of them after I detected the issue. I have also realised that the issue started when I increased the "accept tasks = 3" (Was 1), I thought my mac could handle more than a task at once. Anyway, not sure it is related, but all I know is that once I put back the parameter to 1, restarted, haven't had any occurrence. I can provide the logs and the screenshots if it can help.
Another detail is that the payments that were disappearing was quite high, around 3.78 per task. 
I hope it helps !

**Comment by badb** [comment]
Hi @tenninebt. 
`accept tasks` is a boolean option so there's no point in changing it to anything higher than 1. 
Can you please send us screenshots with logs to contact@golem.network with a reference to this issue? 
The differences may however be a result of slightly different way that successful tasks and payments are defined. The first one means that your machine computed subtask without errors before deadline. It does not implicate however that it manage to send back the results or that results were verified correctly.

**Comment by Krigpl** [comment]
Resolved in 0.18.0
