### ISSUE TITLE
Fix help message to "account withdraw" command

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#2880]
> account withdraw
the following arguments are required: amount, destination, currency

Should be: the following arguments are required: destination amount currency. For eg. account withdraw 0x74446B4FB2Cca2fd8A475Bc40606b77d8d7659C4 3 GNT

Also, information about locked withdraws on the testnet should be shown earlier for the user, not after he types all necessary commands. Maybe just add comment in account “withdrawals are not available for the testnet”

**Comment by etam** [comment]
It's not "fix help message" (nothing's broken here), but "change arguments order".
