### ISSUE TITLE
Requesting node runs out of disk space

### ISSUE THREAD

**Issue by etam** [golemfactory/clay#2889]
Affects: 0.16.0

When running a node that has `accept tasks = 0` and is requesting tasks, it quickly fills the disk space (100GB in 2-3 days). The space can be reclaimed by running `./golemcli.py res clear --provider`.

**Comment by badb** [comment]
@etam What's the connection of `accept tasks = 0` and runningo out of disk space? It seems that `ResourceCleanerService` is not connected in any way to this option. 
You can however force resources to be removed more often by changing `clean resources older than second` option.

**Comment by etam** [comment]
> What's the connection of `accept tasks = 0` and runningo out of disk space?

That's a good question. I pointed this out, to make it clear that the node is not accepting tasks. But the command `./golemcli.py res clear --provider` suggests that it keeps resources as a provider. So either there's something really wrong, or at least the command `./golemcli.py res clear` has swapped meaning of "provider" and "requestor".
