### ISSUE TITLE
Proper capabilities mechanism

### ISSUE THREAD

**Issue by Elfoniok** [golemfactory/clay#2909]
We are lacking proper ways of selecting providers based on their capabilities to compute task.

Recent example show us that due to scarce resources, (because hardware limitation or short allocation in VM settings) some providers doesn't fulfill minimal requirements for the task. Such providers shouldn't be selected by requestor.

Until know our only minimal requirement for a task was `subtask timeout` as we assumed that every task can be calculated anywhere sometimes just painfully slow (maybe using swap memory).

This is connected to our benchmarking mechanism but not quite the same. Current benchmark use bmw scene which require around 300~400Mb of memory (this empirically checked, and it doesn't depend on resolution it's just faster you have smaller resolution) so this way we are not able to check if provider is able to compute big, memory demanding scene like gooseberry.

We could add another minimal requirments which is a memory for blender case.

Requestor should prefer providers with higher benchmark results, but should filter out those who doesn't fulfill minimal requirrments.
Requestor need to estimate somehow minimal requirements (memory, since timeout is given arbitrary)  that need to be met by providers, and then select only those that are up to do the task.
Providers capabilities can change dynamically, but in order to do so, one needs to disconnect from the network, so its not that hard since we can define it once for entire session.
It seems harder to properly estimate minimal requirements for the task.

**Comment by badb** [comment]
There is a memory limit included, it was just not set properly from GUI and require specific user interaction from CLI.
