### ISSUE TITLE
[CI] Pull request approval checking should be separated from the test runs

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/clay#2917]
Right now, when tests are run with not enough approvals, the whole test suite needs to be re-run finally after the approvals of a pull request are there.

That seems detrimental to the task's flow.

**Comment by maaktweluit** [comment]
The build queue got too long when we implemented this. The fast vs slow tests resolves this partially by running shorter builds when there are no approvals ( and the PR could not be merged anyway )

I do not see how this is detrimental to the task flow, when a PR is approved in the grace period ( 1m ) after its made it will build slow right away.

Could you provide a scenario where this is hurting your task flow? i'm happy to help look into ways of solving this :)

**Comment by shadeofblue** [comment]
@maaktweluit ah - well - I didn't know that you were running a different set of tests once the approvals are there... what I was thinking about was to separate the part that's executed after the approvals are added so that it can be executed quickly without a long wait

**Comment by maaktweluit** [comment]
Yes, all tests marked `slow` are only run after approvals. 
Tests not marked are run both times.

Splitting the tests, never running duplicates sounds like a great idea!

The challenge is to combine the coverage of all 6 tests, but this is certainly possible :D 
This will also increase the amount of "status" checks on each PR, but i feel that is worth it.
