### ISSUE TITLE
Task ... request rejected: NoMoreSubtasks

### ISSUE THREAD

**Issue by bortkiewicz** [golemfactory/clay#2919]
I'm running the Golem CLI v0.16.0 on mainnet. A lot of the time, a task will be added and then immediately afterwords it would say

    Task ... request rejected: NoMoreSubtasks

Is this normal?

**Comment by maaktweluit** [comment]
Hey @testitem 

Thank you for reporting this issue!

Yes, this is normal, after the task is added to your list your node will ask for a subtask to start computing. When all subtasks have been given out you will receive a NoMoreSubtasks message back. Your node will try all active tasks in its list once in a while.

Currently there are more providers then requestors in the network so this will happen a lot, once there are more providers this error should be less common but still nothing to worry about.

Closing this issue now, feel free to re-open it when you have any more questions.
You can also join our chat at chat.golem.network and get answers live, you can tag me on the same username if you like.
