### ISSUE TITLE
--log-level overrides log level written to golem.error.log

### ISSUE THREAD

**Issue by etam** [golemfactory/clay#2944]
Affects 0.16.1

**Comment by maaktweluit** [comment]
`--loglevel` is for crossbar and `--log-level` is for golem
crossbar levels are lower case and with `warn`
golem levels are capitals and with `WARNING`
all other levels have the same names, just other capitals

if i remember correctly only `warn` and `error` should show from crossbar inside the golem logs, as `WARNING` and `ERROR`, this can be toggled with the setting for 3rd party logs

not sure if this is related to this issue, hope it helps clarify the arguments :)

**Comment by etam** [comment]
Sorry, it's about `--log-level`

**Comment by etam** [comment]
seems to be resolved with 0.21.0
