### ISSUE TITLE
Task result preview image glitch

### ISSUE THREAD

**Issue by mdtanrikulu** [golemfactory/clay#2946]
There is a glitch while merging all subtask results as preview image. In preview screen of the GUI, some subtasks seems like does not started to computation yet, but expected result should be all fine. 

<img width="767" alt="screen shot 2018-06-29 at 18 14 41" src="https://user-images.githubusercontent.com/2774845/42103456-732c79f8-7bc9-11e8-9255-9d3ad7bc88d4.png">

As observed; Subtask `f65b0eb0-7ba2-11e8-bd1e-6015c9f98f86` seems like not done yet above. But from the result folder, the subtask is done clearly.

<img width="767" alt="screen shot 2018-06-29 at 18 14 41" src="https://user-images.githubusercontent.com/2774845/42103621-e8e73750-7bc9-11e8-8998-65b384d9e93f.png">

**Comment by ederenn** [comment]
https://drive.google.com/open?id=1upxQwsj3cMPy6Mi1NrSMfId5HNbBPrYg
res for subtasks

logs:
[golem.log](https://github.com/golemfactory/golem/files/2150243/golem.log)

task has been started around 2018.06.29 15.48  duration: 1,5h
