### ISSUE TITLE
Cleanup test_docker_dummy_task temp test data

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/clay#2962]
When cleaning the buildbot agents i found a folder that i think belongs to these tests.
![screen shot 2018-07-04 at 12 29 22](https://user-images.githubusercontent.com/10008353/42272288-fc3d914a-7f85-11e8-99cb-3a89a86ebc0a.png)

Originally reported in #2961 but found to be a separate issue.

https://github.com/golemfactory/golem/blob/f82a8bc1275b0eb62cdec3d38c35eb2f05b74203/tests/golem/docker/test_docker_dummy_task.py

**Comment by badb** [comment]
Sorry, it's not ml, it's dummy: https://github.com/golemfactory/golem/blob/f82a8bc1275b0eb62cdec3d38c35eb2f05b74203/tests/golem/docker/test_docker_dummy_task.py

**Comment by maaktweluit** [comment]
Thanks for the update and the link, updated the title and the description
