### ISSUE TITLE
Run resource handshake only when it's needed

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#2972]
Right now resource handshake is required for every new task session. We may soften this requirements and expect resource handshake to occur only when it will be really necessary to exchange resources, ie. when the providers wants to compute task, there are still task available and provider fullfills criteria. It will optimize golem network and resource sending but may add additional difficulty layer for new marketplace algorithm.

**Comment by etam** [comment]
@jiivan is this already done by #2223 ?

**Comment by jiivan** [comment]
Yes
