### ISSUE TITLE
[Front-end] [Concent] the "First Concent deposit" dialog

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/clay#2984]
https://projects.invisionapp.com/share/PDISX9XKYHC#/screens/297460447

not sure what the rules for the initial amount are and whether that's already implemented in Golem core -> @jiivan @Krigpl @lukasz-glen ?

**Comment by jiivan** [comment]
It's defined here: https://github.com/golemfactory/golem-messages/blob/d5244a341ac5d0d308413012ee97c836ff5d42a0/golem_messages/helpers.py#L44-L51
Suggested amount is the "higher value than this task requires"
