### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [golemfactory/clay#2989]
Hi. I'm a graphic designer and an open source enthusiast. I would like to contribute to your awesome project by proposing logo design for it if you allow me. I'll be doing it as a gift for free to your awesome project.
Best regard.
Mirza zulfan

**Comment by badb** [comment]
Hi @mirzazulfan 
Thanks for reaching out. Please contact natalia.mroszczyk@golem.network about this.
