### ISSUE TITLE
Golem 0.16.2 release

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/clay#2994]
* Windows binaries
* Mac binaries / Homebrew
* tweet ?
* update golem website
* seeds update

**Comment by shadeofblue** [comment]
@ktomala @mdtanrikulu 
![image](https://user-images.githubusercontent.com/7963044/42552511-f3ababf0-84dc-11e8-9c3c-158067954fea.png)

**Comment by ktomala** [comment]
Only remaining thing is low-priority seeds update

**Comment by ktomala** [comment]
Seeds updated
