### ISSUE TITLE
Provide a work around for port forwarding

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/clay#2999]
Ports issue, routing. Solving port problems on backend, so users won't need to forward their ports

**Comment by ktomala** [comment]
We can somehow alleviate this problem with providing jump-hosts.

**Comment by badb** [comment]
This issue should be rather solved by Clay team, don't you think @mfranciszkiewicz?

**Comment by mfranciszkiewicz** [comment]
@badb agreed. I'm hijacking this issue.

**Comment by mfranciszkiewicz** [comment]
@shadeofblue Could you remove this issue from your backlog?
