### ISSUE TITLE
Can we replace reosurce network with IPFS (research)?

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#3]
Assumptions:
1. Resources that will be used in Golem Worldwide Renderer stands only for files and directories (with right hierarchy). 
2. Resources for different subtask of the same task will often be the same, so the network should be prepared to send same set of resources to all computing nodes.

**Comment by azawlocki** [comment]
We may also want to look at https://github.com/ipfs/go-libp2p for p2p protocols. 
Golang only though.

**Comment by azawlocki** [comment]
https://github.com/imapp-pl/golem/wiki/ipfs

**Comment by badb** [comment]
How effective is current implementation of IPFS? How long does it take to download resources that are initially placed on only one machine?
