### ISSUE TITLE
Research a way to use only GNT for transactions et al

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/clay#3000]
so that users don't need ETH to pay for gas

Payments in the app. Users need to have two different tokens to make computations and to use Concents (in near future). Ability to use only one token to make the app to work would be an easier entry barrier

**Comment by jamuszyn** [comment]
First: https://eips.ethereum.org/EIPS/eip-86
Latest: https://github.com/ethereum/EIPs/issues/859

**Comment by maaktweluit** [comment]
Other resources that can assist this research:
- https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1077.md
- https://safe.gnosis.io/ 
  - https://gnosis-safe.readthedocs.io/en/latest/services/relay.html
- https://medium.com/@austin_48503/ethereum-meta-transactions-90ccf0859e84
- https://github.com/status-im/contracts/blob/73-economic-abstraction/contracts/identity/IdentityGasRelay.sol
