### ISSUE TITLE
Improve command feedback in golemcli

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/clay#3015]
Currently, cli only reports "Completed in ... " with no actual feedback
* [x] Analyze output of all golemcli commands https://github.com/golemfactory/golem/issues/3968

Changes required:

1. 	[x] account withdraw [address] [Amount GNT] [gas fee WEI]
		is: ['Tx Hash']

	account withdraw  [address] [Amount GNT] [gas fee WEI]
		Sent `Amount` GNT to: [`address`]. With gas fee: `Amount` WEI
		Transaction hash (check on etherscan.io): ['Tx Hash']

---

2. 	[x] concent switch turn on/off
		is: Completed in 0.01 s

	concent switch turn on/off
		Concent switch turned on. Completed in 0.01 s

---

3.	[x] envs disable 'env_name' eg. BLENDER
		is: Completed in 0.01 s

	envs disable `env_name`
		env `env_name` disabled. Completed in 0.01 s

---

4.	[x] envs enable 'env_name' eg. BLENDER
		is: Completed in 0.01 s

	envs enable `env_name`
		env `env_name` enabled. Completed in 0.01 s

---

5.	[x] envs perf_mult_set `value`
		is: Completed in 0.01 s

	envs perf_mult_set `value`
		envs perf_mult_set to `value`. Completed in 0.01 s

---

6. 	[x] network block `node_id`
		is: Completed in 0.01 s

	network block `node_id`
		`node_id` blocked in 0.01 s

---

7. 	[x] network connect 
		The following arguments are required: ip, port_

---

8. 	[x] network connect `ip`
		The following arguments are required: port_

	network connect `ip`
		Required arguments are `ip` and `port`. Port is still missing

---

9. 	[ ] network connect `ip` `port`
		is: Completed in 0.01 s

	network connect `ip` `port`
		Connected with: Ip: `ip` Port: `port` in 0.01 s

---

10.	[x] settings set node_name `node name`
		is: Completed in 0.01 s

	settings set node_name `node name`
		Node name changed to: `node name` in 0.01 s. To confirm run `golemcli settings show`

---

11. [x] settings set accept_tasks `0/1`
		is: Completed in 0.01 s

	settings set accept_tasks `0/1`
		Your node will accept tasks. To confirm run `golemcli settings show`
		Your node will not accept tasks (acting as requestor only). To confirm run `golemcli settings show`

---

12. [ ] settings set getting_tasks_interval `value`
		is: Completed in 0.02 s

	settings set getting_tasks_interval `value`
		Getting tasks interval set to: `value` seconds. To confirm run `golemcli settings show`

---

13. [ ] settings set getting_peers_interval `value`
		is: Completed in 0.02 s

	settings set getting_peers_interval `value`
		Getting peers interval set to: `value`. To confirm run `golemcli settings show`

---

14. [ ] settings set task_session_timeout `value`
		is: Completed in 0.02 s

	settings set task_session_timeout `value`
		Task session timeout set to: `value`. To confirm run `golemcli settings show`

---

15. [ ] settings set p2p_session_timeout `value`
		is: Completed in 0.02 s

	settings set p2p_session_timeout `value`
		p2p session timeout set to: `value`. To confirm run `golemcli settings show`

---

16. [ ] settings set requesting_trust `value`
		is: Completed in 0.01 s

	settings set requesting_trust `value`
		Requesting trust set to: `value`. To confirm run `golemcli settings show`

---

17. [ ] settings set computing_trust `value`
		is: Completed in 0.01 s

	settings set computing_trust `value`
		Computing trust set to: `value` GNT. To confirm run `golemcli settings show`

---

18. [ ] settings set min_price `value`
		is: Completed in 0.01 s

	settings set min_price `value`
		Minimal price set to: `value` GNT. To confirm run `golemcli settings show`

---

19. [ ] settings set max_price `value`
		is: Completed in 0.01 s

	settings set max_price `value`
		Maximum price set to: `value`. To confirm run `golemcli settings show`

---

20. [ ] settings set use_ipv6 `0/1`
		is: Completed in 0.01 s

	settings set use_ipv6 `0/1`
		Using ipv6 set to: `True`. To confirm run `golemcli settings show`
		Using ipv6 set to: `False`. To confirm run `golemcli settings show`

---

21. [ ] settings set opt_peer_num `value`
		is: Completed in 0.01 s

	settings set opt_peer_num `value`
		Number of peers to keep set to `value`. To confirm run `golemcli settings show`

---

22. [ ] settings set send_pings `0/1`
		is: Completed in 0.01 s

	settings set send_pings `0/1`
		Send pings set to: True. To confirm run `golemcli settings show`
		Send pings set to: False. To confirm run `golemcli settings show`

---

23. [ ] settings set pings_interval `value`
		is: Completed in 0.01 s

	settings set pings_interval `value`
		Pings interval set to: `value`. To confirm run `golemcli settings show`

---

24. [ ] settings set max_memory_size `value`
		is: Completed in 0.01 s

	settings set max_memory_size `value`
		Maximal memory size set to: `value`. To confirm run `golemcli settings show`

---

25. [ ] settings set num_cores `value`
		is: Completed in 0.01 s

	settings set num_cores `value`
		Number of CPU cores to use set to: `value`. To confirm run `golemcli settings show`

---

26. [ ] settings set enable_talkback `0/1`
		is: Completed in 0.01 s

	settings set enable_talkbacks `0/1`
		Talkback enabled: `True/False`

---

27. [ ] tasks abort `task-id`
		is: Completed in 0.01 s

	tasks abort `task-id`
		Are you sure? Confirm aborting `task-id` task (y/n)
		Task `task-id` aborted. To confirm run `golemcli tasks show`

---

28. [ ] tasks create `file-path.json`
		is: `task-id`

	tasks create `file-path.json`
		Task with id `task-id` was created. To confirm run `golemcli task show`

---

29. [ ] tasks purge
		is: Completed in 0.01 s

	tasks purge
		Are you sure? Confirm purging all tasks (y/n)
		All tasks were purged. To confirm run `golemcli tasks show`

---

30. [ ] task restart `task-id`
		is: `restarted-task-id`

	task restart `task-id`
		Are you sure? Confirm restarting `task-id` (y/n)
		Task `task-id` was restarted as a new task with id `task-id`

---

31. [ ] tasks restart_subtasks id `task-id`
		is: Completed in 0.01 s

	tasks restart_subtasks id `task-id`
		Are you sure? Confirm restarting all task `task-id` subtasks (y/n)
		All subtasks of a `task-id` task were restarted

---

32. [ ] tasks restart_subtasks subtask_ids `subtask-id`
		is: Completed in 0.01 s 

	tasks restart_subtasks subtask_ids `subtask-id`
		Are you sure? Confirm restarting subtask with `subtask-id` id (y/n)
		Subtask with `subtask-id` was restarted

---

33. [ ] tasks restart_subtasks force `subtask-id`
		is: Completed in 0.01 s

	tasks restart_subtasks force `subtask-id`
		Are you sure? Confirm restarting subtask with `subtask-id` id (y/n)
		Subtask with `subtask-id` was restarted

**Comment by tworec** [comment]
Y-day we (@shadeofblue, @jamuszyn and me) agreed to move this initiative into a newly created work stream called `golem-client`: 

The recommendation is to finish what is started, but not start anything new. So pls report what is started and rest should be moved into a new issue in https://github.com/golemfactory/golem-client

@shadeofblue can you report?

**Comment by tworec** [comment]
closing in favour of golemfactory/golem-client#25

**Comment by mplebanski** [comment]
@tworec Then we could also close PR https://github.com/golemfactory/golem/pull/4023

**Comment by tworec** [comment]
yup!
