### ISSUE TITLE
Add proxy for "ping me" service (ports.golem.network)

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/clay#3018]
+ add the correct address(es) and implement a list of addresses to ping against

**Comment by shadeofblue** [comment]
@etam please communicate with @ktomala and establish the address that needs to be used here

**Comment by etam** [comment]
Seems like the work is already done: 436b5f377a25fbbe59ae8c79b8173ceeae0e423e

**Comment by ktomala** [comment]
I need to set up additional proxy outside of AWS.

**Comment by shadeofblue** [comment]
discussed with @ktomala and the conclusion is that the observed issues were not caused by the "ping me" service
