### ISSUE TITLE
unifying setting results

### ISSUE THREAD

**Issue by jamuszyn** [golemfactory/clay#3020]
right now cli prints "0" or "False" when disabled and "1" or "True" when enabled. It should be unified

**Comment by dybi** [comment]
@jamuszyn, is there any direction preferred? I.e. You would like to have `0` and `1` or `True` and `False` when showing `settings`, `envs`, etc.?

**Comment by dybi** [comment]
I have picked up :
(`0`,`1`) -> (`False`, `True`)
option

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/161383623
