### ISSUE TITLE
remove "version" column in network dht

### ISSUE THREAD

**Issue by jamuszyn** [golemfactory/clay#3022]

**Comment by shadeofblue** [comment]
@jamuszyn instead of removing the column - wouldn't it be better to fill-in that field? or is that not possible? (I haven't looked at the relevant code yet)?

**Comment by jamuszyn** [comment]
If I remember correctly there was just left as an empty with no reason behind it, so I thought about it as a "glitch" that needs to be removed

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/161383434

**Comment by dybi** [comment]
should be removed
