### ISSUE TITLE
fees in payments should not be presented in percentages 

### ISSUE THREAD

**Issue by jamuszyn** [golemfactory/clay#3023]

**Comment by shadeofblue** [comment]
@jamuszyn should be in ETH, right? ...

@mdtanrikulu it doesn't require changes in Elector prior to this change, right?

**Comment by jamuszyn** [comment]
Tx fee should be presented in ETH

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/161383383

**Comment by dybi** [comment]
% -> ETH
