### ISSUE TITLE
Remove compatibility check based on app version

### ISSUE THREAD

**Issue by Krigpl** [golemfactory/clay#3025]
Compatibility check should happen based on protocol version and Golem messages version. Checking app version is currently redundant (minor in app version is bumped iff protocol version has changed) and not needed in general.

-> `taskkeeper.check_version_compatibility`

**Comment by cameel** [comment]
@Krigpl The checks based on app version should be replaced with ones based on protocol version, right? Or are protocol version checks already present somewhere else and the app version checks should be removed completely? I think it's the former but everyone reading the description seems to have a different interpretation :) Could you clarify?
