### ISSUE TITLE
Simple Golem network statistic page shows wrong version of Golem client.

### ISSUE THREAD

**Issue by Flaci75** [golemfactory/clay#3065]
Hi Guys,

I am using Brass Golem v0.16.2 version, but Simple Golem network statistic page shows v0.16.1. Did anybody realized this issue and do you know how to fix it?

Thank you in advance

Laszlo

**Comment by tworec** [comment]
It was a bug in new monitor backend. I had fixed it and deployed to production. Users having this issue should restart their golem nodes to update their status @ stats.golem.network

**Comment by Flaci75** [comment]
Hi tworec,

Thank you for your answer!

**Comment by tworec** [comment]
Did it help for you?
