### ISSUE TITLE
Replace scripts embedded in TaskToCompute with individual parameters

### ISSUE THREAD

**Issue by PaweuB** [golemfactory/clay#3066]
TaskToCompute currently contains parameters for Blender in the form of a script (`script_src` field). Here's a fragment from a sample message:

``` python
for scene in bpy.data.scenes:

    scene.render.tile_x = 0
    scene.render.tile_y = 0
    scene.render.resolution_x = 1000
    scene.render.resolution_y = 600
    scene.render.resolution_percentage = 100
    scene.render.use_border = True
    scene.render.use_crop_to_border = True
    scene.render.border_max_x = 1.0
    scene.render.border_min_x = 0.0
    scene.render.border_min_y = 0.25
    scene.render.border_max_y = 0.375
    scene.render.use_compositing = bool(False)
```

There are two big problems with this approach:
- To render a task you have to run untrusted code supplied by the client
- There's no foolproof way of finding out what these parameters are without executing or parsing the script

We talked about it with @lukasz.glen and he agreed that it's something that should be changed in the protocol. Sending individual parameters and letting the client put them in the template would be safer and simpler. But we understand that a change to the protocol needs to be discussed first. We'd like to ask for some input and suggestions on the matter.

Once we agree on the right solution we offer to implement it and submit a pull request for approval.

**Comment by shadeofblue** [comment]
the idea from our end was to construct some dictionary for possible values in ComputeTaskDef containing:
* the required docker image
* hash and/or name/path/etc of the ComputeTaskDef's `src_code`
* required "schema" / attributes of ComputeTaskDef's `extra_data` which:
** may and will differ between different environments
** is abstract enough to include any arbitrary types of tasks (apart from Blender and LuxRender)
** must still support LuxRender as a reference "other platform"
** for blender - should provide a way to agree on the used `script_src` (via hash/name/path/etc? similarly to CTD.`src_code` -> maybe there should be a common mechanism to pass this information for both CTD itself and for `extra_data` components)

**Comment by kbeker** [comment]
@shadeofblue I would like to purpose solution to yours comment^:
We add some changes to `ComputeTaskDef` body:
- For LuxRender:
```python
['compute_task_def', {
    'task_id': 'd48d577e-9cd3-6b86-aac6-cf0d724f22d9',
    'subtask_id': 'a3cfa0e0-f5cd-8e59-6a18-6a1074967a36',
    'deadline': 1531937928,
    'script_template_hash': 'sha1:e7b4fd074eac12c0bf3d3207d30e64a193fc5459',  #  str
    'task_type' : 'LuxRender'  #  Enum
    'meta_parameters': {
        'scene_file_src': 'Film "fleximage"\n "bool write_exr" ["true"]\n "integer xresolution" [200] "integer yresolution" [100]\n "integer writeinterval" [15]\n "float cropwindow" [0, 1, 0, 1]',  #  str
        'xres': 100,  #  int
        'yres': 200,  #  int
        'halttime': 0,  #  int  
        'haltspp': 1,  #  int
        'writeinterval': 10,  #  int
        'crop': [0., 0.5, 0., 0.6],  #  List[float, float, float, float]
        'frames': [1],  #  List[int]
        'output_format': 'PNG',  #  Enum
    },
    'docker_images': [{
        'repository': 'golemfactory/blender',
        'image_id': None,
        'tag': '1.4'
    }], 
    'short_description': '',
    'working_directory': '',
    'performance': 0
}],
```
- For Blender:
```python
['compute_task_def', {
    'task_id': 'd48d577e-9cd3-6b86-aac6-cf0d724f22d9',
    'subtask_id': 'a3cfa0e0-f5cd-8e59-6a18-6a1074967a36',
    'deadline': 1531937928,
    'script_template_hash': 'sha1:e7b4fd074eac12c0bf3d3207d30e64a193fc5459',  #  str
    'task_type' : 'Blender'  #  Enum
    'meta_parameters': {
        'resolution': (800, 600),  #  Tuple(int, int)
        'borders_x': (3.01, 3.02),  #  Tuple(float, float)
        'borders_y': (4.01, 4.02),  #  Tuple(float, float)
        'use_compositing': True,  #  bool
        'samples': 5,  #  int
        'frames': [1],  #  List[int]
        'output_format': 'PNG',  #  Enum
    },
    'docker_images': [{
        'repository': 'golemfactory/blender',
        'image_id': None,
        'tag': '1.4'
    }], 
    'short_description': '',
    'working_directory': '',
    'performance': 0
}], 
```
Field `task_type` should be Enum and it should contain `LuxRender` and `Blender` to choose. In the case of development for a larger number of rendering programs it will be simple to enlarge Enum.

Field `meta_parameters` should be a dict which contains all parameters needed for specific rendering program. In Golem Message must be forced that if `task_type=Blender` there must be added dict which is designed for Blender.

Field `script_hash` should be sha1 script hash which should be generated by Provider which renders scene using this script for Requestor. Hash would be checked by Concent validators to be sure that script which was used to render scene is correct with parameters which are in `src_package` dict.

Besides, I would like to standardize dictionaries in `meta_parameters`. Something like `ComputeTaskDef`, which is also a dict. For example `BlenderScriptPackage` and `LuxRenderScriptPackage`, which also would be added to `meta_parameters` and also should be in Golem Messages repository. 

About `docker_image`:
I think that we should add this all changes gradually. First we might start with changes to `script_src` than we can add changes related with standardizing `ComputeTaskDef` and adding possible values for the rest of the dict.

Feel free to write what you think is wrong or should be changed in this solution :)

**Comment by shadeofblue** [comment]
@kbeker re: `script_package` there should be some version - or - identifier - or - identifier + version (maybe the identifier could be a sha1 of the raw, unfilled script?) associated with the underlying script so that it would be more obvious that both parties see the same template...

**Comment by badb** [comment]
Could you also show how DummyTask json would look like after  your changes?

We don't want to call it `render_type` - just `task_type`. Not only renderer will be supported in the future. 
Also - frames should be part of `script_package`

And `script_package` name is quite misleading, it's just something as job parameters / metapaprameters. 
Do you also need to to put the list of resources / files inside ComputeTaskDef?

**Comment by kbeker** [comment]
@badb 
> Do you also need to to put the list of resources / files inside ComputeTaskDef?

You mean scene file, or rendered images by Provider, or anything else?

**Comment by shadeofblue** [comment]
@kbeker plus - another thing - there's this `script_src` which is sent inside `ComputeTaskDef.extra_data` -> are you planning to also supersede that with some reference to a file held in a separate dictionary?

**Comment by kbeker** [comment]
@shadeofblue I did a quick check and I saw that `ComputeTaskDef['extra_data']['script_src'] is the same as  `ComputeTaskDef['script_src'], or am I wrong?

**Comment by kbeker** [comment]
These buttons for closing and commenting are definitely too close :P

**Comment by kbeker** [comment]
@shadeofblue After talk with @cameel he decided that the best way would be to put script which is in `src_code` to docker image or just to golem repository instead of keeping it in `ComputeTaskDef`. There is not any benefit for keeping it in `ComputeTaskDef`. It might be another change in Golem Messages.

I think that we should split all changes into few smaller and changing it step by step to be sure that everything works correctly after every update.

**Comment by kbeker** [comment]
https://github.com/golemfactory/golem/issues/3066#issuecomment-414643255 updated with new version of `ComputeTaskDef`

**Comment by cameel** [comment]
1. `src_code` does not contain any hard-coded parameters, just code. It looks like a part of the implementation to me. It will need to be different for different tasks (it needs to know which executable to run) and maybe even for different versions of the program. 

    So instead of it being a template passed inside `TaskToCompute` it would be more natural to just have it as a script in the Docker image. It could take all its parameters on the command line. Or it could be a Python module that provides a function that accepts these parameters.

    I don't think we need to pass a path to it. It could just be in some standard location in the image.

    But I think it would be better to do this in a separate issue and here focus on the `script_src` to keep changes small and easy to test and review.

2. > Field script_hash should be sha1 script hash

    @kbeker You left this in the decription but `script_hash` is no longer in the example.

3. I think that `scene_file_src` should moved to the package with task source files (textures, blender/luxrender project, etc.).

4. There should be more information about the schema. What types are expected for the fields? Which values are valid?

    E.g. what are the allowed values in `output_format`? Do they have to be uppercase? Is it `JPG`, `JPEG` or both for .jpeg files?

5. There's something wrong with nesting in your examples. Why is `}` at the same level as the last `]`?

6. Why is `docker_images` a list? Can there be more than one image?

7. Is `script_hash` in your proposal supposed to be generated from the script or from the template?

8. Maybe it would be a good idea to split `script_src` into two modules? One would be the static, located in the image or in Golem source, and would import a smaller script that only sets variable values. Or returns a dict that the static script uses to set variable values. Only the smaller script would be a template. Or it could be just a JSON dump of a dictionary.

    This way we would not really need to use hashes as versions. We could have a version as a simple integer. Combined with task type it would identify the script to use.

**Comment by kbeker** [comment]
>2. Field script_hash should be sha1 script hash
@kbeker You left this in the decription but script_hash is no longer in the example.

Actually this field exist. Other fields were wrong and now are fixed. 

>4. There should be more information about the schema. What types are expected for the fields? Which values are valid?

All fields which I have mentioned in example I wrote with types as they should be in real. I can also update them with type annotations if you want. 

>E.g. what are the allowed values in output_format? Do they have to be uppercase? Is it JPG, JPEG or both for .jpeg files?

I think that it should be also an Enum with possible values. In all places where I saw `output_format` is uppercased.

>5. There's something wrong with nesting in your examples. Why is } at the same level as the last ]?

Oh, I haven't notice it. Already fixed

**Comment by kbeker** [comment]
@badb 
>Could you also show how DummyTask json would look like after your changes?

I can't find place where in `DummyTask` `script_src` is used. I found that there is only place for `src_code`.

**Comment by kbeker** [comment]
To summarize:
>Is script_hash in your proposal supposed to be generated from the script or from the template?

`script_hash` should be a hash generated from script template to be sure that user used same template as we using for creating scripts. Also then it might have different name e.g. `script_template_hash`?

>I think that scene_file_src should moved to the package with task source files (textures, blender/luxrender project, etc.).

@cameel I fully agree, but maybe it should also be another issue? We should have small issues to review them quicker 

> There should be more information about the schema. What types are expected for the fields? Which values are valid?

[example](https://github.com/golemfactory/golem/issues/3066#issuecomment-414643255) updated. 

>Maybe it would be a good idea to split script_src into two modules? One would be the static, located in the image or in Golem source, and would import a smaller script that only sets variable values. Or returns a dict that the static script uses to set variable values. Only the smaller script would be a template. Or it could be just a JSON dump of a dictionary.
This way we would not really need to use hashes as versions. We could have a version as a simple integer. Combined with task type it would identify the script to use.

I think that it might be bigger change to split it. It might be another issue, but we can't change everything 
 at once :)

@shadeofblue : 
>Why is docker_images a list? Can there be more than one image?

**Comment by shadeofblue** [comment]
> @shadeofblue After talk with @cameel he decided that the best way would be to put script which is in `src_code` to docker image or just to golem repository instead of keeping it in `ComputeTaskDef`. There is not any benefit for keeping it in `ComputeTaskDef`. It might be another change in Golem Messages.
> 
> I think that we should split all changes into few smaller and changing it step by step to be sure that everything works correctly after every update. 

putting it in the docker image might not be the best thing - since we might want to:
* update the script itself without updating the docker images (they are pretty large)
* use the same docker image for two different task types (e.g. when the differences are cosmetic - e.g. GPU vs CPU rendering)

**Comment by shadeofblue** [comment]
> 1. `src_code` does not contain any hard-coded parameters, just code. It looks like a part of the implementation to me. It will need to be different for different tasks (it needs to know which executable to run) and maybe even for different versions of the program. 
> 
>     So instead of it being a template passed inside `TaskToCompute` it would be more natural to just have it as a script in the Docker image. It could take all its parameters on the command line. Or it could be a Python module that provides a function that accepts these parameters.
> 
>     I don't think we need to pass a path to it. It could just be in some standard location in the image.
> 
>     But I think it would be better to do this in a separate issue and here focus on the `script_src` to keep changes small and easy to test and review.

ok, let's move it to a separate issue and not discuss it now


Re: `script_hash` -> yeah, let's call it `script_template_hash` for the sake of clarity


> 3. I think that `scene_file_src` should moved to the package with task source files (textures, blender/luxrender project, etc.).

hmm.... I wouldn't do that as it doesn't solve the issue that we're trying to address - namely - execution of arbitrary code...

> 4. There should be more information about the schema. What types are expected for the fields? Which values are valid?

hmm... well - those are just parameters to fill in template - they can be arbitrary depending on the task - I unsure if we should try to establish strict typing and/or validate those values - at least not here and now with this change... should we?... 


>     E.g. what are the allowed values in `output_format`? Do they have to be uppercase? Is it `JPG`, `JPEG` or both for .jpeg files?

- so, same as above - I don't think this should be validated... 

> 6. Why is `docker_images` a list? Can there be more than one image?

unsure - I'd leave it as a list

**Comment by cameel** [comment]
> > 4. There should be more information about the schema. What types are expected for the fields? Which values are valid?
>
> > hmm... well - those are just parameters to fill in template - they can be arbitrary depending on the task - I unsure if we should try to establish strict typing and/or validate those values - at least not here and now with this change... should we?...

I think that all the parameters that go into the template should have clearly defined types and should be validated. If we allow anything in them and just embed them in the template verbatim without checking, someone could put a part of the script in them.

> > 3. I think that `scene_file_src` should moved to the package with task source files (textures, blender/luxrender project, etc.).
> 
> hmm.... I wouldn't do that as it doesn't solve the issue that we're trying to address - namely - execution of arbitrary code...

OK, it may be out of scope for this task. But what do you think about doing it in general, in a separate task? This really seems like it's a part of the source (analogous to the `.blend` file) rather than parameters that should be in TTC.

**Comment by shadeofblue** [comment]
re: #4
okay ... but this validation should then depend on the type of the task ... so maybe - in some dictionary that defines the neeed parameters for each type of task, there should be an additional dictionary that defines the type/validation criteria... still - I believe it would be an additional assignment - outside of the scope for this task here

re: #3 
@cameel sure, let's treat it as out of scope for this task

**Comment by cameel** [comment]
@shadeofblue 
> re: #3
> @cameel sure, let's treat it as out of scope for this task

I wanted to define an issue for it but when I dug deeper I discovered that this parameter should not even be in `TaskToCompute`.

It seems that @kbeker included it because it's a parameter in [`run_lux_renderer_task()`](https://github.com/golemfactory/golem/blob/0.17.1/apps/lux/resources/scripts/docker_luxtask.py#L75-L111) similarly to how `script_src` is a parameter in [`run_blender_task()`](https://github.com/golemfactory/golem/blob/0.17.1/apps/blender/resources/scripts/docker_blendertask.py#L39-L58). But if you look at how [`LuxTask` obtains this value](https://github.com/golemfactory/golem/blob/0.17.1/apps/lux/task/luxrendertask.py#L151-L154) you'll see that it reads it from a file whose path is in `main_scene_file`. So it's not something that the requestor puts in `TaskToCompute`. It's probably already a part of the .zip package with scene definition.

The `TaskToCompute` for LuxRender probably contains just the path - `main_scene_file`. Or maybe not even that - the code could be generating this path just before rendering by looking at the source package.

@kbeker Please get a real sample of a LuxRender task and make sure that all the fields you proposed are really there. `scene_file_src` should definitely not be there.

> re: #4
> okay ... but this validation should then depend on the type of the task ... so maybe - in some dictionary that defines the neeed parameters for each type of task, there should be an additional dictionary that defines the type/validation criteria... still - I believe it would be an additional assignment - outside of the scope for this task here

I have created an issue for this in golem-messages (since I think that's where the validations should go): https://github.com/golemfactory/golem-messages/issues/260

> > 6. Why is docker_images a list? Can there be more than one image?
> 
> unsure - I'd leave it as a list

Found it: https://github.com/golemfactory/golem/blob/0.17.1/golem/docker/task_thread.py#L87-L94

Looks like the idea is that it should list all the images that could potentially be used to render this task and Golem uses the first one that's available in its local Docker registry.

> putting it in the docker image might not be the best thing - since we might want to:
> 
> - update the script itself without updating the docker images (they are pretty large)
> - use the same docker image for two different task types (e.g. when the differences are cosmetic - e.g. GPU vs CPU rendering)

I have created a separate issue for this and also posted a response there: https://github.com/golemfactory/golem/issues/3309#issuecomment-421157419
