### ISSUE TITLE
Add "awaiting" and "confirmed" additional arguments

### ISSUE THREAD

**Issue by jamuszyn** [golemfactory/clay#3105]
for "payments" and "incomes" to allow the user filtering the list

EDIT:
for "deposit_payments" as well

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/161383329

**Comment by dybi** [comment]
`golemcli payments confirmed`
`golemcli payments awaiting`

`golemcli incomes confirmed`
`golemcli incomes awaiting`

**Comment by dybi** [comment]
`golemcli deposit_payments confirmed`
`golemcli deposit_payments awaiting`
