### ISSUE TITLE
Add `current` additional argument in `tasks` cli call

### ISSUE THREAD

**Issue by jamuszyn** [golemfactory/clay#3106]
Print current task id, task state (progress; is it computing or being computed), task cost, task settings (resolution; frames; subtask; timeouts)

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/161383230

**Comment by dybi** [comment]
new cmd: `golemcli tasks current` or `golemcli tasks show current `

**Comment by dybi** [comment]
just filter out to show tasks which states are in : 
    sending = "Sending"
    waiting = "Waiting"
    starting = "Starting"
    computing = "Computing"

**Comment by dybi** [comment]
just filter out to show tasks which states are in : 
    sending = "Sending"
    waiting = "Waiting"
    starting = "Starting"
    computing = "Computing"
