### ISSUE TITLE
timeout time in interface is wrongly shown, if timeout when app is closed

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#3109]
if on Golem closed during computations and restarted after task timeout in interface for task time is shown timeout + time passed from timeout to app restart.

<img width="490" alt="screen shot 2018-07-30 at 20 22 50" src="https://user-images.githubusercontent.com/32061891/43471811-3953af1c-94ec-11e8-9ad2-b43ad2b96367.png">

on this example:

timeout set for 5 min, Golem restarted 6 minutes later 

encountered in: Golem version: 0.16.1+dev308.g8b5a757

**Comment by ederenn** [comment]
still appears in 0.19.0

**Comment by ZmijaWA** [comment]
@shadeofblue  we need to check this with a new release.

**Comment by shadeofblue** [comment]
I don't think this is an issue anymore
@ederenn  @ZmijaWA please confirm and/or close it, thank you :)

**Comment by ederenn** [comment]
seems to be fixed, checked on build https://buildbot.golem.network/buildbot/#/builders/2/builds/4728
