### ISSUE TITLE
no result image for multiframe when computations are in progress

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#3110]
<img width="477" alt="screen shot 2018-07-30 at 19 26 21" src="https://user-images.githubusercontent.com/32061891/43472030-ba730dd6-94ec-11e8-924f-f3af84ddd873.png">

if task has multiple frames and is multisubtask, previev is shown when whole frame is finished. Computations are in progress, some of subtasks are finished, but results are not shown in preview window

**Comment by mdtanrikulu** [comment]
@ederenn How many subtask you assigned for the given task? The issue is there should be at least one frame needs to be completed to have preview for the multi-frame tasks.

**Comment by ederenn** [comment]
2 frames. written on print screen :)

**Comment by ederenn** [comment]
as Muhammed says, probably to little subtasks finished to have one frame displayed
