### ISSUE TITLE
progress bar not showing progress

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#3175]
#### Encountered on:
Mac OS binaries 0.17.0

computations in progress, progress not shown in interface (checked in developers tools for electron - no error in there)

progress was shown up to 3/4 of the task, when verification of the last subtask has started progress on progress bar has disappeared

<img width="481" alt="screen shot 2018-08-13 at 13 32 38" src="https://user-images.githubusercontent.com/32061891/44049143-9395b7d0-9f33-11e8-9eb5-6f7207212af9.png">

<img width="459" alt="screen shot 2018-08-13 at 13 33 01" src="https://user-images.githubusercontent.com/32061891/44049156-9a8e461a-9f33-11e8-9ec8-7a4eecb6a33e.png">

**Comment by shadeofblue** [comment]
@ederenn has this reappeared? or can we close this issue?

**Comment by ederenn** [comment]
in 19.0 the progress bar is working
