### ISSUE TITLE
golem is not sending back all results from core

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#3176]
#### Encountered on:
Windows, Mac OS, binaries 0.17.0

in logs verification for all task is finished, in res all results are created but in interface task is shown as verifying last subtask, task is ending in timeout, even though task is visible in preview

<img width="461" alt="screen shot 2018-08-13 at 19 59 31" src="https://user-images.githubusercontent.com/32061891/44049617-e1e2e902-9f34-11e8-944c-99f096eb0a0c.png">
<img width="459" alt="screen shot 2018-08-13 at 13 33 01" src="https://user-images.githubusercontent.com/32061891/44049623-e4c146d2-9f34-11e8-8bad-354cfd1dce19.png">

**Comment by ederenn** [comment]
Windows logs on debug, two subtasks in interface in verification, task ended with timeout
https://drive.google.com/open?id=1QjqT379ETrHbA9MxVHIobPXUBWpyipef

```
golemcli tasks subtasks 49669afa-9ef6-11e8-b7a6-9d5cb6e59b28

Failed to import scrypt. This is not a fatal error but does
mean that you cannot create or decrypt privkey jsons that use
scrypt

node           id                                    ETA      status     completion
-------------  ------------------------------------  -------  ---------  ------------
mainichi       61ea4c9c-9ef6-11e8-8537-9d5cb6e59b28  0:00:00  Finished   100.00 %
WhiteKnuckles  64d2c67a-9ef6-11e8-8861-9d5cb6e59b28  0:00:00  Finished   100.00 %
Server6942     65633cfa-9ef6-11e8-975c-9d5cb6e59b28  0:00:00  Verifying  0.00 %
crunch-rhino   65bbb348-9ef6-11e8-ac94-9d5cb6e59b28  0:00:00  Verifying  0.00 %
```

```
golemcli tasks dump 49669afa-9ef6-11e8-b7a6-9d5cb6e59b28

Failed to import scrypt. This is not a fatal error but does
mean that you cannot create or decrypt privkey jsons that use
scrypt

{
    "duration": 1617.013679265976,
    "preview": "C:\\Users\\ederenn\\AppData\\Local\\golem\\golem\\default\\mainnet\\res\\49669afa-9ef6-11e8-b7a6-9d5cb6e59b28\\tmp\\current_task_preview.PNG",
    "id": "49669afa-9ef6-11e8-b7a6-9d5cb6e59b28",
    "name": "scene-Helicopter-27-1",
    "type": "Blender",
    "subtasks": 4,
    "progress": 0.5,
    "options": {
        "frame_count": 1,
        "output_path": "C:\\Users\\ederenn\\Documents",
        "format": "PNG",
        "resolution": [
            400,
            400
        ],
        "frames": "1",
        "compositing": false
    },
    "time_started": 1534164126.6132562,
    "time_remaining": 1617.013679265976,
    "last_updated": 1534165027.568274,
    "status": "Timeout",
    "estimated_cost": "133333333333333336",
    "estimated_fee": "1120000000000000",
    "timeout": "0:15:00",
    "subtask_timeout": "0:10:00",
    "bid": 0.2,
    "resources": [
        "C:\\Users\\ederenn\\Desktop\\do scenariuszy\\scene-Helicopter-27-cycles.blend"
    ],
    "cost": null,
    "fee": null
}
Completed in 0.01 s
```

**Comment by magdasta** [comment]
On Mac the subtasks were verified according to the log, but their statuses remained unchanged. 

On Windows the situation is different, crops for verification of subtask `65633cfa-9ef6-11e8-975c-9d5cb6e59b28` were rendered and labeled `TRUE`, but there was no `Finished verification of subtask...` message in logs and the status did not change to verified.
For subtask `65bbb348-9ef6-11e8-ac94-9d5cb6e59b28` the crops weren't rendered at all. 

It might be OS dependent and they can be two (or even three) completely separate issues.

**Comment by ederenn** [comment]
https://drive.google.com/open?id=1shDVvnHzY0QKFvGz0nsBgyrO2vft0KDn

task res

**Comment by ederenn** [comment]
to be checked if still exists in 18.2

**Comment by ederenn** [comment]
not seen in current (18.3) version
