### ISSUE TITLE
After some time of running, golem has problems with downloading and verifying tasks.

### ISSUE THREAD

**Issue by etam** [golemfactory/clay#3232]
There are no clear indications in logs about what's going on wrong, but the overall picture is that subtasks are ending in `Failure` or `Verifying` state.

~~What's worse: provider is awaiting for payments, that requestor is not sending:
https://www.reddit.com/r/GolemProject/comments/9af27y/node_waikail_almost_never_pays_for_tasks_whats_up/~~
That seems to be a separate issue

**Comment by etam** [comment]
Maybe that's related? https://github.com/mfranciszkiewicz/golem-hyperdrive/issues/12

**Comment by jiivan** [comment]
Fixed by: https://github.com/mfranciszkiewicz/golem-hyperdrive/pull/30

**Comment by etam** [comment]
we'll see...
