### ISSUE TITLE
whitelisting is not working

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#3236]
Currently whitelisting in Golem is not working
tested on mainnet, builds for 0.17.1

#### Steps to reproduce:
- open or create folder `deny.txt` in `mainnet` folder for Golem
- type there `ALL_EXCEPT_ALLOWED <NODE_ID>` and save file
- restart Golem
- create a task
- Golem should start computations on whitelisted node but instead of it computes on any other nodes

file saved:
[deny.txt](https://github.com/golemfactory/golem/files/2324965/deny.txt)

logs from whitelisting - after Golem restart

[whitelisting.log](https://github.com/golemfactory/golem/files/2324969/whitelisting.log)

**Comment by etam** [comment]
You should type ALL_EXCEPT_ALLOWED in a separate line (no matter if it's first, last or wherever). It changes the whole file from being a blacklist to whitelist.

**Comment by tworec** [comment]
Unassigning myself as I'm not in Brass team...
@ederenn, please use @etam hint. It should fix your issue.
There are unit tests for this feature, which are passing
https://github.com/golemfactory/golem/blob/fd37007cc4ef7eaebf6b0c6f5beced93a262bb0c/tests/golem/task/test_acl.py#L51-L61

Furthermore I've tested it manually on all platforms just before 0.16.0 and worked as a charm!
