### ISSUE TITLE
Add verification for task timeout

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#324]
~~Computer should start to compute task only if current time + subtask_ttl < task_timeout~~
Please make sure that task computer sets minimum from task deadline and subtask deadline as it's timeout instead.

**Comment by Wolf480pl** [comment]
You mean `task_timeout` argument to `__compute_task()`, which is calculated from subtask deadline, or do you mean task deadline from task header?

**Comment by maaktweluit** [comment]
@Wolf480pl is this solved fully through #1350 ?

**Comment by Wolf480pl** [comment]
@maaktweluit AFAIK yes.

**Comment by maaktweluit** [comment]
Checked and can indeed be closed
