### ISSUE TITLE
Add an RPC call to verify VT/VT-x status

### ISSUE THREAD

**Issue by ktomala** [golemfactory/clay#3268]
On Windows and MacOS when VT/VT-x is not enabled there will be no indication by Golem if the Virtualization is enabled. Golem will proceed with creating e.g. docker-machine on Windows which will fail in such scenario, without giving any obvious reason except for "Problem with starting Docker". 

We can add checking for VT/VT-x flag if it's enabled in CPU flags. This can be done in various operating systems in different ways, however should be simple enough to add. The logic when virtualization flag is not found in CPU should prevent Golem from starting whatsoever and perhaps give meaningful message in Golem-Electron regarding requirement for enabling VT.

Here are some examples of how to check for existence of this flag:
Linux: https://stackoverflow.com/questions/11116704/check-if-vt-x-is-activated-without-having-to-reboot-in-linux

Mac: https://apple.stackexchange.com/questions/224870/how-to-check-vt-x-status-on-macbook-pro

Windows (paragraph with systeminfo): https://www.shaileshjha.com/how-to-find-out-if-intel-vt-x-or-amd-v-virtualization-technology-is-supported-in-windows-10-windows-8-windows-vista-or-windows-7-machine/

Also some additional resources:
https://github.com/pydata/numexpr/blob/master/numexpr/cpuinfo.py
https://github.com/workhorsy/py-cpuinfo
https://github.com/Blosc/python-blosc2/blob/master/cpuinfo.py
https://www.cyberciti.biz/faq/linux-xen-vmware-kvm-intel-vt-amd-v-support/
https://stackpointer.io/unix/linux-check-running-virtual-machine/553/
http://www.nongnu.org/dmidecode/

**Comment by maaktweluit** [comment]
Please note clay team is working on docker for windows, this will switch the hypervisor from VirtualBox to HyperV

Not sure if it applies to this issue, just FYI :)

**Comment by ktomala** [comment]
@maaktweluit Yes it also applies to Hyper-V
