### ISSUE TITLE
"PNG" output in GUI (when the scene has JPEG output set in the .blend file) doesn't set output format to PNG

### ISSUE THREAD

**Issue by magdasta** [golemfactory/clay#3284]
Encountered in 0.17.0.
To recreate:
- create blender task with scene which have JPEG output defined in it
- choose PNG output in Golem
- the results sent by providers will be JPEG files

I don't know if it occurs in CLI as well.

**Comment by shadeofblue** [comment]
[ possibly resolved -> there's an integration test that checks this scenario and I believe it passes correctly ]

**Comment by pawelkisielewicz** [comment]
I reproduced this with last release versions
- Golem 0.18.2
- Golem Electron 0.18.0
Everything is OK, problems does not exist any more
