### ISSUE TITLE
Update base Docker image to Debian Stretch

### ISSUE THREAD

**Issue by cameel** [golemfactory/clay#3310]
### Overview
 [golemfactory/blender](https://hub.docker.com/r/golemfactory/blender/) image is based on Debian 8 (Jessie), which unlike Debian 9 (Stretch) only provides Python 2.

This is not a problem for Golem itself since it does not run its code in the image but the situation is different in Concent. Currently Concent deals with it by installing Python 3 from testing repository. It would be better to just switch to a newer version of Debian.

@lukasz-glen suggested quite a while ago that we could fix this ourselves and submit a pull request. So I'm defining a task for it. Please post in comments if there are any objections to this change or if something could be done differently.

### Required changes
- In [golemfactory/base Dockerfile](https://github.com/golemfactory/golem/blob/develop/apps/core/resources/images/Dockerfile) change `FROM debian:jessie` to `FROM debian:stretch`
- Test the new container with Golem and Concent
- Ask Golem team to build and upload the new version to Docker Hub

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/160510327

**Comment by Krigpl** [comment]
base image uses ubuntu now and this is no longer relevant.
