### ISSUE TITLE
Space optimizations in Docker images

### ISSUE THREAD

**Issue by cameel** [golemfactory/clay#3311]
#3310 is a good opportunity to optimize Golem's Docker images. They could be made a little smaller by being more careful about layers and removing more stuff that's not used.

There are currently four `Dockerfile`s in Golem's repository
- [golemfactory/base Dockerfile](https://github.com/golemfactory/golem/blob/develop/apps/core/resources/images/Dockerfile)
- [golemfactory/blender Dockerfile](https://github.com/golemfactory/golem/blob/develop/apps/blender/resources/images/Dockerfile)
- [golemfactory/lux Dockerfile](https://github.com/golemfactory/golem/blob/develop/apps/lux/resources/images/Dockerfile)
- [golemfactory/image_metrics Dockerfile](https://github.com/golemfactory/golem/blob/develop/apps/rendering/resources/images/Dockerfile)

1) `golemfactory/base` and `golemfactory/image_metrics` install and then remove packages with two separate `RUN` commands:

    ``` dockerfile
    RUN set -x \
        && apt-get update \
        && apt-get install -y --no-install-recommends ca-certificates wget curl \
        && apt-get install -y python

    (...)

    RUN apt-get clean \
        && apt-get -y autoremove \
        && rm -rf /var/lib/apt/lists/*
    ```

    This unfortunately does not have the intended effect. Each command creates a new Docker layer and these layers are immutable. So removing a file added in a previous layer just hides it. It's inaccessible on the last layer but it's still physically in the image.

    This can be fixed by either
    - Merging these `RUN` commands into one or
    - Doing it all in a shell script executed with a single `RUN` or
    - Grouping `RUN` instructions into stages in a multi-stgage build and then squashing some of the stages into single layers (See [Best practices for writing Dockerfiles > Use multi-stage builds](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#use-multi-stage-builds)).

2) Some images install both `wget` and `curl`. Both do the same thing (download stuff) so we need only one. I'd leave only `curl`.

3) `ca-certificates`, `curl` and `bzip2` are installed only in order to download and unpack packages. They could be removed from the image after that.

4) `golemfactory/image_metrics` does `RUN pip3 install -r /golem/work/requirements.txt` which probably caches the packages it downloads in user's home directory. These packages are quite substantial (OpenCV, scikit, scipy) so removing those cached files could save a lot of space.

5) Don't install Python 2 in `golemfactory/base`.

    This one needs some testing to make sure that Blender can use Python 3 for scripting. If not, Python 2 has to stay.

    If it could be removed, Concent's `verifier` image would become smaller because it installs Python 3 anyway.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/160512071

**Comment by Krigpl** [comment]
All of those have been incorporated.
