### ISSUE TITLE
Add a way to specify the exact scene file to use through RPC / CLI

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/clay#3327]
Currently Golem uses some mechanism to select which possible `.blend` file to use when given a directory containing more than one `.blend` file - we need to provide a way to specify exactly which file should be the main scene file

**Comment by etam** [comment]
Currently Golem picks one with the shortest path (number of chars in filename and all directories it's in).

With my change it's possible to add `main_scene_file` to task definition dictionary. It's not an error if it's also in resources.

Example:
```python
task_def = {
    ...,
    'resources': [
        "/path/to/scene.blend",
        "/path/to/model.blend",
    ],
    'main_scene_file': "/path/to/scene.blend",
}
```
