### ISSUE TITLE
Change testing window layout

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#333]
OK button is misleading. We should remove the possibility to close testing window while test isn't finished or add posibility to stop it. 
We should also remove possibility to close the window by clicking "x" in right corner.

**Comment by banasiakadam60** [comment]
BTW. Maybe I will also disable 'ok' buttons on tests in 'Provider' tab?

**Comment by badb** [comment]
Good idea!

**Comment by banasiakadam60** [comment]
Can it be closed?
