### ISSUE TITLE
Support status. task_id supported=<SupportStatus err ({<UnsupportReason.CONCENT_REQUIRED: 'concent_required'>: True})>

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#3350]
#### Encountered on: 

GOLEM Version: 0.17.1+dev304.g9a8101c
 Protocol Version: 666-testnet
golem_messages Version: 2.14.0

Requestor set on virtual Windows, provider set on host Linux

 computations for task never started
both nodes connected on private

from provider logs
```
2018-09-25 16:27:51 DEBUG    golem.task.taskserver               Support status. task_id=d5a6c526-c0ce-11e8-b93e-7995bf36d741 supported=<SupportStatus err ({<UnsupportReason.CONCENT_REQUIRED: 'concent_required'>: True})>
```

requestor logs
[golem (2).log](https://github.com/golemfactory/golem/files/2420690/golem.2.log)

provider logs:
[golem (3).log](https://github.com/golemfactory/golem/files/2420694/golem.3.log)

task id:
d5a6c526-c0ce-11e8-b93e-7995bf36d741

**Comment by mdtanrikulu** [comment]
Removing `concent_enabled: false` parameter from task definition on golem-electron side didn't help.
