### ISSUE TITLE
Enable migrations for tasks persistence

### ISSUE THREAD

**Issue by jiivan** [golemfactory/clay#3405]
Currently tasks persistence is achieved by pickling *TaskDefinition* instances. When attribute is added to *TaskDefinition* it requires migrating it from old pickles (see: #3300).

One way is to use database models for task persistence. *TaskDefinition* should be a model in our database. We have database migration mechanism in place.

Other solution is suggested in pickle documentation. Use `golem.__version__` in `__getstate__` and write migrations in `__setstate__`.

**Comment by etam** [comment]
related: #2768
