### ISSUE TITLE
No secret for `golemcli` when flag --mainnet is missing

### ISSUE THREAD

**Issue by etam** [golemfactory/clay#3414]
If `golemcli` has wrong parameters and fails to connect to `golemapp`, it just shows an error "WAMP-CRA signature is invalid".

This is very confusing. It should also print hints to check if `-d` and `--mainnet` flags are correct.

See also: #3171 #3348

**Comment by jiivan** [comment]
https://github.com/golemfactory/golem/issues/3477#issuecomment-431384800
