### ISSUE TITLE
GUI: peer table sorting results in incorrect node data

### ISSUE THREAD

**Issue by mfranciszkiewicz** [golemfactory/clay#342]
Table data should be updated in order-independent fashion (e.g. using a sorting proxy)

**Comment by badb** [comment]
How are they incorrect? Can you add more details?

**Comment by mfranciszkiewicz** [comment]
Peer table without sorting:
![pre](https://cloud.githubusercontent.com/assets/3238836/15221827/51fa55aa-186d-11e6-9a90-8cfa290861ae.png)

With sorting, after few updates:
![post](https://cloud.githubusercontent.com/assets/3238836/15221843/6bb95fd6-186d-11e6-81f7-3bb42c67a878.png)

**Comment by badb** [comment]
Ugh, right that's terrible. Let's switch off sorting for this table (maybe we'll try to add this feature back in the future).

**Comment by badb** [comment]
#351
