### ISSUE TITLE
Add reporting of CPU / GPU provider capability to monitor

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/clay#3512]
+ add required information to the status data passed to the monitor
+ add required information to monitor's status display

**Comment by jiivan** [comment]
1. add input: is nvgpu supported field here https://github.com/golemfactory/golem-monitor-replicator/blob/6f0dddd0036129354712af72ffe8797b07d45bf0/src/stats_update.rs#L53
2. add output: https://github.com/golemfactory/golem-monitor-replicator/blob/6f0dddd0036129354712af72ffe8797b07d45bf0/src/stats_update.rs#L302
3. extend login mapping https://github.com/golemfactory/golem-monitor-replicator/blob/6f0dddd0036129354712af72ffe8797b07d45bf0/src/stats_update.rs#L386
4. https://github.com/golemfactory/golem-monitor-replicator/blob/6f0dddd0036129354712af72ffe8797b07d45bf0/src/stats_update.rs#L420
