### ISSUE TITLE
API Documentation for Concent Implementation

### ISSUE THREAD

**Issue by mdtanrikulu** [golemfactory/clay#3514]
We need to create an API documentation for concent related api calls.

**Comment by jiivan** [comment]
1. `pay.deposit_payments` Format is the same as `pay.payments`
1. `pay.deposit_balance` returns a mapping
   1. `value`
   1. `status` *locked|unlocked|unlocking*
   1. `timelock`
   1. https://github.com/golemfactory/golem/blob/7c921e37772cca41b7682ab2820529a2661622d3/golem/interface/client/account.py#L137-L158
1. `pay.deposit.unlock` a.k.a. Turn concent off. It doesn't forbid turning concent on in task definition.
1. `pay.deposit.relock` a.k.a. Turn concent on. It's cheaper cancel previous unlocking than transferring deposit again.
1. `golem.concent.terms` returns boolean; Are terms accepted?
1. `golem.concent.terms.show` returns string (html)
1. `golem.concent.terms.accept` Marks terms as accepted

**Comment by shadeofblue** [comment]
@jiivan don't we have a "pay.deposit.create" to create the deposit? or it just happens on the first task added with Concent Enabled?

**Comment by jiivan** [comment]
> @jiivan don't we have a "pay.deposit.create" to create the deposit? or it just happens on the first task added with Concent Enabled?

It's handled automagically during task enqueuing.

https://github.com/golemfactory/golem/blob/195b157202ed7b08e7e6f2ab2e47bb82a4840432/golem/task/rpc.py#L335-L339

https://github.com/golemfactory/golem/blob/195b157202ed7b08e7e6f2ab2e47bb82a4840432/golem/task/rpc.py#L186-L212

**Comment by mdtanrikulu** [comment]
@jiivan Is there any other rpc that I can get status of Concent for the RPC's below ? 
>pay.deposit.unlock a.k.a. Turn concent off. It doesn't forbid turning concent on in task definition.
>pay.deposit.relock a.k.a. Turn concent on. It's cheaper cancel previous unlocking than transferring deposit again.

**Comment by jiivan** [comment]
If `pay.deposit_balance['status'] == 'locked'` is *true*, it can be interpreted as *Concent active*
