### ISSUE TITLE
[Ubuntu 18.10] segmentation fault

### ISSUE THREAD

**Issue by Slavenin** [golemfactory/clay#3517]
Hi! I install golem on ubuntu 18.10. When i run `golem --mainnet` in console:
`[1]    28530 segmentation fault (core dumped)  golem --mainnet`
In `.local` no `golem` directory. When i can find core dump?

**Comment by mplebanski** [comment]
Hello,

core dumps are created according to `/proc/sys/kernel/core_pattern`. Please investigate the content of this file to determine core dump location. 

My wild guess is that it's related to 18.10 version.

**Comment by Slavenin** [comment]
in this file `|/usr/share/apport/apport %p %s %c %d %P`
but in `/usr/share/apport/apport` empty

**Comment by Slavenin** [comment]
i find in syslog 
```
Nov  6 16:07:57 max-max kernel: [ 5626.004227] golem[19315]: segfault at e6e0c0 ip 0000000000e6e0c0 sp 00007fff16c7d9f8 error 15 in golem[200000+1603000]
Nov  6 16:07:57 max-max kernel: [ 5626.004232] Code: fc 02 b8 47 77 00 30 58 fc 02 08 48 77 00 10 59 fc 02 30 48 77 00 90 59 fc 02 58 48 77 00 c0 59 fc 02 a0 48 77 00 10 5a fc 02 <c0> 48 77 00 40 5a fc 02 e0 48 77 00 80 5a fc 02 c0 49 77 00 b0 5a 

```

**Comment by shadeofblue** [comment]
We should figure out whether that's something we can fix or whether we should just clearly state we don't (yet) support Ubuntu 18.10

**Comment by Slavenin** [comment]
I found solution!!! Similar problem was with slack! 

> For Ubuntu 18.10, the current Slack desktop 3.3.3 does not launch due to outdated libnode.so library. It outputs Segmentation fault (core dumped) when trying to launch from terminal.

And golem app too!
Need to:
```bash
sudo updatedb && locate libnode
```
output something like this:
```
/home/max/golem/electron/libnode.so
/home/max/programms/Postman/Postman-1536669705795-old/libnode.so
/home/max/programms/Postman/Postman-1540968697103/libnode.so
/home/max/programms/Postman/Postman-1541574931281/libnode.so
/home/max/programms/Postman/Postman-1544443729506/libnode.so
/home/max/programms/Postman/Postman-1545039575766/libnode.so
/home/max/programms/Postman/app/libnode.so
/usr/lib/slack/libnode.so
/usr/share/code/libnode.so
```
I use lib from vscode:
```
sudo mv /home/max/golem/electron/libnode.so /home/max/golem/electron/libnode.so.old
sudo ln -s /usr/share/code/libnode.so /home/max/golem/electron/libnode.so
```
and golem is run (only with sudo, without - docker can not work)! 
But now problem with hyperg:
```
hyperg --db /home/max/.local/share/golem/default/mainnet/hyperg --logfile /home/max/.local/share/golem/default/mainnet/logs/hyperg.log
2018-12-28 10:06:39.343 [HyperG] [INFO] Opening HyperG log file: /home/max/.local/share/golem/default/mainnet/logs/hyperg.log
2018-12-28 10:06:39.347 [HyperG] [INFO] [master] Spawning worker
2018-12-28 10:06:39.352 [HyperG] [ERROR] hyperg-worker not found
```
Log file not created and i can not find problem.
Where i can found hyperg config?

**Comment by Slavenin** [comment]
I am do it! Simply create symlink on this files
```bash
sudo ln -s $HOME/hyperg/hyperg-worker /usr/local/bin/hyperg-worker
sudo ln -s $HOME/hyperg/hyperg-client /usr/local/bin/hyperg-client

```

And golem client work on ubuntu 18.10!!!😆 💪
