### ISSUE TITLE
Problem with ports (OS X 10.14)

### ISSUE THREAD

**Issue by Incrediblez7** [golemfactory/clay#3524]
<img width="461" alt="2018-11-07 8 02 17 054" src="https://user-images.githubusercontent.com/34339028/48101859-72c5b780-e263-11e8-8f6d-cd238808d647.png">
I opened 40102, 40103, 3282 manually, and my router supports UPnP, but the app is not working at all.

**Comment by Silko5** [comment]
I have the same problem. App did work until few versions back, but suddenly stopped working. I didn't bother at the time cuz I didn't have enough disk space, but now I bought new disk, updated golem to the last version and still the same problem. When I insert my password golem says "Golem is heaving trouble connecting...". My OS is Windows 10.

**Comment by Incrediblez7** [comment]
<img width="468" alt="2018-11-07 17 11 28 785" src="https://user-images.githubusercontent.com/34339028/48121538-2c4a7a00-e2b0-11e8-8c57-efe9bef1d648.png">
I've restarted my computer, and it's connected. Why is it still idling?

**Comment by Silko5** [comment]
For me restart does not help.

**Comment by cryptobench** [comment]
It's going to stay idle until you receive a job. Nothing u can do than wait.
