### ISSUE TITLE
Move TaskHeader to golem-messages

### ISSUE THREAD

**Issue by jiivan** [golemfactory/clay#3557]
Also remove `FixedTaskHeader` and leave only `TaskHeader`. Since both can only be modified by requestor there is no need for both entities.

related: #80 #2407

**Comment by mfranciszkiewicz** [comment]
@jiivan @shadeofblue Task headers are supposed to be (mainly) immutable and we have to resolve this issue somehow.

What I can think of is:
- add a creation timestamp property to the _immutable_ part of the header (there **has** to be one)
- make `task_id` a derivative of Hash(`FixedTaskHeader`) and exclude it from the fixed part
