### ISSUE TITLE
pay.deposit.relock/unlock:  'NoneType' object has no attribute 'functions'

### ISSUE THREAD

**Issue by mdtanrikulu** [golemfactory/clay#3601]
- pay.deposit.relock
- pay.deposit.unlock

Calling both RPC's above gives the same error; 
```
ERROR    [twisted                            ] AttributeError: 'NoneType' object has no attribute 'functions': Traceback (most recent call last):
  File "/Users/mdt/projects/golem/venv/lib/python3.6/site-packages/autobahn/twisted/websocket.py", line 162, in _onMessage
    self.onMessage(payload, isBinary)
  File "/Users/mdt/projects/golem/venv/lib/python3.6/site-packages/autobahn/wamp/websocket.py", line 95, in onMessage
    self._session.onMessage(msg)
  File "/Users/mdt/projects/golem/venv/lib/python3.6/site-packages/autobahn/wamp/protocol.py", line 895, in onMessage
    on_reply = txaio.as_future(endpoint.fn, *invoke_args, **invoke_kwargs)
  File "/Users/mdt/projects/golem/venv/lib/python3.6/site-packages/txaio/tx.py", line 417, in as_future
    return maybeDeferred(fun, *args, **kwargs)
--- <exception caught here> ---
  File "/Users/mdt/projects/golem/venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/Users/mdt/projects/golem/golem/ethereum/transactionsystem.py", line 625, in concent_unlock
    if self.concent_balance() == 0:
  File "/Users/mdt/projects/golem/golem/ethereum/transactionsystem.py", line 55, in curry
    return f(self, *args, **kwargs)
  File "/Users/mdt/projects/golem/golem/ethereum/transactionsystem.py", line 543, in concent_balance
    account_address=account_address,
  File "/Users/mdt/projects/golem/venv/lib/python3.6/site-packages/golem_sci/implementation.py", line 755, in get_deposit_value
    return self._call(self._gntdeposit.functions.balanceOf(account_address))
builtins.AttributeError: 'NoneType' object has no attribute 'functions'
```

**Comment by shadeofblue** [comment]
@mdtanrikulu are you sure that you aren't trying to run a mainnet node?

**Comment by mdtanrikulu** [comment]
@shadeofblue nope, it was mainnet. but I think it shouldn't raise any error at all, even if it's not available on mainnet now.

**Comment by jiivan** [comment]
We should probably just deploy a contract on **mainnet** that just rejects all operations. When we're ready we could deploy full contracts and change ids in _golem_sci_
CC: @Krigpl

**Comment by shadeofblue** [comment]
@jiivan wouldn't it be less of a hassle to just check if there is any contract defined? it seems very artificial to me to deploy such "no-op" contract just because we cannot implement a simple if/else in the code...

**Comment by shadeofblue** [comment]
iow, I believe there should be a check if the concent is available and if not, just don't try to unlock/relock the deposit...

**Comment by jiivan** [comment]
> @jiivan wouldn't it be less of a hassle to just check if there is any contract defined? it seems very artificial to me to deploy such "no-op" contract just because we cannot implement a simple if/else in the code...

I prefer no-op contract because it won't require a different logic between testnet and mainnet.

**Comment by shadeofblue** [comment]
sure but the "different logic" is really just a single if/else ... I really think that's it's an overkill to deploy no-op contracts here... maybe let's implement a simple check now and once @Krigpl is back, we can let him decide whether he indeed also thinks having no-op contracts is better than just checking this in Golem itself.

**Comment by shadeofblue** [comment]
@Krigpl your opinion needed...

**Comment by Krigpl** [comment]
Concent methods should not be called when Concent is not enabled and there should be code in place to guarantee that. Wasting real money on a no-op contract just because is a no go.
Even after Concent contract is deployed on mainnet there will be an option to run Golem on testnet with Concent disabled and in this case we shouldn't be calling any Concent methods as well.

**Comment by jiivan** [comment]
@mdtanrikulu as suggested by @Krigpl in his [review](https://github.com/golemfactory/golem/pull/3750#pullrequestreview-192140948) concent procedures shouldn't be called when concent is disabled. I've updated golem core to disable concent when contracts are unavailable.

**Comment by shadeofblue** [comment]
@jiivan can this issue be closed then?

**Comment by shadeofblue** [comment]
(apparently, this has been resolved already)
