### ISSUE TITLE
transaction system's `concent_deposit` function doesn't check if the existing deposit is locked

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/clay#3612]
When checking for the existing deposit, we're not ensuring the deposit is in fact locked.

1) When doing my deposit, check if it's locked (in `concent_deposit`)
2) When as provider checking requestor deposit also check if it's locked.

**Comment by etam** [comment]
> 2. When as provider checking requestor deposit also check if it's locked.

It's already done: #3191
