### ISSUE TITLE
Add RPC to report current gas price and the gas limit in SCI

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/clay#3624]
The result should be included:

{'current_gas_price': xxxx, 'gas_price_limit': xxxx }

**Comment by shadeofblue** [comment]
@mdtanrikulu could you put any details re: the currently used RPC endpoint that you're using for gas price estimation into this issue here?

**Comment by mdtanrikulu** [comment]
Currently used RPC for estimated tx fee is; `comp.tasks.estimated.cost`. 
And required parameters are; 
```js
{
    type                    // type of task
    options: {
         price              // your bid
         num_subtasks       // given subtask number
         subtask_time       // given subtask timeout
    }
}
```

And the RPC result is; 
```js
{
    GNT,   // Total GNT price
    ETH    // ETH TX fee to lock
}
```
