### ISSUE TITLE
RPC create_task should give feedback about insufficient funds for concent deposit 

### ISSUE THREAD

**Issue by mplebanski** [golemfactory/clay#3643]
Branch: develop

Additional prerequisites: concent enabled

Right now, if one creates a task and has no GNT to supply the deposit the following error will be logged:

```
ERROR    [golem.task.rpc                     ] Cannot create task {'bid': 1.0, 'subtask_timeout': '00:10:00',
... 
Not enough GNT available. Required: 0.166667, available: 0.000000
```

but RPC call will return valid `task_id` and no `error_message`. This is not consistent with e.g. when one provides an invalid task` type` in task dict.

**Comment by pawelkisielewicz** [comment]
I have investigated this task and the reason of problem is creating task asynchronicity. In function `create_task` (`rpc.py`) there is some validations and there is really `None` and error message returned in case of failed validation. 

But in next step task is created asynchronicity, so if we want to return consistent output we have to **wait** until task is created, check if there were errors and then return valid `task id`. This way all errors from function `enqueue_new_task` will be handled, but it will make the whole flow longer. 

My idea is to **wait** for results of enqueue_new_task and I will start implementation this way. If there is not acceptable for you please let me know.

**Comment by mplebanski** [comment]
Looks good to me. What about you @shadeofblue?

**Comment by mdtanrikulu** [comment]
@pawelkisielewicz It was working like that afaik, but the concept had to change because of UX related issues. When RPC waits until task creation it was taking a lot on GUI to redirect user to the task list screen or give a feedback about the related error. So instead of waiting all process we made this change. 
If we wait whole flow, this issue will pop-up again. Is there any alternative or an idea to shortened the waiting time tolerably?

**Comment by mplebanski** [comment]
@mdtanrikulu How long is this wait time?

**Comment by mdtanrikulu** [comment]
@mplebanski Only thing I remember, it was depend on the task complexity.

**Comment by pawelkisielewicz** [comment]
I spoke with @jiivan on rocket and general suggestion is to move checking of available GNT and ETH before call  asynchronic function - as "expected" fails. I try to extract as much as I can of fast validations to cover as much cases as possible. I'm not sure if it will be 100% perfect, but it seems to be the best approach.

**Comment by PaweuB** [comment]
Pivota:
https://www.pivotaltracker.com/story/show/163016112

**Comment by shadeofblue** [comment]
yeah, @pawelkisielewicz @jiivan the actual deposit can be made asynchronously but the check whether there are funds for the deposit can indeed be made immediately

**Comment by PaweuB** [comment]
This Issue probably would also close an Issue https://github.com/golemfactory/golem/issues/3521
