### ISSUE TITLE
Prerequisites Setup Wizard is Bugged - C++ Redistributable

### ISSUE THREAD

**Issue by Hiturunk** [golemfactory/clay#3691]
Problem: When installation 18.2 with a current version of the C++ Redistributable Prerequisite the installer crashes with the error that it failed to install the Redistributable (Which is unnecessary since the user already has it)

Workaround: Open Installation executable, browse to C:\Users\~USER~\AppData\Roaming\Golem Factory GmbH\Golem 0.18.2\install, copy installation package folder, run golem.msi, complete installation as normal.

Solution: Take a look around the pre-req wizard at what is making it not see current installations of C++ Redistributable.

**Comment by maaktweluit** [comment]
Hi @Hiturunk 

Thank you for the report!
The registry is checked for the version here: https://github.com/golemfactory/golem/blob/develop/Installer/Installer_Win/Golem.aip#L685

Could you check your registry and share the value of `HKLM\Software\Wow6432Node\Microsoft\VisualStudio\14.0\VC\Runtimes\x64\Version`?

What version of C++ redistributable do you have installed? we have seen before it does not always work with newer versions, but installing 2 side by side solved that.

**Comment by Hiturunk** [comment]
Hi, @maaktweluit Please find attached a screenshot of the registry keys in the parent directory, VisualStudio - I have versions 7.1, 8, 10-13 (x86&x64), & 14.10.25008.00 (x86, no x64) installed. This IS a 64 bit system, but notably, it has a skylake dual-core in it. 

I believe the erronous lines are lines 680-683 of https://github.com/golemfactory/golem/blob/develop/Installer/Installer_Win/Golem.aip

The x86 redistributable works fine instead of the REQUIRED x64 distributable in those lines.
Also: I would like to note that Windows 10 (x64) is not included in this command flag:

 WinNTVersions="Windows 9x/ME/NT/2000/XP/Vista/Windows 7/Windows 8 x86/Windows 8.1 x86/Windows 10 x86" WinNT64Versions="Windows XP SP2 x64, Windows Server 2003 SP2 x64, Windows Vista x64, Windows Server 2008 x64, Windows 7 x64, Windows Server 2008 R2 x64, Windows 8 x64, Windows Server 2012 x64, Windows 8.1 x64"

I think if you fixed this flag it would properly install x64 visual studio, however, I also think you just allow the PreReq to accept x86 anyway (To support more systems), by changing the language previous to the command flag on line 681:

<ROW PrereqKey="MicrosoftVisualC" DisplayName="Microsoft Visual C++ 2015 Redistributable (x64) - 14.0.23026" VersionMin="14.0.23026.0" SetupFileUrl="C:\BuildResources\vc_redist.x64.exe" Location="0" ExactSize="0" WinNTVersions="Windows 9x/ME/NT/2000/XP/Vista/Windows 7/Windows 8 x86/Windows 8.1 x86/Windows 10 x86" WinNT64Versions="Windows XP SP2 x64, Windows Server 2003 SP2 x64, Windows Vista x64, Windows Server 2008 x64, Windows 7 x64, Windows Server 2008 R2 x64, Windows 8 x64, Windows Server 2012 x64, Windows 8.1 x64" Operator="1" ComLine="/install /passive /norestart" BasicUiComLine="/install /passive /norestart" NoUiComLine="/install /passive /norestart" Options="zym" TargetName="vc_redist.x64.exe"/>

We need some kind of 'OR' logic here. This was a 'Just get it done" solution. I'm not an expert on AIP, but the XML file seems explicit here.

**Comment by maaktweluit** [comment]
Thank you for the info!

It seems the screenshot is missing from your last comment,  could you send it again? you can also email it to maaktweluit@golem.network

`WinNTVersions` are all the versions that are **not** supported, we only support windows server 2016 x64 and windows 10 x64.

> The x86 redistributable works fine instead of the REQUIRED x64 distributable in those lines.

I think this could be the key, it only checks and allows x64 vcredis 2015.
Did you also tests requesting and providing based on the x32 vcredis install?

Could you install the vcredis.exe ( out of the extracted installer ) manually and send me the errors it gives? when golem installs it all these screens and warnings are hidden

**Comment by Hiturunk** [comment]
https://ibb.co/nCxfc4M

Will Reply with install of VCredis.exe results asap.

**Comment by Hiturunk** [comment]
[logfile_vc_install.txt](https://github.com/golemfactory/golem/files/2703022/logfile_vc_install.txt)

**Comment by Hiturunk** [comment]
The GUI shows: Setup Failed: "One or more issues caused..."

0x90080666 - Another version of this product is already installed.

**Comment by maaktweluit** [comment]
Thanks for the data, this helps a lot!

The logs show you already have vc 2017 x64 installed:
```
[26A8:1C14][2018-12-21T08:02:03]i108: Detected compatible package: vcRuntimeMinimum_x64, provider: Microsoft.VS.VC_RuntimeMinimumVSU_amd64,v14, installed: {03EBF679-E886-38AD-8E70-28658449F7F9}, version: 14.14.26429, chained: {0D3E9E15-DE7A-300B-96F1-B4AF12B96488}
```

This is why the installation of vc 2015 x64 fails

Double checked some things and it looks like:
- 32bit and 64bit should work side by side ([source](https://www.sevenforums.com/software/341372-ok-install-microsoft-visual-c-x86-64-bit-machine.html#post2855110))
- vc 2015 and vc 2017 should share the same registry values ([source](https://docs.microsoft.com/en-us/cpp/ide/redistributing-visual-cpp-files?view=vs-2017))

Could you try to re-install a fresh [downloaded](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) version of vc 2017 x64?
Then please check if the registry is updated accordingly.
