### ISSUE TITLE
Fill `WantToComputeTask.task_header` with the task header

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/clay#3696]
* implement changes from https://github.com/golemfactory/golem-messages/issues/302 in Golem Core
* update the provider code to fill the `task_header` field of `WantToComputeTask`
* update the requestor code to check if the signature of the included `task_header` is valid and that it indeed belongs to the requestor node

**Comment by shadeofblue** [comment]
* update the provider code to fill the `task_header` field of `WantToComputeTask`
* update the requestor code to check if the signature of the included `task_header` is valid and that it indeed belongs to the requestor node

**Comment by PaweuB** [comment]
Pivotal: 
https://www.pivotaltracker.com/story/show/163016843
