### ISSUE TITLE
Icon alignment problem

### ISSUE THREAD

**Issue by mfranciszkiewicz** [golemfactory/clay#372]
Kubuntu 16.04

![image](https://cloud.githubusercontent.com/assets/3238836/15403154/ed54c79e-1df7-11e6-8faa-4f946a171931.png)

**Comment by banasiakadam60** [comment]
Additionally on Ubuntu 16.04 I can move "Account" icon. There is no such problem with other icons
![zrzut ekranu z 2016-05-24 17-23-21](https://cloud.githubusercontent.com/assets/11528913/15509715/bbf36cd8-21d4-11e6-93fb-5a529ebe5b5d.png)
![zrzut ekranu z 2016-05-24 17-23-37](https://cloud.githubusercontent.com/assets/11528913/15509714/bbeb4454-21d4-11e6-8e7a-2cb2e10dad07.png)

**Comment by badb** [comment]
Does this problem is in develop version or in package version? It was supposed to be fixed here: https://github.com/imapp-pl/golem/issues/363? Did you run 'setup.py develop' or 'setupy.py install' after pulling new commits?

**Comment by mfranciszkiewicz** [comment]
Ubuntu 16.04, Qt 4.8.7

![screenshot from 2016-06-01 11-17-02](https://cloud.githubusercontent.com/assets/3238836/15704358/a0dd4bd2-27ea-11e6-9a39-7f0731157fc7.png)

**Comment by badb** [comment]
@mfranciszkiewicz I cannot recreat this error, on clear kubunt 16.04 installation everything looks normal, same after installing libqt4-dev (4.8.7).  Can you add more information about system / configuration / package version?

**Comment by chfast** [comment]
Ubuntu 16.04 / Qt 4.8.7.
![golem app menu issue](https://cloud.githubusercontent.com/assets/573380/15851272/620c7f16-2c9c-11e6-9707-022caf2b1a63.png)

**Comment by mfranciszkiewicz** [comment]
Branch: `develop`
System packages: https://gist.github.com/mfranciszkiewicz/5da63e3ecb47a49e7644a38fc6c60ef5
System libraries: https://gist.github.com/mfranciszkiewicz/615aea6f120027d406d50e678d446e63
