### ISSUE TITLE
Concent deposit Unlock doesn't work

### ISSUE THREAD

**Issue by mdtanrikulu** [golemfactory/clay#3722]
After Turning Concent Off and unlocking the deposit, the status of Concent balance is still `locked` and the timestamp is `0`.

**Comment by jiivan** [comment]
Deposit is unlocked when `pay.deposit.unlock` is called. It's a blockchain operation which burns gas.

**Comment by mdtanrikulu** [comment]
Everything is fine, finally I got it;
```elixir
concentBalance: {
    value: '400000000000000000000',
    status: 'unlocking',
    timelock: '1547848245'
  }
```

No idea why I couldn't have it on first try and actually waited more than half an hour. 

Closing it, as there is no issue right now.
