### ISSUE TITLE
Rename golem/tools/ci.py

### ISSUE THREAD

**Issue by jiivan** [golemfactory/clay#3729]
This module was used only in travis and appveyor

**Comment by etam** [comment]
Instead of appveyor and travis we have now buildbot. `ci.py` should be adjusted, rather than removed.

**Comment by maaktweluit** [comment]
Etam is correct, `ci_skip` is still used on buildbots to skip tests on mac and windows.

Only the old function ( and ENV ) names where kept, they can be renamed to clean it up
