### ISSUE TITLE
Verify and change restart option

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#376]
Check if restart option for task and subtask is working as expected. 
For task: 
- task should change it's state to waiting
- progress should be remove
- preview should be remove
- ~~subtasks list should be cleaned~~
- subtasks should change state to restarted

For subtask: 
- ~~subtask state should be set to failure~~
- subtask state should be set to "restarted"
- ~~"restarted" subtasks should be verified and paid for if it has passed the verification but shouldn't be treated as a proper result (preview, etc).~~ -> moved to different issue
- ~~subtask with similar parameters should be added to a list of failed tasks~~ (?)
- if task was finished then it should change it's state to computing

**Comment by badb** [comment]
* [x] Check again behaviour of subtask after it was restarted. Is the list above up to date?
* [ ] Prepare note that described workflow on R+D wiki
* [x] Check if behaviour on new GUI & from CLI is the same
* [x] Ask @lukasz-glen about compatibility of current behaviour with his research

**Comment by Wolf480pl** [comment]
For a subtask restart:

Looks like the subtask is being set to restarted unless it was already a failure, in which case it stays a failure.
The task is always set to computing.

Didn't check exactly, but it looks like a restarted or failed subtask will not be sent to a provider again, instead a new subtask will be created. Is that the case?

**Comment by Wolf480pl** [comment]
From the UI side, it looks like you can always restart a subtask, no matter what state it's in. (In QT you also see the old subtask in state "Restarted" even though there's new subtask for this part of image, you can't restart the old subtask agian, but you can restart the new one. From CLI you can restart the old "Restarted" subtask, it may cause a bug, I'm not sure).

The preview goes red, but doesn't refresh (so you can see it only if you switch the preview to another task and back), and then when another provider starts the subtask it gets green (and does refresh).

**Comment by Wolf480pl** [comment]
Apparently, the provider who got the subtask before restart can still subimt the result and get paid for it. This is compatible with @lukasz-glen's analysis. The computation agreement between the provider and requestor is not affected.

This might be a problem from UX point of view. The user should be aware that he's paying for each subtask restart.
