### ISSUE TITLE
output files with the same task name are overwritten

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#3785]
#### Encountered on:
Linux, Windows, golem-0.18.3+dev693.g6b46c7a
Steps to reproduce:
- Create a task, wait for task to finish, 
- create second task using the same input file, name task exactly the same as first one, wait for task to finish.
-check if there is new output file in output folder

**Comment by shadeofblue** [comment]
@ederenn how did it work before?

**Comment by shadeofblue** [comment]
iow, please provide missing details:

**Actual result**
_(What is the result of this issue)_

**Expected result**
_(What is the expected result)_

**Comment by ederenn** [comment]
there was added suffix to the output file name to avoid overwriting files

actual result:
two tasks are finished, for example each task has two frames. In output folder there are only two frames created.

expected result:
in output folder there should be created 4 frames in total, with numeral suffixes added to task name to differentiate files

**Comment by etam** [comment]
I don't remember such functionality. And I can't find anything supporting this in the history of our source code.
Anyway, how we should resolve this? Adding incrementing numbers to output filenames might be tricky and error prone with multithreading. Any ideas?

**Comment by etam** [comment]
Or maybe it should be like this: When creating a new task, with the same name and output directory as another task, user should be warned that output files will get overwritten. It sounds like a lot of work with gui and stuff, but I tried to think about what user would expect.

**Comment by shadeofblue** [comment]
@ederenn please confirm that this feature used to work in version b0.18.X

**Comment by shadeofblue** [comment]
@etam we could try to do that on the back end when starting the task - may indeed by trick-ish if there is nothing created when the task is started and only when it's finished...
