### ISSUE TITLE
Blacklisted node is also blacklisted for other tasks

### ISSUE THREAD

**Issue by cryptobench** [golemfactory/clay#3867]
Currently testing the boundaries using my webapp for Golem and if a user uploads a heavy task which some providers might not be able to finish within the requested task timeout time, then they are blacklisted for a period. However if I request another task then they just time out due to every single node being blacklisted. Is it possible to incooporate some kind of blacklisting just for THIS specific task, and 'drop' the blacklist for new tasks because they arent identical to the one before?

**Comment by cryptobench** [comment]
My service is currently operating on the testnet and there's of course not many providers, so it's easier to have some issues regarding tasks timing out, but one user could maliciously do some kind of DoS if he knows he can make my specific node blacklist every other single provider on the network. That wouldn't be great when i'm ready to move over to the mainnet. Thus rendering my service unuseable

**Comment by tworec** [comment]
We have two types of blacklisting in Golem:

1. task specific. It blocks further work offers from provider nodes which failed to calculate previous subtasks for this task. Other tasks are not affected.

1. global, which have also two incarnations
   1. soft. upon resource handshake error it will block peer for 2h. 
   1. hard. persisted in `deny.txt` file as described [here](https://blog.golemproject.net/pre-brass-golem-0-6-0-released-a6501ed8f178). It can be added by manually editing the file or via GUI and CLI `golemcli network block <node_id>` 

What you are describing (when nodes fail to finish within timeout) should be type 1, so does not affect further tasks.

**Comment by shadeofblue** [comment]
@mplebanski @tworec @cryptobench is this indeed an issue or - as @tworec described it and also according to my knowledge - just a temporary per-task ban? can we close the issue?

**Comment by tworec** [comment]
I've nothing to add here.
