### ISSUE TITLE
Add an integration/regression test for the output overwritting issue

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/clay#3869]
* add an integration test (node integration test) that reproduces https://github.com/golemfactory/golem/issues/3785

Suggested test:
* the test should run one task normally, verifying if the output is created in an expected location (this should already be the case in the `regular_task_run` scenario)
* then, the test should create another task with exactly the same properties and this time, verify if the output has been created in an expected way (so as not to overwrite the original output)

To achieve this, a new playbook needs to be added to `playbooks/golem` and a test needs to be added to `tests/test_golem.py`.

Possibly it will require adding another task definition to `tasks` as the original issue only manifested itself (afaik) in multi-frame tasks (if unable to reproduce, please consult with @ederenn ).

**Comment by rwrzesien** [comment]
@shadeofblue https://github.com/golemfactory/golem/issues/3785 is not fixed yet, so what should be actual result of this issue? Should it be:
1. Test that checks if files are overwritten, and is passing now (and will stop passing when https://github.com/golemfactory/golem/issues/3785 is done), or
2. Test that checks if files are not overwritten, and is failing now?

I think it should be option 1 but I want to be sure.

**Comment by rwrzesien** [comment]
@shadeofblue @ederenn Do you maybe have a sample of multi-frame task? Or maybe there is one in the repository?

**Comment by shadeofblue** [comment]
@rwrzesien for the question above: 2 -> failing now

**Comment by ederenn** [comment]
@rwrzesien as for mulitframe file - you can use static blednd file like helicopter but in tasks settings set needed frame range

**Comment by rwrzesien** [comment]
@ederenn How exactly this can be achieved? I couldn't find any example in repository. Settings only `"frame_count": 2,` in task dict `options` doesn't produce 2 files.

**Comment by ederenn** [comment]
1-5 for example

task dump one of the tasks:
```
ederenn@GOLEM2008-VM-UBNT18:~$ golemcli --mainnet tasks dump 8d5b81b0-306b-11e9-93b2-ac201342cfc3
{
    "duration": 5661.23854637146,
    "preview": "/home/ederenn/.local/share/golem/default/mainnet/ComputerRes/8d5b81b0-306b-11e9-93b2-ac201342cfc3/tmp/current_task_preview17.PNG",
    "id": "8d5b81b0-306b-11e9-93b2-ac201342cfc3",
    "name": "scene-Helicopter-10",
    "type": "Blender",
    "subtasks_count": 10,
    "progress": 0.7,
    "options": {
        "frame_count": 30,
        "output_path": "/home/ederenn/Documents",
        "format": "PNG",
        "resolution": [
            400,
            400
        ],
        "frames": "1-30",
        "compositing": false
    },
    "time_started": 1550157410.333355,
    "time_remaining": 2426.245091302055,
    "last_updated": 1550161011.1924596,
    "status": "Timeout",
    "estimated_cost": "500000000000000000",
    "estimated_fee": "2800000000000000",
    "compute_on": "cpu",
    "timeout": "1:00:00",
    "subtask_timeout": "0:15:00",
    "bid": 0.2,
    "resources": [
        "/home/ederenn/Desktop/scene-Helicopter-27-cycles.blend"
    ],
    "concent_enabled": false,
    "cost": null,
    "fee": null
}
Completed in 0.00 s
```

**Comment by shadeofblue** [comment]
[wlochaty 3 anim.zip](https://github.com/golemfactory/golem/files/2866146/wlochaty.3.anim.zip)

@rwrzesien actually, please add an actually animated scene to the test packages (attached) and make the test use this scene (using the `--task-package` kwarg in the test)

**Comment by shadeofblue** [comment]
@zakaprov isn't this already addressed?

**Comment by kmazurek** [comment]
@shadeofblue It is, [here](https://github.com/golemfactory/golem/blob/52e535611c84d37a7595a26b1b4423d5ac7cbf95/scripts/node_integration_tests/playbooks/golem/task_output/playbook.py) is the relevant test.
