### ISSUE TITLE
restarted task showing up as timed out

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/clay#3871]

**Comment by ederenn** [comment]
Steps to reproduce:
- run Golem
- start a task with at least two frames and wait for task to finish 
- restart whole Golemapp
- when Golem is launched again, in task finished previously try to restart one finished frame from second preview window
- whole task will end up in timeout immediately

![screenshot from 2019-02-12 15-47-04](https://user-images.githubusercontent.com/32061891/52649067-de18c880-2ee7-11e9-960b-430de749cca8.png)

![screenshot from 2019-02-12 15-47-34](https://user-images.githubusercontent.com/32061891/52649077-e53fd680-2ee7-11e9-9b67-6da3d52fa071.png)


if Golem is running without restarts of an application it is possible to restart a frame of a finished task without timeout

- run Golem
- start a task with at least two frames and wait for task to finish 
- go to the second preview window and restart one finished frame 
- task will be restarted

![screenshot from 2019-02-12 16-38-31](https://user-images.githubusercontent.com/32061891/52649190-233cfa80-2ee8-11e9-85c2-34fd47b006e0.png)

even though task has been restarted successfully no new nodes had started computations for restarted subtasks

logs on debug

Windows:
https://drive.google.com/open?id=1gu1e-pQvXhfAaZDW1jLBy033I_WHevol

Linux:
https://drive.google.com/open?id=1ykYtPC3qHlr2MEA4pm6O8-e1aTTrw6rA
