### ISSUE TITLE
Transaction history update

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/clay#3880]
* Add support for more payment statuses in the history for both incoming and outgoing payments: 
** (blockchain transaction) rejected, payment overdue (awaiting beyond expected payment time), confirming (on blockchain) @Krigpl (is that possible already - or would it require changes to ETS?)

```
Incoming payments:
1.0 awaiting
2.0 payment overdue (try to use Concent), reasons may include:
Requestor made a transaction that didn’t cover this payment (can be detected earlier)
Requestor didn’t make a transaction at all (actual overdue payment)
4.0 confirmed

Outgoing payments:
1.0 awaiting (/queued)
2.0 payment overdue, reasons may include:
insufficient ETH/GNT
Golem bug
3.0 confirming (on blockchain)
4.0 confirmed
5.2137 operational costs ETH

```

* Outgoing: Add information about the transaction fee (only on confirmed transactions)

* (possibly?) replace the subtask id in the history with a node name

**Comment by Krigpl** [comment]
That should be pretty much possible at this point with little or no changes needed in the transaction system.
