### ISSUE TITLE
Identify unit tests that leave temporary data behind and add clean up

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/clay#3890]
The problem is that right now, each test run leaves cruft after execution and each run adds to the cruft deposited in the system, causing the buildbot instances to get clogged after just a few days.

We need to identify those tests that leave garbage behind and add adequate cleanup methods to remove the cruft after each run of the unit test suite.

## Garbage list:
- docker
  - docker images
  - docker volumes
- /tmp
  - To Be Checked...
- ~/.local/share/golem
  - To Be Checked...

**Comment by rwrzesien** [comment]
@shadeofblue Could you give me a hint what exactly is left over? Or in which directories those things are?

**Comment by Krigpl** [comment]
Isn't this the issue basically? https://github.com/golemfactory/golem/blob/develop/golem/testutils.py#L43-L47

**Comment by rwrzesien** [comment]
@Krigpl This is just one of many. My question is not valid anymore because I was able to identify most of the cases where something is left out, and I am currently working on fixing it,

**Comment by shadeofblue** [comment]
@maaktweluit is this still a thing? @Krigpl went into some discussion with @rwrzesien in the pull request and it was never merged ... but I have a feeling that either you've done some reconfiguration to buildbot or you're actively maintaing the buildbot so that it's not an issue anymore ...  ?

**Comment by maaktweluit** [comment]
@shadeofblue yes this is still a thing. 
there are some cron-jobs for cleanup but it still fills up every now and then

This issue can be used to list the files that are left by the tests and create new issues per case, for each case we can see if its the production code or the test code that should clean up ( as per discussion in the closed PR above )

**Comment by kmazurek** [comment]
A possible solution here is to use the [`tmpdir` fixture](https://docs.pytest.org/en/latest/tmpdir.html) in all tests which require creating directories.
