### ISSUE TITLE
Change task restart RPCs to return results/errors

### ISSUE THREAD

**Issue by kmazurek** [golemfactory/clay#3895]
The RPC calls `comp.task.subtasks.frame.restart` and `comp.task.restart_subtasks` do not return any results. As a consequence, uncaught exceptions will not be visible to the client. To enable reporting errors, these calls should return tuples of optional values - a return value and an error. This way they will be compatible with other task RPC calls (e.g. `comp.task.restart`) and can be properly handled by the `safe_run` decorator.

**Comment by ttanay** [comment]
Hi @zakaprov 
I'd like to work on this issue.

**Comment by kmazurek** [comment]
Hi @ttanay, as part of a larger pull request (see: #4247) I've already included the changes necessary to fix this. If you're still interested in contributing, please take a look at other issues in the Golem repo marked with `good first issue`. Thanks!

**Comment by ttanay** [comment]
Sure @zakaprov :)
I'll take a look at other issues.
