### ISSUE TITLE
New subtask status "Cancelled"

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/clay#3908]
We need a new status for a subtask - `cancelled` - which - for the purpose of task completion and re-assignment should be treated exactly as `restarted` or `failed` with the exception that the node that cancelled the subtask should never be banned.

This status should be assigned to a subtask when the provider node sends an "Offer Cancelled" message within the allowed cancellation window.

**Comment by etam** [comment]
beware of #3173
