### ISSUE TITLE
Add --selfish-tasks-provider flag

### ISSUE THREAD

**Issue by jiivan** [golemfactory/clay#3925]
Add `--selfish-tasks-provider` command line flag. When set, golem will only propagate it's own tasks - won't send others tasks via p2p. For power users.

https://github.com/golemfactory/golem/blob/c8fcef1ed252ab381302efc5f225ece908f91a1b/golem/network/p2p/peersession.py#L340-L342

**Comment by shadeofblue** [comment]
descoped
