### ISSUE TITLE
Virtualisation status check failed on AMD

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/clay#3928]
In public chat a user had trouble creating docker-machines after installing golem 0.19.0 with hyper-v on windows

event log:
```
Hypervisor launch failed; Either SVM not present or not enabled in BIOS.
```

After turning SVM on in bios the docker-machine was created with success

We could add AMD-V as an extension to the VT-x check #3268 so the user is warned in this case as well.

**Comment by kmazurek** [comment]
This turned out not to be an AMD-specific problem - virtualisation checks were failing due to a race condition between Golem core and Electron client (see #3966).

**Comment by shadeofblue** [comment]
@zakaprov can we close this, then?

**Comment by kmazurek** [comment]
@shadeofblue Yes, closing now.
