### ISSUE TITLE
Blender lighting differences between nodes

### ISSUE THREAD

**Issue by magdasta** [golemfactory/clay#393]
Some nodes render darker images than other for the same scene, which results in fair and dark strips in final image. This can be an issue with blender's color management (https://wiki.blender.org/index.php/Dev:Ref/Release_Notes/2.64/Color_Management)
![strips](https://cloud.githubusercontent.com/assets/13525071/15608457/38f77e80-241a-11e6-9c3f-2e8bdec623cb.JPEG)

**Comment by badb** [comment]
TODO: Find out if it's possible to turn off compositing in post processing with python script.

**Comment by badb** [comment]
This probles were caused by postprocessing functions. If we turn off compositing by default for tasks that are split in part, than the effect should not occur.
