### ISSUE TITLE
Add support for AMD-V in virtualization status check

### ISSUE THREAD

**Issue by kmazurek** [golemfactory/clay#3935]
Related to: #3928

The RPC call for checking virtualisation support (`env.hw.virtualization`) currently only checks for Intel VT/VT-x being enabled. AMD CPUs should also be supported.

**Comment by ZmijaWA** [comment]
![image](https://user-images.githubusercontent.com/30795583/55240928-458d9c00-523a-11e9-94a2-a15537f9bd40.png)
