### ISSUE TITLE
Add options to task creation dictionary to make the requestor more lenient towards the verification results

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/clay#3940]
* add an `x-disable-verification` option to the task creation parameters - when specified and `True` - it should completely disable verification for the given task and treat all results as valid without performing any verification - default `False`
* add an `x-lenient-verification` option to the task creation parameters - when specified, the verification should still be performed and then in the event of negative verification result - the subtask itself should be marked as failed as usual and rescheduled and the provider should also be banned from performing any additional subtasks in this task and a failure should still be reported to the golem monitor - BUT - when this flag is present in the task definition - the provider should get a `SubtaskResultsAccepted` response and be issued a payment just as it would had the result been correct. In other words - this flag should cause the verification result to seem positive from the provider's POV.

Those options should only be known to the requestor itself. The options should NOT be exposed in the `TaskHeader` and should be clearly marked in the accompanying comments within the code as experimental.

**Comment by etam** [comment]
I'd change one thing. Having two mutually exclusive bool flags, creates a problem, when both are set `True`. Better solution is one flag `x-run-verification`, with values `enabled` (default if not specified), `lenient` and `disabled`.

**Comment by shadeofblue** [comment]
@etam actually, that's probably indeed a good idea
