### ISSUE TITLE
Refactoring idea: split TaskSession into TaskSessionRequestor and TaskSessionProvider

### ISSUE THREAD

**Issue by etam** [golemfactory/clay#3965]
Our task session is clearly asymmetrical. Provider initiates a connection to requestor, they talk about the task, requestor sends data to provider, provider returns results, requestor validates results. Both ends of this session is handled by a single class `TaskSession`. It has references to both `TaskManager`, which is used by requestor and `TaskComputer`, which is used by provider.

I think it makes sense to split this class into two classes `TaskSessionRequestor` and `TaskSessionProvider`.

This might be also a good opportunity to make it use a [state machine](https://wiki.python.org/moin/FiniteStateMachine).

**Comment by shadeofblue** [comment]
@etam there's a pretty good chance that once we implement message queues, the tasksession's scope will change and especially, we will be able to remove state from `TaskSession` altogether... 

cc: @jiivan

**Comment by etam** [comment]
Those message queues: #2223 ? It seems to me that it adds persistence, which allows to resume a session if a node crashes/restarts. Still you need to have handling of those messages implemented somewhere and I still think it's a good idea to do it using a state machine with separated requestor from provider.

**Comment by shadeofblue** [comment]
@etam let's talk about it when @jiivan and you are at the office next Monday so that we can all be on the same page ... I'm just of an opinion that it doesn't make sense to start working on this issue here without taking the message queues into consideration

**Comment by mfranciszkiewicz** [comment]
@shadeofblue @etam Please consult the RnD team first.

**Comment by etam** [comment]
![new ideas](https://user-images.githubusercontent.com/220752/53953775-8b8c8f80-40d4-11e9-8a7e-8024ee6899de.jpg)

**Comment by Wiezzel** [comment]
Naming idea: it should be `ProviderTaskSession` and `RequestorTaskSession` not `TaskSessionProvider` and `TaskSessionRequestor`.

**Comment by mfranciszkiewicz** [comment]
The idea is not new. This is exactly why you should talk to RnD.

**Comment by etam** [comment]
On hold until message queues are implemented.

**Comment by etam** [comment]
Message queues were implemented some time ago.

This can be taken a step further to also split `TaskServer`.

**Comment by etam** [comment]
I've done some research about state machine implementations for Python and this one I think is the best: https://github.com/pytransitions/transitions

**Comment by jiivan** [comment]
> I've done some research about state machine implementations for Python and this one I think is the best: https://github.com/pytransitions/transitions

IMHO it's a little bit too magical. I.e. magically creating methods.

**Comment by etam** [comment]
> > I've done some research about state machine implementations for Python and this one I think is the best: https://github.com/pytransitions/transitions
> 
> IMHO it's a little bit too magical. I.e. magically creating methods.

True. But I can accept that for all the features it has, compared to alternatives.

**Comment by etam** [comment]
Note: there is a `RequestedTaskManager` introduced in #4462

**Comment by etam** [comment]
I've made a separate issue for making a state machine: #4826
