### ISSUE TITLE
golemcli: `account withdraw` should require confirmation each time

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/clay#3984]
* [ ] change golemcli to ask for manual confirmation when a correctly-formed `account withdraw` command is issued, before the actual transaction is sent
* [ ] add additional parameter `--confirm` to skip that manual confirmation step

**Comment by tworec** [comment]
Y-day we (@shadeofblue, @jamuszyn and me) agreed to move this initiative into a newly created work stream called `golem-client`: 

The recommendation is to finish what is started, but not start anything new. So pls report what is started and rest should be moved into a new issue in https://github.com/golemfactory/golem-client

@shadeofblue can you confirm it is not started yet?

**Comment by kmazurek** [comment]
@tworec I haven't started working on this yet.

**Comment by tworec** [comment]
moving to golemfactory/golem-client#10
