### ISSUE TITLE
How does Golem transfer data?

### ISSUE THREAD

**Issue by avatar-lavventura** [golemfactory/clay#3987]
I was not able to find any documentation related what technology/application does Golem uses to share data in between cluster and client.

On this [link](https://www.reddit.com/r/GolemProject/comments/8xxt3a/how_does_golem_transfer_data/) it is mentioned that Golem currently uses `HyperG` for sharing resources. But it is not mention on Golem's wiki or its white paper.

On the other hand on Golem's white paper and this [closed-issue](https://github.com/golemfactory/golem/issues/25), it is mentioned that Golam plans to use IPFS for data transfer.

I would appreciated if you could clarify that how does Golem transfer data?

**Comment by ktomala** [comment]
Golem uses HyperG (https://github.com/golemfactory/golem-hyperdrive) for file transfer. Underneath Hyperdrive utilizes DAT protocol. This is not an issue per se, I'd recommend to ask such questions on chat.golem.network. Closing issue.

**Comment by avatar-lavventura** [comment]
This information is missing on the white-paper and and other documentation related to Golem. Even on the [GitHub page ](https://github.com/golemfactory/golem-hyperdrive) there is no explanation on the readme. It just says: `Hyperdrive client for the Golem project.`.

=>  By saying Hyberdrive are you referring to this [project](https://github.com/mafintosh/hyperdrive)  or Golem implemented `HyperG ` from scratch? @ktomala

**Comment by ktomala** [comment]
@avatar-lavventura I have pointed out the project source code. I don't know the specifics. This is a place for issues with Golem not the discussion forum, so I would recommend again going to https://chat.golem.network and asking your questions there.
