### ISSUE TITLE
Change timeouts to absolute.

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#40]
We should control and fix timeout that are used in tasks. Mainly task timeouts and subtask timeouts, but also some other timeouts that may occur in code (eg. in task computer or task keeper for removing old tasks).

There are some additional important problems with that, ie differences with timestamps in different timezone.

**Comment by chfast** [comment]
Absolute. Ethereum uses Unix time (number of seconds from 1970-01-01) in UTC timezone and it works fine.

**Comment by chfast** [comment]
Should we change that into a task?

**Comment by badb** [comment]
https://github.com/imapp-pl/golem/pull/322

Further tasks: #324, #325
