### ISSUE TITLE
"computing" state stuck in Golem footer 

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#4027]
## Description

**Golem Version**: 0.19.0

**Golem-Messages version** (leave empty if unsure):  2.24.3

**Electron version** (if used):  0.1.18

**OS** : Any

**Branch** (if launched from source): - 

**Mainnet/Testnet**: 

**Description of the issue**:

On providing node in footer from time to time there is stuck "computing" state.

**Actual result**:

 It doesn't mean node is really computing, it means requesting node is either shut down during task computations or the requested task has been cancelled. 
When node is performing actual computations  proper state in footer is "computing (CPU)" or "Computing (GPU)"

After task cancellation info in footer changes from "computing (CPU)" to "computing".
To be checked if this state disappears after subtask timeout, after task timeout or is stuck until app restart

**Screenshots**:

![Screenshot from 2019-02-19 21-15-32](https://user-images.githubusercontent.com/32061891/54698119-0cb14100-4b2f-11e9-8a5a-79d7aff72504.png)

## Steps To Reproduce

1. Launch the app  on two nodes on private connection
2. Start a task on requestor, for example one frame multisubtask, cpu
3. Wait for provider to start actual computations
4. Cancel a task on requestor
5. Check footer on provider, there should be stuck "computing" instead of "computing (CPU)"
 
## Expected behavior

"Computing"  without CPU/GPU should not show in footer at all. When node is not providing, correct state is idle.

## Logs and any additional context
-

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by shadeofblue** [comment]
@ederenn I'm unsure that I understand what the expected behavior should be ... the screenshot above shows "Computing" so if that's the expected behavior, I'm unsure what the fix should be... ... are you sure your description of "Expected behavior" is correct?

**Comment by ederenn** [comment]
Edited info in issue. Sorry for confusion
