### ISSUE TITLE
Golem not starting up - stuck at "waming up"

### ISSUE THREAD

**Issue by mountassir** [golemfactory/clay#4028]
Hi

I have updated the Golem app to the latest 0.19.0 and now it gets stuck at warming up.

I see this log error 
"2019-03-20 20:56:04 WARNING golem.docker.hypervisor.docker_machine DockerMachine: failed to update env for VM: Command '['docker-machine', '--native-ssh', 'env', '--shell', 'cmd', 'golem']' returned non-zero exit status 1."

Older versions used to work before, I had it running for months.
This is on Windows 10 x64.

![Capture](https://user-images.githubusercontent.com/10292481/54719152-17320180-4b54-11e9-9c87-eff10a0e94ea.PNG)

**Comment by ederenn** [comment]
could you provide the whole golem.log file?

**Comment by vdmpeniel** [comment]
Where you able to solve this issue?

**Comment by mountassir** [comment]
No I did not, I installed the new version it gets stuck at startup then it blue screened my PC consistently.

**Comment by vdmpeniel** [comment]
> 
> 
> No I did not, I installed the new version it gets stuck at startup then it blue screened my PC consistently.

On Linux I am able to run it flawlessly, but on windows 10 it give me this same error.

Two errors actually:
2019-06-06 22:25:22 WARNING  golem.docker.hypervisor.docker_machine DockerMachine: failed to env the VM: Command '['docker-machine', '--native-ssh', 'regenerate-certs', '--force', 'golem']' returned non-zero exit status 2. -- b'Regenerating TLS certificates\nWaiting for SSH to be available...\n'

2019-06-06 22:31:02 WARNING  golem.docker.hypervisor.docker_machine DockerMachine: failed to update env for VM: Command '['docker-machine', '--native-ssh', 'env', '--shell', 'cmd', 'golem']' returned non-zero exit status 1.

**Comment by vdmpeniel** [comment]
> 
> 
> No I did not, I installed the new version it gets stuck at startup then it blue screened my PC consistently.

Check this link, following its instructions I was able to get the docker-machine running.
https://docs.golem.network/#/Products/Brass-Beta/Issues-&-Troubleshooting?id=_6-error-creating-virtual-machine

Now I am having issues pulling the images. :P

**Comment by shadeofblue** [comment]
@vdmpeniel what are those issues with the docker images?
