### ISSUE TITLE
When GPU task is requested Golem sends 2 images, for CPU and GPU

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#4032]
## Description

**Golem Version**: 0.19.1

**Golem-Messages version** (leave empty if unsure): 2.24.3

**Electron version** (if used):  0.1.19

**OS** [e.g. Windows 10 Pro]: Linux

**Branch** (if launched from source): - 

**Mainnet/Testnet**: Mainnet, Testnet

**Description of the issue**:

When GPU task is requested Golem sends 2 images, for CPU and GPU 

**Actual result**:

Golem could perform CPU computations instead of GPU
Golem should send image of one kind.

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by mfranciszkiewicz** [comment]
@ederenn Can we close this issue?
