### ISSUE TITLE
Golemapp.exe is treated as a trojan by Microsot Defender

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#4042]
## Description

**Golem Version**: 0.19.1
bulid 3966

**Golem-Messages version** (leave empty if unsure): 2.24.3

**Electron version** (if used): 0.1.19

**OS** [e.g. Windows 10 Pro]: Windows

**Branch** (if launched from source): -

**Mainnet/Testnet**: Mainnet

**Description of the issue**:

`golemapp.exe` is treated by Microsoft Defender as a trojan and is removed from the path.
In this case I was able to run Golem from shortcut once, after closing app it is not possible to run Golem again.

**Actual result**:

Golem cannot be started, electron can't find golemapp.exe to run the app.

**Screenshots**:

<img width="620" alt="Screen Shot 2019-03-25 at 15 36 25" src="https://user-images.githubusercontent.com/32061891/54935096-ec62f700-4f1f-11e9-81b2-45d3c397e27d.png">

## Expected behavior

Golem after restart is launched normally

## Logs and any additional context

Golem logs debug run, 
[golemapp.log](https://github.com/golemfactory/golem/files/3004268/golemapp.log)

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by mfranciszkiewicz** [comment]
Signing the binaries _may_ help with this situation.

**Comment by ZmijaWA** [comment]
@shadeofblue we did not notice this kind behavior for a while... We can close it, as not a problem anymore?

**Comment by ZmijaWA** [comment]
This is not a problem anymore.
