### ISSUE TITLE
Network trust setting suspected to be set an a non-zero value by default

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/clay#4048]
## Description

**Golem Version**: 0.19.0
**Mainnet/Testnet**: mainnet

**Description of the issue**:

`@donschool` on `#testers` says:

The only setting that I know nothing about is the 'Network Trust' setting. As I found them, they were both set to the middle position of the sliders. I set them to full thumbs up or slider at right (whatever that means) and watched for a day. No change, no jobs. I moved them to full thumbs down (all the way left) and started watching. Within 5 minutes I was processing a job. Another hour and I had processed two new jobs. So, it looks like the *Network Trust setting is the culprit*. Sorry for the waste of your time. Hope this holds true and I continue getting jobs as before.

**Actual result**:

"Network Trust" setting set at a non-zero value by default

## Steps To Reproduce
_Short description of steps to reproduce the behavior:_
e.g.
1. Launch a newly-installed Golem with defaults
2. Go to settings
3. Verify the "Network trust" setting value

## Expected behavior

"Network Trust" setting set at zero by default

**Comment by ZmijaWA** [comment]
This is not a problem anymore.
