### ISSUE TITLE
Crash after updating video driver Ubuntu 18.10 390.116->396.54

### ISSUE THREAD

**Issue by radiolaria81** [golemfactory/clay#4056]
## Description

**Golem Version**: 0.19

**OS** : Ubuntu 18.10

**Mainnet/Testnet**: mainnet

## Steps To Reproduce
1. launch golemapp --mainnet

## Expected behavior

Before i updated my video driver from 390.116 to 396.54, it works like a charm.

## Logs and any additional context

 golemapp --mainnet
INFO     [talkback                           ] Disabling talkback 'sentry' service
INFO     [talkback                           ] Disabling talkback 'sentry-metrics' service
INFO     [golemapp                           ] GOLEM Version: 0.19.0
INFO     [golemapp                           ] Protocol Version: 31
INFO     [golemapp                           ] golem_messages Version: 2.24.3
INFO     [golemapp                           ] system: Linux, release: 4.18.0-16-generic, version: #17-Ubuntu SMP Fri Feb 8 00:06:57 UTC 2019, machine: x86_64
INFO     [golemapp                           ] cpu: GenuineIntel Intel(R) Core(TM)2 Quad CPU    Q9550  @ 2.83GHz, 4 cores
INFO     [golemapp                           ] memory: 7.8 GiB, swap: 7.8 GiB
INFO     [golemapp                           ] Ethereum chain: mainnet
INFO     [golemapp                           ] Concent disabled
INFO     [golem.hardware.presets             ] updating config: name: custom, num_cores: 2, max_memory_size: 4.4 GiB, max_resource_size: 19.2 GiB
WARNING  [twisted                            ] Native worker connection closed uncleanly: A process has ended with a probable error condition: process ended with exit code 255.
ERROR    [twisted                            ] Failed to start native worker: A process has ended with a probable error condition: process ended with exit code 255.
ERROR    [twisted                            ] ApplicationError: ApplicationError(error=<crossbar.error.cannot_start>, args=['Failed to start native worker: A process has ended with a probable error condition: process ended with exit code 255.', ['Failed to write all bytes for numpy.core.umath.so', 'fwrite: No space left on device']], kwargs={}, enc_algo=None): Traceback (most recent call last):
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 384, in processEnded
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/crossbar/controller/native.py", line 82, in connectionLost
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 500, in errback
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
    
--- <exception caught here> ---
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/crossbar/controller/process.py", line 506, in on_ready_error
    
autobahn.wamp.exception.ApplicationError: ApplicationError(error=<crossbar.error.cannot_start>, args=['Failed to start native worker: A process has ended with a probable error condition: process ended with exit code 255.', ['Failed to write all bytes for numpy.core.umath.so', 'fwrite: No space left on device']], kwargs={}, enc_algo=None)

ERROR    [twisted                            ] crossbar.error.cannot_start: Failed to start native worker: A process has ended with a probable error condition: process ended with exit code 255. ['Failed to write all bytes for numpy.core.umath.so', 'fwrite: No space left on device']

**Comment by mfranciszkiewicz** [comment]
The problem lies with the lack of free space on disk.
`'Failed to write all bytes for numpy.core.umath.so', 'fwrite: No space left on device'`

**Comment by radiolaria81** [comment]
omg. i didnt see this. shame on me! thx for the fast response!
