### ISSUE TITLE
Only main administrator user is added to Hyperv Administrators 

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#4059]
## Description

**Golem Version**: 0.19.1

**Golem-Messages version** (leave empty if unsure):2.24.3

**Electron version** (if used): 0.1.19

**OS** [e.g. Windows 10 Pro]: Windows 10

**Branch** (if launched from source): -

**Mainnet/Testnet**: Mainnet

**Description of the issue**:

If on one machine there are several user's accounts and user is installing Golem app with hyperv on account without administrative rights, config files are created for main user not the user who is actually installing Golem.

**Actual result**:

Only main administrator user is added to Groups HyperV Administrators, not the user who was installing Golem. Hyperv Manager is installed on account where Golem installation was run but docker-machine for Golem is not created. Golem is not starting, `No supported VM hypervisor was found.` error shows up in logs.
Only main user with administrative rights is added to the group, nWhen user runs Golem

**Screenshots**:

_If applicable, add screenshots to help explain your problem._

## Steps To Reproduce
1. On clean os add user's account without administrative rights
2. On created account without administrative rights install Golem 0.18.3
3. Run Golem go trough whole onbording and wait for Golem to connect to nodes
4. Switch off Golem
5. Install Golem 0.19.1
6. Hit windows button, type "run"
7. in Run window run lusrmgr.msc
8. In Groups check Hyper-V Administrators which users are added to the group

## Expected behavior

Account on which installation was run should be added to the Hyperv Administrator Group, user should be able to run Golem.

## Logs and any additional context
after running Golem

```
2019-03-29 18:27:13 ERROR    golem.docker.manager                
                ***************************************************************
                No supported VM hypervisor was found.
                Golem will not be able to compute anything.
                hypervisor.setup() returned CalledProcessError(1, ['docker-machine', '--native-ssh', 'start', 'golem'])
                ***************************************************************
                
2019-03-29 18:27:13 ERROR    golem.node                          
                    There was a problem setting up the environment: No VM hypervisor found.
                    Golem will run with limited functionality to support
                    communication with local clients.
                    
2019-03-29 18:27:14 INFO     golem.node                          Waiting for password to unlock the account. Run `golemcli account unlock` and enter your password.
```

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by maaktweluit** [comment]
Resolved by #4064
