### ISSUE TITLE
Golem with Docker Toolbox is not starting, upgrade from 19.0 with hyperv to 19.1 with toolbox

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#4060]
## Description

**Golem Version**: 0.19.1

**Golem-Messages version** (leave empty if unsure): 2.24.3

**Electron version** (if used): 0.1.19

**OS** [e.g. Windows 10 Pro]: Windows 10

**Branch** (if launched from source): - 

**Mainnet/Testnet**: Mainnet

**Description of the issue**:

Golem with Docker Toolbox is not starting. After upgrade from 19.0 with hyperv to 19.1 with toolbox

**Actual result**:

Golem app is hanging after typing in password 

**Screenshots**:

_If applicable, add screenshots to help explain your problem._

## Steps To Reproduce
System with Golem 0.19.0 is needed.

1. Install 0.19.1 Golem Version without Hyperv
2. Check in Windows Features if Hyperv is disabled
3. Install Docker Toolbox 18.6 version
https://github.com/docker/toolbox/releases/download/v18.06.1-ce/DockerToolbox-18.06.1-ce.exe
4. In Powershell with administrative rights type in 

```
C:\windows\System32\InfDefaultInstall.exe "C:\Program Files\Oracle\VirtualBox\drivers\vboxdrv\VBoxDrv.inf"
Set-ItemProperty HKLM:\system\currentcontrolset\services\vboxdrv -Name ImagePath -Value "\??\C:\Program Files\Oracle\VirtualBox\drivers\vboxdrv\VBoxDrv.sys"
Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Services\VBoxDrv" -Name "DelayedAutostart" -Value 1 -Type DWORD
Start-Service vboxdrv
```

5. Restart system
6. Run Docker Toolbox Quickstart, wait for Docker to launch
7. Run Golemapp
8. Golem will hang after typing in password on "Logged in"

## Expected behavior
Golem should launch and connect to nodes

## Logs and any additional context

[golem.log](https://github.com/golemfactory/golem/files/3024430/golem.log)

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by ZmijaWA** [comment]
@Wiezzel Guess we can close it as it is not supported anymore?

**Comment by maaktweluit** [comment]
@ZmijaWA PR #4268 will solve this issue :)

linked them so this issue will get closed when the PR gets merged

**Comment by ZmijaWA** [comment]
PR #4268 will solve this issue
