### ISSUE TITLE
Golem with Docker Toolbox is not starting, clean os installation with no hyperv

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#4061]
## Description

**Golem Version**: 0.19.1

**Golem-Messages version** (leave empty if unsure): 2.24.3

**Electron version** (if used): 0.1.19

**OS** [e.g. Windows 10 Pro]: Windows 10

**Branch** (if launched from source): - 

**Mainnet/Testnet**: Mainnet

**Description of the issue**:

Golem with Docker Toolbox is not starting. Installation on clean system, no hyperv.

**Actual result**:

Golem app is hanging during docker images download

**Screenshots**:

_If applicable, add screenshots to help explain your problem._

## Steps To Reproduce

1. On clean OS install 0.19.1 Golem Version without Hyperv
2. Install Docker Toolbox 18.6 version
https://github.com/docker/toolbox/releases/download/v18.06.1-ce/DockerToolbox-18.06.1-ce.exe
3. In Powershell with administrative rights type in 

```
C:\windows\System32\InfDefaultInstall.exe "C:\Program Files\Oracle\VirtualBox\drivers\vboxdrv\VBoxDrv.inf"
Set-ItemProperty HKLM:\system\currentcontrolset\services\vboxdrv -Name ImagePath -Value "\??\C:\Program Files\Oracle\VirtualBox\drivers\vboxdrv\VBoxDrv.sys"
Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Services\VBoxDrv" -Name "DelayedAutostart" -Value 1 -Type DWORD
Start-Service vboxdrv
```

4. Restart system
5. Run Docker Toolbox Quickstart, wait for Docker to launch
6. Run Golemapp
7. Golem hangs on downloading dockers

## Expected behavior
Golem should launch and connect to nodes

## Logs and any additional context

[golem.log](https://github.com/golemfactory/golem/files/3024453/golem.log)

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by ederenn** [comment]
related
https://github.com/golemfactory/golem/issues/4060

**Comment by ZmijaWA** [comment]
@Wiezzel the same #4060 ?

**Comment by ZmijaWA** [comment]
PR #4268 will solve this issue
