### ISSUE TITLE
'comp.task' doesn't return 'samples' parameter

### ISSUE THREAD

**Issue by mdtanrikulu** [golemfactory/clay#4066]
## Description

'comp.task' RPC does not return 'samples' parameter, after creating task with 'samples' included.

**Golem Version**: 0.19.0

**Golem-Messages version** (leave empty if unsure):

**Electron version** (if used): 0.1.19

**OS** [e.g. Windows 10 Pro]: MacOS

**Branch** (if launched from source):

**Mainnet/Testnet**: Testnet/didn't try on main

**Description of the issue**: 'When I add 'samples' parameter into task definition while creating the task, after creation; this parameter should be in task object but it's not.

**Actual result**:

```json
{  
   "bid":1,
   "compute_on":"cpu",
   "concent_enabled":false,
   "cost":null,
   "duration":2.6573760509490967,
   "estimated_cost":"1333333333333333336",
   "estimated_fee":"224000000000000",
   "fee":null,
   "id":"89b2064a-54a2-11e9-b6a1-77eb653fa050",
   "last_updated":1554139268.396967,
   "name":"heli",
   "options":{  
      "compositing":false,
      "format":"PNG",
      "frame_count":1,
      "frames":"1",
      "output_path":"/Users/mdt/Documents/golem",
      "resolution":[  
         1920,
         1080
      ]
   },
   "preview":"/Users/mdt/Library/Application Support/golem/default/rinkeby/ComputerRes/89b2064a-54a2-11e9-b6a1-77eb653fa050/tmp/current_preview.PNG",
   "progress":0,
   "resources":[  
      "/Users/mdt/Desktop/testFiles/heli.blend"
   ],
   "status":"Not started",
   "subtask_timeout":"0:20:00",
   "subtasks_count":4,
   "time_remaining":null,
   "time_started":1554139268.396977,
   "timeout":"0:20:00",
   "type":"Blender"
}
```

## Steps To Reproduce
Add "samples" parameter while creating blender task,
Try to get details of the task from "comp.task" RPC

## Expected behavior
There should be "samples" parameter in task object

**Comment by shadeofblue** [comment]
@mdtanrikulu has this been fixed?

**Comment by mdtanrikulu** [comment]
@shadeofblue 👍yes :) (message from the past)
