### ISSUE TITLE
AttributeError: 'TaskServer' object has no attribute 'key_id'

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#4117]
## Description

**Golem Version**: GOLEM Version: 0.19.1+dev277.g7435862

**Golem-Messages version** (leave empty if unsure): golem_messages Version: 3.3.0

**Electron version** (if used): 0.1.19

**OS** [e.g. Windows 10 Pro]: Windows 10 Pro

**Branch** (if launched from source): develop

**Mainnet/Testnet**: mainnet

**Description of the issue**:

after task is added on requestor's node on providing nodes error appears in logs

**Actual result**:

Despite critical, subtask has been computed, but node is not providing again for the requestor. Nodes are not banned for each other.

**Screenshots**:

_If applicable, add screenshots to help explain your problem._

## Steps To Reproduce
_Short description of steps to reproduce the behavior:_
e.g.
1. Run Golem from source on develop branch
2. Add short task on requesting node e.g. Helicopter 400x400 1 frame, 3 subtasks
3. Check provider's logs for critical

## Logs and any additional context

```
CRITICAL [twisted                            ]
Traceback (most recent call last):
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\twisted\internet\task.py", line 865, in <lambda>
    d.addCallback(lambda ignored: callable(*args, **kw))
  File "C:\Users\Magdalena Szydlowska\Projects\golem\golem\task\server\resources.py", line 224, in <lambda>
    lambda *_: self._handshake_timeout(self.key_id)
AttributeError: 'TaskServer' object has no attribute 'key_id'
```

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by maaktweluit** [comment]
Made a small PR #4124 with the same fix as #4111 to get the scary error off develop
