### ISSUE TITLE
Refactor golem/task/rpc.py:_inform_subsystems

### ISSUE THREAD

**Issue by mplebanski** [golemfactory/clay#4126]
IMHO: this method has nothing to do with it's actual name.

**Comment by ttanay** [comment]
Hi
I'm new to Golem and would like to give this a shot.

**Comment by mplebanski** [comment]
@ttanay Cool! Go on. 

This is actually very simple. We left an issue open because it was out of scope of the PR where it was found. 

One should determine what the function does and what it returns to determine an appropriate name for it.
