### ISSUE TITLE
 Warning: Can't remove payment lock after removing finished task

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#4136]
## Description

**Golem Version**: 0.19.1+dev381.g7eeee39

**Golem-Messages version** (leave empty if unsure):   3.3.1

**Electron version** (if used): 0.1.19

**OS** [e.g. Windows 10 Pro]: Linux

**Branch** (if launched from source): develop

**Mainnet/Testnet**: mainnet 

**Description of the issue**:

 I'm recieving warning `can't remove payment lock` every time after removing a finished task. Task has been finished and payed fully. In history of payments every transaction for this task was in confirmed state. Right after removing task from taks list in logs/console appears:

```
WARNING  [golem.ethereum.fundslocker         ] I can't remove payment lock from task'defce718-61e4-11e9-b0a7-5ad86f3605c2': unkown task.
```

**Actual result**:

Warning in logs

**Screenshots**:

_If applicable, add screenshots to help explain your problem._

## Steps To Reproduce
_Short description of steps to reproduce the behavior:_
e.g.
1. launch Golem
2. Start a small task, wait for task to finish
3. Restart Golem to trigger batching 
4. Wait to have payments for this task confirmed in payments list
5. Remove finished and confirmed task
6. Check logsf or warning

## Expected behavior

Golem should be able to remove payment lock successfully 

## Logs and any additional context

```
WARNING  [golem.ethereum.fundslocker         ] I can't remove payment lock from task'defce718-61e4-11e9-b0a7-5ad86f3605c2': unkown task.
```

related to https://github.com/golemfactory/golem/pull/4104

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by ZmijaWA** [comment]
This task is not relevant to #4104  It also appears in develop. Need to be fixed. It's not a blocker for a test task #4104.

**Comment by maaktweluit** [comment]
The expected behaviour is wrong, there should not be a lock when the task is not active.

There should be a `task_status.is_active()` check before trying to unlock the funds
