### ISSUE TITLE
Prevent user to upgrade 0.19.1 with HyperV to 0.19.2 with docker toolbox (change the installation process)

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#4222]
## Description

**Golem Version**: 19.2

**Golem-Messages version** (leave empty if unsure):

**Electron version** (if used): 0.1.20

**OS** [e.g. Windows 10 Pro]: Windows 10 Pro

**Branch** (if launched from source): -

**Mainnet/Testnet**: mainnet

**Description of the issue**:

Upgrade from  Golem 0.19.1 with Hyperv to 19.2 with toolbox fails. 
After choosing not to install Hyperv with the installer, Hyperv is not disabled automatically in Windows Features. 

Golem does not support this kind of upgrade but it is possible for a user to do that. 

**Actual result**:

Hyperv is not disabled and two docker-machines are avaliable. Hyperv needs to be disabled manually. Two docker machines are avaliable. It is not possible to fully launch Golem without removing hyperv machine manually.

**Screenshots**:

<img width="709" alt="Screen Shot 2019-05-22 at 18 06 58" src="https://user-images.githubusercontent.com/32061891/58194855-ec386b00-7cc6-11e9-99cd-41b4637c5444.png">

## Steps To Reproduce
System with Golem 0.19.1 is needed.

1. Install 0.19.2 Golem Version without Hyperv
2. Check in Windows Features if Hyperv is disabled
3. If not, disable Hyperv
4. Install Docker Toolbox 18.6 version
https://github.com/docker/toolbox/releases/download/v18.06.1-ce/DockerToolbox-18.06.1-ce.exe
5. In Powershell with administrative rights type in
C:\windows\System32\InfDefaultInstall.exe "C:\Program Files\Oracle\VirtualBox\drivers\vboxdrv\VBoxDrv.inf"
Set-ItemProperty HKLM:\system\currentcontrolset\services\vboxdrv -Name ImagePath -Value "\??\C:\Program Files\Oracle\VirtualBox\drivers\vboxdrv\VBoxDrv.sys"
Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Services\VBoxDrv" -Name "DelayedAutostart" -Value 1 -Type DWORD
Start-Service vboxdrv
6. Restart system
7. Run Docker Toolbox Quickstart, wait for Docker to launch
8. In command line type in: `docker-machine ls`, two machines will be listed
9. Run Golemapp
10. Golem will hang after typing in password on "Logged in"

After removing hyperv machine with `docker-machine -f rm golem` in command line it is possible to launch Golem with success.

## Expected behavior

**Golem should prevent a user to upgrade golem with HyperV to golem with docker toolbox.**

## Logs and any additional context

```C:\Users\ederenn>docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER     ERRORS
default   *        virtualbox   Running   tcp://192.168.99.100:2376           v18.09.6
golem     -        hyperv       Error                                         Unknown    Failed to find the VM status
```

```2019-05-22 17:11:47 INFO     golem.node                          Waiting for password to unlock the account. Run `golemcli account unlock` and enter your password.
2019-05-22 17:11:50 ERROR    golem.docker.hypervisor             DockerMachine: failed to check status: Command '['docker-machine', '--native-ssh', 'status', 'golem']' returned non-zero exit status 1.
2019-05-22 17:11:50 INFO     golem.docker.hypervisor             Docker: restoring machine state not implemented
2019-05-22 17:11:50 INFO     golem.docker.hypervisor             Docker: starting VM golem
2019-05-22 17:11:51 ERROR    golem.docker.hypervisor             Docker: failed to start the VM: CalledProcessError(1, ['docker-machine', '--native-ssh', 'start', 'golem'])
2019-05-22 17:11:51 ERROR    golem.docker.manager                
                ***************************************************************
                No supported VM hypervisor was found.
                Golem will not be able to compute anything.
                hypervisor.setup() returned CalledProcessError(1, ['docker-machine', '--native-ssh', 'start', 'golem'])
                ***************************************************************
                
2019-05-22 17:11:51 ERROR    golem.node                          
                    There was a problem setting up the environment: No VM hypervisor found.
                    Golem will run with limited functionality to support
                    communication with local clients.
                    
2019-05-22 17:11:52 INFO     golem.node                          Waiting for password to unlock the account. Run `golemcli account unlock` and enter your password.
2019-05-22 17:11:55 INFO     golem.node                          Got password
```

## Proposed Solution?
Change the installation process.

**Comment by shadeofblue** [comment]
@Wiezzel @maaktweluit do we support such an "upgrade"?

**Comment by Wiezzel** [comment]
@shadeofblue No, we don't

**Comment by ZmijaWA** [comment]
@Wiezzel @shadeofblue  As we discuss this morning we need to pass the information to users that this kind of upgrade is not supported by the Golem team :) I will change the subject to something like: "change installation process to prevent this kind of upgrade"
