### ISSUE TITLE
"None of the Docker images are available" - integration test fail

### ISSUE THREAD

**Issue by ZmijaWA** [golemfactory/clay#4238]
## Description

**Golem Version**: dev+branch

**Golem-Messages version** (leave empty if unsure):

**Electron version** (if used):

**OS** [e.g. Windows 10 Pro]:

**Branch** (if launched from source): CGI/blender_verifier_refactor_review

**Mainnet/Testnet**: mainnet/testnet

**Description of the issue**: 

_A clear and concise description of what went wrong, in which component, when and where._

During integration tests, I found an issue with docker image. All subtask end with timeout status. We repeat test manually and the result was the same.

**Actual result**:

_What is the observed behavior and/or result in this issue_

Task timed out

```
2019-05-24 09:23:05 WARNING  golem.task.taskthread               Task computing error None of the Docker images are available
2019-05-24 09:23:05 WARNING  golem.verifier.blender_verifier     Verification process exception. Subtask_id: 25240d02-7e05-11e9-aaff-81eeb426f8aa. Exception: [Failure instance: Traceback: <class 'golem.task.taskthread.JobException'>: None of the Docker images are available
/usr/lib/python3.6/threading.py:884:_bootstrap
/usr/lib/python3.6/threading.py:916:_bootstrap_inner
/home/buildbot-worker/worker/test_node_integration/build/golem/docker/task_thread.py:140:run
--- <exception caught here> ---
/home/buildbot-worker/worker/test_node_integration/build/golem/docker/task_thread.py:122:run
]
2019-05-24 09:23:05 WARNING  apps.core.verification_queue        Finishing verification with fail

```

```

>> subtasks show f6bbb522-7e28-11e9-9d48-7702b396b732
deadline: 1558705601
extra_data: {'scene_file': '/golem/resources/scene-Helicopter-27-cycles.blend', 'resolution': [200, 200], 'use_compositing': False, 'samples': 0, 'frames': [1], 'output_format': 'PNG', 'path_root': '/home/ederenn/Desktop/test files', 'start_task': 1, 'total_tasks': 1, 'crops': [{'outfilebasename': 'scene-Helicopter-27-cycl_1', 'borders_x': [0.0, 1.0], 'borders_y': [0.0, 1.0]}], 'entrypoint': 'python3 /golem/entrypoints/render_entrypoint.py'}
node_id: 8a87b7e8e51b07c56cdc94200dcbf559f6db5bf4f161ab68ecc88669e891420523d59ffb30986bc2a8b172a262e9ce30807b321a0739aa3ca112191a412aa2d9
node_name: bad wolf t
price: 119918316327578832
progress: 1.0
results: ['/home/ederenn/.local/share/golem/default/rinkeby/ComputerRes/e11f9a7e-7e28-11e9-b2a5-7702b396b732/tmp/scene-Helicopter-27-cycl_10001.png']
status: Failure
stderr: [GOLEM] Not accepted
stdout: /home/ederenn/.local/share/golem/default/rinkeby/ComputerRes/e11f9a7e-7e28-11e9-b2a5-7702b396b732/tmp/f6bbb522-7e28-11e9-9d48-7702b396b732/stdout.log
subtask_id: f6bbb522-7e28-11e9-9d48-7702b396b732
time_started: 1558705001

>> 

```

**Screenshots**:

_If applicable, add screenshots to help explain your problem._

## Steps To Reproduce
Start the simple task on this branch.
Look in the logs.

## Expected behavior
_(What is the expected behavior and/or result in this scenario)_

Task finished with success. 

## Logs and any additional context
_(Any additional information that could help to resolve the issue, which systems were checked to reproduce the issue)_
_Please upload your logs if possible_
from integration test: 
prov: 
[golem.error.log](https://github.com/golemfactory/golem/files/3222263/golem.error.log)

req:
[golem.error.log](https://github.com/golemfactory/golem/files/3222267/golem.error.log)

- this is just error logs from one test if you will need more you can find in:
[integration test](https://buildbot.golem.network/buildbot/#/builders/15/builds/682)

From manual test:
requestor:
[golem.log](https://github.com/golemfactory/golem/files/3222406/golem.log)

provider:
[golemprov.log](https://github.com/golemfactory/golem/files/3222408/golemprov.log)

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by magdasta** [comment]
blender_verifier:1.3 was missing in docker hub
