### ISSUE TITLE
Rename `golem.config` to `ChainConfig` and implement it as a singleton

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/clay#4254]
## Rationale
The current solution with the values included in `golem.config.environments` determined at import time causes issues when the code relying on that module is patched etc, resulting in a race-condition-like behavior (e.g. values partially overwritten).

Futhermore, using system environment variables to hold (initial/global) application state seems suboptimal as well.

### Technical specification
* refactor `golem.config` module so that it is a singleton class that, initialized once, can be relied upon to stay consistent throughout app's execution.
* clearly separate (and possiby rename) the transaction's system `EthereumConfig` from the config that Golem uses to determine which Concent instance - and thus, GNTDeposit contract -  it communicates with

**Comment by mfranciszkiewicz** [comment]
> golem.config.environments determined at import time causes issues when the code relying on that module is patched etc

There are helper functions exactly for this purpose in `tests.golem.config.utils`. Otherwise, you're not supposed to patch the environment at all.

> using system environment variables to hold (initial/global) application state seems suboptimal as well

I'd agree only if we didn't allow setting the Golem env via environment variables. Also we are **not** messing with system environment variables, we are only changing environment variables for the current execution context (if not set by the user).

**Comment by shadeofblue** [comment]
> > golem.config.environments determined at import time causes issues when the code relying on that module is patched etc
> 
> There are helper functions exactly for this purpose in `tests.golem.config.utils`. Otherwise, you're not supposed to patch the environment at all.

We're not patching the environment....

We're patching other Golem modules and issues with the environment config are just an unintended and _unexpected_ side effect
