### ISSUE TITLE
object has no attribute '_handshake_error'

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#4261]
## Description

Golem Version: GOLEM Version: 0.19.2+dev524.g9d0fba9

Golem-Messages version (leave empty if unsure):

Electron version (if used): 3.4.0

OS [e.g. Windows 10 Pro]: Windows 10

Branch (if launched from source): fix/not_correct_volumes_windows(issue#4246)

Mainnet/Testnet: mainnet

**Description of the issue**:

After the the handshake between two nodes has started in logs appeared error

**Actual result**:

handshake ends with error, node will be banned

**Screenshots**:

_If applicable, add screenshots to help explain your problem._

## Steps To Reproduce
_Short description of steps to reproduce the behavior:_
e.g.
1. Launch the app with '...'

## Expected behavior
_(What is the expected behavior and/or result in this scenario)_

## Logs and any additional context

```
INFO     [golem.task.server.resources        ] Starting resource handshake with 'd178f6b5..042a2b93'
ERROR    [golem.resource.hyperdrive.resourcesmanager] Error adding file: <twisted.python.failure.Failure twisted.internet.error.ConnectionRefusedError: Connection was refused by other side: 10061: WSAECONNREFUSED.>
Unhandled error in Deferred:
CRITICAL [twisted                            ] Unhandled error in Deferred:

CRITICAL [twisted                            ]
Traceback (most recent call last):
  File "C:\Users\ederenn\projects\golem-env\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "C:\Users\ederenn\projects\golem\golem\task\server\resources.py", line 287, in <lambda>
    lambda exc: self._handshake_error(key_id, exc)
AttributeError: 'TaskServer' object has no attribute '_handshake_error'
```

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by ZmijaWA** [comment]
@shadeofblue We can notice this issue from time to time. We cannot reproduce it on demand.
