### ISSUE TITLE
Change log management

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#428]
Log files are growing too quickly. Possible solutions:
- turn off debug message
- save errors and warnings into separate files
- don't put computation logs in the golem log
- change golem log file more often 
- ... ?

**Comment by chfast** [comment]
Some suggestions:
1. I'm not sure it is standard or not, but I've seen and like the config in form of `":warning;golem.*:info;golem.pay:debug"`.
2. Our logging.ini config file sucks. I tried to use it many times but still cannot figure out how it works if at all. Can we replace that with something usable?
3. Let's have "info" level by default.
