### ISSUE TITLE
Problem in reporting provider active task

### ISSUE THREAD

**Issue by prekucki** [golemfactory/clay#4300]
## Description

golemapp from b0.20.

## Steps To Reproduce

1. Start golemapp.py
2. Wait for incomming task
3. during task processing call RPC `comp.tasks.stats`

```
$ golemcli tasks stats

__init__() missing 1 required keyword-only argument: 'outfilebasename'
```

**Comment by shadeofblue** [comment]
duplicate of: https://github.com/golemfactory/golem/issues/4116
