### ISSUE TITLE
Move changes from packaging back to develop

### ISSUE THREAD

**Issue by chfast** [golemfactory/clay#434]
The packaging branch has started to live its own life and is currently the only branch that works. Diff between these branches is quite big. Creating PRs for develop branch does not make much sense.

**Comment by badb** [comment]
Well, develop branch is still working, but doesn't connect to external nodes on purpose. 
But UGH. This merge is going to be massacre. I was sure that packaging branch is merged regularly with develop :/ 
Any ideas how we can solve this problems and made mammoth merge?

**Comment by chfast** [comment]
I was thinking more about dividing the packaging changes into pieces and review as PRs, one by one. It does not has to instant. But testing two versions at the same time is not ideal.

**Comment by chfast** [comment]
Also looks like the develop still requires ipfs.

**Comment by mfranciszkiewicz** [comment]
It's enough to merge the `netcode` branch to retain connectivity, but it will still be a lot of work. I'm looking into that.
