### ISSUE TITLE
Subtask computations for a first task after Golem restart are not starting

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#4399]
## Description

**Golem Version**: 0.20.0

**Golem-Messages version** (leave empty if unsure): 
3.7.0
**Electron version** (if used): 0.2.0

**OS** [e.g. Windows 10 Pro]: Windows 10 Pro, Linux 18.04

**Branch** (if launched from source): -

**Mainnet/Testnet**: mainnet

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:

 After Golem restart computations of task are not starting. Task is started but no subtask appears on a subtask list. After task is created all required handshakes end with success.This happens for a task created right after app restart. If next task is requested computation for both tasks are starting.

**Screenshots**:

_If applicable, add screenshots to help explain your problem._

## Steps To Reproduce

Prerequisites: at least three providers

1. Launch Golem
2. Start a small task 400x400 30 samples per pixel, Helicopter, 1 frame, 5 subtasks. 10 minutes for task. 10 minutes for subtask, bid 0.2 
3. Wait for task to finish, request another two, could be set wit the same parameters.
4. Restart requestor.
5. Request another small task
6. No subtask of this task is started. Subtask list is empty (both in Gui and in cli), task ends in timeout
7. In logs starts to repeat error `in get_fragments     
builtins.TypeError: 'NoneType' object is not iterable`

Additional info.
After restart of a requestor when the new providing node is set requestor will start computations only on this new node.

## Expected behavior
Nodes should start computations of subtasks

## Logs and any additional context
in `golem.log` repeats error 

```
2019-06-27 08:08:33 ERROR    twisted                             TypeError: 'NoneType' object is not iterable: Traceback (most recent call last):
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\autobahn\twisted\websocket.py", line 162, in _onMessage
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\autobahn\wamp\websocket.py", line 95, in onMessage
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\autobahn\wamp\protocol.py", line 895, in onMessage
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\txaio\tx.py", line 429, in as_future
    
--- <exception caught here> ---
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\twisted\internet\defer.py", line 150, in maybeDeferred
    
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\task\rpc.py", line 921, in get_fragments
    
builtins.TypeError: 'NoneType' object is not iterable
```

```
C:\Users\ederenn>golemcli --mainnet tasks subtasks a7c5cbb6-98eb-11e9-8aba-c0fee64a7c8a
No subtasks

C:\Users\ederenn>
```

Linux full debug logs added below:

https://drive.google.com/open?id=1FmX4Y1FGHMOttoAB6akngDvwVjj8EsnI

tasks computed in this log run

```
>> tasks show 
id                                    ETA        subtasks_count  status    completion
------------------------------------  -------  ----------------  --------  ------------
c67e6ed0-9990-11e9-aaf3-bc2e959fc96d  0:00:00                 5  Finished  100.00 %
d09c45d2-9991-11e9-8e8d-bc2e959fc96d  0:00:00                 5  Finished  100.00 %
148bedc2-9991-11e9-b4ac-bc2e959fc96d  0:00:00                 5  Finished  100.00 %
08eda6b6-998f-11e9-9b2e-bc2e959fc96d  ???                     5  Timeout   0.00 %
5eb50726-9992-11e9-abf9-bc2e959fc96d  ???                     5  Waiting   0.00 %
>> tasks subtasks 5eb50726-9992-11e9-abf9-bc2e959fc96d
No subtasks
>> tasks show 
id                                    ETA        subtasks_count  status     completion
------------------------------------  -------  ----------------  ---------  ------------
c67e6ed0-9990-11e9-aaf3-bc2e959fc96d  0:00:00                 5  Finished   100.00 %
d09c45d2-9991-11e9-8e8d-bc2e959fc96d  0:00:00                 5  Finished   100.00 %
148bedc2-9991-11e9-b4ac-bc2e959fc96d  0:00:00                 5  Finished   100.00 %
08eda6b6-998f-11e9-9b2e-bc2e959fc96d  ???                     5  Timeout    0.00 %
5eb50726-9992-11e9-abf9-bc2e959fc96d  ???                     5  Timeout    0.00 %
25b95bd0-9994-11e9-8ee9-bc2e959fc96d  0:01:13                 5  Computing  40.00 %


## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by kmazurek** [comment]
@ederenn The attached logs from Ubuntu are not with debug level.

**Comment by ederenn** [comment]
@zakaprov @etam switched to debug

**Comment by etam** [comment]
This looks like a combination of 2 bugs:
1) When task has no subtasks yet, then `get_fragments` fails with `'NoneType' object is not iterable`.
2) After restarting requestor, it performs resource handshake with provider, and the communication is stalled.

**Comment by kmazurek** [comment]
@etam I'll fix the first issue.
