### ISSUE TITLE
 Golem reports timeout on port `3282`

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#4400]
## Description

**Golem Version**: 0.20.0

**Golem-Messages version** (leave empty if unsure): 
3.7.0
**Electron version** (if used): 0.2.0

**OS** [e.g. Windows 10 Pro]: Windows 10 Pro

**Branch** (if launched from source): -

**Mainnet/Testnet**: mainnet

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:

After installation on clean system Golem reports timeout on one of the ports. Reported in interface and in cli.  Despide warning it is possible to connect to nodes and preform computations. When checked externally all ports are opened. e.g. with canyouseeme.org

**Actual result**:

Golem should report actual state of the ports.

**Screenshots**:
![Screenshot from 2019-06-27 15-14-53](https://user-images.githubusercontent.com/32061891/60297934-a73ccf80-9929-11e9-937d-26c6c65cbd2f.png)

## Steps To Reproduce
Prereq:
Clean system with no Golem installation

1. Install Golem
2. Go trouhg the whole onbording
3. Wait to have connection to nodes or "no nodes connected"
4. GUI reports problem with ports.

it also happens on Golem upgrade after changing from hyperg 2.X to 3.2

## Logs and any additional context

```
C:\Golem>golemcli network status
Port(s) 40102: open, 40103: open, 3282: timeout. Connected
```
several checks showed that Golem reports problem with 3282 port. Not checked on every launch
## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by kmazurek** [comment]
Initial findings: so far the issue was only reproduced on Windows and only during the first run of the application after installing.
Given the preconditions it's most likely that the problem lies in the timing between the user granting Golem permissions and the port check actually happening (since the check is only done once).

**Comment by shadeofblue** [comment]
@zakaprov maybe solution would be to execute this check each time the `network.status` RPC is called?
