### ISSUE TITLE
Support starting and stopping nodes in node_integration_tests

### ISSUE THREAD

**Issue by etam** [golemfactory/clay#4410]
## Rationale
Testing for cases like in #4399 require starting and stopping one of the nodes.
The test `lenient_verification` could be also improved by this.

## Description
`node_integration_tests` should have starting and stopping of nodes as steps.

**Comment by shadeofblue** [comment]
@etam well, they do ... 

https://github.com/golemfactory/golem/blob/develop/scripts/node_integration_tests/playbooks/base.py#L396

https://github.com/golemfactory/golem/blob/develop/scripts/node_integration_tests/playbooks/base.py#L418

**Comment by etam** [comment]
I want to be able to start and stop them individually. And possibly, with option of not having them all started at beginning.
