### ISSUE TITLE
Typo in image in published blogpost

### ISSUE THREAD

**Issue by evandrix** [golemfactory/clay#4411]
~~COMPLIE~~ => COMPILE

image https://lh3.googleusercontent.com/ksVDr6MHb-4yeXwkjnix_8fuXUWKCrJZFRRmh__nCd13NhwcGFaiQIJB9X6DGXwELMb6KM41J_y0FrcEPP1jyLZQIXRMefCzsJxMhFu--lj5seC1HV5Ub8B_5JgtR7arvlu3SnnX

from blogpost https://blog.golemproject.net/gwasm-in-answers-some-things-you-need-to-know-about-our-latest-use-case

**Comment by jamuszyn** [comment]
My bad, thank you for catching this. Fixed.
