### ISSUE TITLE
error creating subtasks for gpu task on Linux; get_fragments      builtins.TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#4424]
## Description

**Golem Version**:     GOLEM Version: 0.20.0
ttps://buildbot.golem.network/buildbot/#/builders/2/builds/4749

**Golem-Messages version** (leave empty if unsure):   golem_messages Version: 3.7.0

**Electron version** (if used): 0.2.0

**OS** [e.g. Windows 10 Pro]: Linux 18.04

**Branch** (if launched from source): -

**Mainnet/Testnet**: mainnet

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:

After creating a GPU task on Linux 18.04 computations of task are not starting. Task is started but no subtask appears on a subtask list. 
Computations for GPU tasks are working on Windows and Mac OS

**Actual result**:

Task ends in timeout

## Steps To Reproduce
_Short description of steps to reproduce the behavior:_
e.g.
1. Launch the app on Linux
2. add a GPU task. Table GPU, resolution: 400x400, samples 30, 1 frame, 4 subtasks, task timeout 3  min, subtask timeout 3 min, bid 0.2
3. Go to task details, in GUI instead of list off subtasks appears `fetching subtasks information`
4.Check `golem.log` for error

## Logs and any additional context

```
2019-07-03 20:58:53 ERROR    twisted                             TypeError: 'NoneType' object is not iterable: Traceback (most recent call last):
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/autobahn/twisted/websocket.py", line 162, in _onMessage
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/autobahn/wamp/websocket.py", line 95, in onMessage
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/autobahn/wamp/protocol.py", line 895, in onMessage
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/txaio/tx.py", line 429, in as_future
    
--- <exception caught here> ---
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/rpc.py", line 921, in get_fragments
    
builtins.TypeError: 'NoneType' object is not iterable
```
logs on debug
[golem.log](https://github.com/golemfactory/golem/files/3356615/golem.log)

```
ederenn@GOLEM2008-VM-UBNT18:~$ golemcli --mainnet tasks dump 1ea9229c-9dc9-11e9-8336-bc2e959fc96d
{
    "preview": "/home/ederenn/.local/share/golem/default/mainnet/ComputerRes/1ea9229c-9dc9-11e9-8336-bc2e959fc96d/tmp/current_preview.PNG",
    "id": "1ea9229c-9dc9-11e9-8336-bc2e959fc96d",
    "name": "3Table_GPU",
    "type": "Blender_NVGPU",
    "subtasks_count": 1,
    "progress": 0.0,
    "options": {
        "frame_count": 1,
        "output_path": "/home/ederenn/Documents/3Table_GPU_2019-07-03_21-31-13",
        "format": "PNG",
        "resolution": [
            400,
            400
        ],
        "frames": "1",
        "compositing": false,
        "samples": 30
    },
    "time_started": 1562182274.0056787,
    "time_remaining": null,
    "last_updated": 1562182454.154949,
    "status": "Timeout",
    "estimated_cost": "10000000000000000",
    "estimated_fee": "112000000000000",
    "compute_on": "gpu",
    "timeout": "0:03:00",
    "subtask_timeout": "0:03:00",
    "bid": 0.2,
    "resources": [
        "/home/ederenn/Desktop/Table_GPU.blend"
    ],
    "concent_enabled": false,
    "cost": null,
    "fee": null
}
Completed in 0.00 s
```

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by kmazurek** [comment]
The binary used for this test was found to be from before the fix for this specific problem (#4402). Closing this issue.
