### ISSUE TITLE
Testnet not transporting tasks

### ISSUE THREAD

**Issue by cryptobench** [golemfactory/clay#4477]
## Description
Tasks are timing out on the testnet due to no provider being found.

**Golem Version**:
0.20.0

**Golem-Messages version** (leave empty if unsure):

**Electron version** (if used):
Latest from 0.20.0

**OS** [e.g. Windows 10 Pro]:
Ubuntu 18.04

**Branch** (if launched from source):

**Mainnet/Testnet**:
Testnet

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:
I don't know if this is the same thing for mainnet or not, but the testnet seems not be operating as it should. Tasks posted are just timing out due to no provider being found. I'm connected to 10 nodes, and in the last 5 and half minutes this task has been active for, only one node tried to handshake but failed. Nothing really happens and I assume the task are going to timeout. I've increased the bid to 10 GNT/h but doesn't change anything. 

The GUI in dev mode lists that there's currently 0 tasks on the network. Whether it can be trusted or not, i don't know.

This was the same thing @wp described on rocket chat he's also experiencing on the testnet while testing out wasm.

**Actual result**:

Task times out

_What is the observed behavior and/or result in this issue_

Task times out
**Screenshots**:

![image](https://user-images.githubusercontent.com/33448819/61250628-75fd3580-a758-11e9-81b5-f92c6819885d.png)
![image](https://user-images.githubusercontent.com/33448819/61250662-92996d80-a758-11e9-8a06-8e2ec114ba6c.png)

_If applicable, add screenshots to help explain your problem._

## Steps To Reproduce
_Short description of steps to reproduce the behavior:_

1) Launch Testnet 0.20.0
2) Submit a task to the network
3) Wait for Timeout

## Expected behavior
_(What is the expected behavior and/or result in this scenario)_

1) Launch Testnet
2) Submit task to the network
3) Receive result back

## Logs and any additional context
_(Any additional information that could help to resolve the issue, which systems were checked to reproduce the issue)_

[logs.zip](https://github.com/golemfactory/golem/files/3394274/logs.zip)

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by kubkon** [comment]
This might be related to an issue originally submitted by @wp31: golemfactory/g-flite#11.

**Comment by cryptobench** [comment]
@kubkon 
All ports are opened and fully functioning. Feel free to query 5.103.154.168 for port 40105, 40106, 3294 and RPC 61010. 

```
golemgrid@golemgrid:~/.local/share/golem/default/rinkeby$ sudo golemcli --port=61010 network status
[sudo] password for golemgrid: 
Port(s) 40105: open, 40106: open, 3294: open. Connected
```

Btw, this is a blender task i've submitted with the following dict:
```
blender_dict = {
    "name": "Golem Task",
    "type": "Blender",
    "subtasks_count": 2,
    "options": {
        "frame_count": 1,
        "output_path": "output/",
        "format": "PNG",
        "resolution": [
            400,
            400
        ],
        "frames": "1",
        
    },
    "timeout": "00:60:00",
    "subtask_timeout": "00:30:00",
    "bid": 10.0,
    "resources": [
        "bmw27_cpu.blend"
    ]
}
```

**Comment by cryptobench** [comment]
Update: Task timed out. All subtasks status are `Not started`

**Comment by wp31** [comment]
Yes, same problem here.

**Comment by cryptobench** [comment]
Just launched 0.20.1 and I don't know if a fix has been made for this issue or not, but now 1 of the 2 subtasks has been sent out to a peer for computation. Gonna monitor if it works or not. So far it's a good start.

**Comment by cryptobench** [comment]
Task finished now after 4 minutes compared to the timeout of 1 hour in previous 0.20.0 version.

**Comment by kubkon** [comment]
So, so far so good @cryptobench ? @wp31 could you apply the patch as well and check if it fixes your timeout issues as well?

**Comment by cryptobench** [comment]
Seems to be fixed. Closing issue for now.
