### ISSUE TITLE
`ValueError: invalid literal for int() with base 10: 'True'` while loading app_cfg.ini

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/clay#4478]
## Description

**Golem Version**: `0.20.0+dev9.g13fafea`
**OS** [e.g. Windows 10 Pro]: `Ubuntu 18.04`
**Branch** (if launched from source): `b0.20`
**Mainnet/Testnet**: mainnet
**Description of the issue**:

```
'Reading config from file /home/blue/hyperg-test/mainnet/app_cfg.ini' ... failed with an exception
Traceback (most recent call last):
  File "/home/blue/PycharmProjects/golem/golem/core/simpleconfig.py", line 125, in __init__
    self.__read_options(cfg)
  File "/home/blue/PycharmProjects/golem/golem/core/simpleconfig.py", line 194, in __read_options
    prop.set_value_from_str(self.__read_option(cfg, prop))
  File "/home/blue/PycharmProjects/golem/golem/core/simpleconfig.py", line 48, in set_value_from_str
    value_type = self._value_type(val)
ValueError: invalid literal for int() with base 10: 'True'
```

## Steps To Reproduce
1. Launch a brand-new instance of Golem on mainnet directly from shell (using `golemapp.py`)
2. Have it act as a provider?
3. Stop Golem, Start Golem

## Expected behavior
No error

**Comment by etam** [comment]
Could not reproduce. I tried both on current b0.20 and 13fafea. Got more tips?

**Comment by shadeofblue** [comment]
@ederenn @ZmijaWA maybe a datadir that reproduces this issue could be provided to @etam ?

**Comment by ederenn** [comment]
couldn't reproduce on b0.21.0. closing for now

**Comment by etam** [comment]
Got it!
```
enable talkback = False
enable monitor = True
```
causes this error and is changed into
```
enable talkback = 0
enable monitor = 1
```

**Comment by etam** [comment]
Steps to reproduce:
1. start golem with fresh, clear datadir
2. accept terms via rpc (cli or gui)
3. restart golem
