### ISSUE TITLE
Memory usage issue (possibly due to Hyper V)

### ISSUE THREAD

**Issue by vincenttaglia** [golemfactory/clay#4479]
## Description

**Golem Version**: 0.20.0

**Golem-Messages version** (leave empty if unsure):

**Electron version** (if used):

**OS** [e.g. Windows 10 Pro]: Windows 10

**Branch** (if launched from source):

**Mainnet/Testnet**: Mainnet

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P1 label is set  for Severity-Critical/Effort-hard_

**Description of the issue**:

A driver used 25GB of memory even when Golem wasn't in use. First, I used poolmon to pinpoint the driver using so much RAM, but it wasn't listed. Then, I used Windows Assessment Console to run a memory test. It showed 25GB under "Driver Non-Paged Allocations" and further under "DriverLockedSystemPages." However, when listing the driver, WAC displays "Unknown." Right before I was about to reinstall Windows, I realized I downloaded Golem shortly before I had these issues. After uninstalling and restarting, everything is back to normal.

Since no one else is reporting anything like this, I think it might have to do with my new Zen 2 CPU. There have been a good number of problems with the recent Zen 2 launch. My specs are as follows:

Ryzen R9 3900X
ROG Strix X570-F
Radeon 5700 XT Anniversary Edition
32GB DDR4 3600 (4x8GB)
HP EX950 M.2 NVMe SSD

This may be hard to reproduce, and it may not even be Golem, but Hyper V, but I thought I would write this report anyway.

**Screenshots**:

![Memtest](https://user-images.githubusercontent.com/15239196/61286433-71e90c00-a788-11e9-9a37-00bbafb59a5b.PNG)

## Steps To Reproduce
_Short description of steps to reproduce the behavior:_
e.g.
1. Install on a system with Zen 2 or R9 3900X
2. Restart the system

## Expected behavior
To allocate no RAM while not running.

**Comment by blaine614** [comment]
Same issue. Had to kill HyperV processes to get my RAM back after PC startup :(
Update:
Go into hyper-v and update the max amount of ram allowed to be used. This fixed it for me.
