### ISSUE TITLE
Adapt HyperdriveClient to simple-transfer error reporting

### ISSUE THREAD

**Issue by kmazurek** [golemfactory/clay#4481]
## Rationale
With the release of Golem 0.20, [hyperg](https://github.com/golemfactory/golem-hyperdrive) was replaced with [simple-transfer](https://github.com/golemfactory/simple-transfer). While the API for both is identical, `simple-transfer` has changed the way errors are reported. Golem's `HyperdriveClient` needs to be adapted to handle these errors correctly.

### Technical specification
Generally, `simple-transfer` reports errors back to the client  using the appropriate HTTP status codes. This means that for general failures a `500 Internal Server Error` will be returned. Similarly, for invalid requests the server will respond with a `400 Bad Request` status.

In particular, when getting a non-existent resource (via `/api/download` command), `simple-transfer` will return the HTTP status code 500 in a fail-fast manner. This is in contrast with the previous implementation which would hang indefinitely (or until timeout is reached) in such a situation.

#### Which application modules will be updated?
`HyperdriveClient`, `HyperdriveAsyncClient` (`golem/network/hyperdrive/client.py`)

#### Additional tests
Hyperdrive client tests (`tests/golem/network/hyperdrive/test_hyperdrive_client.py`) will need to be updated to include more specific error cases.

**Comment by shadeofblue** [comment]
irrelevant
