### ISSUE TITLE
Provider usage reporting for gWASM subtasks (GR-183)

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/clay#4526]
## Description

US. As a Golem requestor I need to get usage  report for every subtask completed in order to calculate payment and evaluate provider according to my market strategy.

It includes change in RCT message. It can be extra data. (possibly it should be a separate field?)

As soon as a subtask verification is finished, usages of providers who passed verification should be reported to the market strategy module.

AC. PR sent to review.

**Comment by etam** [comment]
What if provider is lying about resources usage?

**Comment by Wiezzel** [comment]
@etam AFAIR it is covered in the Pay-as-you-Golem document.

**Comment by etam** [comment]
@Wiezzel where is this document?

**Comment by Wiezzel** [comment]
@etam Can't find the link now. Ask the R&D team.
