### ISSUE TITLE
Remove Twisted dependencies from brass marketplace

### ISSUE THREAD

**Issue by mplebanski** [golemfactory/clay#4539]
## Rationale
To progress with usage marketplace for gWASM we need clearly defined abstraction of what market is in golem. Currently OfferPool class relies heavily on Twisted and it increases new implementations complexity.

### Functional specification
* What are the components of the required feature?

Modified OfferPool class.

* What is the designed behavior of those components?

OfferPool class no longer depends on Twisted framework.

* What are the failure modes and how are they supposed to be handled?

- n/a

### User Interface

* None.

### Technical specification

* Refactoring.

## Dependencies
* None.

#### Base test process
** Full Test (full set of tests for the whole application - in case of more extensive application updates, refactoring etc)

### Possible regressions
* is there any functionality that is likely to experience regressions?

Yes, offer choice is crucial. Bug in here could break tasks exchange. 

* are there any existing application components that should be tested more thoroughly?

Golem tasks exchange.

### Development
* [x] Feature implemented
* [x] Feature unit/integration tests implemented

### Dev QA
* [x] Basic tests by the developer pass
* [x] Unit tests pass
* [ ] Golem integration tests pass
* [ ] Concent integration tests pass
* [ ] Concent acceptance tests pass

### QA team
* [ ] Base scenario passes
* [ ] Additional test 1 passes... 
* [ ] ... 

## Issues encountered during QA
_When adding an issue here, please update testing scenarios and QA progress above_
* [ ] link to issue... 
* [ ] ...

**Comment by mbenke** [comment]
The failing integration tests are the same as one commit  before it on develop; cf https://buildbot.golem.network/buildbot/#/builders/15/builds/841

**Comment by mplebanski** [comment]
We decided that QA process will be done as a part of the next release, therefore leaving this PR to develop not touched by the QA team.
