### ISSUE TITLE
Check testing with frames

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#454]
Are we testing a small part of each frame or just the first frame? There are some reported problem with testing task with 300 frames (and not with 100). How it should be done properly? Maybe we should test the first one and the last one?

**Comment by banasiakadam60** [comment]
From gdb:
`Unhandled error in Deferred:`
`Traceback (most recent call last):`
`File "/home/adam/Repo/golem/golem/client.py", line 555, in __do_work`
`self.p2pservice.ping_peers(self.config_desc.pings_interval)`
`File "/home/adam/Repo/golem/gnr/gnrapplicationlogic.py", line 51, in check_network_state`
`self.remote_client.check_network_state()`
`File "/home/adam/Repo/golem/golem/rpc/service.py", line 144, in wrapper`
`return rpc.call(name, False, *args, **kwargs)`
`File "/home/adam/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1274, in unwindGenerator`
`return _inlineCallbacks(None, gen, Deferred())`
`--- <exception caught here> ---`
`File "/home/adam/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks`
`result = g.send(result)`
`File "/home/adam/Repo/golem/golem/rpc/service.py", line 163, in call`
`session = self.get_session()`
`File "/home/adam/Repo/golem/golem/rpc/service.py", line 182, in get_session
    .format(self.rpc_address))`
`golem.rpc.exceptions.RPCSessionException: RPC: no session established with ws://127.0.0.1:49408`
`WARNING - golem.task.taskserver - Starting session for 3601923d6ff99410c82a7290163c441b03963bf066f56877958b9c519b8f8fff5880416bfdf5a90254475faea22d75f9f50b6f427b2a19ed6b4589ea8cff2205 impossible`
`WARNING - golem.task.taskserver - Starting session for 3601923d6ff99410c82a7290163c441b03963bf066f56877958b9c519b8f8fff5880416bfdf5a90254475faea22d75f9f50b6f427b2a19ed6b4589ea8cff2205 impossible`
`WARNING - golem.task.taskserver - Starting session for 3601923d6ff99410c82a7290163c441b03963bf066f56877958b9c519b8f8fff5880416bfdf5a90254475faea22d75f9f50b6f427b2a19ed6b4589ea8cff2205 impossible`
`[Thread 0x7fffcbfff700 (LWP 11981) exited]`
`[Thread 0x7fffba73f700 (LWP 17375) exited]`
`[Thread 0x7fffd9fc2700 (LWP 17157) exited]`
`[Thread 0x7fffdc20a700 (LWP 11642) exited]`
`[Thread 0x7fffd8f72700 (LWP 11651) exited]`
`[Thread 0x7ffff7f0c700 (LWP 11650) exited]`
`[Inferior 1 (process 11518) exited normally]`
`(gdb)`

After that (16% of computation) application just exited without any error message. I haven't found any message also in log files

**Comment by badb** [comment]
Was it on package version or develop version? Can you send us the full log?

**Comment by banasiakadam60** [comment]
Develop version. I don't have this logs anymore (unfortunately I've removed it). If you want I can reproduce it and send them tomorrow morning.

**Comment by badb** [comment]
Yep, please try to reproduce it, because we haven't seen recently.

**Comment by banasiakadam60** [comment]
I've uploaded logs on Google Drive: golem_AB_2016-07-21.7z

**Comment by magdasta** [comment]
Testing is fine, the problem is probably using too much RAM for preview when the number of frames is big and the resolution is high.
