### ISSUE TITLE
blocking nodes is not working

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#4543]
## Description

**Golem Version**: 0.20.1+dev294.gffa862e

**Golem-Messages version** (leave empty if unsure):3.9.0

**Electron version** (if used): 0.2.1

**OS** [e.g. Windows 10 Pro]:Mac OS

**Branch** (if launched from source): develop, develop based branches

**Mainnet/Testnet**: mainnet

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:

It is not possible to block node from GUI by clicking "block node" button in subtask details.
**Actual result**:

Nothing happens after clicking "block" button, no message in logs about blocking node.

**Screenshots**:

<img width="476" alt="Screen Shot 2019-07-25 at 14 24 39" src="https://user-images.githubusercontent.com/32061891/61874438-abd4b380-aee8-11e9-96ac-1b24fa0c3e30.png">

## Steps To Reproduce
_Short description of steps to reproduce the behavior:_
e.g.
1. Launch Golem, start a short task with at least two subtasks.
2. Wait for task to finish, go to task details.
3. Unfold subtask details
4. Click locker to block selected node
5. Modal appears "Are you sure you want to block a node", click "Block"
6. Nothing happens
7. Check the logs

## Expected behavior
Chosen node should be blocked and saved on deny list

## Logs and any additional context
-

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by etam** [comment]
@mdtanrikulu I think it's a problem on electron side. The button seems to just do nothing and RPC request is not even sent.

I tested golem b0.20 (2f6025e9b) and electron b0.20.1 (3f1be0565)

**Comment by mdtanrikulu** [comment]
@etam Thanks for informing. It was on electron side, so I made a fix PR.
