### ISSUE TITLE
after all subtasks were assigned, numbers of work offers is constantly rising

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#4624]
## Description

**Golem Version**: 0.20.1+dev89.gb105bd7

**Golem-Messages version** (leave empty if unsure): 3.7.0

**Electron version** (if used):0.2.2-RCv1

**OS** [e.g. Windows 10 Pro]: Linux

**Branch** (if launched from source): 0.20.1 based

**Mainnet/Testnet**: mainnet

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:

After creating a task and assigning all subtasks to providing nodes Golem receives raising number of work offers.Task Helicopter 400x400, 10 frames, 30 subtasks has been computed in 4 min. Final number of received work offers is around 814.
`INFO     [golem.task.taskrequestorstats      ] Received work offers: 814`

**Actual result**:

Possible delay in electron

_If applicable, add screenshots to help explain your problem._

## Steps To Reproduce
_Short description of steps to reproduce the behavior:_
e.g.
1. Launch the Golem
2. Start a task Helicopter, 400x400, 10 frames, 30 samples, 30 subtasks, 30 min for subtask, 10 min for a task, bid 0.2
3. wait for task to finish
4. Check  golem.log for the latest work offer number for this task
## Expected behaviour
_(What is the expected behavior and/or result in this scenario)_

## Logs and any additional context

[golem.log](https://github.com/golemfactory/golem/files/3516883/golem.log)

**Comment by shadeofblue** [comment]
hmm... why exactly this would be an issue? @ederenn

**Comment by ederenn** [comment]
seems like it is slowing down accepting proper offers
