### ISSUE TITLE
Golemcli tasks abort TaskID - not working

### ISSUE THREAD

**Issue by cryptobench** [golemfactory/clay#4673]
## Description
Trying to abort a task using the CLI results in an error.
**Golem Version**:
0.20.2
**Golem-Messages version** (leave empty if unsure):

**Electron version** (if used):
latest
**OS** [e.g. Windows 10 Pro]:
Mac OS
**Branch** (if launched from source):

**Mainnet/Testnet**:
Testnet
**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:
Trying to abort a task that is currently running using `golemcli tasks abort TaskID` results in an error saying `ERROR [golemcli] wamp.error.runtime_error: wamp.error.runtime_error`

**Screenshots**:
![image](https://user-images.githubusercontent.com/33448819/64187942-c13ae700-ce71-11e9-8dc9-b4f565593dff.png)

_If applicable, add screenshots to help explain your problem._

## Steps To Reproduce
1. Launch task
2. Open terminal and abort task using `golemcli tasks abort TaskID`
3. Observe error.

## Expected behavior
Golem cancels the task.

## Logs and any additional context
[Golemlogs.zip](https://github.com/golemfactory/golem/files/3570298/Golemlogs.zip)

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by shadeofblue** [comment]
@cryptobench what kind of a task was that?

**Comment by cryptobench** [comment]
@shadeofblue Just wasm.

**Comment by shadeofblue** [comment]
@cryptobench thanks

**Comment by mbenke** [comment]
This may be the reason: https://github.com/golemfactory/golem/blob/0.20.2/apps/wasm/task.py#L424

```
def abort(self):
        raise NotImplementedError()
```

**Comment by cryptobench** [comment]
Definitely looks and sounds like it, haha!

**Comment by jiivan** [comment]
> This may be the reason: https://github.com/golemfactory/golem/blob/0.20.2/apps/wasm/task.py#L424
> 
> ```
> def abort(self):
>         raise NotImplementedError()
> ```

IMHO it would be nice to handle this gracefully in CLI. I.e. to:

1. Handle not `NotImplemented` error as a special case
1. Handle all other errors with a more readable way

**Comment by mplebanski** [comment]
An actual fix for that is simply not overriding `abort`. There is more logic to aborting to be found in TaskServer and `abort` at task level is a simple hook that can e.g. do nothing. The problem here is that is raises an exception insteading doing nothing...
