### ISSUE TITLE
wasm creating incorrect amount of subtasks

### ISSUE THREAD

**Issue by cryptobench** [golemfactory/clay#4678]
## Description
Creating a wasm task with x subtasks will result in the gui creating not the requested amount of subtasks, but an incorrect number.

**Golem Version**:
0.20.2
**Golem-Messages version** (leave empty if unsure):

**Electron version** (if used):
Latest with 0.20.2 release
**OS** [e.g. Windows 10 Pro]:
Mac OS
**Branch** (if launched from source):

**Mainnet/Testnet**:
Testnet
**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:
Creating a task with 6 subtasks will result in the GUI/CLI reporting 10 subtasks instead.

_What is the observed behavior and/or result in this issue_
Incorrect amount of subtasks created.
**Screenshots**:
[Video](https://streamable.com/aqwar)

## Steps To Reproduce
1. Launch wasm task with x subtasks
2. Observe incorrect amount.

## Expected behavior
Create the same amount of subtasks as requested.

## Logs and any additional context
[wasmerror.zip](https://github.com/golemfactory/golem/files/3574293/wasmerror.zip)
Task ID = 60cc89b0-cf06-11e9-95ed-46cb63f127ae
Task creation log also reports 10 subtasks created.

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by cryptobench** [comment]
@mplebanski explained to me on rocket chat that it's because 

> added verification by redundancy

I didn't know this was intended. Closing the issue, although for UX I don't think it should be shown, as it's confusing for the requestor and one might wonder if they pay extra for that.

**Comment by mplebanski** [comment]
Reopening until internal discussion finishes.

**Comment by mplebanski** [comment]
Fixed.
