### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by chfast** [golemfactory/clay#47]
Build servers:
- [Travis CI](https://travis-ci.com/plans): easy config, old Python packages causes some build failures. **DISABLED**
- [CircleCI](https://circleci.com/pricing): super easy config, works for free :+1: 
- [AppVeyor](http://www.appveyor.com/pricing): price from $29/m, Windows!

Code Coverage / Analysis:
- https://coveralls.io/
- https://codeclimate.com/pricing
- https://codecov.io :+1:

**Comment by badb** [comment]
Is this one finished or are we planning to add something more here?

**Comment by chfast** [comment]
We are planning to add something more. Windows builds.
