### ISSUE TITLE
ERROR: Failed downloading nvidia-container-runtime packages list.

### ISSUE THREAD

**Issue by arminmacx** [golemfactory/clay#4729]
im trying to install golem on fresh ubuntu 19.04 but the installer script gave me this error ERROR: Failed downloading nvidia-container-runtime packages list.
and i cant bypass it
my system spec :
core i5 4570
32gb ram 
128 ssd
gt640 2gb gpu

**Comment by freespirit** [comment]
I receive a similar error:
```
DEBUG: Downloading https://nvidia.github.io/nvidia-docker/ubuntu19.04/amd64/Packages as file /tmp/nvidia_docker_packages
```

The url in it leads to a page with the following error message:
> Unsupported distribution! Check https://nvidia.github.io/nvidia-docker

Following the link in the message I can see that there is no `Ubuntu 19.04` repository configuration. It looks like the installer script doesn't work at all on `19.04`.

**Comment by GPaso** [comment]
Hi!

Same error here:
ERROR: Failed downloading nvidia-container-runtime packages list.

I tried to install Golem from the script provided on this web page:
https://golem.network/download/brass-beta/ubuntu/

System specs
OS: Linux Mint 19.3 (base Ubuntu 18.04)
CPU: i7-3520M
GPU: GT 635M
