### ISSUE TITLE
one node disconnecting with others

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#4737]
## Description

**Golem Version**:  0.20.2+dev521.g091078f

**Golem-Messages version** (leave empty if unsure): 3.11.0

**Electron version** (if used): 0.2.2

**OS** [e.g. Windows 10 Pro]: Linux 18.04

**Branch** (if launched from source): based on b.021

**Mainnet/Testnet**: mainnet

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:

6 nodes were connected with each other. During the day one (node: oncoming storm) was running stable, no restarts, others had been restarted (vv win, vv lin, maczmija, win zmija).
At one point all nodes were running at the same time. Ooncoming storm lost connection with two of them (linmacz win zmija). Rest of the nodes (vv win, vv lin) were connected still with those two and oncoming storm. 

**Actual result**:

Loosing connection with some of the nodes

## Logs and any additional context

oncoming storm: 
[golem (2).log](https://github.com/golemfactory/golem/files/3617363/golem.2.log)

vm linux: 
[golem (3).log](https://github.com/golemfactory/golem/files/3617366/golem.3.log)

vm win: 
[golem (4).log](https://github.com/golemfactory/golem/files/3617381/golem.4.log)

vm mac: 
[golem (5).log](https://github.com/golemfactory/golem/files/3617383/golem.5.log)

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by shadeofblue** [comment]
not enough info here... @ederenn
