### ISSUE TITLE
User manual

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#474]
Options for delivery:
1. GitHub wiki (not git access, no PRs).
2. GitHub pages -- git repo with Markdown + Jekyll
3. Read the Docs  -- git repo, RST?, e.g. http://www.ethdocs.org/en/latest/

**Comment by chfast** [comment]
Let's create golem-docs repo with Markdown files in it. `Testing.md` document is a good start.

**Comment by badb** [comment]
Check this out: https://github.com/imapp-pl/golem-docs. Is this what you had in mind?

**Comment by chfast** [comment]
Yes. Should it be a public repo?

**Comment by badb** [comment]
It's private right now, but we'll open it when we're ready.

**Comment by magdasta** [comment]
screenshots:
![main_window](https://cloud.githubusercontent.com/assets/13525071/16989156/5a402b52-4e93-11e6-844e-4ad1fc3fd40c.png)
![main_window_tasks_added](https://cloud.githubusercontent.com/assets/13525071/16989157/5c61c954-4e93-11e6-8e1c-ae826bca5b27.png)
