### ISSUE TITLE
WASM tasks not finishing when run in parallel

### ISSUE THREAD

**Issue by mplebanski** [golemfactory/clay#4754]
## Description

**Golem Version**: b0.21

**Golem-Messages version** (leave empty if unsure): 3.11

**Electron version** (if used): n/a

**OS** [e.g. Windows 10 Pro]: Ubuntu 18.04LTS

**Branch** (if launched from source): b0.21^4dfc1d422ae4453dd2c62e9976657ea3f396ded9

**Mainnet/Testnet**: Both

**Description of the issue**:

**Actual result**:

WASM tasks are not finishing when run in parallel. This is happening because one provider is offering for two tasks and a race can occur in which he wins both auctions, thus will he receive two TTCs and drop one of them with OfferCancelled. This triggers `restart_subtask` call on requestor side, which was not implemented since GUI has no controls for WASM tasks. 

## Steps To Reproduce
1. Launch 1 Golem requestor and 2 Golem providers
1. Request two tasks with g-flite with at least 10 subtasks each
2. Observe progress

## Expected behavior

Tasks finishing smoothly.

## Proposed Solution?
Implement/ `restart_subtask` for WASM VbR virtual subtasks.

**Comment by ederenn** [comment]
checked with 10 subtasks running in parallel, tasks are finishing
