### ISSUE TITLE
 in second preview not restarted frame is shown in yellow instead of green after frame restart

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#4767]
## Description

**Golem Version**: INFO     0.20.2+dev538.g964b8e3

**Golem-Messages version** (leave empty if unsure): golem_messages Version: 3.11.0

**Electron version** (if used): 

**OS** [e.g. Windows 10 Pro]: any

**Branch** (if launched from source): -

**Mainnet/Testnet**: mainnet, testnet

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:

In restarted task, in second preview window, previously finished frames are displayed in yellow (computing), not green (finished). After task is finished sittuation remains

**Screenshots**:

frames of a finished task in second preview window:

![Screenshot from 2019-09-20 20-59-07](https://user-images.githubusercontent.com/32061891/65514238-37fd5a00-dedd-11e9-94de-095fa3367102.png)

-----------------
frames of a finished task created by restart in second preview window:

![Screenshot from 2019-09-20 21-01-48](https://user-images.githubusercontent.com/32061891/65514352-7430ba80-dedd-11e9-9296-044e2267c61f.png)

## Steps To Reproduce
_Short description of steps to reproduce the behavior:_
e.g.
1. Launch Golem
2. Start a short task with at least two frames e.g. small_shark, resolution from file, 2 frames, 4 subtasks, task timeout 10 min, subtask timeout 5 min, bid 0,1.
3.Wait for task to finish
4. Open second preview window and resubmit from there one frame.
5. Wait for task to finish.
6. Check second preview window. One frame is marked in green the other one in yellow.

## Expected behavior
Not restarted frames should be marked in green, frame is already finished, results rewritten from restarted task.

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by etam** [comment]
I sense a smell of #3173 here.

**Comment by etam** [comment]
It's even worse. `FrameRenderingTask` has a separate `FrameState`, which needs to be updated after creating new task with copied results.

Anyway, have I said anything about implicit state machines?

![or was it just my imagination?](https://i.redd.it/daaw7yoghql01.jpg)

**Comment by etam** [comment]
merged to b0.22
