### ISSUE TITLE
Please add usege information in log

### ISSUE THREAD

**Issue by ZmijaWA** [golemfactory/clay#4877]
## Rationale

To test and information proposes we need info in golem logs what is the value of usage for gWasm task/subtask. Cos this is the value that causes the token transfer. 
This request is to test the Usage Market with Redundancy for gWasm.

## Description
Read the info above...

### Functional specification

* What is the designed behavior of those components?  --- Just another record in logs

## Dependencies
_Enumerate other issues the completion of which is critical for this feature to be finished - or which block this feature from progressing with implementation_

### Blockers
_For any issues that block this issue, add links_
* ?
* ?

### New feature tests
Test Usage Market and check if it still works.
Check the log files for usage info 

### Possible regressions
* there should be none regression

### Development
* [ ] Feature implemented
* [ ] Feature unit/integration tests implemented

### Dev QA
* [ ] Basic tests by the developer pass
* [ ] Unit tests pass
* [ ] Golem integration tests pass
* [ ] Concent integration tests pass
* [ ] Concent acceptance tests pass

**Please choose the priority label for QA. It is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

### QA team
* [ ] Base scenario passes
* [ ] Additional test 1 passes... 
* [ ] ... 

## Issues encountered during QA
_When adding an issue here, please update testing scenarios and QA progress above_
* [ ] link to issue... 
* [ ] ...

**Comment by shadeofblue** [comment]
closed in https://github.com/golemfactory/golem/pull/4884
