### ISSUE TITLE
Can't start network - Key error: 'docker_cpu'; (deferred, self.BENCHMARK_TIMEOUT)

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#4879]
## Description

**Golem Version**:  GOLEM Version: 0.21.0+dev402.g4a05d87

**Golem-Messages version** (leave empty if unsure):  3.14.0

**Electron version** (if used): -

**OS** [e.g. Windows 10 Pro]: Linux 18.04

**Branch** (if launched from source): b0.22

**Mainnet/Testnet**: mainnet

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:

After starting an app Golem crashes with an error:
```CRITICAL [golem.client                       ] Can't start network. Giving up.
Traceback (most recent call last):
  File "/home/ederenn/projects/golem/golem/client.py", line 357, in start
    self.start_network()
  File "/home/ederenn/projects/golem/golem/client.py", line 409, in start_network
    task_finished_cb=self._task_finished_cb,
  File "/home/ederenn/projects/golem/golem/task/taskserver.py", line 197, in __init__
    sync_wait(deferred, self.BENCHMARK_TIMEOUT)
  File "/home/ederenn/projects/golem/golem/core/deferred.py", line 59, in sync_wait
    result.raiseException()
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/twisted/python/failure.py", line 488, in raiseException
    raise self.value.with_traceback(self.tb)
KeyError: 'docker_cpu'
```

## Steps To Reproduce

1. checkout branch b0.22
2. run Golem
3. see error

## Logs and any additional context

```
ederenn@GOLEM2008-UBNT18:~/projects/golem$ git log
commit 4a05d87bc3581a26614be68c89f619cecfc0adb1 (HEAD -> b0.22, origin/b0.22)
Merge: 689843d47 449bb332b
Author: Marek Franciszkiewicz <mfranciszkiewicz@users.noreply.github.com>
Date:   Tue Nov 12 20:31:46 2019 +0100

    Merge pull request #4868 from golemfactory/dump_docker_logs
    
    Dump docker logs

commit 449bb332b1d4b7ccc6597e01b55566e648a52a71
Merge: f57f12c6b 689843d47
Author: Marek Franciszkiewicz <marek@golem.network>
Date:   Tue Nov 12 19:44:40 2019 +0100

    Merge remote-tracking branch 'origin/b0.22' into dump_docker_logs

commit 689843d4745e66a027a5abdc0968acc3e3fd6d86
Author: Marek Franciszkiewicz <mfranciszkiewicz@users.noreply.github.com>
Date:   Tue Nov 12 19:39:04 2019 +0100

    Bump: Task API v0.24.0 (#4873)

commit 5f4d42e808a5e99b04c842385b4493a1fac89f64
:

```

when checked out on commit `18116ab6a56c4dcd0e2919b795f4017680df3aa6` it is possible to run Golem

log on debug, with latest run is on previous commit:
[golem (1).log](https://github.com/golemfactory/golem/files/3841704/golem.1.log)

**Comment by kmazurek** [comment]
https://github.com/golemfactory/golem/pull/4880 https://github.com/golemfactory/golem/pull/4881
