### ISSUE TITLE
Newly created Gwasm tasks are not appearing on top of a task list

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#4890]
## Description

**Golem Version**: 0.21.0+dev413.g4be8f69

**Golem-Messages version** (leave empty if unsure): 3.14.0

**Electron version** (if used): 0.21.0

**OS** [e.g. Windows 10 Pro]: Linux 18.04

**Branch** (if launched from source): b0.22

**Mainnet/Testnet**: mainnet

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:

When Gwasm task is created it appears in some random place at the task list in GUI, not at the top of the task list. Easy visible when there are numerous tasks on the task list.

**Screenshots**:

![Screenshot from 2019-11-14 17-25-07](https://user-images.githubusercontent.com/32061891/68878433-fd0eea00-0707-11ea-8e48-953397d0b46a.png)

![Screenshot from 2019-10-23 16-46-14](https://user-images.githubusercontent.com/32061891/68878560-3ba4a480-0708-11ea-9cb3-7ba8ad096a98.png)

## Steps To Reproduce
_Short description of steps to reproduce the behavior:_
e.g.
1. Launch Golem at b0.22 brach
2. Launch electron
3. On task list there should be already some tasks created previously
4. Run gflite task with any settings
5. Check position of a new task on a task list  

## Expected behavior
New task should appear at the top of the task list

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by kmazurek** [comment]
Closed by https://github.com/golemfactory/golem/pull/4920
