### ISSUE TITLE
on Mac Golem after closing the app stays in background processes 

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#4996]
## Description

**Golem Version**: GOLEM Version: 0.21.0+dev512.gb0e075

**Golem-Messages version** (leave empty if unsure): 3.14.1

**Electron version** (if used):

**OS** [e.g. Windows 10 Pro]: Mac OS

**Branch** (if launched from source): 

**Mainnet/Testnet**: mainnet

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:

Despite closing the app from the interface and from  the dock Golem stays in background processes. When checked in terminal after closing the app there still there are related to Golem processes running, some of them are multiplied. Regression comparing to 0.21.0

**Actual result**:

Seems Golem is not fully closed, that could cause problems with restarting the app. 

## Steps To Reproduce
_Short description of steps to reproduce the behavior:_
e.g.
1. Run Golem normally, connect with other nodes.
2. Close Golem from interface
3. Quit Golem from dock
4. Checki in terminal `ps aux | grep golem`

## Expected behavior
Golem should be shut down fully.

## Logs and any additional context

```
as-Mac:~ a$ ps aux | grep golem
a 506 0.7 0.0 4268024 776 s002 S+ 1:18PM 0:00.00 grep golem
as-Mac:~ a$ ps aux | grep golem
a 531 1.0 1.8 4839284 148128 ?? S 1:19PM 0:36.72 golemapp -r localhost:61000 --mainnet
a 622 0.0 0.1 4292640 9664 s001 S+ 1:22PM 0:00.03 golemcli -i
a 617 0.0 0.1 4303024 7816 ?? S 1:21PM 0:00.04 hyperg --port 3282 --rpc_host localhost --rpc_port 3292 --db /Users/a/Library/Application Support/golem/default/mainnet/hyperg --logfile /Users/a/Library/Application Support/golem/default/mainnet/logs/hyperg.log
a 544 0.0 1.1 4583712 92936 ?? S 1:19PM 0:10.56 /usr/local/Cellar/golem/0.21.0/bin/golemapp standalone _exec_worker --cbdir /Users/a/Library/Application Support/golem/default/mainnet/crossbar --node as-mac.local --worker worker001 --realm crossbar --personality crossbar.personality.Personality --klass crossbar.worker.router.RouterController --loglevel info --title Golem
a 539 0.0 1.5 4513048 126324 ?? S 1:19PM 0:02.64 /usr/local/Cellar/golem/0.21.0/bin/golemapp standalone _exec_worker --cbdir /Users/a/Library/Application Support/golem/default/mainnet/crossbar --node as-mac.local --worker worker001 --realm crossbar --personality crossbar.personality.Personality --klass crossbar.worker.router.RouterController --loglevel info --title Golem
a 528 0.0 1.5 4513048 126324 ?? S 1:18PM 0:02.95 golemapp -r localhost:61000 --mainnet
a 722 0.0 0.0 4258648 200 s002 U+ 2:04PM 0:00.00 grep golem
as-Mac:~ a$
```

below how it should look like, checked on 0.21.0 version
```
iMac-ederenn:~ ederenn$ ps aux | grep golem
ederenn          33928   0.0  0.0  2432804   1976 s004  S+    5:53PM   0:00.00 grep golem
iMac-ederenn:~ ederenn$ 

```

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by kmazurek** [comment]
This turned out to be an issue in Golem Electron, resolved in: https://github.com/golemfactory/golem-electron/commit/25cadc8770a75cbe681055f36e94855b5174ba40
