### ISSUE TITLE
Trading system prototype

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#5]
- [x] **First version** 
  Requestor broadcast his task with maximum price. All providers who can compute task for price lower than defined will be accepted. Final price equals to price offered by provider multiplied by computation time. 
- [ ] **Second version**
  Requestor broadcast his task with maximum price. For some time offers from providers are collected. Finally the set of best providers is chosen. Function for provider validation should be take price, performance and reputation as parameters. 
- [ ] **Third version:**
  Providers may try to cheat and declare too high performance and too high computation time. Therefore requester will try to predict computation time. Benchmark will be run on requester's computer to compute his performance and expected time. Based on this result requester will to predict computation time for each provider based on their performance. Provider will have to accept this time multiplied by declared price as a fixed remuneration for computation. For each subtasks there is defined timeout so there's no risk of computing a subtask forever.

**Comment by chfast** [comment]
@badb are you working on that?

**Comment by badb** [comment]
No. We have a first prototype version, but it should further developed. First we must change current simple version to fit payment system model, then we may make further experiments.

**Comment by badb** [comment]
I'm closing this issue for know. We will create a new one with updated description after we prepared task & transaction protocol description.
