### ISSUE TITLE
Display incoming payments

### ISSUE THREAD

**Issue by chfast** [golemfactory/clay#501]
The list of all cached incoming payments can be fetched from PaymentMonitor by [`get_incoming_payments()`](https://github.com/imapp-pl/golem/blob/6a5aa690e01f222419720ecfa9b8068ccbd072c0/golem/ethereum/paymentmonitor.py#L27).

Two solutions:
1. Display these payments in table, just like outgoing payments.
2. Try to match them with tasks and peers that own you.

Task list:
- [x] Decide the solution and implement it.
- [x] Fix disabled Incoming Payments table display in https://github.com/imapp-pl/golem/blob/6a5aa690e01f222419720ecfa9b8068ccbd072c0/gnr/customizers/paymentsdialogcustomizer.py#L30.
- [x] Reenable UI unit test in https://github.com/imapp-pl/golem/blob/6a5aa690e01f222419720ecfa9b8068ccbd072c0/tests/gnr/customizers/test_paymentsdialogcustomizer.py#L20.

**Comment by badb** [comment]
We use simple incomes version from  payment monitor without linking payment to task for Brass 0.3. We'll improve it later.

**Comment by chfast** [comment]
Closed by #503.
