### ISSUE TITLE
When task creation fails due to insufficient funds, task stays in 'Creating' state

### ISSUE THREAD

**Issue by kmazurek** [golemfactory/clay#5012]
## Description

**Golem Version**: 0.21.0+dev408.g4a05d87

**Golem-Messages version** (leave empty if unsure): 3.14.1

**Electron version** (if used):

**OS** [e.g. Windows 10 Pro]: Ubuntu 18.04.3 LTS

**Branch** (if launched from source): b0.22

**Mainnet/Testnet**: both mainnet and testnet

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:

When attempting to create a new task with not enough funds available, the task stays in `Creating` state.

## Steps To Reproduce
1. Launch the Golem app.
2. Try creating a new task for which there is not enough funds available (e.g. set the `bid` field high enough). This was observed when creating a task from the CLI (command `tasks create <path_to_your_task_definition>).
3. Wait for the task creation to fail (i.e. for insufficient funds error to be reported).
4. Check the status of the requested tasks (e.g. call `tasks show`). The status for the attempted task will be reported as `Creating`.

## Expected behavior
An error status should be reported, e.g. `Error creating`.

**Comment by kmazurek** [comment]
One additional side effect is that this effectively blocks graceful shutdown, since the task stuck in `Creating` is considered to be in progress.

**Comment by etam** [comment]
fix merged to b0.23
