### ISSUE TITLE
in task api tasks delete doesn't works for finished tasks

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#5020]
## Description

**Golem Version**: GOLEM Version: 0.21.0+dev531.g329e2ba 

**Golem-Messages version** (leave empty if unsure): 3.14.1

**Electron version** (if used): 

**OS** [e.g. Windows 10 Pro]: any

**Branch** (if launched from source):

**Mainnet/Testnet**: testnet 

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:

`tasks delete <task_id>` for task API tasks works only when the task is running. When task is finished it is not possible to remove it from the task list with `tasks delete`. When the task is finished delete works as abort. 

**Actual result**:

not possible to remove finished tasks from the task list

## Steps To Reproduce
_Short description of steps to reproduce the behavior:_
e.g.
1. Launch the app on testnet
2. Create a task API task
3. Wait for task to finish or timeout
4. Try to remove created task with `tasks delete <task_id>`

## Expected behavior
Task should be deleted

## Logs and any additional context

```
ederenn@GOLEM2008-UBNT18:~/Desktop$ golemcli tasks list
┌────────────────────────────────────────┬───────┬──────────────────┬────────────┬──────────────┐
│  id                                    │  ETA  │  subtasks_count  │  status    │  completion  │
├────────────────────────────────────────┼───────┼──────────────────┼────────────┼──────────────┤
│  fcf6b99a-1dc4-11ea-b8aa-1a83d0c4dce2  │       │                  │  Timeout   │              │
│  791db440-2326-11ea-8107-1a83d0c4dce2  │       │                  │  Finished  │              │
│  80de35b8-233a-11ea-ab81-1a83d0c4dce2  │       │                  │  Finished  │              │
│  dc94be1c-233b-11ea-bb6b-1a83d0c4dce2  │       │                  │  Finished  │              │
└────────────────────────────────────────┴───────┴──────────────────┴────────────┴──────────────┘
ederenn@GOLEM2008-UBNT18:~/Desktop$ golemcli tasks delete dc94be1c-233b-11ea-bb6b-1a83d0c4dce2 
ERROR [golemcli] wamp.error.runtime_error: Task not active, can not abort. task_id=dc94be1c-233b-11ea-bb6b-1a83d0c4dce2
ederenn@GOLEM2008-UBNT18:~/Desktop$ 
```

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by jiivan** [comment]
fixed in #5021
