### ISSUE TITLE
Golem does not support Ubuntu Eoan

### ISSUE THREAD

**Issue by cr44d** [golemfactory/clay#5051]
## Description

**Golem Version**: N/A

**Golem-Messages version** (leave empty if unsure):

**Electron version**: N/A

**OS** [e.g. Windows 10 Pro]: Ubuntu 19.10 Eoan Ermine

**Branch** (if launched from source):

**Mainnet/Testnet**: N/A

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:

_User is unable to install Golem on Ubuntu Eoan (see logs for details)_

**Actual result**:

_See logs_

## Steps To Reproduce
1. Download [https://raw.githubusercontent.com/golemfactory/golem/0.21.0/Installer/Installer_Linux/install.sh](install.sh) from [https://golem.network/download/brass-beta/ubuntu/]
2. Run `chmod +x install.sh && ./install.sh`

## Expected behavior
_Golem is installed_

## Logs and any additional context
```
root@osboxes:/home/osboxes/Downloads# chmod +x install.sh && ./install.sh
Golem Linux Installer version 0.1.0
 ⬝ Downloading manifest ✓
 ⬝ Downloading install script for extension 'gvisor' ✓
 ⬝ Downloading runsc ✓
 ⬝ Downloading runsc hash ✓
 ⬝ Checking runsc hash ✓
 ⬝ Installing runsc ✓
 ⬝ Downloading install script for extension 'linuxmint' ✓
 ⬝ Downloading install script for extension 'nvidia' ✓
WARNING: Not supported: nvidia-container-runtime: incompatible device
 ⬝ Removing obsolete docker ✓
 ⬝ Installing docker dependencies ✓
 ⬝ Adding docker repository GPG key ✓
 ⬝ Adding docker repository ✕

Command returned errors:
------------------------
Warning: apt-key output should not be parsed (stdout is not a terminal)
E: The repository 'https://download.docker.com/linux/ubuntu eoan Release' does not have a Release file.

ERROR: Failed adding docker repository.
```
## Proposed Solution?
_Wait for `docker.org` to support this Ubuntu version._

**Comment by flolu** [comment]
Got a similar error:
```
Command returned errors:
------------------------
Warning: apt-key output should not be parsed (stdout is not a terminal)
E: The repository 'https://download.docker.com/linux/ubuntu eoan Release' does not have a Release file.
E: The repository 'http://ppa.launchpad.net/eosrei/fonts/ubuntu eoan Release' does not have a Release file.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://brave-browser-apt-release.s3.brave.com stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A8580BDC82D3DC6C

ERROR: Failed adding docker repository.
```
