### ISSUE TITLE
Golem launches Task API requestor app on start, when task has already timed out

### ISSUE THREAD

**Issue by ktomala** [golemfactory/clay#5066]
## Description

**Golem Version**: b0.22

**Golem-Messages version** (leave empty if unsure):

**Electron version** (if used):

**OS** [e.g. Windows 10 Pro]: Ubuntu

**Branch** (if launched from source): b0.22

**Mainnet/Testnet**: testnet

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:

When Golem is started, it launches Task API Requestor App, even though it probably shouldn't.  

**Actual result**:

Golem shouldn't launch the Task API requestor app if task was already timed out.

**Screenshots**:

_If applicable, add screenshots to help explain your problem._

## Steps To Reproduce
1. Launch Golem
2. Create a Task API task with task timeout
3. Let it run for a while and allow providers to start computing
4. Close Golem with requestor app
5. Wait until task times out
6. Start Golem again
7. Golem will show in the logs that task timed out, but will start Requestor App anyway

## Expected behavior

Do not run Requestor App

## Logs and any additional context

```
INFO     [golem.envs.docker.cpu              ] Prerequisites installed. 
INFO     [golem.task.requestedtaskmanager    ] Got service for app='68c6fcd43b6d6efb3eb84a40fbd1e743', service=<golem.task.task_api.EnvironmentTaskApiService object at 0x7fdfb04d1ac8> 
INFO     [golem.envs.docker.cpu              ] Preparing runtime... 
INFO [hyperg::server] Connection from: 18.185.104.14:40312
INFO [hyperg::connection] opened connection [0] [18.185.104.14:40312]
INFO [hyperg::connection] closed connection [0] [18.185.104.14:40312]
INFO     [golem.network.p2p.peersession      ] Starting peer session. address=18.185.104.14:34884 
WARNING  [golem.envs.docker.cpu              ] Container creation warning: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. 
INFO     [golem.envs.docker.cpu              ] Runtime prepared. 
INFO     [golem.envs.wrappers.dump_logs      ] Dumping runtime output to PosixPath('/home/wolverine/.local/share/golem/default/rinkeby/logs/docker_cpu/36459299f15d7ea4a8f512993cdbc0d2eefae0a499355e53f801c2a1480c3c2f_stdout.txt') 
INFO     [golem.envs.wrappers.dump_logs      ] Dumping runtime output to PosixPath('/home/wolverine/.local/share/golem/default/rinkeby/logs/docker_cpu/36459299f15d7ea4a8f512993cdbc0d2eefae0a499355e53f801c2a1480c3c2f_stderr.txt') 
INFO     [golem.envs.docker.cpu              ] Starting container '36459299f15d7ea4a8f512993cdbc0d2eefae0a499355e53f801c2a1480c3c2f'... 
INFO     [golem.envs.docker.cpu              ] Runtime started. 
INFO     [golem.task.requestedtaskmanager    ] app_client created for app_id='68c6fcd43b6d6efb3eb84a40fbd1e743', clients=<golem_task_api.client.RequestorAppClient object at 0x7fdfb0235b00> 
INFO     [golem.envs.docker.cpu              ] Runtime stopped. 
INFO     [golem.envs.docker.cpu              ] Cleaning up runtime... 
INFO     [golem.envs.docker.cpu              ] Removing container: '36459299f15d7ea4a8f512993cdbc0d2eefae0a499355e53f801c2a1480c3c2f' 
INFO     [golem.envs.docker.cpu              ] Runtime torn down. 
INFO     [golem.envs.docker.cpu              ] Runtime is no longer running. Stopping status update thread. 
INFO     [golem.network.p2p.peersession      ] Starting peer session. address=94.23.196.166:40102 
INFO     [golem.network.p2p.peersession      ] Starting peer session. address=94.23.57.58:40102 
ERROR    [asyncio                            ] Unclosed connection: Channel('172.17.0.4', 50005, ..., path=None) 
```

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by maaktweluit** [comment]
This is working as intended, the app is started to call `abort_task(task_id)`

**Comment by ktomala** [comment]
Ok, so we can close this. There's however there is also this error: "Unclosed connection"

**Comment by maaktweluit** [comment]
great!
this is already an issue: #5000 will add some labels :)
