### ISSUE TITLE
Broken customizer tests

### ISSUE THREAD

**Issue by chfast** [golemfactory/clay#508]
I cannot pass customizer tests locally. Problem with them is if they fail the Qt usually crashes and there is not error output.

Tests on CI crashes only from time to time:
https://circleci.com/gh/imapp-pl/golem/1874
https://circleci.com/gh/imapp-pl/golem/1853
https://circleci.com/gh/imapp-pl/golem/1865

The problematic commit is https://github.com/imapp-pl/golem/commit/b32661c4a617db6ed78bfc3345447d8efc29bd47 (found by git bisect).

Test command

```
python setup.py develop && py.test tests/gnr/customizers
```

**Comment by mfranciszkiewicz** [comment]
`py.test tests/gnr/customizers --ignore tests/gnr/customizers/test_identitydialogcustomizer.py` also results in a segfault, so it's the wrong commit. Anyway, I'm looking into resolving this issue.

**Comment by chfast** [comment]
Customizer tests are quite flaky. Some issues show up only if you run a series of them.
