### ISSUE TITLE
windows: can not install because too weak password for created user 

### ISSUE THREAD

**Issue by tworec** [golemfactory/clay#5081]
## Description
A friend of mine was trying to install Golem 0.22.0 on Windows machine bound to enterprise domain with password policy, and was denied because of to weak password for created user

**Golem Version**:
0.22.0

**Comment by tworec** [comment]
related to #4224

**Comment by Wiezzel** [comment]
A duplicate of #4224

**Comment by tworec** [comment]
duplicate
