### ISSUE TITLE
Golem has problem connecting to other nodes on b0.23

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#5125]
## Description

**Golem Version**: GOLEM Version: 0.22.1+dev104.g9a13476

**Golem-Messages version** (leave empty if unsure): 3.15.0

**Electron version** (if used): 

**OS** [e.g. Windows 10 Pro]: Ubuntu mainly but happens also on Windows

**Branch** (if launched from source):

**Mainnet/Testnet**: mainnet

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:

There are problems with connecting nodes on b0.23 branch. When connecting Linux node to other ones ucing `golemcli network connect <node id> <port>` in logs it appears node has started connection, but checked from cli and interface node is in fact disconnected. 

```
INFO     [golem.network.p2p.peersession      ] Starting peer session. address=10.30.10.183:40102 
INFO     [golem.network.p2p.peersession      ] Starting peer session. address=10.30.10.184:40102 
INFO     [golem.network.p2p.peersession      ] Starting peer session. address=10.30.10.184:50631 

```

```
>> network status
Port(s) 40102: open, 40103: open, 3282: open. Not connected to Golem Network, check seed parameters.
>> network status
```

Node connect to others after several tries or if connect command is called from the other side. E.g. from Windows to Linux or Mac to Linux.

**Actual result**:

Node could stay not connected to other nodes with same version in network.

## Steps To Reproduce
_Short description of steps to reproduce the behavior:_
e.g.
1. Launch at least 3 nodes, Golem version based on b0.23, one Linux, rest any combination from: Mac, Linux, Windows.
2.Try to connect Linux one from cli `golemcli network connect <node id> <port>` with chosen node.
3. Check from cli if nodes are connected `golemcli network status`
4. Check in interface if nodes are connected
5. Check in logs in connection was established

## Logs and any additional context

logs on debug:

Linux: 
[golem (14).log](https://github.com/golemfactory/golem/files/4307844/golem.14.log)

Windows:
[golem (15).log](https://github.com/golemfactory/golem/files/4307855/golem.15.log)

Linux2:
[golem.log](https://github.com/golemfactory/golem/files/4307858/golem.log)

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by etam** [comment]
Seems related: https://buildbot.golem.network/buildbot/#/builders/15/builds/978

**Comment by ederenn** [comment]
Another version of connecting problems:
cannot connect node to any other nodes in network
I cannot connect node 10.30.10.181 with anyone.
```
ederenn@GOLEM2008-UBNT18:~/projects/golem-electron$ golemcli network show
┌──────┬────────┬──────┬────────┐
│ ip │ port │ id │ name │
├──────┼────────┼──────┼────────┤
│ │ │ │ │
└──────┴────────┴──────┴────────┘
ederenn@GOLEM2008-UBNT18:~/projects/golem-electron$ golemcli network status
Port(s) 40102: open, 40103: open, 3282: open. Not conne
```


Also cannot connect to it from other nodes, when trying to connect to 181, in logs shows up message:
```
INFO     [golem.network.p2p.peersession      ] Starting peer session. address=10.30.10.181:40102
INFO     [golem.network.transport.session    ] Received disconnect message. reason=NoMoreMessages, address=10.30.10.181:40102
```

full log:
[golem (4).log](https://github.com/golemfactory/golem/files/4395381/golem.4.log)

 GOLEM Version: 0.22.1+dev123.gcfba2ab
messages Version: 3.15.0
Ubuntu 18.04
mainnet
run from source, branch `mwu/whitelist_dates`

previously on this branch node was run without any problems and similar situation happened on node on `b0.23`

**Comment by etam** [comment]
fix merged to b0.23
