### ISSUE TITLE
TypeError: send() missing 1 required positional argument: 'x'

### ISSUE THREAD

**Issue by Smayki** [golemfactory/clay#5167]
I'm currently working on a project that needs a traffic redirection, so I have an issue while executing a file ( coded with python3) and this is where the issue is located:

```
 def inject(self, src, dst, sport, dport, seq, ack):
    payload = self.selectors.get(src, PAYLOAD_FOX)
    p = IP(src=src, dst=dst) / TCP(sport=sport, dport=dport, seq=seq+1, ack=ack, flags="PA") / payload
    **self.socket.send(p)**
    print ("Shooting: %r" % p)
```

I'm realy getting frustrated. HELP!

**Comment by etam** [comment]
Hello, and welcome to the Golem project!
This place is not an open forum to ask about any programming problem you have. This is specifically to report issues with Golem software.
A better place to ask is for example at https://stackoverflow.com/questions
