### ISSUE TITLE
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/golem-messages/

### ISSUE THREAD

**Issue by nelsonmora48** [golemfactory/clay#5191]
## Description
I Get this error when try install golem from git sources after type:
pip3 install -r requirements.txt

This is the error:
"Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/golem-messages/"

**Golem Version**:
Latest

**Branch** (if launched from source):
develop

**Actual result**:

I Can't to complete the installation

**Comment by badb** [comment]
Hi, 

Can you please try to install with explicit --extra-index-url, ie. 
`pip3 install -r requirements.txt --extra-index-url https://builds.golem.network ` and see if that works?
