### ISSUE TITLE
Fully functional CLI

### ISSUE THREAD

**Issue by magdasta** [golemfactory/clay#548]
Would be useful for systems not supporting graphics / accessed remotely. Testers point that it's very important.

**Comment by badb** [comment]
-  Possible technologies: `cmd`? `click`?
- Interactive or deamon + stat commands? 
- We may want to change interface logic to general interface logic and use implemented rpc services for communication. 
- `gt` format for saving task should be changed into something that can be edited by user, eg. yaml.

**Comment by magdasta** [comment]
Project of supported commands: https://docs.google.com/document/d/1TMhwy18bacSdevxlN8QuN-8YW9MCNmhCPGvT_Ab5yfQ/edit?usp=sharing
