### ISSUE TITLE
Empty GUI windows

### ISSUE THREAD

**Issue by magdasta** [golemfactory/clay#567]
On some machines GUI loads only partially (windows are displayed with their names but no content is shown, however it is still possible to blindly interact with the content).
The problem was observed on Fedora 23 and Arch Linux. On Arch problem could have been solved by running Golem without root priviliges, but on Fedora this didn't help.

Reported by: 
nik.zantner (Arch): 
[nik_zantner.log.txt](https://github.com/imapp-pl/golem/files/418285/nik_zantner.log.txt)
[nik_zantner_golem_client.log.txt](https://github.com/imapp-pl/golem/files/418279/nik_zantner_golem_client.log.txt)
[nik_zantner_golem_gui.log.txt](https://github.com/imapp-pl/golem/files/418278/nik_zantner_golem_gui.log.txt), 

artur.stanek (Fedora 23):
[golem logs from Artur Stanek (kermitas).zip](https://github.com/imapp-pl/golem/files/418300/golem.logs.from.Artur.Stanek.kermitas.zip)
reinstalling / installing ibus didn't help

**Comment by badb** [comment]
There is no point in fixing this issue, because we're migrating to new GUI.
