### ISSUE TITLE
Golem payments interface + user interface

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#60]
Interface that should allow user to see past and future payments. 

What other methods should this interface make available? Should it allow to make payments before expected time? Should it allow to make see Ethereum account balance? Should it allow to send additional money to Eth account?

**Comment by globatum** [comment]
@badb just checking in to see if we bring this to a close.

**Comment by badb** [comment]
Further discussions about interface changes should be move to golem-design & golem-electron.
