### ISSUE TITLE
Make gossiping steps more often and use UTC time

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#625]

**Comment by paulperegud** [comment]
@badb Do you want to use UTC time on the wire or both on the wire and internally?

**Comment by badb** [comment]
Preferably both.

**Comment by paulperegud** [comment]
We are using timestamps with UTC on the wire for all messages for some time:
https://github.com/imapp-pl/golem/commit/61015575ffdba035f92704bd10fee81e552ff2f0#diff-e47df84b6400638b0e292bca6c49ef3aL175
