### ISSUE TITLE
Upnp support

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#63]
Add support for UPnP to Golem.  

Adding this option will eliminate the need to forward ports  by hand for some users. Port forwarding is very uncomfortable process or sometimes not even possible for some users. Having it partially automated will significantly improve UX. 

User should be able to choose if she/he wants this option or not. There should be additional flag in config file that would turn on/off this functionality.

We should check if there are any python libraries that support that. The most popular one in C (and used in all p2p application) is miniupnp.

**Comment by chfast** [comment]
1. We should have it as soon as possible if easy to integrate. It gives users a public port so they can be seeds.
2. It should not be optional. UPnP (and other similar technologies) are features of routers, so if turned on applications should use it.

**Comment by badb** [comment]
It will be useful, but some people don't trust upnp and may not want to use application that uses it. For example what if should they do if situation like this: https://bitcoin.org/en/alert/2015-10-12-upnp-vulnerability repeates?

**Comment by chfast** [comment]
The issue is about UPnP client implementation, not UPnP per se.
1. We can look for Python implementation, e.g. https://github.com/skatkov/upnp-client-lib.
2. We can check if the miniupnp issue has been fixed.
