### ISSUE TITLE
Subtask delegation

### ISSUE THREAD

**Issue by mfranciszkiewicz** [golemfactory/clay#638]
Organisations (companies, universities, data centers) should be able to create Golem subnetworks, capable of computing batches of subtasks.

**Comment by mfranciszkiewicz** [comment]
A draft on how it might be implemented:
- a **subnetwork** consists of **group leaders** and **group members**
- a **group member** is a node that:
  - was provided with priority list of `host:port` of group leaders and their common `pubkey` via config
  - uses the same `pubkey` as other group members
  - rejects nodes from outside the group
  - accepts tasks only from group leaders
  - maintains p2p connections with all group nodes
- a **group leader** is a node that:
  - was provided with priority list of `host:port` of group leaders via config
  - was provided with a whitelist of group members' `pubkey`s via config (own, lone `pubkey` by default)
  - is responsible for:
    - requesting batches of subtasks (proportional to the number of known group members) from their leaders or requestors
    - assigning subtasks to group members
    - collecting _information on_ computed results and forwarding it to requestors (i.e. result hashes)
  - maintains p2p connections with all group nodes
  - current leader replicates it's state among the failover leaders (if any)
  - monitors heartbeats of other leaders and takes over if necessary

Instead of manually specifying group leaders, an election could take place. At this stage of development, elections could be based on node capabilities, i.e. node being a supernode, then based on bandwidth, performance, etc, without structuring the network or taking network topology into account.

**Comment by mfranciszkiewicz** [comment]
Other known issues:
- batch subtask requests vs reputation
- batch subtask requests vs nested groups
- node's group reputation (whether and how it is calculated)

**Comment by maaktweluit** [comment]
@mfranciszkiewicz this seems solved by golem unlimited, can it be closed?
