### ISSUE TITLE
Revise Task interface

### ISSUE THREAD

**Issue by azawlocki** [golemfactory/clay#66]
- We have both computation_finished() and finished_computation() methods
- query_extra_data() should probably be changed to a better name
- Is there a difference between needs_computation() and get_tasks_left() != 0?

**Comment by badb** [comment]
Remember to check [wiki](https://github.com/imapp-pl/golem/wiki/Golem-Task)

1) `finished_computatation` is a question, `computation_finished` information. Do you have better ideas for names? 
2) Maybe `get_next_subtask`?
3) In current tasks there is no difference. We can imagine some scenarios where it may be a difference, but in most cases it should mean the same.

**Comment by azawlocki** [comment]
1) maybe `on_computation_finished`, since this is kind of a callback? Or `react_to_computation_finished`. Some general convention would be useful here.
2) sounds good
3) I see

**Comment by badb** [comment]
1) Personally I prefer `react_to_computation_finished` (convention with verb), but other proposition is also good.
