### ISSUE TITLE
Limit the number of saved task headers

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#665]
Especially don't save too many tasks from the same task requestor. The limit can be arbitrarily set or dynamically adjusted to the global number of tasks in the network. 

Which tasks should have priorities? 

- The oldest
- The ones with closest timeout

**Comment by Wolf480pl** [comment]
Do we want a limit per requestor public key? What if someone has many public keys?

**Comment by Wolf480pl** [comment]
As for priorities, I think it requires some consideration from security point of view.
I asked @paulperegud and he had some ideas, but he's not sure for which protocol version this is for.
@badb is it for gossip or broadcast?

**Comment by paulperegud** [comment]
This one is for broadcast. Please limit yourself to limiting the amount of tasks from single author.

**Comment by paulperegud** [comment]
This one is for broadcast. Please limit yourself to limiting the amount of tasks from single author.

**Comment by Wolf480pl** [comment]
@paulperegud which ones should I drop? oldest? newest? cheapest? random?

**Comment by badb** [comment]
I vote for removing the newest. Maybe @paulperegud has different idea, but this one should work well. If there are no more subtasks in some old tasks it's going to be removed from the list anyway, so there's a place for the new task to be added.

**Comment by Wolf480pl** [comment]
A task header doesn't even have a creation time, so I guess it'd be by receive time.

**Comment by Wolf480pl** [comment]
If we drop a task because we reached the limit, do we want to trigger the post-removal cooldown (the thing that prevents the task from being re-added too quickly) ?
