### ISSUE TITLE
Can we remove chmod

### ISSUE THREAD

**Issue by banasiakadam60** [golemfactory/clay#671]
`chmod` is used in two places:
```
./golem/testutils.py:45
./scripts/packaging/package_creator.py::883
```
Can it be removed?

**Comment by paulperegud** [comment]
First does not accept user input and is always executed on developer machine only.
Second - only used by developer during packing process.

They can't be used to gain access to any sensitive files. Why is this an issue or a security issue?

**Comment by banasiakadam60** [comment]
This is one of the bugs found by `bandit`. I've reported all of them to let us investigate and to not miss any issue. If you're sure it's not a bug just close this issue.
