### ISSUE TITLE
Allow multiple seed addresses

### ISSUE THREAD

**Issue by azawlocki** [golemfactory/clay#69]

**Comment by badb** [comment]
I change task specification (see title). https://github.com/imapp-pl/golem/pull/81

**Comment by badb** [comment]
Seeds should be given in separated file that is kept in new config directory.  After successful connection with some nodes their addresses may be added to seed file. 
Seed from config should be taken away and replaced with option "connect to node".

**Comment by chfast** [comment]
This sounds good.

However I would like to suggest alternatives:
1. Simpler solution is to hardcode the list of bootstrap nodes. This can be also the first step of this task.
2. We can remember addresses of previous nodes in database. No need to prepare special file for that.
3. The list of peers can change quite often. Do you want to remember all of them? When to save the file? I think the list of predefined bootstrap nodes should be always kept.
4. If we want the file to be editable by a (power) user, let's use JSON or YAML.
