### ISSUE TITLE
Fix wiki doc

### ISSUE THREAD

**Issue by Elfoniok** [golemfactory/clay#694]
In installation instructions https://github.com/golemfactory/golem/wiki/Installation
there is wrong git clone address
is git clone git@github.com:golemfactory/golem.git
should be git@github.com/golemfactory/golem.git

Moreover it wouldn't hurt if apt-get install instructions of prerequisite packages got additional package
python-dev otherwise one can get confusing messages about lacking Python.h header file during compilation of some projects.

**Comment by paulperegud** [comment]
I've changed URL to https version that will work for everyone, and added python-dev package to list of deps.
