### ISSUE TITLE
Geth not working.

### ISSUE THREAD

**Issue by Elfoniok** [golemfactory/clay#697]
Fix installation documentation. It lacks description of how to resolve missing "geth" command.
Add instruction about downloading and installing ethereum geth.

When i installed version geth-linux-amd64-1.5.0-c3c58eb6.tar.gz i cant process created task. Task in "waiting" state. I have following logs from golem client:

```
2016-12-03 12:51:48,772    INFO paymentprocessor - Peer count: 0 
2016-12-03 12:51:48,772    INFO paymentprocessor - Synchronized: False 
2016-12-03 12:52:48,676    INFO paymentprocessor - Peer count: 0 
2016-12-03 12:52:48,677    INFO paymentprocessor - Synchronized: False 
2016-12-03 12:53:48,676    INFO paymentprocessor - Peer count: 0 
2016-12-03 12:53:48,676    INFO paymentprocessor - Synchronized: False
```

**Comment by paulperegud** [comment]
Ad geth: installation page updated. Since this part of installation manual is for developers, I'm just pointing to geth release page.

**Comment by Elfoniok** [comment]
But this not resolving issue that latest geth don't work with golem. I have found that 1.4.18 is working for me. But i dont know why.

**Comment by paulperegud** [comment]
I've updated geth node that is running our private Ethereum network to 1.5.4.

@mfranciszkiewicz we need to update version of geth in our package

**Comment by paulperegud** [comment]
@Radagast-red May I ask you to switch to geth 1.5.4 and test if it is connecting properly to remote peer?

**Comment by Elfoniok** [comment]
Yes, although i still cant process task, mentioned logs disappeared and i seem to be connected, so probably problem is somewhere else. I think this can be closed now.

**Comment by paulperegud** [comment]
Thank you!

As for inability to process task - that might be caused by problems with NAT piercing of our p2p code. We are considering switching to devp2p, so work on fixing this issue is currently on hold.
