### ISSUE TITLE
Network Protocols description

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#7]
on wiki

**Comment by badb** [comment]
Coś jeszcze tu opisać, inny format? 

https://github.com/imapp-pl/golem/wiki/Golem-Network

**Comment by chfast** [comment]
https://github.com/imapp-pl/golem/wiki/Golem-Network#basic-messages-shared-between-p2p-task-and-resource

> Send information about **node2** closest neighboursh: **node2** --`MessagePeers` --> **node1**  

Not about **node1**?

**Comment by badb** [comment]
No, he may try to connect with nodes that are with specifi distance from him (or at least get information about them), ie. belong to specific kademlia bucket.

**Comment by chfast** [comment]
It is more than enough for now. Thanks.
