### ISSUE TITLE
Replace packaging with an installer

### ISSUE THREAD

**Issue by mfranciszkiewicz** [golemfactory/clay#735]
Current packaging process:
- is tightly coupled with architectural changes
- updating it is too time consuming, since the `freeze` library doesn't produce the expected distribution
- creates an isolated environment (`PATH` and `LD_LIBRARY_PATH` / `DYLD_LIBRARY_PATH`), which requires additional testing
- embedded libraries often cause trouble on different Linux distros

We could create an installer that:
- sets up a portable python distribution (Windows / OS X and Linux if the required version is not present)
- creates a virtualenv with required packages
- installs required system libraries
- places an entrypoint script / binary in system path

Related to #729

**Comment by banasiakadam60** [comment]
- [x] Versioning
- [x] Tests
