### ISSUE TITLE
Private key backup

### ISSUE THREAD

**Issue by Elfoniok** [golemfactory/clay#741]
Currently there is no way to backup Golem Account.

Of course user can manually backup his account. But this is installation dependent and provide no coherence way of doing this. This might be a good idea to manage this from golem application.

User should have a way to backup and restore his account from golem application.

**Comment by chfast** [comment]
What more than Ethereum account key file do you want to backup?

**Comment by badb** [comment]
New changes that are being implemented in https://github.com/golemfactory/golem/pull/1412 will make [this PR](https://github.com/golemfactory/golem/pull/1410) useless. To be able to solve this issue we will need additional changes in both Golem core & GUI / CLI. @chfast Please define the changes that should be done to make this possible here or in separate issues.
