### ISSUE TITLE
Account management

### ISSUE THREAD

**Issue by mfranciszkiewicz** [golemfactory/clay#750]
Golem should have a notion of user accounts, including ethereum account information.

1. persisted application state, settings and history should be tied to a user account
2. ethereum accounts and settings should be paired with Golem accounts
3. ui should provide a way to backup and restore user (#741) + ethereum accounts
4. (Optional) ui may include an account selection view

**Comment by badb** [comment]
1. First and minial requirement is to be able to make Ethereum account backup
2. Additional requirement is to prepare backup of Golem state, settings and history. 
Points 3 and 4 about restoring /changing account in UI should be ignored for now.
