### ISSUE TITLE
Hey guys, do you have to - do list? 

### ISSUE THREAD

**Issue by AlexanderKozhevin** [golemfactory/clay#756]
The stuff sounds cool. Can I participate somehow?

**Comment by chfast** [comment]
Hi,

The todo list is mostly [the issues list](https://github.com/golemfactory/golem/issues). They are not very well ogranized, but we know how complex is each now. The onse labeled [planned] should have good description and be ready to start, but I can see this set is not complete.

If you will have trouble finding anything there for you, we can review the list and mark some task easy to start with.

**Comment by AlexanderKozhevin** [comment]
Ok.
