### ISSUE TITLE
Turn off compositing only if it's needed

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#769]
Right now compositing is turn off by default. We don't have to be as strict. We can turn it on by default, if there are more frames than subtasks.

**Comment by maaktweluit** [comment]
Looked into this issue a bit, and found the following:
- All variables called `compositing` are set to `false`, user can toggle them in options / ui. One of these should be changed.
- We can make a function that uses the fields `subtasks` and `frames` as input for the calculation: `return numberOfFrames( frames ) > subtasks`
- We should update the value when the user changes the input fields or warn about bad config

This goes quite far for a 'up-for-grabs', so i think its best to be split as:
- Set default to true #769
- Add warning or error for bad config (next issue)
- Automatically update and be pretty for user ( next next issue )

Please let me know what you think, i have [made a start](https://github.com/golemfactory/golem/compare/develop...maaktweluit:issue%23769?expand=1) on setting the default to true. Can tweak and improve it to become better, please advise.

**Comment by maaktweluit** [comment]
When reading through more of the issues i found 2 related topics:
- show warning #768 
- redesign task creation #823 

These answer most of the questions from my previous comment :+1:

**Comment by globatum** [comment]
@maaktweluit how's this coming along? ready for closure?

**Comment by maaktweluit** [comment]
@globatum Thank you for the check-up. 
Yes, if the [proposed fix](https://github.com/golemfactory/golem/compare/develop...maaktweluit:issue%23769?expand=1) is enough for now I can make a PR and close the issue.
Is it better to make a PR right away or ask questions on the issue first?

**Comment by globatum** [comment]
@maaktweluit I think @badb should sign-off since he opened the issue. I don't have clearance to make that determination haha

**Comment by maaktweluit** [comment]
@globatum agree! But can imagine this issue is lower priority: lots of text, little code ;)
