### ISSUE TITLE
Introduce "Golem Node Address" concept

### ISSUE THREAD

**Issue by chfast** [golemfactory/clay#77]
Golem Node Address is an address that identifies a particular node in the network. The issue is what is the minimal set of information needed to point other node in the network.

Let's say we have nodes A, B and C. B is connected to both A and C. B would like to tell A it is connected to C. What address of C should B send to A to allow A to connect to C? Does C have the same address of itself as B has?

Information that might be needed:
- public IP address (aka remote address),
- private IP address (aka local address),
- TCP port (I would prefer to multiplex protocols on one port),
- public key.

Also, we should consider formats of the address. Examples:
- `enode://<public-key>@<remote-ip>:<tcp>`,
- `/ip/<ip>/tcp/<tcp>/pub/<public-key>`.

**Comment by badb** [comment]
Could you add short description to this task? I don't remember what it was about and I don't know if it's still important/valid.
