### ISSUE TITLE
Slightly better timeout estimation

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#770]
Right now we have fixed default timeouts values - 4 hours for task, 20 minutes for subtask. We cannot predict rendering time, but we can add a task-specific function with slightly better estimation. 

For Blender: 
* timeouts may depend on output resoultion, number of frames, size of reources.
* Additional estimation may be done after test.

For Luxrender:
* if halttime option is chosen, than it's simple - we should just add some time for resource transfer and providers choosing process. 
* Timeouts may depend on output resolution, number of samples per pixel and size of resources.

**Comment by globatum** [comment]
@badb I noticed you opened the majority of issues on the Brass milestone page. Can you verify each one soon to make sure closed issues do not remain open? Keep rockin', bro! 👍
