### ISSUE TITLE
Possibly wrong 'if' condition in p2pservice.change_config()

### ISSUE THREAD

**Issue by azawlocki** [golemfactory/clay#78]
There's probably something wrong with the 'if' here: 
https://github.com/imapp-pl/golem/blob/develop/golem/network/p2p/p2pservice.py#L239

Shouldn't this be

```
... and (peer.address == self.config_desc.seed_address)
```

or maybe 

```
... and (peer.host == self.config_desc.host)
```

?

**Comment by badb** [comment]
Yeah, thanks for finding that. I've added a quick fix.
