### ISSUE TITLE
p2pservice.__is_new_peer() incorrectly compares string id with long key

### ISSUE THREAD

**Issue by azawlocki** [golemfactory/clay#79]
https://github.com/imapp-pl/golem/blob/develop/golem/network/p2p/p2pservice.py#L703

`id_` is a string (hex encoding of an id) and `self.get_key_id()` is a long

**Comment by azawlocki** [comment]
This bug causes self to be added to the list of peers.

**Comment by chfast** [comment]
Where the nodes own address shows up from in the first place?
Node A should not send B's peer information to Node B.
