### ISSUE TITLE
"preparing test" loop / Blender

### ISSUE THREAD

**Issue by ghost** [golemfactory/clay#795]
"test task" goes into loop. I attach logs.
[golem_komputernowy_2017-01-27_14-42-29_2.txt](https://github.com/golemfactory/golem/files/735367/golem_komputernowy_2017-01-27_14-42-29_2.txt)

**Comment by badb** [comment]
There are two problems here. 
1) Your Docker isn't working. Have you installed it? 
2) There is a problem if Golem is installed on other disk than the data - I'll create an issue with better description.

**Comment by ghost** [comment]
1. I will try to reinstall it.
2. It helped, now I get normal error message. I think there's a lack of informations about this "issue" with files splitted between drives.

**Comment by ghost** [comment]
During the first installation no .iso or geth were downloaded so a lot of files was missing but console hadn't reported any issues. Also PATH variable wasn't updated. After reinstallation on one disk everything is working.

**Comment by ghost** [comment]
Now I get random loops.

[golem_komputernowy_2017-02-12_01-01-20.txt](https://github.com/golemfactory/golem/files/769027/golem_komputernowy_2017-02-12_01-01-20.txt)
