### ISSUE TITLE
Unable to start Golem on Ubuntu 16.04.1 and Linux Mint 18.1 (VirtualBox).

### ISSUE THREAD

**Issue by greenjellygit** [golemfactory/clay#813]
After the correct installation of Docker on Ubuntu and Linux Mint I tried to start Golem. I type "sudo ./golem.sh --gui" and at the first time "golem-latest.zip" is downloaded sucessfully. At the second time I type "sudo ./golem.sh --gui" and after pulling everything "Protocol error" occurs.

Ubuntu and Linux Mint are installed on VitualBox.

Logs from terminal:
http://pastebin.com/0YcnwSzx

**Comment by mfranciszkiewicz** [comment]
Could you upload the contents of `golem_jelly-VirtualBox_nie__5_lut_2017__18:35:09_CET.log`?

**Comment by greenjellygit** [comment]
File "golem_jelly-VirtualBox_...log" is only mentioned in the logs. Golem directory and subfolders does not contain this file.

[Golem directory preview](https://ibin.co/3BOOOMjFSsMa.jpg)

**Comment by mfranciszkiewicz** [comment]
That's unfortunate. It should be created on start, among `golem_client.log` and `golem_gui.log`.

Could you please paste the output of `./exe.linux-x86_64-2.7/golemapp --gui`?

**Comment by greenjellygit** [comment]
Ok, this is the output:
http://pastebin.com/raw/EN9C7reM

**Comment by maaktweluit** [comment]
Hey!

Not sure if its still applicable, but found this [in the wiki](https://github.com/golemfactory/golem/wiki/Installation):

If you run into import problems, e.g. ImportError: cannot import name keccak, run:
```
sudo apt-get remove python-crypto
sudo pip install --upgrade pycryptodome
```

Hope it helps!

Maaktweluit

**Comment by badb** [comment]
Please ask to reopen this issue, if the error still occurs.
