### ISSUE TITLE
Cannot run Golem on Windows10 Pro x64 ('evt.net.connection' session is not yet established).

### ISSUE THREAD

**Issue by greenjellygit** [golemfactory/clay#814]
After installing Docker using DockerToolbox tried to run Golem:
1. Double click on golem.cmd.
- Begins copying of golem-win32.zip to golem.
- Occurs ["Error extracting updates"](https://ibin.co/3BNLcvgCLNVK.jpg). 
- I click on ok button.
2. Type in console "golem.cmd --gui".
- ["Starting golem"](https://ibin.co/3BNMdgXb5qwe.jpg) appears and nothing happens.

Logs from golem_client.log:
http://pastebin.com/2T8XdXCT

**Comment by mfranciszkiewicz** [comment]
Please download the (full) package from http://52.40.149.24:9999/golem/golem-win32-latest.zip and extract it manually.

Current "installation" process does not provide enough feedback and we're working on a replacement.

**Comment by greenjellygit** [comment]
It works now, thanks. 👍
