### ISSUE TITLE
Move node.py out of examples/gnr/ to golem/ and pass the environments from the outside

### ISSUE THREAD

**Issue by azawlocki** [golemfactory/clay#82]
For example: 

```
$ golem/node.py --env Blender --env LuxRender
```

would be equivalent to adding the following code in `node.py`:

```
client.environments_manager.add_environment(BlenderEnvironment())
client.environments_manager.add_environment(LuxRenderEnvironment())
```

(see https://github.com/imapp-pl/golem/blob/develop/examples/gnr/node.py#L14)

Another possibility would be to read the list of environments from a config file.

But what about setting `accept_tasks = True` that we now have in `node.py`?
More general, how to pass options to a specific environment?

**Comment by chfast** [comment]
1. You can have command line options like `--env Blender LuxRender`. See https://github.com/imapp-pl/golem/pull/81#discussion-diff-46923535
2. I think we need another option that tells the node to accept tasks for computation, e.g. `--accept-task`, `--compute`, etc. Environments should be passive, a "requirement" that makes some kind of task computations possible. After some time we can also introduce "task filters" to specify what kind of tasks a node accepts.
