### ISSUE TITLE
Cannot run Golem on Windows 10 (Error setting up host only network)

### ISSUE THREAD

**Issue by greenjellygit** [golemfactory/clay#820]
![img_05022017_225520](https://cloud.githubusercontent.com/assets/12233387/22757671/1989d83e-ee4c-11e6-88fc-5d01eca22ee3.png)

**Comment by badb** [comment]
Can you chceck if there is a running instance of "default" Virtual Machine using VirtualBox? If there is power it off and try again.

**Comment by jiivan** [comment]
Probably fixed in new releases.
