### ISSUE TITLE
Expanded view for monitor

### ISSUE THREAD

**Issue by jiivan** [golemfactory/clay#828]
Create expanded view in monitor which will pop over when a node row is clicked in a list.

### Show in expanded view:
- [ ] full golem cliid
- [ ] node name (same as in a list view)
- [ ] ip (same as in a list view)
- [ ] income and expenditure
- [ ] golem version (and golem protocol versions)
- [ ] benchmark results (performance: general, blender, lux)
- [ ] max memory size
- [ ] max resource size 
- [ ] number of cores
- [ ] information if node is accepting tasks
- [ ] min trust (computing and requesting)
- [ ] number of requested subtasks
- [ ] number of subtasks that node tries to compute but they timeouted
- [ ] number of subtasks that node tries to compute but they ended up with error
- [ ] time the node spent computing tasks `node_info.EMA_computation_time_(success|failure)`

**Comment by harshjv** [comment]
@jiivan any mockup for this UI?
