### ISSUE TITLE
Config management redesign

### ISSUE THREAD

**Issue by chfast** [golemfactory/clay#83]
### Requirements
1. Multiple nodes running with different configurations on same host machine.
2. All options available from config file.
### Design
1. Node has _data dir_ assigned to it.
2. Data dir contains configuration file (e.g. golem.cfg, golem.yml).
3. Data dir can be set by command line option `--data-dir` in every client interface. If not set client chooses OS-specific dir suitable to application data.
4. Config contains at least section for generic Golem node configuration. Application specific configuration is optional, but can be kept in the same file.
5. Command line options can override values from config file.
### Considerations
1. Some OSes advice to keep configuration data separated from application data. e.g. node config should be stored in different folder than Golem task database. See Chrome example: https://www.chromium.org/user-experience/user-data-directory
2. We can add additional rules for data dir selection. E.g. `node.py --name "N1"` might be better than `node.py --data-dir $HOME/.local/share/gnr/N1`.
3. Config file format: [YAML](https://en.wikipedia.org/wiki/YAML) is trendy.
4. We can forbid running multiple nodes with shared data dir (by file locks).

**Comment by azawlocki** [comment]
I like the overall idea. It may be useful to allow sharing of some config files between nodes running in the same host machine. We could have separate --config-dir, with read-only config files that can be shared, and --data-dir used exclusively by a single node.

**Comment by chfast** [comment]
I would rather go for option `--config-file` (or simply `--config`) to point config file.
E.g. `node.py --data-dir /tmp --config-file /usr/share/gnr/common.cfg`.
