### ISSUE TITLE
Use light Ethereum protocol

### ISSUE THREAD

**Issue by chfast** [golemfactory/clay#836]
Just add `--light` flag to `geth`.

Blocked by https://github.com/ethereum/go-ethereum/issues/3639.

**Comment by paulperegud** [comment]
Workaround: use IPC instead of RPC. Both switch to light protocol and switch to IPC are implemented in #832

**Comment by paulperegud** [comment]
Blocked by https://github.com/ethereum/go-ethereum/issues/3752

This affects our ability to distinguish between mined and not-yet-mined transactions.
