### ISSUE TITLE
Session added twice to P2PService.all_peers

### ISSUE THREAD

**Issue by azawlocki** [golemfactory/clay#84]
After a P2P connection is established, the same session object (seemingly, the peer address and a random value agree) is added twice to `client.p2pservice.all_peers` list. First in `P2PService.new_connection()`, then in `P2PService.__connection_established()`.

I don't know what this list is for, and this may be harmless, but maybe this list should have a set semantics?

**Comment by badb** [comment]
Well, in fact, we don't need all_peers structure at all. General information about peers in the network should be kept in `PeerKeeper`, about open sessions in `peers` and about peers with whom we may connect in the future in `free_peers`. This list was never really used. I'll remove it completely.

**Comment by badb** [comment]
I make a quickfix in develop branch.

**Comment by chfast** [comment]
I would like propose a policy to add regression tests for bug fixes.
