### ISSUE TITLE
Calculate payment fee in USD

### ISSUE THREAD

**Issue by chfast** [golemfactory/clay#848]
We have payments in GNT and fees in ETH. But we also have GNT/ETH/USD price oracle. Use the oracle to calculate the fee as (USD/ETH)/(USD/GNT). We should also store USD prices in the database.

**Comment by paulperegud** [comment]
This can and should be implemented in UI only (maybe even without touching Golem Core?).

**Comment by paulperegud** [comment]
This can and should be implemented in UI only (probably without a need to touch Golem Core at all).

**Comment by chfast** [comment]
I agree. @badb can you re-label it?
