### ISSUE TITLE
Additional extension in lux output added if output file has extension with capital letters

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#852]
To reproduce: 
* Choose Lux task
* Define output with proper extension but with captial letters, eg. "/home/golem/pics/myoutput.EXR"
* End editing output file field
* Golem changes output file to "/home/golem/pics/myoutput.EXR.exr"

**Comment by maaktweluit** [comment]
Made an attempt to fix this issue, please check [PR#1148](https://github.com/golemfactory/golem/pull/1148)

_edit: added link_
