### ISSUE TITLE
testGetHostAddress fails for IPv6 addresses with percent sign 

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#856]
`ip_address` function doesn't parse ipv6 notation with percent sign, eg. `fe80::71a3:2b00:ddd3:753f%16`

Therefore `testGetHostAddress` function from `test_hostaddress` can fail

```
>       self.assertTrue(is_ip_address(get_host_address(None, True)))
E       AssertionError: False is not true
```

**Comment by zeeshanabid94** [comment]
Hey! I am interested in this task. I would like to contribute. But I am only a beginner in contributing to the open source community. I can work on this function and try to fix it. Do you want it to parse the ipv6 notation properly?

**Comment by ujjwalgulecha** [comment]
Do we still have this issue? @badb
