### ISSUE TITLE
Optimize tests with images 

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#860]
Unit tests with images can take long time, slowing down testing and developing process. Let's try to optimize them by decreasing images resolutions and / or limiting numer of such tests. 

Especially check:
* [ ] docker blender test
* [ ] tests from apps/blend
* [ ] tests for previews

Build times can be found at the end of the [test ( sub-build: unittest_linux, branch: develop)](https://buildbot.golem.network/buildbot/#/builders/4):
for example:
```
111.40s call     tests/golem/verificator/test_blenderverifier.py::TestBlenderVerifier::test_multiple_frames_in_subtask
63.16s call     tests/golem/verificator/test_blenderverifier.py::TestBlenderVerifier::test_bad_image
62.52s call     tests/golem/verificator/test_blenderverifier.py::TestBlenderVerifier::test_good_image
61.67s call     tests/golem/task/dummy/test_dummy_task.py::TestDummyTask::test_dummy_task_computation
```

**Comment by badb** [comment]
~[Assigned to Creed]~

**Comment by maaktweluit** [comment]
Updated the main comment:
- Removed lux from the checklist
- Added recent build times as example to fix
