### ISSUE TITLE
setup.py expects Golem is installed

### ISSUE THREAD

**Issue by chfast** [golemfactory/clay#877]
Inception level 2:
```
python setup.py develop                                                                                                                      develop 
Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    from gui.view.generateui import generate_ui_files
  File "/home/chfast/Projects/golem/golem/gui/view/generateui.py", line 3, in <module>
    from golem.core.common import get_golem_path
  File "/home/chfast/Projects/golem/golem/golem/core/common.py", line 6, in <module>
    from pathlib import Path
ImportError: No module named pathlib
```

**Comment by chfast** [comment]
This is back.

**Comment by badb** [comment]
In all installation from source instructions is specified to run `pip install -r requirements.txt` before running `setup.py`. 
Issues with pathlib can be relatively easily solved, eg. by moving get_golem_path function to external file that imports only os. 
But we're still going to need PyGit version installed before. Also PyQt installed and some additionall packages. Maybe we can create better developer instalator later, but for now I'm closing this issue.
