### ISSUE TITLE
Remove from preview for tasks in frames

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#896]
In `remove_from_preview` function in `renderingtask` there is a line that check if the preview file path is a list. If it is (ie. the task is frame rendering task) then preview is not changed. 
1) This checking should be to framerenderingtask. Rendering task should not know that preview may be a list of previews
2) Function for removing previews from frames should be implemented.

**Comment by yashodeepm** [comment]
I am new to contributing. Can you help me take this issue?

**Comment by badb** [comment]
When subtask is restarted, then the part of image that it produces should be removed from preview. 
For single frame task in Blender it is done by just painting the right part of the preview with black color. This procedure is not done however when there are many frames - and that's something that should be implemented. 
As you noticed properly [this part](https://github.com/golemfactory/golem/blob/develop/apps/rendering/task/renderingtask.py#L167)  of the code should be removed, but only after a proper method in framerenderingtask is implemented. We need `_remove_from_preview` function implemented in framerenderingtask that runs parent method if task is not using multiple frames and it’s own removal method in other case.
