### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by cookiengineer** [golemfactory/clay#912]
I was reading the [wiki entries](https://github.com/golemfactory/golem/wiki) but it's currently totally unclear on how to get actually started.

Is there something like a boilerplate that people can reuse to get started much easier than installing those hundreds of packages? Why is golem not containerized in docker or lxc to prevent version mismatches and installation problems?

In your video, you claim that golem is ready for machine learning and artificial intelligence simulations. My questions are the following:

1. How can I deploy my own Linux/Unix/OSX package to your golem network (preferably an up-to-date archlinux if possible)
2. Is there a simple docker image that golem runs in?
3. How to deploy my binaries and execute them on the networked machines?
4. Is there a library to connect to your network? If so, in which languages?

I think all these things need to be in the wiki until people can start using your project. Personally, my interest is for deploying [lychee.js](https://github.com/Artificial-Engineering/lycheejs) instances which require parallelized backprop ES/HyperNEAT instances in order to have all simulations up and running.

**Comment by minersday** [comment]
I was also thinking that you would provide a OVF appliance file for testing and bigger installations, this would run on top of vmware, hyper-v, kvm etc..
Simple installation just deploy the ovf file and you have a golem appliance.

**Comment by minersday** [comment]
I got connected to network with the following seed address:
194.181.80.71 & seed port: 40112

**Comment by zdavatz** [comment]
How did you connect to the network? I am still getting the following: 
![golem_2](https://cloud.githubusercontent.com/assets/4953/24540641/64675348-15f4-11e7-9e93-5c153412ea82.jpg)

**Comment by minersday** [comment]
Seed address 194.181.80.71
port 40112

only those

On Fri, Mar 31, 2017 at 10:28 AM, Zeno R.R. Davatz <notifications@github.com

**Comment by zdavatz** [comment]
are you on Linux or Windows? This worked, thanks!

**Comment by zdavatz** [comment]
How do I start selling my CPU power? Ok this is not yet possible, see: https://golemproject.slack.com/messages/G1RBKD5B2/convo/G1RBKD5B2-1490949875.217082/

**Comment by minersday** [comment]
linux

On Fri, Mar 31, 2017 at 11:38 AM, Zeno R.R. Davatz <notifications@github.com

**Comment by minersday** [comment]
you are the provider of cpu power, you set the prices there in ETH.
currently it's not real coins, they are only on the testnet.

On Fri, Mar 31, 2017 at 11:47 AM, Zeno R.R. Davatz <notifications@github.com

**Comment by alexmukho** [comment]
Golem was running for 4 hours on my PC and no tasks at all. Is it ok?

**Comment by badb** [comment]
Thank you for your suggestions @cookiengineer 
Support for developers, ie. possibility to add your own tasks with proper set of tools and documentation are planned for next milestones, ie. Clay, Stone and Iron. You can check the roadmap here: https://github.com/golemfactory/golem/wiki/Roadmap
New installators should be more useful, however we definietely need easier instalation for developers. 

I'm closing this issue, because there are too many different topics here.
