### ISSUE TITLE
[ERR] Blender test fails although it reports that it works

### ISSUE THREAD

**Issue by rh314** [golemfactory/clay#913]
I've tried both with "git checkout develop" and with "git checkout 0.3.2" versions, but in both cases the generated output file remains empty.

Also, these messages repeat themselves over and over:
```
ERROR    [golem.network.p2p.peersession      ] Protocol version mismatch 12 vs 11 (local)
WARNING  [golem.network.p2p.peersession      ] Failed to decrypt message, maybe it's not encrypted? wrong ecies header
```

Any ideas?

**Comment by badb** [comment]
These error messages aren't connect with test error. They just indicates that the version that you've installed is newer than the most of the test network from package. 
Can you describe this test fail with more detail? Are you using GUI or CLI? If GUI what is displayed in popup window and what in logs? Do you have Docker installed and working properly?

**Comment by rh314** [comment]
**Here are some more details**
- docker --version
  - Docker version 1.11.0, build 4dc5990
- Docker works?
  - Yes, `docker run --rm -it  golemfactory/blender` brings up a working python shell.
- uname -a
  - Linux 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
  - (Ubuntu 16.04)
- Connectivity
  - Ports 40102+40103 are open - tested from from an outside server.
- Blender version
  - Blender 2.76

**More details on the test fail:**
- Using the GUI `./golemapp`
- Apply the attached patch file to make sure the app does not delete the result file. (so we can see if it actually contains anything after running)
- Run the task with a .blend file  (e.g. https://www.blender-models.com/model-downloads/architecture/id/low-ploy-environment-scene-2/)
- Expect the resulting output file (in this case a PNG) to have contents.
- Currently, the output file is empty (i.e. fail)

**Logs:**
[golemclient.log.txt](https://github.com/golemfactory/golem/files/872105/golemclient.log.txt)
[golem_gui.log.txt](https://github.com/golemfactory/golem/files/872106/golem_gui.log.txt)

**Video of test: **
https://drive.google.com/open?id=0By2hs4I_yjPVN0pYYl95QTJzd2M

I can do more tests + collect more information if you need it.

**Comment by rh314** [comment]
Forgot the patch file to reproduce.
[keep-output.patch.txt](https://github.com/golemfactory/golem/files/872189/keep-output.patch.txt)

**Comment by badb** [comment]
Wow, great description!

Test phase shouldn't generate final image. It locally renders a small part of the image somewhere in your temp directory. To generate the final output you have to click "create task" and then "start task". Then it will be sent to Golem network and rendered on providers machines (and not your own). 

The test result should be saved in `~/.local/share/golem/default/task_tmp/output`. You can specify different directory with `--datadir` description.

**Comment by rh314** [comment]
Thanks - will see if I can get it working.
