### ISSUE TITLE
Remove code for pausing task

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#928]
In almost every version of task protocol that we're consider this option is not allowed. It may be possible in the future for some very specific use cases, but right now we should remove everything connected to it for simplicity.

**Comment by TheWaler** [comment]
Mind if I grab it?

**Comment by paulperegud** [comment]
Please do it :)

**Comment by TheWaler** [comment]
Awesome. Just to clarify:
Should I remove the code for pausing completely (in task manager if I understand correctly) or just anything that references it?
Also, I assume I should do the same for resuming, correct?

**Comment by badb** [comment]
Anything that references to it. Task manager, tasks implementatino in apps (if there are left any), interface part, task states, etc.
