### ISSUE TITLE
Issue while running Golem 0.4.0 for MacOS (10.11.6)

### ISSUE THREAD

**Issue by apolikamixitos** [golemfactory/clay#931]
Apparently MacOS versions below 10.12 are not supported … I’m currently using 10.11.6 and i received this message:

```
Error loading Python lib '/var/folders/6b/y35jpkpx41xbjtn5drl5y0gm0000gp/T/_MEIWKunPr/Python': dlopen(/var/folders/6b/y35jpkpx41xbjtn5drl5y0gm0000gp/T/_MEIWKunPr/Python, 10): Symbol not found: _getentropy
  Referenced from: /var/folders/6b/y35jpkpx41xbjtn5drl5y0gm0000gp/T/_MEIWKunPr/Python (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /var/folders/6b/y35jpkpx41xbjtn5drl5y0gm0000gp/T/_MEIWKunPr/Python
```

**Comment by gipskruid** [comment]
Can someone confirm?

**Comment by apolikamixitos** [comment]
@gipskruid This was in 0.4.0 release, i read that they added the support for the older versions, but i wasn't able to test it out since i upgraded to Sierra (too excited to test Golem maybe ?).

I guess this issue needs to be closed, don't you think @badb ?

**Comment by gborowik** [comment]
Thank you for reminding. Yes, recent versions i.e. Yosemite and later are supported now.
