### ISSUE TITLE
Remove description feature 

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#934]
People are not using it and we're not planning to continue to support it. Let's remove it from message & config and gui.

**Comment by zeeshanabid94** [comment]
Hey! I am interested in this task. I would like to contribute. But I am only a beginner. Can I get more description of the task?

**Comment by matthewsedam** [comment]
I am already working on this issue.

**Comment by TheWaler** [comment]
@matthewsedam Have you closed this by any chance yet? If not, are you going to or can this be moved to someone else? Thanks

**Comment by matthewsedam** [comment]
There is an open PR for this issue. See PR #1226. There is a problem with tests being non-deterministic which is affecting my PR as well. That is why work on it is paused until the tests are fixed.

**Comment by matthewsedam** [comment]
This issue needs to be closed @badb.

**Comment by badb** [comment]
Was done by @matthewsedam Thanks again for contributing!
