### ISSUE TITLE
Rendering issues on some nodes (0.4.0) [Test network]

### ISSUE THREAD

**Issue by apolikamixitos** [golemfactory/clay#937]
On the test network, i was trying to render an A380 Airbus model, but i noticed some issues with it.

![image](https://cloud.githubusercontent.com/assets/1634635/24570093/c85ca3b8-167a-11e7-9f6f-c2531732028c.png)

The rendering is working fine with a node called `bgb` (8b7f64f9537c36e), but with other nodes, `milliwatt-g4` (e23aeddd03ef009), `milliwatt-g7` (b2dd022ac734058) and `milliwatt-g10` (e868ddca541c1d7), the default Blender object is being rendered.

**Comment by badb** [comment]
Wow, that's pretty strange. Would it be possible to share with  us the scene that you have used? Are there any special plugins / renderes that are needed to render properly this scene?

**Comment by apolikamixitos** [comment]
@badb Actually i downloaded the model online, i suppose there are no plugins involved.

I checked the logs and i saw on these nodes this message:

```
found bundled python: /opt/blender-2.78a-linux-glibc211-x86_64/2.78/python
read blend: /golem/resources/Airbus_a380.blend
Error: Failed to read blend file '/golem/resources/Airbus_a380.blend': Missing DNA block
```
I attached below the model as well.

[87811_Airbus-A380.zip](https://github.com/golemfactory/golem/files/890506/87811_Airbus-A380.zip)

Expected output:

![image](https://cloud.githubusercontent.com/assets/1634635/24616501/5ab9363a-18a2-11e7-9933-9243c1802e7b.png)
