### ISSUE TITLE
Issue launching golemapp on macOS 10.12.3

### ISSUE THREAD

**Issue by evandev** [golemfactory/clay#938]
https://hastebin.com/egixeviwef.sql

**Comment by evandev** [comment]
During golem brew install: 
Warning: golemfactory/golem/golem dependency golemfactory/hyperg/hyperg was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.

**Comment by gipskruid** [comment]
same here... any solution available?

**Comment by evandev** [comment]
Haven't tried again, I was waiting to see if this ticket was updated.

**Comment by mfranciszkiewicz** [comment]
`"Error detecting VBox version: exit status 126"` might appear if you have uninstalled VirtualBox but `VboxManage` is still present on your PATH. 

To check if this is the case, run (should be empty):
`which VboxManage`
If you do not have VirtualBox installed, please remove this executable.
