### ISSUE TITLE
Building taskcollector on Linux does not work

### ISSUE THREAD

**Issue by chfast** [golemfactory/clay#941]
These linker flags are not correct for Linux: `LDFLAGS=-static -L /usr/lib/libfreeimage.so -lfreeimage`.
The /usr/lib/libfreeimage.so path does not seem to be right in general. And you cannot link the static library.

**Comment by mfranciszkiewicz** [comment]
You can compile with `-Bstatic`, which is not what we really want for packaging, or compile `freeimage` manually.

**Comment by chfast** [comment]
The point is `python setup.py` fails because of it.

**Comment by mfranciszkiewicz** [comment]
I'm assuming you're using Ubuntu (or Ubuntu-based distro) - it's actually an issue with the [`libfreeimage-dev` package](https://bugs.launchpad.net/ubuntu/+source/freeimage/+bug/1583328).

We can either:
- change the linker flag
- update the wiki accordingly

**Comment by etam** [comment]
Why was this issue closed? It's still not resolved.

The resulting binary is still not statically linked. It dynamically loads libfreeimage.so.

Why is a static binary needed?

I think is should be cleaned up to
```
else
	CXX=g++-5
	LDFLAGS=-lfreeimage
endif
```
