### ISSUE TITLE
testnet faucet code does not work well with the faucet

### ISSUE THREAD

**Issue by paulperegud** [golemfactory/clay#951]
Example crashes are here: https://gist.github.com/paulperegud/8a6308722ea7d28ee7d45c9e8df4e399

One with "known transaction" and code = -32000 definitely can be handled.

**Comment by paulperegud** [comment]
6 transactions in 3 minutes - probably as a result of not handling "code=-32000" error.

https://ropsten.etherscan.io/address/0x7b7bfbce50f270c764a1744effafc7b6f9eb419b

**Comment by mfranciszkiewicz** [comment]
This was a problem with the faucet web service code. Closing.
