### ISSUE TITLE
Call `remove_old` less often

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#952]
There are many `remove_old_*` function in the code. We don't reallly have iterate through all lists every time to make sure that timeoute objects are detected and removed. 
It would be good to create planned calls (on timeout) when we're adding new object to the list. 
Additional full list scanning may be left but called really rarely.

**Comment by mdtanrikulu** [comment]
I created a decorator which controls if function is executed once in given time period;
```python
@run_once_in(30) #seconds
def __remove_old_tasks(self):
    self.task_keeper.remove_old_tasks()
    ...
```

So it'll prevent to execute remove_old_*  functions,  if sync function is triggered consecutively.
Any suggestions?
