### ISSUE TITLE
Issue with refresh button for disk usage [Golem 0.4.0] [MacOS 10.12.4]

### ISSUE THREAD

**Issue by apolikamixitos** [golemfactory/clay#969]
When i try to click on 'Refresh' button, this issue shows up.
 
![image](https://cloud.githubusercontent.com/assets/1634635/24774627/be43ee18-1b2a-11e7-903a-93859bc294ad.png)

![image](https://cloud.githubusercontent.com/assets/1634635/24774622/b2b91c44-1b2a-11e7-8895-afa7d49d98cf.png)

**Comment by badb** [comment]
Resolved by #981
