### ISSUE TITLE
[ERR] Wrong task header received Deadline already passed

### ISSUE THREAD

**Issue by alexmukho** [golemfactory/clay#979]
Brass Golem (0.4) / Ubuntu 16.04

Continuously getting next error: 
> [golem.task.taskkeeper] Wrong task header received Deadline already passed

Any thoughts?

**Comment by badb** [comment]
Do you have your system clock properly synchronized?

**Comment by alexmukho** [comment]
Yes, synchronized with NTP.

**Comment by badb** [comment]
It's generally caused by other nodes with desynchronized clocks sending messages to the system. This log information however shouldn't have "error" level, just warning. 
I'm going to prepare PR that changes this.
