### ISSUE TITLE
Display app version in peer view

### ISSUE THREAD

**Issue by mfranciszkiewicz** [golemfactory/clay#991]

**Comment by maaktweluit** [comment]
Looked at adding this to the cli, [worked for the 'interface'](https://github.com/golemfactory/golem/compare/develop...maaktweluit:version_for_network?expand=1) part but the data is missing.

- Is the version number of each node available in the peersession info?
- What version are we looking for; app, p2p or an other?
- Does it make sense to add it to the gui with Electron coming?

**Comment by Elfoniok** [comment]
Hi

Thanks for commit. Definitely there is sens, as we would like to even extend cli methods.
I think that its APP_VERSION that you can get from golem.core.variables.

You could also add this in golem.rpc.mapping so we can consider addint this to ui

**Comment by maaktweluit** [comment]
Anytime! Thank you for the quick reply!

So I can:
- expose `APP_VERSION` to the rpc
- add it to the `peer` and/or `PeerSessionInfo`
- put it on the screen as int

Will look for where the peer data is loaded later, have to go now.

**Comment by mfranciszkiewicz** [comment]
Hey, addressing your points:
- peer's version number is not present in `PeerSessionInfo` (it should be)
- I think we should settle with app version
- lets skip GUI for now

`APP_VERSION` is your local app version, instead we can update `PeerSessionInfo` with app version that ought to be sent in `MessageHello`.

**Comment by maaktweluit** [comment]
Thanks for the clear reply! It helped me make the commit into this PR.

should we make a new issue for the rpc mapping?

**Comment by maaktweluit** [comment]
Updated the PR with test results, this made some new questions:

- How to not hard-code the version in tests? import and use `APP_VERSION`?
- Is the "patch" for `network dht` enough for now? will make a new issue to follow up.

**Comment by Elfoniok** [comment]
Maybe lets leave rpc mapping topic for now. We don't have ui ready for this anyway. Although we could add to cli method for checking your own golem version so this could be potential new issue.

**Comment by maaktweluit** [comment]
ok, sounds good!

`golemapp --version` should do the trick in most cases, if properly linked.. :)
